### PR TITLE
Feat/add delay between signals

### PR DESCRIPTION
**Pull request by cardosofede**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Add functionality of delay between signals requested by a community member

**Tests performed by the developer**:
run a directional strategy that returns all the time 1 and check that the script waits until the next signal

**Tips for QA testing**:

### CODE REVIEW

**Review by rapcmia — APPROVED** [review]
LGTM
- Observe behavior of directional_strategy script when delay_between signals is set with different internvals {5s,10s,120s}
- After a position executor is closed, there will be a delay depending on the set `delay_between_signals` then it checks the signal 
- Tested with tight RSA values to ensure we can open a position and `time_limit`

**Comment by rapcmia** [comment]
HI @cardosofede i tried to run the Github CI and getting this result 2/2
image

**Comment by cardosofede** [comment]
@rapcmia fixed!

**Comment by rapcmia** [comment]
Merged PR on behalf of the foundation team to development and will be available on release version 1.18.0

**Pull request merged**
