### PR TITLE
feat/upgrade cython version

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Modified the `environment.yml` dependencies to upgrade Cython to the latest 3.0 version (to move out from the alpha version the project is currently depending on).
Upgrading to the latest version allow Hummingbot to include all latest bugfixes. It will also allow the community to add the new functionality included in Cython 3.0 to generate a compiled Cythonized version of a pure Python module by just adding some Cython decorators to classes/functions.

I had to add a compiler configuration `"annotation_typing": False` to maintain backwards compatibility with the .pyx files in the project that include standard Python type hinting in pure Python functions. By default in Cython version 3 the developer is expected to use the Cython type hinting. I will let the Foundation decide if they prefer to remove/replace the standard Python type hinting in `pyx` files, and if so then remove the compiler configuration in `setup.py`

**Tests performed by the developer**:
Hummingbot conda environment installation and project compilation without issues.
All unit tests passing in green.
Executed a bot trading with Avellaneda strategy using Binance paper trade without issues.
Executed a bot trading with PMM strategy using Binance paper trade without issues.

**Tips for QA testing**:
Run the bot with any strategy implemented in Cython.

### CODE REVIEW

**Review by cardosofede — APPROVED** [review]
LGTM! @rapcmia we need to run the test suggested by Abel

**Comment by aarmoa** [comment]
@david-hummingbot Could you please attache the log files? There is not much to do without that information.

**Comment by aarmoa** [comment]
> Sorry forgot to add the logs, I've added them below @aarmoa
> 
> [logs_conf_xemm_1.log](https://github.com/hummingbot/hummingbot/files/12542710/logs_conf_xemm_1.log) [logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/12542711/logs_hummingbot.log)

I pushed an update that I think fixes the issue

**Comment by aarmoa** [comment]
Any news about this PR @david-hummingbot @cardosofede ?

**Pull request merged**
