### PR TITLE
Feat/Add Status Updates to Orchestration Remote Interface module - Basic availability

### PR DESCRIPTION
**Pull request by TheHolyRoger**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Adds basic availability status updates to the remote iface/MQTT orchestration module

**Tests performed by the developer**:
Tested it.

**Tips for QA testing**:

### CODE REVIEW

**Comment by TheHolyRoger** [comment]
@klpanagi

**Comment by cardosofede** [comment]
@klpanagi @TheHolyRoger the purpose of this pr is to check if the bot is running or not with that message? I thought that KLPANAGI it's not possible to infer this from another channel? For me seems okey since it's just another way to ask if the bot is running a Strat or not but idk if it was already implemented.

**Comment by TheHolyRoger** [comment]
@cardosofede At the moment the bot sends a heartbeat message, but for the purposes of my new home assistant integration it's much better to have this connection state broadcast. I'd like to add more status info to this channel in the future too

**Review by rapcmia — APPROVED** [review]
image
- Setup PR and broker `emqx_v5`
- Tried to setup to hbot_remote_client_py using listener_example.py, no go atm.
- Test using commlib-cli endpoints calling `status_updates`, all ok
  - Relaunch client or disconnect mqtt connection ✅

**Pull request merged**
