### PR TITLE
(fix) Defaulting Decimal to 0 in performance.py

### PR DESCRIPTION
**Pull request by MementoRC**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Issue: https://github.com/hummingbot/hummingbot/issues/5115
The solution was already provided

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by MementoRC** [comment]
Is there a way to downgrade one commit? I mixed-up 2 different PRs and don't seem to be able to remove the second one at my end

**Review by nikspz — APPROVED** [review]
Test performed:
Cloned and installed feature branch
Created XEMM strategy using Spot+Gateway connectors
Configured profitability to trigger trades 
Configured order amount
Started XEMM strategy using Spot+Gateway connectors
Checked order execution and history / CSV / Fees
Checked history and history --verbose displayed trade history for both maker/taker connectors
Tested on AWS Source and Docker

**Comment by rapcmia** [comment]
Hi @MementoRC can you fix the branch conflicts on the PR? thank you

**Review by cardosofede — CHANGES_REQUESTED** [review]
create a new pr without this conflicts, it will be much more cleaner. Also discussed on Discord

**Comment by nikspz** [comment]
@MementoRC Could you please create new PR with same changes as suggested? Thank you

**Comment by MementoRC** [comment]
New PR created:https://github.com/hummingbot/hummingbot/pull/5750

**Pull request closed without merging**
