### PR TITLE
Fix/gateway amount quantize

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This mainly fixes the issue with quantizing amount for gateway connectors.

**Tests performed by the developer**:
- Run LP strategy with WETH-USDC and confirmed LP positions are created successfully
 Reason for using that pair is that USDC had 6 decimal places, hence, a good one to test this fix.

**Tips for QA testing**:
- Test LP and AMM strategies with any pair having less decimals to confirm this fix.

### CODE REVIEW

**Comment by nikspz** [comment]
related to https://github.com/hummingbot/hummingbot/issues/5642

**Comment by vic-en** [comment]
@nikspz 
Can you post a link to the issue page you're describing for Kovan and Optimism?

**Comment by nikspz** [comment]
@vic-en https://github.com/hummingbot/hummingbot/issues/5668

**Comment by nikspz** [comment]
Tests Performed:
- arbitrum
    - checking amm_arb
        - using [https://rpc.ankr.com/arbitrum](https://rpc.ankr.com/arbitrum) nodeURL
            - could check balance
            - Bot return huge traceback after start of amm_arb strategy
        - using [[https://arbitrum-mainnet.infura.io/v3/8e7e…………………………..e0927](https://arbitrum-mainnet.infura.io/v3/8e7e%E2%80%A6%E2%80%A6%E2%80%A6%E2%80%A6%E2%80%A6%E2%80%A6%E2%80%A6%E2%80%A6%E2%80%A6%E2%80%A6..e0927)](https://arbitrum-mainnet.infura.io/v3/8e7ede0dd2034cb0b058d9c6338e0927) nodeURL
            - Failed to check balance
                - Bot returns an `exceptions.TimeoutError`
            - start the strategy - bot failed to start
                - Call to [https://localhost:30806/network/status](https://localhost:30806/network/status) failed
                - asyncio.exceptions.TimeoutError
            - `previously` I was able to `start the strategy and do the trades` using this nodeURL (`now doesn’t work`)
- optimism
    - checking amm_arb
    - [https://ropsten.infura.io/v3/](https://ropsten.infura.io/v3/) nodeURL - failed to connect wallet
    - [https://rpc.ankr.com/optimism](https://rpc.ankr.com/optimism) node URL
        - Failed to check balance
            - Bot returns an `exceptions.TimeoutError`
        - Failed to trigger no arb opportunity
- UniswapLP
    - Blocked with https://github.com/hummingbot/hummingbot/issues/5657
    - tried Delete gateway_connections.json file in the humminbot/conf dir
        - issue still persists

**Comment by vic-en** [comment]
@arnelhbot @nikspz 
image

1. None of those issues reported are related to the changes I've made.
2. I'm unable to reproduce any of the issues that have been reported

**Comment by nikspz** [comment]
- Fix/gateway amount quantize #5664
    - Currently blocked with  [https://github.com/hummingbot/hummingbot/issues/5657](https://github.com/hummingbot/hummingbot/issues/5657) (pending check for UniswapLP)
    - Tests Performed:
        - Cloned and installed branch
        - Created gateway image manually
        - Gateway generate certs/crete successfully
            - UniswapLP
            Blocked with [https://github.com/hummingbot/hummingbot/issues/5657](https://github.com/hummingbot/hummingbot/issues/5657)
        - Amm arbitrage:
            - Mainnet:
                - stuck into `uniswap_ethereum_mainnet not ready: waiting for allowances.`
            - Arbitrum one:
                - Connected key - ok
                - Checked balance - ok
                - Create/started strategy successfully - ok
                - Triggered no arb opportunity
                - Set up min profitability and trigger trades - ok
                - Checked history/CSV - ok
            - Optimism:
                - Connected key - ok
                - Checked balance - ok
                - Create/started strategy successfully - ok
                - Triggered no arb opportunity
                - Set up min profitability and trigger trades - ok
                - Checked history/CSV - ok
            - Kovan:
                - Connected key - ok
                - Checked balance - ok
                - Create/started strategy successfully - ok
                - Triggered no arb opportunity
                - Set up min profitability and trigger trades - ok
                - Checked history/CSV - ok
            - Pangolin:
                - Connected key - ok
                - Checked balance - ok
                - Create/started strategy successfully - ok
                - Triggered no arb opportunity

**Review by nikspz — APPROVED** [review]
- Tests Performed:
        - Cloned and installed branch
        - Created gateway image manually
        - Gateway generate certs/crete successfully
            - UniswapLP
                Arbitrum One:
                - connected key - ok
                - checked balance - ok
                - created/started uniswap_v3_lp strategy - ok
                - added liquidity - ok
                - checked on exchange - ok
                Optimism:
                - connected key - ok
                - checked balance - ok
                - created/started uniswap_v3_lp strategy - ok
                - added liquidity - ok, `Note: bot not showed liquidity added in the log pane`
                - checked on exchange - ok
        - Amm arbitrage:
            - Arbitrum one:
                - Connected key - ok
                - Checked balance - ok
                - Create/started strategy  using WETH-USDC pair rate successfully - ok
                - Triggered no arb opportunity - ok
                - Set up min profitability and trigger trades - ok
                - Checked history/CSV - ok
            - Optimism:
                - Connected key - ok
                - Checked balance - ok
                - Created strategy  using WETH-USDC pair and rate oracle source coingecko for OETH-USDC successfully
                - Started strategy - ok
                - Set up min profitability and trigger trades - ok
                - Checked history/CSV - ok
            - Pangolin: = OK
                - Connected key - ok
                - Checked balance - ok
                - Create/started strategy using AVAX-USDC.e pair successfully - ok
                - Triggered no arb opportunity
                - Set up min profitability and trigger trades - ok
                - Checked history/CSV - ok

**Comment by vic-en** [comment]
@nikspz @arnelhbot 
What else is blocking this pr?

**Comment by nikspz** [comment]
@vic-en Pending dev review from @Faouzijedidi1

**Review by Faouzijedidi1 — APPROVED** [review]
LGTM

**Pull request merged**
