### PR TITLE
Feat/uniswap v3 part 2

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This concluding part adds the connector and strategy on the client side along with test cases.

**Tests performed by the developer:**

- Configured and run strategy several times
- Manually run nosetest for new test cases.

**Tips for QA testing:**

- Add configuration for uniswapLP connector using gateway connect command
- Create and runa uniswap_v3_lp strategy.

**Notes:**
The strategy basically ensures that there's always an active position at all time provided there are more assets to create new position as the price moves.
It advisable to run on testnet or sidechains because of high gas fees for lp transactions.

### CODE REVIEW

**Comment by vic-en** [comment]
PRP https://snapshot.org/#/hbot-prp.eth/proposal/0xb54649cb2da38f3f842e3b642bae3594e1de345e87ce04bffccf078da4159147

**Comment by rapcmia** [comment]
PR update:
- Install and manually created docker image successfully
- Gateway connect uniswapLP via kovan testnet, all ok 
- Setup uniswap_v3_lp strategy, error validation for incorrect values are all ok

Tested Low tier,  Bot was trying to create a new position on specific range however we kept on getting `Error: Transaction out of gas..`

```
2022-06-23 14:15:47,548 - 7980 - GatewayEVMAMMLP - INFO - Created ADD liquidity order add-COIN3-COIN1-1655964936659687 txHash: 0xd0f1a21558495fea888f38af2232f30197acb6a7ac848176a6d65a80d63c6e8d on kovan. Estimated Gas Cost: 0.000376721000000000  (gas limit: 150688, gas price: 2.500000007000000135093387143569998443126678466796875)
2022-06-23 14:15:47,548 - 7980 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1655964947.0, "order_id": "add-COIN3-COIN1-1655964936659687", "exchange_order_id": "0xd0f1a21558495fea888f38af2232f30197acb6a7ac848176a6d65a80d63c6e8d", "order_action": "LPType.ADD", "trading_pair": "COIN3-COIN1", "fee_tier": "LOW", "lower_price": "0.156794358650000", "upper_price": "0.158370181350000", "amount": "1.000000000000000", "creation_timestamp": 1655964936.0, "token_id": 0, "event_name": "RangePositionUpdateEvent", "event_source": "uniswapLP_ethereum_kovan"}
2022-06-23 14:15:54,935 - 7980 - GatewayEVMAMMLP - ERROR - Error on POST https://localhost:24712/network/poll Error: {'message': 'Transaction out of gas.', 'httpErrorCode': 503, 'errorCode': 1003, 'stack': 'Error: Transaction out of gas.\n    at /usr/src/app/dist/src/chains/ethereum/ethereum.controllers.js:222:31\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/src/chains/ethereum/ethereum.controllers.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)'}
Traceback (most recent call last):
  File "/home/rapcmia/github/5388/hummingbot/connector/gateway_EVM_AMM_LP.py", line 1111, in _status_polling_loop
    await safe_gather(
  File "/home/rapcmia/github/5388/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/rapcmia/github/5388/hummingbot/connector/gateway_EVM_AMM_LP.py", line 872, in update_order_status
    raise update_result
  File "/home/rapcmia/github/5388/hummingbot/core/gateway/gateway_http_client.py", line 344, in get_transaction_status
    return await self.api_request("post", "network/poll", request, fail_silently=fail_silently)
  File "/home/rapcmia/github/5388/hummingbot/core/gateway/gateway_http_client.py", line 167, in api_request
    raise e
  File "/home/rapcmia/github/5388/hummingbot/core/gateway/gateway_http_client.py", line 163, in api_request
    raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
ValueError: Error on POST https://localhost:24712/network/poll Error: {'message': 'Transaction out of gas.', 'httpErrorCode': 503, 'errorCode': 1003, 'stack': 'Error: Transaction out of gas.\n    at /usr/src/app/dist/src/chains/ethereum/ethereum.controllers.js:222:31\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/src/chains/ethereum/ethereum.controllers.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)'}
```

Pending tests:
- Tier: Med and High
- Check position ID
- Retrieve position ID

**Comment by vic-en** [comment]
@rapcmia manually set gasLimit in uniswap.yml config to 3000000 for now.
Some other prs that'll that update that sections will be merged soon.

**Comment by rapcmia** [comment]
PR update:
- Tested today and manually edit uniswap.yml from the docker instance folder to `3000000` and played around different values: `300000, 500000, 5000000 and 1000000` but still getting the same error of `Transaction out of gas`. Tried to run `gateway config ethereum.gasLimit xxxxx` as well using the said values still a no go.  A sample scenario is available below

https://user-images.githubusercontent.com/73840223/175482656-a02aa665-0031-4b74-b919-938ca0e9b99a.mp4

Tried to test curl and approved 2 tokens ea between `uniswap and uniswapLP` however after executing `..amm/liquidity/add` and return txhash, it does not seem to show any data on [kovan etherscan](kovan.etherscan.io). Tried to send 0.001eth to another testnet wallet address to renew the nonce and execute the curl command again but no avail.

175488083-ead91355-7baa-4f53-92d8-602cc9d869c4

Pending test:
Tier: Med and High
Check position ID
Retrieve position ID

**Comment by JeremyKono** [comment]
Hi @vic-en, can you please resolve conflicts in this PR? Thanks!

**Comment by rapcmia** [comment]
PR update:
While testing commit `97c665a3d7c1` we are getting `unhandled error in background task: set` when setting up `uniswap_v3_lp` strategy

```
2022-07-04 03:05:32,142 - 338120 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'set' object has no attribute 'append'
Traceback (most recent call last):
  File "/home/ubuntu/github/5388/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/github/5388/hummingbot/client/command/create_command.py", line 65, in prompt_for_configuration
    file_name = await self.prompt_for_configuration_legacy(file_name, strategy, config_map)
  File "/home/ubuntu/github/5388/hummingbot/client/command/create_command.py", line 124, in prompt_for_configuration_legacy
    await self.prompt_a_config_legacy(config)
  File "/home/ubuntu/github/5388/hummingbot/client/command/create_command.py", line 201, in prompt_a_config_legacy
    err_msg = await config.validate(input_value)
  File "/home/ubuntu/github/5388/hummingbot/client/config/config_var.py", line 84, in validate
    self._on_validated(value)
  File "/home/ubuntu/github/5388/hummingbot/strategy/uniswap_v3_lp/uniswap_v3_lp_config_map.py", line 14, in exchange_on_validated
    required_exchanges.append(value)
AttributeError: 'set' object has no attribute 'append'
```

image

Steps to reproduce:
1. Setup uniswap_v3_lp strategy

[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/9036291/logs_hummingbot.log)

**Pull request closed without merging**
