### PR TITLE
fix/Error_writing_configs

### PR DESCRIPTION
**Pull request by lt7**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Fix Error writing configs: ('cannot represent an object', WindowsPath('C:/dev/hummingbot/logs') #5573 on Windows.

When transversing through the items log_file_path is a WindowsPath object which causes the error described in #5573. 

This change added a check if the value is PureWindowsPath then use the printable_value instead.

image

image

**Tests performed by the developer**:

Created new strategy, it saves without an error. All binance unit tests still pass. 

**Tips for QA testing**:

Ensure other config related settings are ok.

### CODE REVIEW

**Comment by lt7** [comment]
Snapshot - https://snapshot.org/#/hbot-prp.eth/proposal/0x0b073a46088e297a4a35f41a4d7b3f941bb8f6048e59ded4f38b0361768afe2a

**Comment by JeremyKono** [comment]
Hi @lt7, can you please resolve conflicts in this PR?

**Comment by lt7** [comment]
> Hi @lt7, can you please resolve conflicts in this PR?

Done

**Review by nikspz — APPROVED** [review]
Test performed:
Clone and install feature branch
Created a strategy
Tested on Windows gitbash, MacOS, Ubuntu source/docker

**Pull request merged**
