### PR TITLE
feat/order age from creation timestamp

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Change in the implementation of the order age calculation to stop using the timestamp that is part of the order_id and start using the new creation_timestamp field in the orders.

**Tests performed by the developer**:
Added unit tests.
Manually tested using a PMM strategy connected to paper trade Binance spot connector.

**Test Summary**:
- Create and start a PMM strategy using AscendEX, Binance, and Binance_paper_trade connector
- Run status --live and monitor the age of each order created: Confirmed that each order gets cancelled according to the specified order refresh time
- Filled event: Ok
- Run history --verbose to check the order_age
- Compare the timestamp saved in the CSV and sqlite file (filled table): Match
- Compare the order age of the filled order using the data on history vs order age in the csv file and using the creation timestamp and filled timestamp in the sqlite file: Order age matched
- Create an Avellaneda MM strategy, Liquidity Mining strategy, Perpetual MM, Aroon Osicillator and Hedge strategy then repeat the steps: Confirm that order age recorded in the history, CSV, and Sqlite file are matched
- Confirmed that all exchanges that support paper trade working as expected with order age.

**Tips for QA testing**:
- Check status command for the strategies report age correctly.
- Check age in trade events stored in the DB and in CSV files is correct.

This PR is created based on https://github.com/CoinAlpha/hummingbot/pull/61

### CODE REVIEW

**Comment by aarmoa** [comment]
The error in the test `AltmarketsWebsocketTests` should be solved after merging https://github.com/hummingbot/hummingbot/pull/5141

**Comment by dennisocana** [comment]
Proposal created: https://snapshot.org/#/hbot-prp.eth/proposal/0x6e73f949ce98705411cef2d252551912d7b48ce971d1ac85c6a1d191aea7418e

**Comment by JeremyKono** [comment]
Hi, @aarmoa. Please resolve branch conflicts in this PR. thanks!

**Comment by aarmoa** [comment]
@JeremyKono all conflicts are solved now

**Review by rapcmia — APPROVED** [review]
Test performed:
- Created simple Pure market-making strategy
- Orders cancelled according to set order_refresh time
- Monitor trade events and compare timestamps from history, CSV and connector's trade history, all ok 
- Compare `age` on history and CSV files, ok 
- Tested on Avellaneda, Liqudity-mining, Perpetual, Aroon Oscillator and Hedge strategy
- Tested papertrade connectors, ok

**Comment by aarmoa** [comment]
@JeremyKono @mifeng this PR has been approved by QA and has also been voted positive (and PRP finished on March 4th). Is there any problem preventing it from being merged in development?

**Comment by JeremyKono** [comment]
Hi @aarmoa, this PR will be going into the April release which contains all PRPs from the voting during the March period. `development` hasn't been synced to staging that's why this PR hasn't been merged into `development` yet

**Comment by aarmoa** [comment]
@JeremyKono even when the release is not too close please try to merge PRs into development as soon as possible. In general we have more changes waiting to be sent because they have dependencies between each others

**Pull request merged**
