### PR TITLE
(feat) add kucoin perpetual connector

### PR DESCRIPTION
**Pull request by ethicrypt**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR adds a Kucoin Perpetual derivative connector to Hummingbot. It allows for connecting to the Kucoin Futures testnet and mainnet. There are no additional dependencies introduced by this connector. 

This work was done for the following Bounty Board issue: [https://github.com/hummingbot/hummingbot/issues/5796](url)

**Tests performed by the developer**:

Using both testnet and mainnet, I verified that I was able to successfully:

- Connect with a valid API key
- Retrieve current balances and positions
- Get autocompletion of pairs during strategy creation
- Place orders
- Cancel orders
- Handle order fills and other updates
- Run the Perpetual Market Making strategy

All unit tests created for this connector are passing.

**Tips for QA testing**:

- Kucoin Futures (both test and mainnet) API accounts are entirely separate from the Spot Kucoin API accounts and keys. 
- The ask orderbook in testnet is completely empty, so the mainnet orderbook is looked at while in testnet mode to allow it to function. This setup allows for successfully placing orders on the testnet, but they generally go unfilled.
- The ticker for BTC on Kucoin Futures is XBT.

### CODE REVIEW

**Comment by ethicrypt** [comment]
Bear with me folks, I'm working on addressing the tests that are failing and will have this fully ready to be reviewed in the next few days.

**Comment by rapcmia** [comment]
Hi @ethicrypt thanks for the update. The foundation team will review this PR and await for the fix on failing test 🙇

**Comment by rapcmia** [comment]
PR update:
- Successfully connected API for kucoin_perpetuals
- Setup simple perp-mm
  - Order create and cancel successful
  - Position successfully opened and take-profit order created
  - Position closed and take-profit order successfully filled `pending`
  - Stop loss order created ok 
  - Funding time `not started`
  - Position mode:
     - Oneway ✅ 
     - Hedge not supported
       image

Pending
- Monitoring long term bot

**Comment by rapcmia** [comment]
We'd like to address as well an issue when using BTC-USDT, it does not seem to be available on the list of markets for Kucoin perpetual. It is also not available on the list when you use `tab`

image

**Comment by ethicrypt** [comment]
> We'd like to address as well an issue when using BTC-USDT, it does not seem to be available on the list of markets for Kucoin perpetual. It is also not available on the list when you use `tab`
> 
> image

On Kucoin, they use the ticker XBT instead of BTC and the autocomplete does work for XBT. I believe I just need to figure out how to make it display as BTC instead. I know Kraken uses XBT behind the scenes as well, so I'll see how it's handled in that connector.

**Comment by rapcmia** [comment]
PR update:
- Review log file of overnight bot
- Observed `HTTP status is 429` but this is expected found on spot connector as well
- No Stuck orders and order are successfully created/cancelled
- Trade data between csv, history and exchange trade history matched
- Set kucoin_perpeptual to price_source_derivative, ok 
- Funding time ✅

**Review by rapcmia — APPROVED** [review]
LGTM

**Review by cardosofede — APPROVED** [review]
LGTM! Good job.
One thing that probably in the future with the usage we should review is the implementation of: _is_order_not_found_during_status_update_error and _is_order_not_found_during_status_update_error
The last update of the order tracker uses this to delete "lost orders" for example if you sent an order and in the middle, you have network issues and you are not receiving a response, the connector will ask for this order. Usually, if the order does not exist in the exchange you are going to receive a message that says that the order is not there, and after trying 3 times are going to discard that order.

**Pull request merged**
