### PR TITLE
Feat/okx perpetuals candles feed

### PR DESCRIPTION
**Pull request by tomasgaudino**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Incorporate support for candles feed utilizing the OKX Historical Data API, ensuring seamless integration with the current Hummingbot architecture (following Binance Perpetuals candles feed current standard)

**Tests performed by the developer**:
- Replicated current tests used for Binance Perpetuals candles feed

**Tips for QA testing**:
1) Pull this PR
2) Run the attached script ([candles_example.txt](https://github.com/hummingbot/hummingbot/files/13967137/candles_example.txt)) by:
    a) Replacing `.txt` with `.py` and placing it in `./scripts` folder
    b) Start hummingbot
    c) Run `start --script candles_example.py`
    d) When everything is ready, run `status --live`
    e) Compare Binance Perpetuals vs. OKX Perpetuals candles behaviour 
3) _[Optional]_ Feel free to try different intervals / trading pairs

### CODE REVIEW

**Comment by nikspz** [comment]
Test performed:
- Cloned and installed PR6791 commit 1b6c625
- Start hummingbot successfully
- start --script candles_example.py advised by dev

default script issues:

A) first 3-4 timestamp lines is inconsistent for okx_perpetual (after start of the script). 
Tried to change params (interval (15m,1h, 1d) and increase max_records to 200, 500 etc) - still inconsistent

B) volume VS quote_asset_volume are the same values

C) Comparing OHLC Client candles example VS Exchange could be not accurate


image
image
image

1) 1m max records 200

image

2) 15m max records 500

image
image

3) 1h max records 500

image

4) 1d max records 200

image

5) 1d max records 5 binance_perpetual VS okx_perpetual

image
image

**Comment by cardosofede** [comment]
@tomasgaudino the trading pair should be BASE-QUOTE, and the candles feed is only for perpetuals

**Comment by tomasgaudino** [comment]
Ok @cardosofede , tomorrow i'll push the last updates

**Comment by tomasgaudino** [comment]
@nikspz ready for review

**Review by nikspz — APPROVED** [review]
Test performed:
- Cloned and installed PR6791 commit 1b6c625
- Start hummingbot successfully
- start --script candles_example.py advised by dev
- commit [[d951a98](https://github.com/hummingbot/hummingbot/pull/6791/commits/d951a9805e7d73e45fda01f20ecb6d8c3c577006)](https://github.com/hummingbot/hummingbot/pull/6791/commits/d951a9805e7d73e45fda01f20ecb6d8c3c577006)
  - 1m candles matched
  - 5m candles / 300 records, matched close enough to exchange UI OHLC, compared to binance as well (max difference with OHLC spotted was 0.05 for SOL-USDT)
  - 15m candles / 300 records, matched close enough to exchange UI OHLC, EMA 14 matched with exchange UI (max difference spotted is ~0.01)  
  - 1h candles / 300 records, matched close enough to exchange UI OHLC, EMA 14 matched with exchange UI (max difference spotted is ~0.01)  
  - 1d / 200 records, candles matched, compared to binance as well (max difference with OHLC spotted was 0.2 to ~0.5 for ETH-USDT)

**Comment by nikspz** [comment]
@tomasgaudino Could you please also add comment about this issue, the reason is okx_perpetual connector logic related?
image

**Comment by tomasgaudino** [comment]
sure @nikspz , you can visit both urls:

 - For REST Requests: https://www.okx.com/docs-v5/en/?shell#order-book-trading-market-data-get-candlesticks-history
 - For WS Connections: https://www.okx.com/docs-v5/en/?shell#order-book-trading-market-data-ws-candlesticks-channel

They both give the same answer, and those fields are not currently available. I'll share a more extended screenshot here:

image

Feel free to make more questions

**Comment by nikspz** [comment]
oki, Thanks @tomasgaudino 🙏

**Review by cardosofede — APPROVED** [review]
LGTM!

**Pull request merged**
