### PR TITLE
Fix/TWAP - default values don't make sense

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

A fix of following issue:
- order price optional in strategy parameters - order price needs to be always provided, can't be optional
- default values of `is_buy`, `target_asset_amount`, `order_step_size`, `order_price` are not justified, "1" is not an universally correct value, and the parameters always have to be provided by the user

**Tests performed by the developer**:

- ran the strategy, printed actual order price being sent
- ran the unit tests

**Tips for QA testing**:

- verify that the actual submitted order price corresponds to the configuration order_price

### CODE REVIEW

**Comment by dennisocana** [comment]
Proposal created: https://snapshot.org/#/hbot-prp.eth/proposal/0x6d98d56509fe9f5dd7ec9b9699ebeac8b0331ea3aab0f5430d9493e310497b7d

**Comment by rapcmia** [comment]
PR update: ongoing test

**Review by Nullably — APPROVED** [review]

**Comment by nikspz** [comment]
* order_price needs to be always provided = OK
* default values removed - Failed

Steps:
Start to create new TWAP strategy

Actual:
Showing default values for:
`trade_side`  (buy)
`target_asset_amount`  (1.0)
`order_step_size`  (1.0)

Expected:
these parameters always have to be provided by the user

image
image
image

**Comment by mhrvth** [comment]
This PR is not about configuration but about the class parameters.

**Review by rapcmia — APPROVED** [review]
Test performed:
- Setup simple TWAP strategy, ok  
- Successfully start TWAP without any error
- Confirmed the order price are displaying correctly
- Confirmed that the total size of the orders that will be placed are equal to the current target amount and once orders are all filled, the bot stop placing orders.
- Tested on source and docker build, all ok

**Pull request merged**
