### PR TITLE
Feat/repo clean up

### PR DESCRIPTION
**Pull request by cardosofede**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
In this PR I'm doing a big clean up of the repository, some of the main changes are:
- Remove PMM Scripts
- Remove integration test
- Remove debug test
- Simplify methods on base classes
- Adapt test and config map
- Adding a lock on time synchronizer requests to avoid multiple ones if deque is empty

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update:
- Installation ok on source
- Remove PMM Scripts
    - `config pmm_script_mode` not available 
    - Editing the `conf_client.yml` file located inside the conf folder, not available
    - `./pmm_scripts` folder not available
    - Compare with development branch
- Remove integration and debug tests
    - Run offline `make test` on macOS m1 3/3 all ok
    
 ---

Todo:
- Setup with development gateway, deploy
- Setup v2 strategy and run overnight

**Comment by cardosofede** [comment]
@rapcmia @nikspz unit test ready

**Comment by rapcmia** [comment]
PR update:
- Setup this PR with gateway ok 
- Setup this PR with deploy development
  - Blocked atm, not able to run backend-api on local macOs both development and main 🛑 
- Running long term bot on binance spot using pmm_simple controller with long refresh time `in progress`

**Comment by rapcmia** [comment]
PR update:
> Running long term bot on binance spot using pmm_simple controller with long refresh time

- Review logs of binance spot running overnight, did not found errors related to https://github.com/hummingbot/hummingbot/issues/7098
- Setup OKX on v2 strategy and monitoring today `in progress`

**Comment by nikspz** [comment]
Test performed:
- Cloned and installed PR7121, manually created docker image successfully
- Cloned dashboardPR160 + backendPR24 and created docker images for both
- Use Deploy repo, deleted pull line and used docker images to use dashboard successfully
- connected exchange successfully
- created/started v2 pmm_simple successfully
- Review orders created on Client and exchange successfully

**Review by rapcmia — APPROVED** [review]
LGTM 
- Setup this PR on source 
- Run offline tests on mac 3/3 ok 
- Check all related to `pmm_scripts`
  - `config pmm_script_mode` not available
  - Editing the `conf_client.yml `file located inside the conf folder, not available
  - `./pmm_scripts` folder not available
  - Compare with development branch all ok 
- Run tests on binance and okx for two days and not seen errors related to `timestamp 1000ms ahead..`
- Build docker image and setup with deploy 160 
  - Run backtests with PMM simple ok 
  - Setup bollinger band config with binance perp ok
  - Not tested all available controllers ❌ 

---

QA approved 1/2

**Review by nikspz — APPROVED** [review]

**Pull request merged**
