### PR TITLE
feat: add hashkey global spot and perpetual connector

### PR DESCRIPTION
**Pull request by dengyh**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:
image

**Tips for QA testing**:

### CODE REVIEW

**Comment by nikspz** [comment]
hi @dengyh Please add unit tests coverage https://github.com/hummingbot/hummingbot/actions/runs/10466742375/job/28984160362?pr=7171

**Comment by nikspz** [comment]
image
@dengyh 
Please sent a message here when PR is ready

**Comment by dengyh** [comment]
> @dengyh Please sent a message here when PR is ready
@nikspz My PR is ready. I can give you an account in sanbox for validating.

**Comment by nikspz** [comment]
Steps:
1. Clone and install PR7171
2. connect hashkey_perpetual_testnet and review balance 
3. create perpetualMM strategy using hashkey_perpetual_testnet
4. start the strategy 
Actual: 
review orders to OPEN position `not placed`
status reported - connector not ready
Expected:
Client placed order to open position, status reported orders and prices.
balance show correct and only values used for futures




image


Balance reported all the assets instead of Futures account?
image
Futures Account:
image
Trading account:
image

**Comment by nikspz** [comment]
@dengyh Could you fix failing tests?
Please check this PR: #7180

**Review by nikspz — APPROVED** [review]
c7d3ac5
Test performed:
- Cloned and installed PR7171
- Started the client Successfully
- Manually built docker image successfully
- Connected the hashkey and hashkey_perpetual connector API keys successfully
- Balance output: ok
- Create/Import/Start a strategy: ok
- Check status and status --live match with exchange: ok
- Order cancellation: ok
- Order filled events handling: ok
- Vertify fees recorded: ok
- longrun on pureMM using hashkey with multiple order levels and hanging orders: ok
- longrun test on bollinger_v1 using hashkey_perpetual with binance_perpetual candles: ok

**Review by cardosofede — APPROVED** [review]
Great work @dengyh. check that we updated the info on the client order tracker and now the price is logged, review those test and it's ready to merge

**Comment by dengyh** [comment]
> Great work @dengyh. check that we updated the info on the client order tracker and now the price is logged, review those test and it's ready to merge

@cardosofede I had pulled the latest development branch and rebased it. Can you trigger the check again?

**Comment by dengyh** [comment]
> Hi @dengyh Can you also add the docs for the connector to our site - https://github.com/hummingbot/hummingbot-site You can use the other existing connectors as a template. Thanks!

@david-hummingbot Here is the PR for hummingbot-site: https://github.com/hummingbot/hummingbot-site/pull/387

**Comment by nikspz** [comment]
hi @dengyh Please check and fix failing tests here:
https://github.com/hummingbot/hummingbot/actions/runs/10553834706/job/29234766794?pr=7171

**Pull request merged**
