### PR TITLE
Feat/remove unvoted connectors

### PR DESCRIPTION
**Pull request by cardosofede**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Remove connectors that didn't meet the criteria in the last poll.

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update:
- Install on source ok
    - When starting hummingbot:
      image
      - quickstart and start script return the logs above when starting the hummingbot
      - check conf_fee_overrides.yml and saw some hitbtc, tried to comment and still getting same behavior
        image
- Connect does not display removed connectors HitBTC and bit_com ✅ 
- Autocomplete does not display any of the connectors  ✅ 
- Errors does not indicate any of the remove connectors  ✅ 
- Run make tests locally ok  ✅

**Comment by nikspz** [comment]
- Connect does not display removed connectors HitBTC and bit_com ✅
- Autocomplete does not display any of the connectors  ✅

> PR update:
> 
> * Install on source ok
>   
>   * When starting hummingbot:



Same thing on docker installation

Noticed some issue on docker image creation, not related to this PR (Happened on dev as well)
image

image
image

**Comment by rapcmia** [comment]
Hi @cardosofede , hmm i think we should remove dydx v3 too. It seems its not accessible on their website anymore https://dydx.trade/

image

cc: @fengtality

**Comment by rapcmia** [comment]
PR update:
- Run tests `4c62419648dbb04075a994071a060f3e16c592f5`
- Dydx v3 has been successfully removed ✅ 
- Run make tests locally, all ok 
- Still getting the error when using `./start` command
  image
  - Does not occur when using `bin/hummingbot.py`
  - Tried to remove all related to hitbtc from `conf_fee_overrides.yml` and `conf_fee_overrides_TEMPLATE.yml` and run `./start` again, all ok
    image

**Pull request merged**
