### PR TITLE
Refactor/Replace websockets library with aiohttp library - Bitmart

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Replacement of websockets with web_assistant (aiohttp)

Up to now hummingbot has been using the websockets library to create socket connections to exchanges. Currently this library is being replaced with aiohttp, another socket library, because websockets is being maintained only by a single developer, which poses various risks to the client, both technical and strategic. Along with this refactoring a unified component simplifying REST and socket connections was developed - web_assistant. The goal of this change is to replace the websockets connections in the Bitmart connector with the web_assistant / aiohttp.

**Tests performed by the developer**:

Ran unit tests
Ran pure MM with the connector

### CODE REVIEW

**Comment by phbrgnomo** [comment]
Link for the Proposal: https://snapshot.org/#/hbot.eth/proposal/0xfdf064a9ed3f3b22a39d50e59b21de266a5042e6b3344d1c86420654c3a399b3

@mhrvth @aarmoa a few details to be addressed:

- Add more details to the PR description. Remember to add as many relevant information as possible. The PR description will be basically the core of the PRP.
- If the PR have an Issue related to it, add it to the PR description, to help give context to why the PR is being created in the first place (And help the foundation team to close issues that are no longer relevant)

**Comment by rapcmia** [comment]
PR update: on-going test

**Review by rapcmia — APPROVED** [review]
Tested and confirmed working by QA
Test performed:

- Successfully connected API and balance checks
- Created pure market making strategy 
- Started strategy and able to create/cancel orders however, there are instances of issues 4961 and 4958
- Executed trades and confirmed no issues on trade fill
- Trade information matched from connector and client 
- The client was able to handle long and short refresh time
- Successfully place orders on multiple and hanging order settings
- Tested on different strategies, all ok

**Review by rapcmia — APPROVED** [review]
Tested by QA and got the same test results. Re-approving PR

**Review by Nullably — APPROVED** [review]
LGTM

**Pull request merged**
