### PR TITLE
 HIP-4 Part 4: Support uniswap v2 and v3 on the polygon chain

### PR DESCRIPTION
**Pull request by james-hummingbot**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
1. Add polygon as a chain for uniswap. 
2. Fix some UI issues in hummingbot related to selecting the chain with `gateway connect`. This is the first time hummingbot/gateway supports multiple chains on a single connector.

This is branched off of this PR: https://github.com/hummingbot/hummingbot/pull/5334

**Tests performed by the developer**:
I created an amm_arb strategy between uniswap_polygon_mumbai WMATIC-DAI and binance paper. It was able to perform trades. 

**Tips for QA testing**:
Try testing on mumbai. If it works then try mainnet. You will MATIC and WMATIC tokens.

### CODE REVIEW

**Comment by nikspz** [comment]
@james-hummingbot Could you please resolve branch conflicts?

**Comment by JeremyKono** [comment]
@james-hummingbot please fix gateway unit tests in this Pr. Thanks!

**Comment by rapcmia** [comment]
PR update:
- Test latest commit `3784725b` and the issue below has been fixed
   > We are getting an warning of `Call to https://localhost:17558/evm/approve failed` and error `Error: cannot override "gasLimitTransaction"` when the strategy is trying to initiate approvals
   
While setting up uniswap via polygon chain, we noticed that it still prompts the `kovan and ropsten` option. While checking `gateway config polygon` it does not seem that it has `kovan and ropsten`

Screenshot 2022-08-03 170635

Screenshot 2022-08-03 170808

Pending:
- Setup AMM arbitrage using different tokens available on mainnet and mumbai testnet
- Filled order event
- Docker build

**Review by mifeng — APPROVED** [review]

**Comment by mifeng** [comment]
Merging this this PR so that @vic-en can add additional commits that addresses the issues found

**Comment by denks13** [comment]
while running uniswap v3 LP on polygon i get infinite connector_not_ready
uniswapv3polygon

**Pull request merged**
