### PR TITLE
Fix new api update from binance

### PR DESCRIPTION
**Pull request by mlguys**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Fix issue: https://github.com/hummingbot/hummingbot/issues/6985
- Disable Binance US in rate oracle for Binance to fix balance command not working for Binance
- Split Binance US rate oracle from Binance oracle

**Tests performed by the developer**:
- Run PMM
- Run Balance command

**Tips for QA testing**:

### CODE REVIEW

**Review by nikspz — APPROVED** [review]
Test performed:
- Clone and install PR6986
- connect binance successfully
- check API keys connected successfully
- checked balance successfully
- created/started pureMM using binance successfully
- review on exchange UI, orders placed
- status --live: ok
- order cancellation: ok
- orders filled: ok
- History --verbose: ok
- Trade fees compared with exchange: ok
- Data aggregation on datadog according to Client and exchange: ok
image

**Comment by mlguys** [comment]
Hey @nikspz , since I disabled the rate oracle for Binance US from Binance code, I added new code to finally split them apart as separated Rate Oracle.

**Review by cardosofede — APPROVED** [review]
LGTM!

**Comment by mmarooney** [comment]
@cardosofede, @nikspz  Was this tested against Binance.US?  I am getting the same errors as the original issue:

2024-04-30 14:52:05,902 - 63999 - hummingbot.connector.exchange.binance.binance_api_order_book_data_source.BinanceAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/hummingbot/hummingbot/connector/exchange/binance/binance_api_order_book_data_source.py", line 75, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "//miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'BTC-USDT' 

I am running the latest code from the master branch.  

Thanks!

**Comment by nikspz** [comment]
> I am getting the same errors as the original issue on Binance.US :
> 
> 2024-04-30 14:52:05,902 - 63999 - hummingbot.connector.exchange.binance.binance_api_order_book_data_source.BinanceAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams... Traceback (most recent call last): File "/hummingbot/hummingbot/connector/exchange/binance/binance_api_order_book_data_source.py", line 75, in _subscribe_channels symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair) File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair return symbol_map.inverse[trading_pair] File "//miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in **getitem** return self._fwdm[key] KeyError: 'BTC-USDT'
> 
> I am running the latest code from the master branch.

Thanks for the report, we'll try to check if related

**Pull request merged**
