### PR TITLE
Gateway: add option to Avalanche to use dynamic gas price

### PR DESCRIPTION
**Pull request by james-hummingbot**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

If `gasPriceRefreshInterval` is set in the Avalanche config for the node you are using, then it will use the dynamic gas price from the node.

**Tests performed by the developer**:

I ran amm_arb with pangolin and binance_paper_trade. It was able to make lots of trades successfully over a running time of 30 minutes.

**Tips for QA testing**:

Try running amm_arb with pangolin.

### CODE REVIEW

**Comment by rapcmia** [comment]
Hi @james-hummingbot I'm having some issues at the moment testing Pangolin-Avalanche with Moralis node and created a github issue ticket since its also happening on dev branch. We tried to crosscheck it from local and AWS instance and getting the same issue.
 
Link: https://github.com/hummingbot/hummingbot/issues/5342

**Comment by rapcmia** [comment]
Upon testing commit `46f6950833`, I'm not able to get the `markets are ready, trading started`. Getting error of `Avalanche not available` and still stuck on `markets not ready..`. Tried to wait for few minutes, reclone/build and tested on AWS instance still getting the same behavior

```

2022-06-07 10:37:52 | error | 	Avalanche is not available | Error: Avalanche is not available
    at Pangolin.<anonymous> (/usr/src/app/dist/src/connectors/pangolin/pangolin.js:53:23)
    at Generator.next (<anonymous>)
    at /usr/src/app/dist/src/connectors/pangolin/pangolin.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/src/app/dist/src/connectors/pangolin/pangolin.js:4:12)
    at Pangolin.init (/usr/src/app/dist/src/connectors/pangolin/pangolin.js:51:16)
    at /usr/src/app/dist/src/services/connection-manager.js:52:37
    at Generator.next (<anonymous>)
    at /usr/src/app/dist/src/services/connection-manager.js:8:71
    at new Promise (<anonymous>)
```

https://user-images.githubusercontent.com/73840223/172346126-d81fee82-6591-4303-9d9c-1e898011b877.mp4

AWS:
image


Crosscheck with latest development branch `b68798bc` and seems to be working fine 
image

[logs_gateway_app.log.2022-06-07.log](https://github.com/hummingbot/hummingbot/files/8851945/logs_gateway_app.log.2022-06-07.log)

**Comment by rapcmia** [comment]
Tried to test the latest commit `e229f1c` but still getting the same issue `Avalanche is not available` on docker logs resulting client to be stuck on `markets not ready`

Local testing with docker desktop
image

AWS instance
image

Crosscheck with dev branch `f37e9a31`
image

Attached:
[logs_gateway_app.log.2022-06-09.log](https://github.com/hummingbot/hummingbot/files/8866832/logs_gateway_app.log.2022-06-09.log)

**Comment by JeremyKono** [comment]
Moving this PR to July release as it hadn't met the deadline last week.

**Comment by JeremyKono** [comment]
Hi, please resolve conflicts in this PR. Thanks!

**Review by rapcmia — APPROVED** [review]
Test performed:
- Clone and install sucessfully
- Manually create gateway docker image for testing, ok 
- Connect Moralis and Pangolin-Avax wallet then balance check, ok 
- Setup simple AMM arb strategy using WAVAX-USDT.e
- Setup gasPriceRefreshInterval from 60 to 30s and 10s intervals
- Monitor docker logs while doing trade executions, gasPrice changes displayed
- Trades are successful and fees, CSV and txhash matched
- Tested on both source (AWS) and docker (local/docker desktop)

**Review by Faouzijedidi1 — APPROVED** [review]
LGTM

**Pull request merged**
