### PR TITLE
(fix) campaign_retval type error

### PR DESCRIPTION
**Pull request by KimChow**
campaign_retval sometimes is str or None.

**Before submitting this PR, please make sure**:

* [ ] Your code builds clean without any errors or warnings
* [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

2021-07-30 07:20:33,632 - 5266 - hummingbot.connector.parrot - ERROR - Unexpected error while requesting data from Hummingbot API.
Traceback (most recent call last):
File "/home/clint_g/hb-general/hummingbot/connector/parrot.py", line 32, in get_campaign_summary
campaigns = await get_active_campaigns(exchange, trading_pairs)
File "/home/clint_g/hb-general/hummingbot/connector/parrot.py", line 70, in get_active_campaigns
for market in campaign_retval["markets"]:
TypeError: string indices must be integers

campaign_retval sometimes is str or None. By adding campaign_retval type detection to prevent errors during operation

**Tests performed by the developer**:

During operation, the above prompt will no longer appear

**Tips for QA testing**:

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramz9u) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by dennisocana** [comment]
This seems to be a fix for this bug https://github.com/CoinAlpha/hummingbot/issues/3823

@KimChow thanks for contributing. We have other pull requests from the community that are under code review now then we'll look into this. For now, please add unit tests coverage as part of the contribution requirements.

image

**Comment by KimChow** [comment]
This test coverage, I don't know how it should be. In actual tests, it is found that sometimes the returned result may only be characters or other types that cause errors. The way I can think of is to separate the request and specify the data type separately for unit testing during testing.

**Comment by phbrgnomo** [comment]
Hello @KimChow 

The Hummingbot Foundation just started the governance process for the community to approve or reject Pull Requests through **Pull Request Proposals**.

For more information about how PRP votes work, check this page: https://hummingbot.org/governance/prp/

We want to know if you still have interest in having your Pull Request merged into the main codebase.

If so, please check the following on your Pull Request for our team to be able to open it for community voting:

- Your Pull Request is targeted to the `development` branch
- Your branch is up to date with the current `development` branch
- All GitHub checks have passed
- There is no merging conflicts

If you have any questions or need any help, feel free to reach us out on the #dev-general channel on our Discord (https://discord.gg/HAgZ79nzU4)

----
If you have no interest in merging this PR to our code-base or don't reply to this comment in 30 days, the Foundation team will close this PR.

You can still create a new PR any time you want!

Thank you for contributing to Hummingbot Client!

**Comment by JeremyKono** [comment]
Closing this PR as the developer has not responded and created a PRP.

**Pull request closed without merging**
