### PR TITLE
Feat/dydx refactor

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

The default gold standard updates:
- Adapt all REST API interactions to use the recently developed web assistant.
- Adapt all websocket API interactions to use the recently developed web assistant.
- Change implementation of all data source classes to use only one websocket connection in each of them.
- Ensure all consumptions of the API are regulated by the use of the throttler (both REST and websocket API)
- Refactor the connector to use the newly developed client order tracker to manage in flight orders.
- Refactor the connector to stop using ad hoc logic to translate from exchange token-pair notation to client token-pair notation and the other way round. Instead keep track of the mapping base on the information provided by the exchange and the tokens composing each pair (as done in NDAX and Beaxy connectors)
- Ensure we are using the latest version of the exchange API.

Additional changes:
- Also addresses some issues with the current implementation of the perpetual py base.

**Tests performed by the developer**:

- Ran perpetual MM successfully.
- All test passing.

**Tips for QA testing**:

### CODE REVIEW

**Comment by dennisocana** [comment]
Hummingbot Improvement Proposal : https://snapshot.org/#/hbot-ip.eth/proposal/0x9f6a13e17917c688bac237fb311d652a787b46843598ec46050b36ae3780624d

**Comment by rapcmia** [comment]
Hi @petioptrv good day,
We would need you to fix the branch conflicts on the PR please, thank you

**Comment by rapcmia** [comment]
PR update:
- Initially tested and adding dYdX APIs are working ok 
- However our wallet got blocked atm and working on a new wallet address.

**Comment by rapcmia** [comment]
PR update:
- Create new wallet for test
- Setup simple Perpetual market making strategy using LINK-USD
- Create order and cancel accordingly
- Orderbook matched between client and exchange
- Trade data between client and exchange matched 
- Position created successfully
- Position retrieved when client is relaunched
- Position is successfully closed when exit price order is filled 
- Funding time worked as expected (every hour)

Pending:
- Monitor long term bot
- Check docker build

**Comment by rapcmia** [comment]
PR update:
Checked long term bot and noticed that its stuck on `failed to submit orders`.  Review the log file and noticed that after the client successfully filled the take profit order for SHORT position at `2022-11-08 14:32:41,000`, it did not create bid/ask to open a new position but instead continue to create another take profit order and doubles the order amount per filled event.

1. `2022-11-08 14:32:41,000` take profit order filled to close SHORT position however it seems the client failed to get the event resulting to create another take-profit to close the position with order_amount doubled `from 1LINK to 2LINK`
2. `2022-11-08 14:43:15,000` same scenario on step 1 and this time the order_amount doubled again from `2LINK to 4LINK`
3. This continued until `2022-11-08 15:38:52,001` where the order_amount was 32LINK and the client can't create order because balance is insufficient

We tried to reproduce but no go, running long term bot for the next 3-5hrs

Attached: Added labels # sell1 to sell8 for easy tracking
[partial-logs_perp-mm.log](https://github.com/hummingbot/hummingbot/files/9960015/partial-logs_perp-mm.log)

**Comment by aarmoa** [comment]
@rapcmia was the bot running using ONE-WAY position mode or HEDGED position mode? If possible please share the strategy configuration file. That will help use reproduce the same scenario.

**Comment by rapcmia** [comment]
Hi @aarmoa yes the config was set to `Oneway` since DyDx does not support `Hedge`. Apologies I think i forgot to add the config file earlier please see attached. Thank you

[perp-dydx.zip](https://github.com/hummingbot/hummingbot/files/9961003/perp-dydx.zip)

**Comment by rapcmia** [comment]
PR update:
- As of commit `4c6389d` we have not seen the previous reported issue.
   > Checked long term bot and noticed that its stuck on `failed to submit orders`. Review the log file and noticed that after the client successfully filled the take profit order for SHORT position at `2022-11-08 14:32:41,000`, it did not create bid/ask to open a new position but instead continue to create another take profit order and doubles the order amount per filled event.
- Orders for short position now creates the correct take-profit order and managed to close it. 
- We are running an overnight tests for this commit and review the logs again

**Review by rapcmia — DISMISSED** [review]
Test performed:
- Installed on both source and docker successfully
- Test valid and invalid APIs
- Connect dydx wallet and balance displayed correct
- Setup simple Perpetual-MM using LINK-USD
- Create and cancel order are all ok 
- Order execution is ok, the client managed to open position
- The connector was able to retrieve the position when the client is relaunched
- When the position is closed, the client managed to create bid/ask to open a new position again 
- DyDx does not support Hedge position mode 
- Trade data between client and exchange trade history matched 
- Setup testbot to run overnight for monitoring tests, logs reviewed and all are ok 
- Ran tests on source/docker build

**Review by cardosofede — APPROVED** [review]
LGTM!

**Comment by JeremyKono** [comment]
@aarmoa can you please resolve conflicts in this PR?

**Comment by JeremyKono** [comment]
@petioptrv can you please fix the failing tests in this PR? Thanks

**Review by rapcmia — APPROVED** [review]

**Pull request merged**
