### PR TITLE
Fix Bot Orchestration module - MQTT start command with script parameter

### PR DESCRIPTION
**Pull request by TheHolyRoger**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Fix Bot Orchestration module - MQTT start command with script parameter

Issue raised on discord by katarpilar:
https://discord.com/channels/530578568154054663/563462222878212098/1087430859134611598
Fixes: https://github.com/hummingbot/hummingbot/issues/6146

**Tests performed by the developer**:
Unittests

**Tips for QA testing**:
Usual MQTT orchestration steps

### CODE REVIEW

**Comment by klpanagi** [comment]
:+1:

**Comment by nikspz** [comment]
Issue reproduced using this PR and latest dev branch (dev-1.14.0)

Steps to reproduce:
1. Clone and install fix branch/development branch
2. Clone/install https://github.com/robotics-4-all/commlib-py
3. Clone/install https://github.com/robotics-4-all/commlib-cli.git
4. Clone https://github.com/hummingbot/brokers start emqx_v5 with ./launch
5. run the Client and execute mqtt start 
6. on separate terminal execute command to check/change config `commlib-cli --host localhost --port 1883 --btype mqtt rpcc 'hbot/bot1/config' '{"params": []}'`

Actual:
failed to check/change params config using commlib-cli
bot returns error:
```
ERROR - 1 validation error for Request value is not a valid list (type=type_error.list)
```

Expected: 
Able to check/change config using commlib-cli commands



[logs_paper.log](https://github.com/hummingbot/hummingbot/files/11050154/logs_paper.log)

```
2023-03-23 10:33:30,298 - 1255549 - commlib.rpc - ERROR - 1 validation error for Request
params
  value is not a valid list (type=type_error.list)
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/commlib/transports/mqtt.py", line 505, in _on_request_internal
    resp = self.on_request(self._msg_type.Request(**req_msg.data))
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Request
params
  value is not a valid list (type=type_error.list)
```
image

**Comment by TheHolyRoger** [comment]
Tests will fail right now, need to update the commlib dependency which will do tomorrow

**Comment by klpanagi** [comment]
@TheHolyRoger use version 0.10.6 from Pip for installing commlib-py

https://pypi.org/project/commlib-py/0.10.6/

**Comment by TheHolyRoger** [comment]
@cardosofede @nikspz the current failing test is nothing to do with us sirs, development branch is failing tests for my locally on the same test `test_get_listen_key_exception_raised` in `test.hummingbot.connector.derivative.binance_perpetual.test_binance_perpetual_user_stream_data_source`

**Comment by cardosofede** [comment]
@TheHolyRoger the test are okey on dev branch: 
image
The thing that is failing is that docker service is not available

**Pull request merged**
