### PR TITLE
Feat/gateway v2 openocean

### PR DESCRIPTION
**Pull request by onjeffery**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

GatewayV2 openocean.finance exchange added ethereum, harmony, polygon 3 chains again

**Tests performed by the developer**:

Write and pass unit tests, postman executes price and trade interface tests, and completes trade on-chain transactions

**Tips for QA testing**:

### CODE REVIEW

**Comment by fengtality** [comment]
Please base changed on `development` branch, not `master. Please read these contribution guidelines beforehand: https://docs.hummingbot.org/developers/contributions/

**Comment by rapcmia** [comment]
Hi @onjeffery good day
May you please update the PR to latest development branch, Thank you

**Comment by onjeffery** [comment]
image

This warning is the content of the token file in the gateway framework, and it should have nothing to do with openocean.

**Review by fengtality — APPROVED** [review]
LGTM

**Comment by nikspz** [comment]
Hi @onjeffery , could you check polygon? currently crosschecking on this issue
6015 polygon WMATIC USDC infura

**Comment by nikspz** [comment]
@onjeffery This behavior not showing for quickswap_polygon, do you think that's expected for openocean?

**Comment by onjeffery** [comment]
> 

image
1.The reason for the failure should be that our contract only authorized 5 USDC and needs about 11 USDC. But 1 WMATIC only needs about 1 USDC, so there is no warning
2.You should have authorized more than 5 USDC to quickswap, so there is no such warning

**Comment by rapcmia** [comment]
PR update:
- Ran test on AWS instance Ubuntu20.04lts
- Setup source client + gateway: ok 
- Setup docker client + gateway: ok 
- Connect openocean wallet for ethereum, harmony and polygon successfully
- Balance displays correct as well as `gateway connector-tokens`
- `gateway list` now shows the supported chains for openocean connector 
- Setup simple AMM-arb strategy
   - Token approval done manually and showing profitability on the client
   - Monitor for couple of hours, all ok
   - Order execution displays insufficient balance as well
 
 PR is good for approval however due to failing GitHub CI we have to make sure it is passed. Our team will have a look on this issue and will update you. Thank you
 
image

**Comment by fengtality** [comment]
@onjeffery There is an error in the OpenOcean configs that you need to fix. Before you submit the pull request, you should able to run `yarn test:cov` successfully, since that's the command that Github CI is also running.

(hummingbot) ➜  gateway git:(openocean-finance-feat/gateway-v2_openocean) yarn test:cov
yarn run v1.22.10
warning ../../../package.json: No license field
$ NODE_OPTIONS=--max_old_space_size=8192 jest -w 1 --coverage --forceExit ./test/
Error: Jest: Got error running globalSetup - /Users/feng/Code/hummingbot/gateway/test/setup.ts, reason: openocean config file seems to be outdated/broken due to "type" in "/contractAddresses/avalanche/routerAddress" - must be object. Kindly fix manually.
    at ConfigurationNamespace.loadConfig (/Users/feng/Code/hummingbot/gateway/src/services/config-manager-v2.ts:153:31)
    at new ConfigurationNamespace (/Users/feng/Code/hummingbot/gateway/src/services/config-manager-v2.ts:124:14)
    at ConfigManagerV2.addNamespace (/Users/feng/Code/hummingbot/gateway/src/services/config-manager-v2.ts:278:78)
    at ConfigManagerV2.loadConfigRoot (/Users/feng/Code/hummingbot/gateway/src/services/config-manager-v2.ts:354:18)
    at new ConfigManagerV2 (/Users/feng/Code/hummingbot/gateway/src/services/config-manager-v2.ts:233:14)
    at ConfigManagerV2.getInstance (/Users/feng/Code/hummingbot/gateway/src/services/config-manager-v2.ts:242:41)
    at new OverrideConfigs (/Users/feng/Code/hummingbot/gateway/test/config.util.ts:22:64)
    at Object.<anonymous> (/Users/feng/Code/hummingbot/gateway/test/config.util.ts:43:26)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._compile (/Users/feng/Code/hummingbot/gateway/node_modules/pirates/lib/index.js:136:24)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by onjeffery** [comment]
> 

image
image


I executed "yarn jest -w 1 --coverage --forceExit ./test/" locally and did not report your error. Can I trouble you to confirm your "openocean-schema.json" file?

**Pull request closed without merging**
