### PR TITLE
[feat] cross exchange mining

### PR DESCRIPTION
**Pull request by bsmeaton**
The cross exchange mining strategy sets orders on a maker exchange and seeks to profit off of the difference in the spread between taker and maker exchanges. The strategy is similar to the cross exchange market making strategy however it is more reliable in ensuring orders on the taker side are filled and assets remain hedged and balanced across exchanges. This is done by instead of looking for fill events on the maker side and attempting a trade on the taker (Which can fail) it constantly surveys the balance of currency across exchanges and buys or sells the currency on the most profitable exchange when a fill on the maker side occurs. This process is continuous and will not allow the hedge to fail.

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
The pull request adds a new strategy named cross exchange mining, the strategy is similar to cross exchange market making but instead of taker trades being acted upon from a maker side fill event, the strategy instead constantly monitors balances of the base asset across the two exchanges and upon finding a reduction or addition of the base asset above or below the set base amount (caused by a sell or buy event on the maker exchange), will attempt to balance by increasing or decreasing the asset through a market order on the most profitable exchange. This balancing process is checked each tick meaning the user will not be left with base asset unhedged in case of a single market order failure.

This results in a much more stable and reliable strategy as the XEMM strategy can often become unbalanced over time due to unforseen issues or events that cause the taker side market order to fail. This is the key reason that users would lose money on this strategy due to a loss of quote and base balance across exchanges.

Additional features
1. Addition of a volatility calculation that will widen the spread automatically
2. Addition of a script to scan the data/trades file for completed and hedged orders to calculate current profitability on the last 24 hrs
3. Addition of a feature (maker_buffer_qty) for when prices on taker and maker exchanges are extremely far away from each other and therefore to achieve the min_profitability figure would mean a very high spread, this can allow the script to place the order at the price level consistent with this order qty, which although would not be profitable if the order was filled would increase mining rewards (Currently some issues would advise against use)

**Tests performed by the developer**:
Four weeks run time across three exchanges (Kucoin, Binance, Gate) with 10-20K of assets.

**Tips for QA testing**:

### CODE REVIEW

**Comment by nikspz** [comment]
`status` and `status --live` showing raw data for current active orders 
 
 Steps to reproduce:
 create cross exchange mining strategy
 start the bot and wait for orders placed
 check  `status` or `status --live`
 
 Actual:
 Bot's showing raw data, not showing the exchange, order age
 
 Expected:
 Bot shows user friendly info of active orders and order age
 
image
image

**Comment by nikspz** [comment]
Bot showing Unexpected error running clock tick. (AttributeError: 'CrossExchangeMiningPair' object has no attribute 'market') on the initial start of the bot

Steps to reproduce:
create cross-exchange mining strategy with sufficient funds to do the one trade on both sides of taker and maker exchanges)
start the bot

Actual: 
Bot showing Unexpected error running clock tick. (AttributeError: 'CrossExchangeMiningPair' object has no attribute 'market') 

Expected:
Bot started successfully, No error should occur.


[logs_xemining2-11-10.log](https://github.com/hummingbot/hummingbot/files/9760061/logs_xemining2-11-10.log)
[xemining2-11-10 - Copy.txt](https://github.com/hummingbot/hummingbot/files/9760062/xemining2-11-10.-.Copy.txt)

```
2022-10-05 12:42:29,028 - 66947 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/cross_exchange_mining/cross_exchange_mining.pyx", line 501, in hummingbot.strategy.cross_exchange_mining.cross_exchange_mining.CrossExchangeMiningStrategy.c_tick
    self.c_cancel_order(market_pair, active_order.client_order_id)
  File "hummingbot/strategy/strategy_base.pyx", line 589, in hummingbot.strategy.strategy_base.StrategyBase.c_cancel_order
    ConnectorBase market = market_trading_pair_tuple.market
AttributeError: 'CrossExchangeMiningPair' object has no attribute 'market'
```
Xemining2 - Unexpected error running clocktick

**Review by cardosofede — CHANGES_REQUESTED** [review]
I think that the strategy can work, but also there are some improvements: 
- define a balance target in percentage for one of the markets.
- the logic of the set order and check balance can be improved
- the only thing that makes the strategy adjust using the balance is the balance_adjustment_duration. I think that also you can add some validations.

**Comment by bsmeaton** [comment]
@cardosofede thankyou for taking the time to review! Agree that the percentage target across exchanges is a good future improvement but I wouldn't have said it was required for the strategy to function. The check and set orders improvement seems a bit vague is there any further notes on this? I don't agree with the balance adjustment duration being an integral part of the strategy it could be removed or set to 0 and the strategy would just balance when required. The variable doesn't initiate balancing of the wallets it simply provides a time gap between subsequent rebalancing. Tbh there's no good reason why this is required if set for 5s and you had two limit orders filled within that time the strategy would immediately rebalance the first one but then not rebalance the second until after 5s. I can remove this variable.

**Comment by cardosofede** [comment]
@bsmeaton as it's a community strategy, the logic that you provide is up to you and to the community to improve it.
The problem with the rebalance is that if you are running that process before the balance is updated, you can have then some issues .
My recommendation is to fix those small observations and ask the community what they think about it and start working on improving the strategy.
The last thing that I didn't mention...  
Link of the strategy design template: https://hummingbot-foundation.notion.site/Cross-Exchange-Mining-3ed5f77af5134505ac88f7d5923905a5
It was one of the clearest templates, and if you like we can do a session where you can present the strategy by using the template and the people can ask you about it.

**Comment by cardosofede** [comment]
@bsmeaton sorry one more.
The test are failing because you are not following the flake8 rules.
You should fix them. 

image

**Comment by cardosofede** [comment]
Just to summarize:
- Fix the issues mentioned in the code
- Fix the Flake8 errors
With that we are ready to merge @bsmeaton

**Comment by bsmeaton** [comment]
@cardosofede understood! Thanks

**Comment by bsmeaton** [comment]
Hi @preze93 thanks for the interest! On the first question your right currently the buy/sell with market function has the market order flag for balancing but it does add a slippage buffer amount on the price if put through as a limit order. This seems to work fine with exchanges like gate.io
For the second question there is a min order amount variable which is designed to prevent this problem it essentially acts to prevent balancing if the amount to balance is less than this figure.

**Comment by preze93** [comment]
Hi @bsmeaton, I tried installing it to test it but I'm getting this error:
image

Am I doing anything wrong?

**Comment by bsmeaton** [comment]
Interesting one although I haven't updated to 1.9, would it be possible to just show the log file output in hummingbot/logs

**Comment by preze93** [comment]
[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/9861870/logs_hummingbot.log)

Here you go mate @bsmeaton

**Comment by nikspz** [comment]
Could you please fix UI issues on `create cross exchange mining startegy` step?

remove one redundant `>>>` here:
image

**Comment by preze93** [comment]
Hi @bsmeaton 
I'm getting a few errors with some exchanges like OKX, FTX, Gate.IO that sometimes prevents orders from being executed
Have you noticed this in your tests?

[bugs.log](https://github.com/hummingbot/hummingbot/files/9927101/bugs.log)


Log file attached

**Comment by bsmeaton** [comment]
> Hi @bsmeaton 
> 
> I'm getting a few errors with some exchanges like OKX, FTX, Gate.IO that sometimes prevents orders from being executed
> 
> Have you noticed this in your tests?
> 
> 
> 
> [bugs.log](https://github.com/hummingbot/hummingbot/files/9927101/bugs.log)
> 
> 
> 
> 
> 
> Log file attached

Thanks @preze93 I haven't seen any errors on gate while using it, the errors tend to come if you don't have enough enough balance on either exchange to make the order, it's worth setting order amount lower than your amount of quote currency so there's some buffer. I don't have accounts with OKX or FTX to check those, I've mainly checked on binance, kucoin and gate.

**Comment by nikspz** [comment]
@bsmeaton  Found another minor issue with UI, Currently `filled trades not showed on the output pane` (hovewer `filled orders show on Log pane and Bottom navigation bar`)


Steps:
1. start a XEMining strategy and set up tight to get filled orders
2. Review output pane

Actual:
filled trades not showed on the output pane
image

Expected:
filled trades showed on the output pane

example from XEMM strategy run:
image

**Review by nikspz — APPROVED** [review]
Tests performed:

- Cloned and installed feature branch
- Started bot successfully with no errors
- Created XEMining strategy
- Changed strategy configs caused no issue
- Reviewed params changed accordingly
- Started XEMining strategy using spot LM connectors
- Reviewed no errors showed on the run
- Order cancellation = OK
- Reviewed history, CSV and exchange matched after filled order events

Notes:
1. issue with UI, Currently filled trades not showed on the output pane (hovewer filled orders show on Log pane and Bottom navigation bar), discussed that could be fixed later
2.Faced XEMM issue (https://github.com/hummingbot/hummingbot/issues/5284), not related to this PR

**Review by cardosofede — APPROVED** [review]
LGTM!

**Comment by JeremyKono** [comment]
Hi @bsmeaton can you please create a strategy file in the hummingbot.org website? Thanks!

**Pull request merged**
