### PR TITLE
fix/ add wallet and other bugs

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This pr fixes bug introduced in ref connector pr when adding wallet on the client.

In addition, it also provides fix for the following bugs which were outside that pr:
- Bug due to no validator for polygon when adding a wallet for polygon connectors
- Bug due to incorrect parsing of gateway connector names. 

**Tests performed by the developer**:
- End-to-end testing. Added wallets and ran the balance command.

**Tips for QA testing**:
- Perform end-to-end testing. Add wallets and run the balance command.

### CODE REVIEW

**Comment by vic-en** [comment]
Primarily fixes https://github.com/hummingbot/hummingbot/pull/5888

**Comment by rapcmia** [comment]
PR update: 
- Successfully connected the wallets for other connectors uniswap, uniswaplp, pangolin and ref. 
- However we are not able to connect to mad_meerkat and vvs finance, getting error `Unhandled error in background task: Error on POST https://localhost:20413/wallet/add`
```
2022-11-16 13:37:23,064 - 16773 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Error on POST https://localhost:20413/wallet/add Error: {'message': 'No validator exists for cronos.', 'httpErrorCode': 404, 'errorCode': -1, 'stack': 'Error: No validator exists for cronos.\n    at throwIfErrorsExist (/usr/src/app/dist/src/services/validators.js:38:15)\n    at /usr/src/app/dist/src/services/validators.js:103:40\n    at /usr/src/app/dist/src/services/wallet/wallet.routes.js:25:58\n    at Generator.next (<anonymous>)\n    at /usr/src/app/dist/src/services/wallet/wallet.routes.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/src/app/dist/src/services/wallet/wallet.routes.js:4:12)\n    at /usr/src/app/dist/src/services/wallet/wallet.routes.js:24:86\n    at /usr/src/app/dist/src/services/error-handler.js:37:28\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/src/app/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)'}
Traceback (most recent call last):
  File "/home/rapcmia/github/5888/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/rapcmia/github/5888/hummingbot/client/command/gateway_command.py", line 431, in _gateway_connect
    response: Dict[str, Any] = await self._get_gateway_instance().add_wallet(
  File "/home/rapcmia/github/5888/hummingbot/core/gateway/gateway_http_client.py", line 264, in add_wallet
    return await self.api_request(
  File "/home/rapcmia/github/5888/hummingbot/core/gateway/gateway_http_client.py", line 218, in api_request
    raise e
  File "/home/rapcmia/github/5888/hummingbot/core/gateway/gateway_http_client.py", line 206, in api_request
    raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
ValueError: Error on POST https://localhost:20413/wallet/add Error: {'message': 'No validator exists for cronos.', 
```

Endpoint for `wallet/add` on Cronos chain 
Screenshot 2022-11-16 135215

Steps to reproduce:
1. Run gateway connect mad_meerkat or vvs
2. At the prompt of enter your private key, it would return the error on the log panel

Attached:
[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/10018490/logs_hummingbot.log)

**Comment by JeremyKono** [comment]
@vic-en can you also look at the failed gateway tests?

**Comment by nikspz** [comment]
> Endpoint for `wallet/add` on Cronos chain Screenshot 2022-11-16 135215
> 
Happened also for Docker-Client/Docker-gateway build
image

**Comment by vic-en** [comment]
@JeremyKono @nikspz @rapcmia 
Pls reported issues resolved.

**Comment by nikspz** [comment]
`Issue` with Failed to gateway connect Mad Meerkat and VVS connector `fixed` on [c8e88f5](https://github.com/hummingbot/hummingbot/pull/5888/commits/c8e88f597309e64c971fe4c2f4e714ffc4fbefe7)

Tests performed: 

Cloned and installed fix branch
Manually created gateway image successfully 

- vvs and mad_meerkat connected, checked balance successfully 
- uniswap (mainnet,optimism, arbitrum-one), polygon connected, checked balance successfully 
- uniswapLP ethereum (mainnet,optimism, arbitrum-one), polygon connected, checked balance successfully 
- pangolin, traderjoe, openocean avalanche connected, checked balance successfully 
- quickswap polygon connected, checked balance successfully
- perp optimism connected, checked balance successfully
- defira harmony connected, checked balance successfully
- sushiswap ethereum mainnet connected, checked balance successfully 
- ref near mainnet connected, checked balance successfully
Checked connector-tokens working as expected
Manually created docker image of instance successfully
Tested on AWS Source+dockergw

Pending: 
Docker-dockergateway test

**Review by rapcmia — APPROVED** [review]
Test performed: 
- Setup gateway all gateway connector wallets successfully 
- Setup gateway connector-tokens successfully 
- Balance command display the assets correct
- Test on source and docker gateway builds 
- Test on soruce and docker client builds
- Setup and monitor AMM-Arbitrage strategy and had runtime of 10-15s each connector, all ok

**Pull request merged**
