### PR TITLE
Fix/controller total amount decimal

### PR DESCRIPTION
**Pull request by cardosofede**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Fix an error introduced in a previous PR regarding to the type of the total amount quote.

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by rapcmia** [comment]
Test in progress

**Comment by rapcmia** [comment]
PR update:
- Test commit `118de3ad7f45b4867260ec4c8202077c796cfd6e`
- Compare behavior with development branch `in progress`
- Setup pmm_simple controller and dmanv2, getting TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
  image
  ```
  2024-08-02 12:02:47,030 - 53012 - hummingbot.client.hummingbot_application - INFO - Creating the clock with tick size: 1.0
  2024-08-02 12:02:47,031 - 53012 - hummingbot.client.hummingbot_application - INFO - start command initiated.
  2024-08-02 12:02:47,532 - 53012 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
  2024-08-02 12:02:47,791 - 53012 - hummingbot.connector.exchange.binance.binance_api_user_stream_data_source.BinanceAPIUserStreamDataSource - INFO - Successfully obtained listen key XR88xf34rE8stk8cNdlS2kxVwngpVm9NoI8ICdjz4aGA5ON25esZK7j17YDG
  2024-08-02 12:02:48,109 - 53012 - hummingbot.strategy.script_strategy_base - WARNING - binance is not ready. Please wait...
  2024-08-02 12:02:48,151 - 53012 - hummingbot.connector.exchange.binance.binance_api_order_book_data_source.BinanceAPIOrderBookDataSource - INFO - Subscribed to public order book and trade channels...
  2024-08-02 12:02:48,201 - 53012 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for NOT-USDT. 1/1 completed.
  2024-08-02 12:02:49,013 - 53012 - hummingbot.strategy.script_strategy_base - WARNING - binance is not ready. Please wait...
  2024-08-02 12:02:50,153 - 53012 - hummingbot.strategy_v2.runnable_base - ERROR - unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
  Traceback (most recent call last):
    File "/Users/rapcomia/github/hummingbot/7151/hummingbot/strategy_v2/runnable_base.py", line 69, in control_loop
      await self.control_task()
    File "/Users/rapcomia/github/hummingbot/7151/hummingbot/strategy_v2/controllers/controller_base.py", line 163, in control_task
      executor_actions: List[ExecutorAction] = self.determine_executor_actions()
    File "/Users/rapcomia/github/hummingbot/7151/hummingbot/strategy_v2/controllers/market_making_controller_base.py", line 230, in determine_executor_actions
      actions.extend(self.create_actions_proposal())
    File "/Users/rapcomia/github/hummingbot/7151/hummingbot/strategy_v2/controllers/market_making_controller_base.py", line 241, in create_actions_proposal
      price, amount = self.get_price_and_amount(level_id)
    File "/Users/rapcomia/github/hummingbot/7151/hummingbot/strategy_v2/controllers/market_making_controller_base.py", line 305, in get_price_and_amount
      spreads, amounts_quote = self.config.get_spreads_and_amounts_in_quote(trade_type)
    File "/Users/rapcomia/github/hummingbot/7151/hummingbot/strategy_v2/controllers/market_making_controller_base.py", line 207, in get_spreads_and_amounts_in_quote
      return spreads, [amt_pct * self.total_amount_quote for amt_pct in normalized_amounts_pct]
    File "/Users/rapcomia/github/hummingbot/7151/hummingbot/strategy_v2/controllers/market_making_controller_base.py", line 207, in <listcomp>
      return spreads, [amt_pct * self.total_amount_quote for amt_pct in normalized_amounts_pct]
  TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
  2024-08-02 12:02:50,309 - 53012 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
  2024-08-02 12:02:51,164 - 53012 - hummingbot.strategy_v2.runnable_base - ERROR - unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
  Traceback (most recent call last):
    File "/Users/rapcomia/github/hummingbot/7151/hummingbot/strategy_v2/runnable_base.py", line 69, in control_loop
      await self.control_task()
    File "/Users/rapcomia/github/hummingbot/7151/hummingbot/strategy_v2/controllers/controller_base.py", line 163, in control_task
      executor_actions: List[ExecutorAction] = self.determine_executor_actions()
    File "/Users/rapcomia/github/hummingbot/7151/hummingbot/strategy_v2/controllers/market_making_controller_base.py", line 230, in determine_executor_actions
      actions.extend(self.create_actions_proposal())
    File "/Users/rapcomia/github/hummingbot/7151/hummingbot/strategy_v2/controllers/market_making_controller_base.py", line 241, in create_actions_proposal
      price, amount = self.get_price_and_amount(level_id)
    File "/Users/rapcomia/github/hummingbot/7151/hummingbot/strategy_v2/controllers/market_making_controller_base.py", line 305, in get_price_and_amount
      spreads, amounts_quote = self.config.get_spreads_and_amounts_in_quote(trade_type)
    File "/Users/rapcomia/github/hummingbot/7151/hummingbot/strategy_v2/controllers/market_making_controller_base.py", line 207, in get_spreads_and_amounts_in_quote
      return spreads, [amt_pct * self.total_amount_quote for amt_pct in normalized_amounts_pct]
    File "/Users/rapcomia/github/hummingbot/7151/hummingbot/strategy_v2/controllers/market_making_controller_base.py", line 207, in <listcomp>
      return spreads, [amt_pct * self.total_amount_quote for amt_pct in normalized_amounts_pct]
  TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
  2024-08-02 12:02:52,167 - 53012 - hummingbot.strategy_v2.runnable_base - ERROR - unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
  ```
    - seems only market_making controllers are affected 
- Setup supertrend_v1 controller, ok
- Setup xemm_multiple_orders  controller, ok

Steps to reproduce:
- Setup market_making controllers then start script

[08022024.zip](https://github.com/user-attachments/files/16465380/08022024.zip)

**Comment by rapcmia** [comment]
PR update for commit `f0211814778964895ee06507f818bd1bcf404e8c`
> Setup pmm_simple controller and dmanv2, getting TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
- Fixed 👍🏼 
- Successfully run market making controllers ok 
- Ran quick tests on supertrend and xemm_multiple_pairs controllers ok 
- Ran online make test locally with excluding ndax, getting errors:
  ```
      ---
      loop = loop or asyncio.get_running_loop()
  RuntimeError: no running event loop
  ```
   - See attached log file [08022024_online.log](https://github.com/user-attachments/files/16472384/08022024_online.log)

**Review by nikspz — APPROVED** [review]
f021181
Test performed:
- Cloned and installed PR7151
- Reviewed TypeError: unsupported operand type(s) for /: 'float' and 'decimal.Decimal' was fixed for:
  - bollinger_v1 binance_perpetual: ok, got orders filled
  - dman_v3 on okx_perpetual: ok
  - xemm on binance + okx: ok
  - pmm_simple: ok
  
Pending: Failing tests fix


candles fix xemm ok

image

**Review by rapcmia — APPROVED** [review]
LGTM
- Ran tests on market making and directional controllers ok 
- Reported issue on tests has been fixed by dev

---

Note: PR good to merge, attache are the `make tests` done locally online/offline using MacOS (m1)
- There are failing tests due to:
  ```
  pydantic.error_wrappers.ValidationError: 1 validation error for BaseTradingStrategyConfigMap
  market
    COINALPHA-HBOT is not an active market on binance. (type=value_error)
  ```
[08052024_offline.log](https://github.com/user-attachments/files/16495142/08052024_offline.log)
[08052024_online.log](https://github.com/user-attachments/files/16495143/08052024_online.log)

**Pull request merged**
