### PR TITLE
Feat/injective v2 rate limits

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Configuring the rate limits for Injective V2 connectors (spot and perpetual) according to the new rate limits that will be enforced for the public nodes in the coming days.
- Fixed an issue when requesting the latest trades for a market. The response when there are still no trades is different than expected in the initial implementation.
- Included a validation to avoid errors when parsing markets info for markets with tickers that do not follow the pattern "BASE/QUOTE"
- Added some missing dependencies present in the file "environment.yml" that were not included in "setup.py"

**Tests performed by the developer**:
All unit tests passing in green.
Tested running a bot with a pure market making strategy using the spot connector for delegated accounts.

**Tips for QA testing**:
The public Injective nodes are not enforcing the rate limits yet, so it is not possible to test that the rate limits configuration is correct. For the moment the validation performed should be just running a bot and checking that it operates without failing due to an invalid or not found rate limit

### CODE REVIEW

**Review by cardosofede — APPROVED** [review]
LGTM!

**Comment by aarmoa** [comment]
@cardosofede if possible let's wait to merge. I am investigating an issue that Ralph sent me in Discord. It seems there are issues with grpc libraries in Mac ARM that started happening yesterday in `development`

**Comment by aarmoa** [comment]
It seems like the issues are fixed. Please proceed.

**Comment by aarmoa** [comment]
The current version is producing again the segmentation fault error in Mac Intel

**Comment by aarmoa** [comment]
I had to add an extra line in `install` script to reinstall `grpcio` in Mac Intel machines, because the `grpcio` package from conda is broken for Mac Intel (caused the segmentation fault)

**Comment by rapcmia** [comment]
PR update:
- Test latest commit `9de5ab59ba7f72`
- Ran tests on local Macbook (m1)
- On different tests below, we had to remove the hummingbot env per different platform {osx-64, osx-arm64}
- Ran tests on `osx-64` platform and still having the issue on segment fault like on mac-intel build ❌ 
- Ran tests on `osx-arm64`, all ok ✅ 
- Ran`account_delegation_script.py`
  - When running the script on a `osx-64` or mac-intel build you would get this error:
    image
  

Steps to reproduce 
1. Make sure hummingbot is not available on `conda env list`, else remove it
2. change platform to osx-64 running `conda config --env --set subdir osx-64`
3. Run source installation 
4. Start client, observe segment fault error 
5. Run account_delegation_script.py, observe segment fault error  

 ---

Ran injective_v2 for both PMM and PerpMM
- Connect both on mainnet `{sentry0 and sentry3}`
- For spot connector, we are getting failed to submit order due to small spendable balance smaller than `73389500000000inj`
    ```
    2023-09-01 14:47:23,576 - 42072 - hummingbot.connector.exchange.injective_v2.injective_v2_exchange.InjectiveV2Exchange - NETWORK - Error submitting buy LIMIT_MAKER order to Injective_v2 for 0.800000 ATOM-USDT 6.870.
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/6552/hummingbot/connector/exchange/injective_v2/data_sources/injective_data_source.py", line 442, in create_orders
        raise ValueError(f"Error sending the order creation transaction ({result['rawLog']})")
    ValueError: Error sending the order creation transaction (spendable balance  is smaller than 73389500000000inj: insufficient funds: insufficient funds)
    2023-09-01 14:47:23,577 - 42072 - hummingbot.connector.exchange.injective_v2.injective_v2_exchange.InjectiveV2Exchange - WARNING - Failed to submit buy order to Injective_v2. Check API key and network connection.
    ```
- For perpetual connector, same error due to spendable balance smaller than `116867000000000inj`
    ```
    2023-09-01 14:45:06,001 - 42072 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Changing position mode to ONEWAY succeeded.
    2023-09-01 14:45:07,002 - 42072 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ATOM-USDT) Creating 1 LIMIT bid orders at (Size, Price): ['0.9 ATOM, 6.868 USDT'] to OPEN position.
    2023-09-01 14:45:07,003 - 42072 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ATOM-USDT) Creating 1  LIMIT ask orders at (Size, Price): ['0.9 ATOM, 7.006 USDT'] to OPEN position.
    2023-09-01 14:45:11,377 - 42072 - hummingbot.connector.derivative.injective_v2_perpetual.injective_v2_perpetual_derivative.InjectiveV2PerpetualDerivative - NETWORK - Error submitting buy LIMIT order to Injective_v2_perpetual for 0.90 ATOM-USDT 6.868000.
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/6552/hummingbot/connector/exchange/injective_v2/data_sources/injective_data_source.py", line 442, in create_orders
        raise ValueError(f"Error sending the order creation transaction ({result['rawLog']})")
    ValueError: Error sending the order creation transaction (spendable balance  is smaller than 116867000000000inj: insufficient funds: insufficient funds)
    2023-09-01 14:45:11,378 - 42072 - hummingbot.connector.derivative.injective_v2_perpetual.injective_v2_perpetual_derivative.InjectiveV2PerpetualDerivative - WARNING - Failed to submit buy order to Injective_v2_perpetual. Check API key and network connection.
    2023-09-01 14:45:11,378 - 42072 - hummingbot.connector.derivative.injective_v2_perpetual.injective_v2_perpetual_derivative.InjectiveV2PerpetualDerivative - NETWORK - Error submitting sell LIMIT order to Injective_v2_perpetual for 0.90 ATOM-USDT 7.006000.
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/6552/hummingbot/connector/exchange/injective_v2/data_sources/injective_data_source.py", line 442, in create_orders
        raise ValueError(f"Error sending the order creation transaction ({result['rawLog']})")
    ValueError: Error sending the order creation transaction (spendable balance  is smaller than 116867000000000inj: insufficient funds: insufficient funds)
    2023-09-01 14:45:11,379 - 42072 - hummingbot.connector.derivative.injective_v2_perpetual.injective_v2_perpetual_derivative.InjectiveV2PerpetualDerivative - WARNING - Failed to submit buy order to Injective_v2_perpetual. Check API key and network connection.
    ```
- After the failed to submit error, the connector then sends out this error on log panel
    ```
    2023-09-01 14:45:19,536 - 42072 - hummingbot.connector.exchange.injective_v2.data_sources.injective_grantee_data_source.InjectiveGranteeDataSource - ERROR - Error while listening to transaction stream, reconnecting ... (<AioRpcError of RPC that terminated with:
	    status = StatusCode.UNAVAILABLE
	    details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:15.235.86.222:9911: tcp handshaker shutdown"
	    debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:15.235.86.222:9911: tcp handshaker shutdown {created_time:"2023-09-01T14:45:19.534705+08:00", grpc_status:14}"
    >)
    ```  


Steps to reproduce:
1. Connect to mainnet {sentry0 or sentry3}
2. Make sure the market_id use is approved on the grantee account ✅ 
3. Setup spot or perp connector for `injective_v2`
4. Start and observe behavior 

[logs_pmm-injective-v2.log](https://github.com/hummingbot/hummingbot/files/12495259/logs_pmm-injective-v2.log)
[logs_perp-injective-v2.log](https://github.com/hummingbot/hummingbot/files/12495263/logs_perp-injective-v2.log)

**Comment by aarmoa** [comment]
> PR update:
> 
> * Test latest commit `9de5ab59ba7f72`
> * Ran tests on local Macbook (m1)
> * On different tests below, we had to remove the hummingbot env per different platform {osx-64, osx-arm64}
> * Ran tests on `osx-64` platform and still having the issue on segment fault like on mac-intel build ❌
>   
>   * Crosscheck the issue on latest development, not able to reproduce
> * Ran tests on `osx-arm64`, all ok ✅
> * Ran`account_delegation_script.py`
>   
>   * When running the script on a `osx-64` or mac-intel build you would get this error:
>     image
> 
> Steps to reproduce
> 
> 1. Make sure hummingbot is not available on `conda env list`, else remove it
> 2. change platform to osx-64 running `conda config --env --set subdir osx-64`
> 3. Run source installation
> 4. Start client, observe segment fault error
> 5. Run account_delegation_script.py, observe segment fault error
> 
> Ran injective_v2 for both PMM and PerpMM
> 
> * Connect both on mainnet `{sentry0 and sentry3}`
> * For spot connector, we are getting failed to submit order due to small spendable balance smaller than `73389500000000inj`
>   ```
>   2023-09-01 14:47:23,576 - 42072 - hummingbot.connector.exchange.injective_v2.injective_v2_exchange.InjectiveV2Exchange - NETWORK - Error submitting buy LIMIT_MAKER order to Injective_v2 for 0.800000 ATOM-USDT 6.870.
>   Traceback (most recent call last):
>     File "/Users/rapcomia/github/hummingbot/6552/hummingbot/connector/exchange/injective_v2/data_sources/injective_data_source.py", line 442, in create_orders
>       raise ValueError(f"Error sending the order creation transaction ({result['rawLog']})")
>   ValueError: Error sending the order creation transaction (spendable balance  is smaller than 73389500000000inj: insufficient funds: insufficient funds)
>   2023-09-01 14:47:23,577 - 42072 - hummingbot.connector.exchange.injective_v2.injective_v2_exchange.InjectiveV2Exchange - WARNING - Failed to submit buy order to Injective_v2. Check API key and network connection.
>   ```
> * For perpetual connector, same error due to spendable balance smaller than `116867000000000inj`
>   ```
>   2023-09-01 14:45:06,001 - 42072 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Changing position mode to ONEWAY succeeded.
>   2023-09-01 14:45:07,002 - 42072 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ATOM-USDT) Creating 1 LIMIT bid orders at (Size, Price): ['0.9 ATOM, 6.868 USDT'] to OPEN position.
>   2023-09-01 14:45:07,003 - 42072 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ATOM-USDT) Creating 1  LIMIT ask orders at (Size, Price): ['0.9 ATOM, 7.006 USDT'] to OPEN position.
>   2023-09-01 14:45:11,377 - 42072 - hummingbot.connector.derivative.injective_v2_perpetual.injective_v2_perpetual_derivative.InjectiveV2PerpetualDerivative - NETWORK - Error submitting buy LIMIT order to Injective_v2_perpetual for 0.90 ATOM-USDT 6.868000.
>   Traceback (most recent call last):
>     File "/Users/rapcomia/github/hummingbot/6552/hummingbot/connector/exchange/injective_v2/data_sources/injective_data_source.py", line 442, in create_orders
>       raise ValueError(f"Error sending the order creation transaction ({result['rawLog']})")
>   ValueError: Error sending the order creation transaction (spendable balance  is smaller than 116867000000000inj: insufficient funds: insufficient funds)
>   2023-09-01 14:45:11,378 - 42072 - hummingbot.connector.derivative.injective_v2_perpetual.injective_v2_perpetual_derivative.InjectiveV2PerpetualDerivative - WARNING - Failed to submit buy order to Injective_v2_perpetual. Check API key and network connection.
>   2023-09-01 14:45:11,378 - 42072 - hummingbot.connector.derivative.injective_v2_perpetual.injective_v2_perpetual_derivative.InjectiveV2PerpetualDerivative - NETWORK - Error submitting sell LIMIT order to Injective_v2_perpetual for 0.90 ATOM-USDT 7.006000.
>   Traceback (most recent call last):
>     File "/Users/rapcomia/github/hummingbot/6552/hummingbot/connector/exchange/injective_v2/data_sources/injective_data_source.py", line 442, in create_orders
>       raise ValueError(f"Error sending the order creation transaction ({result['rawLog']})")
>   ValueError: Error sending the order creation transaction (spendable balance  is smaller than 116867000000000inj: insufficient funds: insufficient funds)
>   2023-09-01 14:45:11,379 - 42072 - hummingbot.connector.derivative.injective_v2_perpetual.injective_v2_perpetual_derivative.InjectiveV2PerpetualDerivative - WARNING - Failed to submit buy order to Injective_v2_perpetual. Check API key and network connection.
>   ```
> * After the failed to submit error, the connector then sends out this error on log panel
>   ```
>   2023-09-01 14:45:19,536 - 42072 - hummingbot.connector.exchange.injective_v2.data_sources.injective_grantee_data_source.InjectiveGranteeDataSource - ERROR - Error while listening to transaction stream, reconnecting ... (<AioRpcError of RPC that terminated with:
>       status = StatusCode.UNAVAILABLE
>       details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:15.235.86.222:9911: tcp handshaker shutdown"
>       debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:15.235.86.222:9911: tcp handshaker shutdown {created_time:"2023-09-01T14:45:19.534705+08:00", grpc_status:14}"
>   >)
>   ```
> 
> Steps to reproduce:
> 
> 1. Connect to mainnet {sentry0 or sentry3}
> 2. Make sure the market_id use is approved on the grantee account ✅
> 3. Setup spot or perp connector for `injective_v2`
> 4. Start and observe behavior
> 
> [logs_pmm-injective-v2.log](https://github.com/hummingbot/hummingbot/files/12495259/logs_pmm-injective-v2.log) [logs_perp-injective-v2.log](https://github.com/hummingbot/hummingbot/files/12495263/logs_perp-injective-v2.log)

@rapcmia that seems more like a user error than a connector issue. Do you have enough INJ in the wallets you are using to broadcast transactions? You need to have enough INJ to pay for the gas fee

**Comment by rapcmia** [comment]
> @rapcmia that seems more like a user error than a connector issue. Do you have enough INJ in the wallets you are using to broadcast transactions? You need to have enough INJ to pay for the gas fee

Thanks for the reply:
- Our wallet have enough INJ to create order (metamask and helixapp) on mainnet, still getting the same behavior. Will approve and community should be able to use the connector with more funds.
- Ran testnet for long/short refresh time  and multiple order levels ✅ 
     - Trades data between client and exchange matched
- Issue on segment fault is now fixed on latest commit `8240edec7cb` able to test on osx_64 platform on mbp(m1)
- Ran tests on docker build ✅

**Review by rapcmia — APPROVED** [review]

**Review by cardosofede — APPROVED** [review]
LGTM!

**Pull request merged**
