### PR TITLE
(doc) update CONTRIBUTING to refer to the correct upstream repository

### PR DESCRIPTION
**Pull request by ctria**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
These changes follow the guidelines at:
https://hummingbot.org/developers/contributions/

**Tests performed by the developer**:
Not applicable, there are no code changes to be tested.

**Tips for QA testing**:
There is one more inconsistency regarding the preferred prefix for the documentation related branches.

The https://hummingbot.org/developers/contributions/#2-creating-your-branch and CONTRIBUTING.md mention "doc/" while the github PR template (https://github.com/hummingbot/hummingbot/blob/master/.github/pull_request_template.md) wants "docs/" (thus i didn't check the box above).

### CODE REVIEW

**Comment by ctria** [comment]
Resolves #5316

**Review by aarmoa — APPROVED** [review]
The change looks good.

--Reviewed in representation of the Hummingbot Foundation Technical DAO

**Comment by ctria** [comment]
PRP: https://snapshot.org/#/hbot-prp.eth/proposal/0x974c552ba9fe761a1d8389c8ef6445dc07f456163a62cc904d73b3bcdc10ed07

**Comment by JeremyKono** [comment]
Hi, @ctria. Please fix the failed GitHub checks in this PR. Thanks!

**Comment by ctria** [comment]
Yeah looks like another PR covered those :)

**Pull request closed without merging**
