### PR TITLE
Feat/dexalot

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This PR introduces the Dexalot connector. It's meant to be used with the `feat/dexalot` Gateway branch.

**Tests performed by the developer**:

- Unite tests
- Manually added and re-added a Dexalot wallet, Injective wallet, and a Uniswap wallet
- Tested balances
- Setup and executed a basic PMM strategy
- Examined the live order book and checked against the website

**Tips for QA testing**:

The exchange requires an API key which can be obtained by contacting the Dexalot team.
As with Injective, there could be a lot of failed order status updates here as well. If there are no lost orders at the end of the strategy run and all order fills are recorded correctly, then we are in good shape.

Please also do briefly test Injective as this PR makes changes to the CLOB connectors base class.

**Associated Gateway pr**
https://github.com/hummingbot/gateway/pull/65

**PRP**
https://snapshot.org/#/hbot-prp.eth/proposal/0x8bad2ca5bb8b699af91ab63c22698f2fae085ccc5ccaf1231360e42e0bd4b5ed

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update: Test in progress

@vic-en Can you please take a look on the GitHub failed tests, thank you🙇

**Comment by rapcmia** [comment]
Hi @vic-en 
We noticed this part on the setup of dexalot wallet. Just want to confirm how important is the dexalot API key for the wallet setup? Also just incase this is required to create a support ticket from them, are there other ways to contact the dexalot team for the API prompt? Thank you

image

While this happened we still managed to connect the wallet and balance displayed on the client.

**Comment by petioptrv** [comment]
@rapcmia, the API key is required, yes. Currently awaiting reply from the Dexalot team on best way to reach out.

**Comment by nikspz** [comment]
image
Steps:
Clone and install PR6153 and gatewayPR65
start the client and gateway ONLINE
gateway connect dexalot
on Enter your Dexalot API key paste your key

Actual:
Everyone could see the API key

Expected:
API Key is hidden with stars *

**Comment by nikspz** [comment]
Tests performed:

- Cloned and installed PR6153 and gw PR#65
- Connected dexalot_avalanche_dexalot with dexalot API key
- Created/started/imported strategy using dexalot: ok
- Balance command showing exchange balance: ok
PureMM and AMM_arb:
- Filled events work as expected
- Order cancellation: ok, bot cancel orders after bot stopped, manually placed orders stay on the exchange
- Data integrity confirmed synced to exchange
- History / -verbose display fiiled orders

Noted: Some runs bot could be triggered with failed to cancel order/orders after strategy stopped

**Review by cardosofede — APPROVED** [review]
LGTM!

**Comment by petioptrv** [comment]
@nikspz, the latest commit should fix the last cancelation error you reported, which is related to `amm_arb`. I will be investigating the pmm-related errors next.

**Comment by petioptrv** [comment]
@nikspz, for the logs you've sent (the issue where the bot failed to cancel one order during a PMM run), it looks like there was a network error that cut the communication between the client and Gateway. The strange thing is that your client CLI still shows gateway as connected... If this is truly due to network issues on the local machine, there is not much that can be done on either side of the code.

Looking up the SSL error message from the logs, I ended on discussions re multiple processes binding to the same port. If you see this issue happening again, can you please leave the bot running and try to issue a curl command to gateway (doesn't have to be to the Dexalot gateway connector), to see if it will respond. Then if it does, stop the strategy and without restarting the bot process, start another strategy that will use gateway. Finally, if that strategy also fails, restart the bot and attempt a gateway strategy again (can be the original Dexalot strategy). This sequence of tests will allow me to determine where I should look for the issue.

**Comment by rapcmia** [comment]
PR update:
We are checking why the exchange does not let us use some of our assets for creating orders atm. This is observed happening on both client and curl post_order which did not happened before on when PR is tested.

We currently don't have an open order on the exchange at the moment however the balance is showing that there is a allocated asset used.

image

image

Pending
- Retest Pure market making and AMM strategy
- Investigating where these orders are placed

**Comment by rapcmia** [comment]
> PR update:
> We are checking why the exchange does not let us use some of our assets for creating orders atm. This is observed happening on both client and curl post_order which did not happened before on when PR is tested.

The issue on balance has been resolved. It was related to the exchange and we are able to cancel these "active" orders that were sent yesterday's tests. Test is now in progress again

**Comment by rapcmia** [comment]
PR update:
- Tested on WSL and AWS both running on `Ubuntu20.04`
- Setup PMM on AVAX-USDC 
- Successfully created and cancelled order
    - It is noticeable there is a delay on cancellation of orders roughly 3-10s but no stuck orders occurred
    - When order amount is insufficient, it displays on logs
    - Getting `failed to fetch trade updates` and occurred more if your setup is with insufficient balance
       - While this happened, it stops when order is successfully created on the exchange which we assume is expected since the client is in the process to get the data from the exchange
       image
          ```
              2023-03-22 11:02:31,500 - 5331 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - WARNING - Failed to fetch trade updates for order 0x0000000000000000000a2d573d6c23057b593e88e3260ba2837ae8f79313ae5e. Error: 
              Traceback (most recent call last):
                File "/home/rapcmia/github/hummingbot/6153/hummingbot/connector/gateway/gateway_in_flight_order.py", line 150, in get_creation_transaction_hash
                  await self._creation_transaction_hash_update_event.wait()
                File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/asyncio/locks.py", line 309, in wait
                  await fut
              asyncio.exceptions.CancelledError
              
              During handling of the above exception, another exception occurred:
              
              Traceback (most recent call last):
                File "/home/rapcmia/github/hummingbot/6153/hummingbot/connector/exchange_py_base.py", line 979, in _update_orders_fills
                  trade_updates = await self._all_trade_updates_for_order(order=order)
                File "/home/rapcmia/github/hummingbot/6153/hummingbot/connector/gateway/clob_spot/gateway_clob_spot.py", line 591, in _all_trade_updates_for_order
                  trade_updates = await self._api_data_source.get_all_order_fills(in_flight_order=order)
                File "/home/rapcmia/github/hummingbot/6153/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 199, in get_all_order_fills
                  await self.get_order_status_update(in_flight_order=in_flight_order)
                File "/home/rapcmia/github/hummingbot/6153/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 172, in get_order_status_update
                  await in_flight_order.get_creation_transaction_hash()
                File "/home/rapcmia/github/hummingbot/6153/hummingbot/connector/gateway/gateway_in_flight_order.py", line 150, in get_creation_transaction_hash
                  await self._creation_transaction_hash_update_event.wait()
                File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
                  self._do_exit(exc_type)
                File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
                  raise asyncio.TimeoutError
              asyncio.exceptions.TimeoutError
          ```
    - We also observed of rate limited as well on a single orders    
       image
    - Orders are created and cancelled using `clob/batchOrders` endpoints based on docker logs
    - Run for 1-2hours with spreads enough for filled trade but still not able to get the opportunity but so far no stuck orders on the following test:
       - At cancelling order,  run stop command and check the exchange ✅ 
       - Run client for 3mins refresh time and observe order/cancel ✅ 
       - While client is running, run exit command and relaunch, no stuck orders ✅ 

Pending:
- Running long term bot for monitoring:
   - Order filled event, trade data between client and exchange 
   - Long refresh time (15mins) and behavior

**Comment by nikspz** [comment]
@petioptrv Could you please answer about dexalot API Key function? I ask because current one is not encrypted in gateway_connections.json

image

**Comment by nikspz** [comment]
Tests performed:
- Cloned and installed feature branch PR6153 + gateway PR65
- Connected dexalot with private key and dexalot API key successfully
- dexalot available on gateway list
- Create/start/import strategies using dexalot: ok
- Ran pureMM/amm_arb strategy using dexalot: ok
- Order cancellation: ok
- Filled order events: ok
- Data integrity synth with exchange: ok
- handling different order refresh time: ok
- Longterm bot test: ok
- Manually created docker image for PR6153 and gateway PR65
- Checked docker installation has no issues on strategy ran using dexalot

Note:  failed to fetch orders on logs due to exchange in the process of creating it

**Comment by petioptrv** [comment]
@nikspz, currently, the key is only used for WS connections, but all "secret" communication requires a signature obtained using the wallet private key, so the API key is not a piece of credential that can be used to perform any account actions. In fact, the Dexalot team is working on removing it for WS as well, in which case, the communication will become entirely based on the wallet private key (it will be a quick patch to remove the API key code).

**Comment by nikspz** [comment]
@petioptrv  Also I will add as a note that we Need to be clear where (link) to request API keys a request from community

**Comment by petioptrv** [comment]
@nikspz, a link for requesting API keys will have to be added on Gateway, so I will bring this up during our morning sync.

Please also note that Dexalot has informed us of an ongoing Avalanche incident that blocks transaction submission. I will post here as the situation develops.

**Comment by nikspz** [comment]
Merged the PR in behalf of foundation team to development and will be available on the next version 1.14.0

**Pull request merged**
