### PR TITLE
fix/hyperliquid_spot_backend_error

### PR DESCRIPTION
**Pull request by yancong001**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

fix the issue similar to  https://github.com/hummingbot/backend-api/issues/43

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by isreallee82** [comment]
This is not a bug. The key difference between the two code snippets lies in how the wallet is handled and the choices regarding reusability, scoping, and dependencies, which are more of a refactor...

**Comment by cardosofede** [comment]
@isreallee82 is a bug since you can't create an instance of the connector without the keys.
Actually the right solution should be if self._trading_required .... -> create wallet

**Comment by isreallee82** [comment]
hmm I see, it should be called only when trying to sign a transaction

**Comment by cardosofede** [comment]
@isreallee82 mmm, that's a solution that was implemented in this PR but I think that the original solution of doing the initialization in the __init__ was the right choice so you don't need to re-create that object every time that you sign. on the other hand, it should be only initialized if trading is required. if you want to take over and do it feel free to contribute, I think that this PR is not related to any bounty it is a contribution and you are the creator of this connector ;)

**Comment by isreallee82** [comment]
> @isreallee82 mmm, that's a solution that was implemented in this PR but I think that the original solution of doing the initialization in the **init** was the right choice so you don't need to re-create that object every time that you sign. on the other hand, it should be only initialized if trading is required. if you want to take over and do it feel free to contribute, I think that this PR is not related to any bounty it is a contribution and you are the creator of this connector ;)

Oh, it's fine. I'm open to any potential improvement. since this change is aimed at solving an error on the backend-api. I was only confused when the commit was described as a bug.

**Comment by cardosofede** [comment]
@isreallee82 

this is the error anytime that I want to initialize the connector without keys to use the public funcitonalities
image

**Comment by isreallee82** [comment]
oh i see @cardosofede

**Comment by isreallee82** [comment]
tried the trading_required method @cardosofede and it works fine

**Comment by isreallee82** [comment]
It’s so fun coding on hummingbot 🤩, just a little tweak i will run test and create pr.

**Comment by isreallee82** [comment]
pr #13936

**Pull request closed without merging**
