### PR TITLE
Feat/xemm gateway

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Adds an option to use DEX as taker exchanges through the gateway in the strategy.

**Tests performed by the developer**:

Added new unit tests
Ran all existing unit tests
Tested with binance paper & uniswap (kovan)
Tested with binance paper & pangolin (fuji)
Tested with binance & kucoin

**Tips for QA testing**:

Please test thoroughly both with CEX and DEX.

### CODE REVIEW

**Comment by mhrvth** [comment]
PRP: https://snapshot.org/#/hbot-prp.eth/proposal/0x1dae80eb568a0a9f31035d3b9763ef65711dda81f990389622933bbc39560283

**Comment by mhrvth** [comment]
@nikspz that seems to be an issue of the history command in how it handles gateway markets. The failure occurs in the current base balance query, which, looking into the history command's code, is taken from the market itself. This likely fails also for he `amm_arb` with the gateway. If that's the case, then it's not an issue of this PR, which is just about integration of the gateway connector into the XEMM.

**Comment by mhrvth** [comment]
Looking more closely into the code it looks like `get_all_balances()` of the gateway connector is returning a base asset balance as an integer, and not Decimal. Or not returning the base asset at all in the dictionary and instead in `_initialize_metrics()` 0 is taken, which is not a Decimal but an integer. 

Whatever is the case, this is not an issue of this PR but the gateway connector.

image


image

image

image

**Comment by nikspz** [comment]
> @nikspz that seems to be an issue of the history command in how it handles gateway markets. The failure occurs in the current base balance query, which, looking into the history command's code, is taken from the market itself. This likely fails also for he `amm_arb` with the gateway. If that's the case, then it's not an issue of this PR, which is just about integration of the gateway connector into the XEMM.

@mhrvth Yeah, similar issue was catched before in past versions here: https://github.com/hummingbot/hummingbot/issues/5115


however, for the amm_arb strategy `issue is not showing for latest dev-1.7.0` (using uniswap kovan and binance_paperTrade)
dev1 7 0- issue not showing for amm_arb (uniswap kovan - binancepaper

**Comment by mhrvth** [comment]
@nikspz beside my investigation that traced the true problem, since it happened for `amm_arb` before and no fix was created, it means it's a shared bug and the common denominator is either the gateway or the core code, but neither of the strategies. Therefore it's not an issue of this PR.

**Comment by nikspz** [comment]
Test performed:
Cloned and installed feature branch	
 - Manually created a docker image from /gateway folder = OK
 - Generated certs and gateway created = OK
 - Setup Cross-Exchange market making strategy = OK
 - Setup xemm with CEX and Kovan testnet = OK
Ethereum 
 - Setup xemm with CEX and Mainnet = OK
 - Setup xemm with papertrade and kovan testnet = OK
 - Setup xemm with papertrade and Mainnet = OK
Avalanche 
 - Setup xemm using CEX and Avalanche = OK
 - Setup xemm using papertrade and Avalanche = OK
CEX 
 - Setup xemm on any CEX connectors = OK
 
 ongoing issues: 
 bot not showing history and trades/assets/performance for history --verbose (https://github.com/hummingbot/hummingbot/issues/5115)

**Comment by rapcmia** [comment]
PR update:
- Manually created a docker image from /gateway folder
- Setup docker client + gateway 
- Tested XEMM configs with gateway
   - Does not support when order_amount is `0`
   - Notice some issues not related to PR, created separate ticket
- Setup XEMM Binance + uniswap_kovan: ok

Pending:
- XEMM pangolin + traderJoe
- XEMM CEX + avalanche
- XEMM CEX + CEX

**Review by nikspz — APPROVED** [review]
Test performed:
- Clone and install successfully
- Manually create docker gateway image for testing from /gateway folder 
- Manually create docker client image for testing
- Setup gateway nodeURLs for uniswap-kovan and avalanche
- Setup gateway connectors for ethereum and avalanche
- Setup simple XEMM strategy
    - Setup XEMM with paper + uniswap-kovan, ok 
    - Setup XEMM with paper + pangolin-avalanche or traderjoe-avalanche, ok 
    - Setup XEMM with CEX (binance) + uniswap-kovan, ok 
    - Setup XEMM with CEX (binance) + pangolin-avalanche or traderjoe-avalanche, ok 
    - Setup XEMM with DEX + DEX, not possible for GW connectors be set as maker connectors
    - SETUP XEMM with CEX + CEX, ok 
- Tested on source and docker build 
- Ran test bot overnight and review logs for possible long term running issues: ok
    - during overnight run 4 times got `Warning - Server disconnected` and `Gateway: failed to obtain order price`, however bot was able to reconnect and recover successfully
- Note: 
    - make sure the order_amount is sufficient for creating orders specially for GW as it will return a `amm/price` error.
    - XEMM+GW setup does not support order_amount 0 which works on CEX+CEX setup

**Comment by mhrvth** [comment]
🤝

**Comment by aarmoa** [comment]
@cardosofede @JeremyKono this PR has been approved by the community and by QA almost a week ago. Is there any reason why it is not merged into development?

**Review by cardosofede — APPROVED** [review]
LGTM

**Pull request merged**
