### PR TITLE
feat / Implement AMM-like inventory skew algorithm

### PR DESCRIPTION
**Pull request by bitphage**
**Before submitting this PR, please make sure**:

* [x] Your code builds clean without any errors or warnings
* [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Adds an option to switch inventory skew algorithm. It tries to maintain target inventory split using the same concept as an AMMs.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakwk3) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by bitphage** [comment]
I initially missed the ability to use `order_override` from scripts, so implemented the feature as a strategy option.

**Comment by phbrgnomo** [comment]
Something to checkout for:

The inventory rebalance shouldn't nullify the previous arbitrage profit.

For example:

Arbitrage opportunity found:

Inventory Exchange A:
1 BTC
20k USD

Inventory Exchange B:

1 BTC
20k USD

| Coin  |    Exchange A Buy price | Exchange B Sell price |
|--------|----------|---------|
| BTC  |    19,000.00     |   20.000,00   |
|  USD |  21,000.00   |  22.000,00   | 

Buy Exchange A for 20k
Sell Exchange B for 21k

profit 5% - 1k

After arb executed:

Inventory Exchange A:

2 BTC
0k USD

Inventory Exchange B:

0 BTC
41k USD

Prices

| Coin  |    Exchange 1 Buy price | Exchange 2 Sell price |
|--------|----------|---------|
| BTC  |    19,000.00     |   21.000,00   |
|  USD |  20,000.00   |  22.000,00   | 

If the rebalance would be executed at this point:

Sell Exchange A for 19k
Buy Exchange B for 22k

Inventory Exchange A:

1 BTC
19k USD

Inventory Exchange B:

1 BTC
19k USD

Total inventory at the end of the rebalance

| Coin | Before trade + rebalance | After trade + rebalance | Final result |
|----|----|----|
| BTC | 2 | 2  |
| USD | 40k | 38k |

this would put the arb strategy at a loss.

**Comment by bitphage** [comment]
@phbrgnomo this feature is for pure-MM strategy only, not arbitrage. If an account is shared with arb strategy worker, `balance limit` should be used to not mix outcomes from different strategies.

**Comment by phbrgnomo** [comment]
Oh, ok. I thought it was a rebalance for arbitrage (which is actually a feature we might need to add).

But what would be the difference from this one to the `inventory_skew` we have at the moment?

Or this would work similar to this script: https://github.com/CoinAlpha/hummingbot/blob/master/scripts/inv_skew_using_spread_script.py

**Comment by bitphage** [comment]
Current inventory skew uses order amounts bigger than needed to bring inventory to the target ratio. This algorithm calculates the exact amount to maintain target inventory split at a spread prices, similar to what AMMs like uniswap are doing.

**Comment by rxlxrxsx** [comment]
When both assets are already within the target % the bot will stop creating orders.

Screen Shot 2021-01-05 at 5 53 02 PM
Screen Shot 2021-01-05 at 6 00 04 PM

**Comment by bitphage** [comment]
@rxlxrxsx it's because calculated order amounts are less than minimum allowed. Order will be placed when ratio deviation will be high enough to require an order > minimum to rebalance.

**Comment by phbrgnomo** [comment]
Hello @bitphage 

The Hummingbot Foundation just started the governance process for the community to approve or reject Pull Requests through **Pull Request Proposals**.

For more information about how PRP votes work, check this page: https://hummingbot.org/governance/prp/

We want to know if you still have interest in having your Pull Request merged into the main codebase.

If so, please check the following on your Pull Request for our team to be able to open it for community voting:

- Your Pull Request is targeted to the `development` branch
- Your branch is up to date with the current `development` branch
- All GitHub checks have passed
- There is no merging conflicts

If you have any questions or need any help, feel free to reach us out on the #dev-general channel on our Discord (https://discord.gg/HAgZ79nzU4)

----
If you have no interest in merging this PR to our code-base or don't reply to this comment in 30 days, the Foundation team will close this PR.

You can still create a new PR any time you want!

Thank you for contributing to Hummingbot Client!

**Comment by bitphage** [comment]
I'll close this PR for now - don't have enough efforts to work on this currently.

**Pull request closed without merging**
