### PR TITLE
(feat) Add Gate.Io as a Rate Oracle

### PR DESCRIPTION
**Pull request by MementoRC**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Adds Gate.IO as a RateOracle
Replaces:https://github.com/hummingbot/hummingbot/pull/5774 and #5420 

**Tests performed by the developer**:
Lots of tests are failing locally, which is why use ot IsolatedAsyncioTestCase was attempted in previous PR

**Tips for QA testing**:

### CODE REVIEW

**Comment by rapcmia** [comment]
Hi @MementoRC good day to you
For feature-related PRs we would need you to submit a [PRP](https://snapshot.org/#/hbot-prp.eth) also so the community can vote for it, Thank you

**Comment by MementoRC** [comment]
PRP: https://snapshot.org/#/hbot-prp.eth/proposal/0xd1d959ad7f51d8cd783fef9d3e9510bf4a55fcb680dd03631cc8d845e6048f2e

**Comment by rapcmia** [comment]
Hi @MementoRC good day,
We observed that this PR is returning [failed test runs on GitHub](https://github.com/hummingbot/hummingbot/actions/runs/3246889358/jobs/5356766394) on this error:
image

We tried to run it locally as well and got the same result

**Comment by MementoRC** [comment]
@rapcmia This seems to be originating from the attempt to make Asyncio testing cleaner with IsolatedAsyncioTestCase, the class likely closes the event loop that other tests relies upon
Would using IsolatedAsyncioTestCase not be a better approach for HB?

**Comment by cardosofede** [comment]
Hi!
The changes of the configs are not related with this PR.
I think they are good, but to approve this PR, we should test all the configs of the client, including telegram, databases, etc..
The code is good and if you like do build more rate oracle sources I can work on a proposal to do a similar thing of the connectors revamp but with this. @MementoRC

**Comment by MementoRC** [comment]
The extra changes were removed. It's not clear how many other exchanges would have public `tickers` API method suitable for RateOracle, but sure that'd be good. Currently, there is a puzzling issue with the Coin Gecko oracle

**Review by rapcmia — APPROVED** [review]
Test performed:
- Setup simple PMM strategy using GateIO
- Setup markets that are not available on other rate_oracle_source, tested using LIME-USDT
- Setup rate_oracle_source to gate_io 
- After getting order filled, there are no `could not find exchange rate..` on log panel
- Ran the bot for couple of hours, all ok 
- Changed to other rate_oracle_source and got the `could not find exchange rate..` which seems to be expected.
- Test on source and docker build, all ok

**Review by cardosofede — APPROVED** [review]
LGTM

**Pull request merged**
