### PR TITLE
fix / k2 startup error

### PR DESCRIPTION
**Pull request by martinkou**
Fixed k2 trading pairs error message when starting Hummingbot.

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**Tips for QA testing**:

Start Hummingbot
Verify that the k2 fail to fetch trading pairs error message is no longer there.

This PR comes from https://github.com/CoinAlpha/hummingbot/pull/184

### CODE REVIEW

**Review by aarmoa — APPROVED** [review]
The solution looks good to me

**Comment by aarmoa** [comment]
PRP: https://snapshot.org/#/hbot-prp.eth/proposal/0x79c3de42b48af2661dec75ac8af28f2b2713ecf8c0cab4eaf75e2c1ff5f0b351

**Review by nikspz — APPROVED** [review]
Testing summary:
- Cloned feature branch with no issues
- Started client with out an errors
- Visually verified that there was no K2 error in log pane

**Comment by lt7** [comment]
Are there details on what this connector does, it's not listed in https://hummingbot.org/exchanges/spot/ or show up in any search.   If the cert is expired cannot it not be renewed rather than be ignored ?

**Comment by dennisocana** [comment]
@lt7 it's a connector has been sitting in the codebase for a long time but the production endpoints from the exchange itself were not working.

**Comment by lt7** [comment]
> @lt7 it's a connector has been sitting in the codebase for a long time but the production endpoints from the exchange itself were not working.

@dennisocana sure I understand the problem and fix, but as the exchange is unable to be identified, there is no maintainer and it has issues perhaps removing it should be considered ?

**Comment by dennisocana** [comment]
@lt7 I agree personally. We should probably create a proposal so the community can vote and get others' thoughts on it.

**Pull request merged**
