### PR TITLE
feat / Add gateway balance command

### PR DESCRIPTION
**Pull request by isreallee82**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This is a PR to solve #6395 . Add gateway balance command

Removal of display of DEX balances from balance command.
Addittion of a new gateway balance command that reports balances and allowances of connected wallets.
Reafctor of all the necessary function to make the command work, including util funcs like like df building funcs

**Tests performed by the developer**:

Added few exchanges tor the client 
pangolin_avalanche_avalanche ✅
uniswarp_ethereum_mainet ✅
uniswap_ethereum_arbitrum_one ✅
others pending

**Tips for QA testing**:

### CODE REVIEW

**Comment by isreallee82** [comment]
okay will work on all that asap @rapcmia

**Comment by nikspz** [comment]
Latest commit 07ffe84

Steps to reproduce:
    - Cloned and install PR6608 and gateway Development
    - gateway connect uniswap mainnet, arbitrum
    - gateway connector-tokens uniswap_ethereum_arbitrum USDC,WETH,USDC.e
    - Check balance
Actual: 
Failed check balance for arbitrum when additional tokens added


[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/13047269/logs_hummingbot.log)

```
2023-10-19 20:02:04,498 - 2953554 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: [<class 'decimal.InvalidOperation'>]
Traceback (most recent call last):
  File "/home/nikita/gwbalance6608/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/nikita/gwbalance6608/hummingbot/client/command/gateway_command.py", line 464, in _get_gateway_balance
    all_balances = await self.get_balances()
  File "/home/nikita/gwbalance6608/hummingbot/client/command/gateway_command.py", line 418, in get_balances
    await asyncio.gather(*tasks)
  File "/home/nikita/gwbalance6608/hummingbot/client/command/gateway_command.py", line 423, in process_chain_network
    all_tokens, balances, allowances = await self.get_token_balances_and_allowances(chain_network_address, connector_tokens, connector)
  File "/home/nikita/gwbalance6608/hummingbot/client/command/gateway_command.py", line 442, in get_token_balances_and_allowances
    allowances = [str(round(Decimal(allowance_data.get(token, "0")), 4)) for token in all_tokens]
  File "/home/nikita/gwbalance6608/hummingbot/client/command/gateway_command.py", line 442, in <listcomp>
    allowances = [str(round(Decimal(allowance_data.get(token, "0")), 4)) for token in all_tokens]
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
```
image

**Comment by isreallee82** [comment]
will check that @nikspz

**Comment by isreallee82** [comment]
@nikspz done with the decimal fix

**Comment by nikspz** [comment]
Steps:
Clone PR6608 and latest gateway development
gateway connect uniswap polygon mainnet
check gateway balance

Actual:
Client returns an Error on POST https://localhost:15888/chain/allowances Error: 'message': 'Unknown error.', 'httpErrorCode': 503

[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/13073611/logs_hummingbot.log)

[logs_gateway_app.log.2023-10-23.log](https://github.com/hummingbot/hummingbot/files/13073610/logs_gateway_app.log.2023-10-23.log)

```
2023-10-23 16:32:12,815 - 73466 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15888/chain/allowances failed. See logs for more details.
2023-10-23 16:32:12,817 - 73466 - hummingbot.client.hummingbot_application - INFO - Error fetching balances and approval for ('polygon', 'mainnet', '0x08940dc9B5a19FAb9319b77C61DDA7B8067E6843'): Error on POST https://localhost:15888/chain/allowances Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': 'Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0x0000000000000000000000000000000000001010","data":"0xdd62ed3e00000000000000000000000008940dc9b5a19fab9319b77c61dda7b8067e684300000000000000000000000068b3465833fb72a70ecdf485e0e4c7bd8665fc45","accessList":null}, error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\\"jsonrpc\\":\\"2.0\\",\\"id\\":45,\\"error\\":{\\"code\\":-32000,\\"message\\":\\"execution reverted\\"}}","error":{"code":-32000},"requestBody":"{\\"method\\":\\"eth_call\\",\\"params\\":[{\\"to\\":\\"0x0000000000000000000000000000000000001010\\",\\"data\\":\\"0xdd62ed3e00000000000000000000000008940dc9b5a19fab9319b77c61dda7b8067e684300000000000000000000000068b3465833fb72a70ecdf485e0e4c7bd8665fc45\\"},\\"latest\\"],\\"id\\":45,\\"jsonrpc\\":\\"2.0\\"}","requestMethod":"POST","url":"https://polygon-mainnet.infura.io/v3/4937790794744fe781f3f9b0e64c1d83"}, code=CALL_EXCEPTION, version=providers/5.7.2)\n    at Logger.makeError (/home/nikita/gwdevbalance/node_modules/@ethersproject/logger/lib/index.js:238:21)\n    at Logger.throwError (/home/nikita/gwdevbalance/node_modules/@ethersproject/logger/lib/index.js:247:20)\n    at checkError (/home/nikita/gwdevbalance/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:108:16)\n    at StaticJsonRpcProvider.<anonymous> (/home/nikita/gwdevbalance/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:751:47)\n    at step (/home/nikita/gwdevbalance/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)\n    at Object.throw (/home/nikita/gwdevbalance/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)\n    at rejected (/home/nikita/gwdevbalance/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'}
```
image

**Comment by isreallee82** [comment]
## Balance and Allowance

Screenshot 2023-10-24 at 04 55 30

## Balances

Screenshot 2023-10-24 at 04 40 04

hi @nikspz will you recommend I separate the pr so I can look more into the allowance

I noticed balance for polygon main shows which is unusual but I am trying to debug what's causing the the allowance revert

**Comment by isreallee82** [comment]
#6629 
Feat gateway balance

**Comment by nikspz** [comment]
Closing this PR since new created #6629

**Pull request closed without merging**
