### PR TITLE
Feat/phemex perpetual

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This pr adds the Phemex perpetual(USDT margined) connector. 
Both one-way and hedge position modes are supported.

**Tests performed by the developer**:
- Unit tests
- Tested with Perpetual Market making using ONE-WAY position mode 
- Tested with Perpetual Market making using HEDGE position mode 

**Tips for QA testing**:
- Tested with Perpetual Market making using ONE-WAY position mode 
- Tested with Perpetual Market making using HEDGE position mode 

Link to PRP - https://snapshot.org/#/hbot-prp.eth/proposal/0x6f4f16e7cebffe5258138b841963849d9a9d185e5afa714c5d769687c0ed8899

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update:
- Tested local on mbp(m1)
- Request CA QA team to share test account, all ok 
- Connect API keys successfully on mainnet
   image
    - We observed this behavior when adding invalid api keys
    - Crosscheck other perpetual connectors and do same steps, does not occur
    - Error does not show on log file
- Connect also a test wallet with no asset and setup simple  perp-mm
    - Observed logs regarding insufficient funds which is expected
    - Observed position mode both hedge and oneway ok
    - Orderbook ok

Pending:
- Connector not yet fully tested (WIP)

**Comment by rapcmia** [comment]
PR update:
- CA QA shared account and setup simple perp-mm
- Orders are created and canceled on set order refresh time
- Open long position, take-profit/stop-loss order created
- Open short position, take-profit/stop-loss order created
- Take-profit/Stop-loss order filled, position closed. Next refresh time orders created to open position
- If PnL is negative, no take-profit/stop-loss order is created
- Retrieve position, ok
    - If position mode is different? not possible.
- Position mode: hedge
    - Both long and short open, ok
    - Both tp/sl order created and filled.
    - Position close after successful order fill for tp/sl
    - Both position successfully retrieved

**Comment by rapcmia** [comment]
> image
> * We observed this behavior when adding invalid api keys

Checked again and does not occur. Seems related to the terminal where the PR is tested.

**Review by rapcmia — APPROVED** [review]
- Tested on local mbp(m1)
- CA QA team shared account ok 
- Connect API successfully (also invalid API)
- Orders created / canceled on set refresh time
- Open long/short, take-profit/stop-loss order created
- Take-profit/Stop-loss order filled, position closed
- Positon retrieval working as expected
- Does not retrieve when changing position mode from hedge to oneway or the other
- Position mode Hedge is supported
   - Both long and short open, ok
    - Both tp/sl order created and filled
    - Position close after successful order fill for tp/sl
    - Both position successfully retrieved

**Review by cardosofede — APPROVED** [review]
LGTM!

**Comment by Zzuummzz** [comment]
I was just testing the Phemex exchange now, and I found the following oddity:
The script sends a buy or sell market order on signal (Phemex perpetual). At the same time, it records the current Ask and Bid prices.
The orders are of minimal size, so as not to shift the price.
After receiving a message about order execution, and checking the position volume in the connector (that the position is really open), the script records the current Ask and Bid prices and the order execution price in the log.
And after running it for 10 hours on 5 pairs, I found that the execution price does not match the Ask and Bid prices that I receive in the script.
Here are screenshots of the table, a piece of log that the script writes when sending an order and its execution: 
Screenshot 12 55 30
Screenshot 12 55 12
Screenshot 12 54 51
Screenshot 12 54 28
Screenshot 12 54 03
Screenshot 12 52 49Also, two important things I've noticed:
The spread signal appeared on different pairs at 48 minutes of the hour, between 50 and 58 seconds (HH:47:50-HH:47:58).
Before the order execution Ask and Bid prices are the same as after the execution. Although these prices are updated in the script at the beginning of each tick. Tick duration is set to 0.1 seconds.
In this case I suppose two possibilities from where such a problem originated:
1. the Exchange executes the market order not at the price of the best Ask or Bid. But this is an extremely unlikely reason.
2. Some problem with updating prices in the connector (order book).
Please help me to understand this problem and fix it!

**Comment by cardosofede** [comment]
Hey! Nice research.
Phemex is a bronze connector so the community is in charge of the
maintenance, but we met the team in Singapore and they are willing to offer
bounties to fix it!
One thing that is important is that depending on the order amount that you
are using, the best bid and best ask are probably different than the order
amount  since you can have some slippage if the volume of the first level
is small.

**Comment by cardosofede** [comment]
Btw, by seeing the results I think that there is a problem in the connector.

**Comment by Zzuummzz** [comment]
Yes, I know that slippages are possible if the volume of the best Bid or Ask is smaller than the order size. But this is not the case. 
The volume of orders was intentionally around the minimum possible. To be more precise, I took the target position volume of 5 dollars with 2 leverage, and based on this I calculated the order volume for each currency pair.
Here is the same table with the specified volumes:
Screenshot 14 19 33

**Comment by cardosofede** [comment]
Yeah there is a bug in the connector

**Comment by Zzuummzz** [comment]
The target position volume is set without a sign (vol_target column).
The exchange volume is taken from the connector (column vol_exch).
All parameters are updated on each tick of the script.

**Comment by Zzuummzz** [comment]
What confused me the most was that Bid and Ask did not change after the order was executed, with the execution price not matching them very much.

**Pull request merged**
