### PR TITLE
Feat/add kucoin spot candles feed

### PR DESCRIPTION
**Pull request by tomasgaudino**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Add kucoin spot candles following binance structure
- Standardize interval management (1m vs 1min vs ...)

Sadly, Kucoin hasn't developed klines with web socket yet. I'll be waiting for more updates in candles_base.py so it can handle only rest calls

**Tests performed by the developer**:

**Tips for QA testing**:

- Try using this:
```
# Replace in scripts/candles_example.py

eth_1m_candles = CandlesFactory.get_candle(connector="kucoin",
                                           trading_pair="ETH-USDT",
                                           interval="1m", max_records=500)
eth_1h_candles = CandlesFactory.get_candle(connector="kucoin",
                                           trading_pair="ETH-USDT",
                                           interval="1h", max_records=500)
eth_1w_candles = CandlesFactory.get_candle(connector="kucoin",
                                           trading_pair="ETH-USDT",
                                           interval="1w", max_records=50)```

### CODE REVIEW

**Comment by rapcmia** [comment]
Hi @tomasgaudino good day
Can you please check the failed tests below, thank you

image

**Comment by tomasgaudino** [comment]
Hi @rapcmia, sure! 

I'll be fixing this as soon as possible :)

**Review by rapcmia — APPROVED** [review]
LGTM

image
- OHLC matched
- Volume and quote_asset_volume ok 
- Observed some data not available yet and will be improve on future updates for the Kucoin connector

**Comment by tomasgaudino** [comment]
@rapcmia done!

**Review by cardosofede — APPROVED** [review]
LGTM!

**Pull request merged**
