### PR TITLE
feat / gateway v2

### PR DESCRIPTION
**Pull request by martinkou**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

* Adds the gateway v2 component, under the `gateway/` directory.
* Adds `GatewayEVMAMM` connector, which can be used to connect to Uniswap and Pangolin across Ethereum and Avalanche blockchains - and uses Gateway V2 as the middleware to talk to blockchain protocols.
* Modifies the `amm_arb` strategy to work with the new `GatewayEVMAMM` connector.
* Adds new test cases for `GatewayEVMAMM` connector, and `amm_arb` strategy.

**Tests performed by the developer**:

* All unit tests passing
* End-to-end tests with Uniswap vs. Binance, and Pangolin vs. Binance passing.

This PR comes from https://github.com/CoinAlpha/hummingbot/pull/185

Snapshot proposal: https://snapshot.org/#/hbot-prp.eth/proposal/0xf4120a45f2d563b010e5392e3a56171c700867b568a4e4850253e8bb75bc2833

### CODE REVIEW

**Review by nikspz — APPROVED** [review]
Test performed:

- Start the Hummingbot client and setup a password - Ok
- Download gateway docker image - Ok
- Add an infura API key - Ok
- Check the gateway status in the client - Ok
- Test the gateway connection - Ok
- Stop and start the gateway container - Ok
- Gateway v2 commands - Ok

AMM Arbitrage
Uniswap mainnet, testnet:
- Create an AMM arbitrage strategy using uniswap and preferred second exchange - Ok
- Start the strategy - Ok
- Check the status - Ok
- Check the profitability - Ok
- Filled event - Ok
- History - Ok
- Check txhash - Ok
- Verify the fee - Ok

Pangolin mainnet, testnet:
- Create an AMM arbitrage strategy using uniswap and preferred second exchange - Ok
- Start the strategy - Ok
- Check the status - Ok
- Check the profitability - Ok
- Filled event - Ok
- History - Ok
- Check txhash - Ok
- Verify the fee - Ok

**Comment by JeremyKono** [comment]
Hi, please resolve conflicts in this PR. Thanks!

**Comment by martinkou** [comment]
Done - merge conflicts are resolved.

**Comment by JeremyKono** [comment]
Seems like there is another one @martinkou. Sorry for the issue, but can you please resolve the conflicts again?

**Review by nikspz — APPROVED** [review]

**Pull request merged**
