### PR TITLE
Feat/Foxbit Exchange Connector

### PR DESCRIPTION
**Pull request by mfavareto-vitra**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This Pull Request aims to add the connector for Foxbit Exchange.
Foxbit is a Brazilian company that since 2014 has everything you need to start investing in bitcoin, cryptocurrencies and digital assets.

**Tests performed by the developer**:
Development team has run several performance tests and it was ok to go to production (in fact, we already using it).

**Tips for QA testing**:
You'll nedd to access your Foxbit account and get your User Access Code, it will needed to inform during connect process.

### CODE REVIEW

**Comment by rapcmia** [comment]
Hi @mfavareto-vitra Please create a New Post at Discord's [#proposal-discussions](https://discord.com/channels/530578568154054663/1037719198983532604) channel, with links of this PR, [snapshots](https://docs.hummingbot.org/governance/proposals/), and other websites/webapp. Include also information about litebit exchange

Other community devs, and members may prefer to know more and ask questions before voting / approving.

**Comment by rapcmia** [comment]
Hi @mfavareto-vitra please rebase your PR from master to development. Thank you

**Comment by mfavareto-vitra** [comment]
Hi @rapcmia 
done ;)

**Comment by rapcmia** [comment]
Hi @mfavareto-vitra we cant seem to rebase this PR to the development branch getting the error below. We decided to close this PR and suggest you to create a new one. Thank you

image

**Comment by mfavareto-vitra** [comment]
I see, in this case, please, close this at snapshot too...
https://snapshot.org/#/hbot-prp.eth/proposal/0x03d108e585dc7b8d81bc81bbc2caf52bf81b7952b099a2c42e2223e4afb80dfe

**Comment by mfavareto-vitra** [comment]
And, I open a new PR:
https://github.com/hummingbot/hummingbot/pull/6133

is that right now?
if you considere it ok, I'll open to vote at snapshot...

TIA

**Pull request closed without merging**
