### PR TITLE
remove unused gateway docker code (redux)

### PR DESCRIPTION
**Pull request by fengtality**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

- Remove legacy code from when Gateway was spun off automatically as a child Docker process for `gateway create`
- Removes `gateway status` command and unused functions

Based on #6296

### CODE REVIEW

**Comment by nikspz** [comment]
Steps:
Cloned fix branch and gateway-development
Start the instance and gateway-development
Type gateway then spacebar

Actual:
gateway status command still showing in autocomplete list

Expected:
removed commnds not showed in autocomplete


image

**Review by cardosofede — APPROVED** [review]
LGTM! Please make sure that the build from docker is working correctly @rapcmia

**Comment by rapcmia** [comment]
> LGTM! Please make sure that the build from docker is working correctly @rapcmia

- Build docker client image locally for this PR and setup with latest development docker gateway ✅ 
- Getting the same reported above from Nikita 
   image


PR good to be approved, just need to fix the cosmetic bug for the autocomplete on `gateway` command.

Steps to reproduce:
- Type `gateway` then spacebar or tab

**Review by rapcmia — APPROVED** [review]
LGTM

- Test latest commit `9b66d522f`
- Setup with latest development gateway ✅
- Check again reported `gateway status`, removed and fixed
- Successfully built docker image for client and gateway ✅
- Run simple amm-arb on source/docker build with traderjoe-avalanche ✅

**Pull request merged**
