### PR TITLE
Fix/Uniswap Liquidity Error #225 [WIP]

### PR DESCRIPTION
**Pull request by mlguys**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Solution for fixing this issue: https://github.com/hummingbot/gateway/issues/225

TODOs:
- [x] Added solution to prevent creating new position that uses more fund than the available fund
- [x] Improved handling out of range positions
- [x] Fixed creating ZERO_LIQUIDITY position
- [ ] Update test cases
- [x] Fixing instance where transactions to get position info and collect fees got rejected
- [x] Refactor check if position in range logic

**Tests performed by the developer**:
- Run `uniswap_v3_lp` strategy on ARB-USDC.e pair on Arbitrum for several hours

**Tips for QA testing**:
- This is still working on progress
- Will ask issue owner to verify the fix when it is ready
- Counterpart of this PR on gateway side: https://github.com/hummingbot/gateway/pull/257

### CODE REVIEW

**Comment by mlguys** [comment]
Updated todos in PR description.

**Comment by nikspz** [comment]
@mlguys Could you please add coverage here?
https://github.com/hummingbot/hummingbot/actions/runs/7884532705/job/21513732177

**Comment by mlguys** [comment]
Hey @nikspz will do by the weekend, I need to add some more updates to finalize the solution too.

**Comment by nikspz** [comment]
@mlguys Could you please add test coverage on this PR here when you have time?
https://github.com/hummingbot/hummingbot/actions/runs/8068196861/job/22040391549?pr=6731

**Pull request closed without merging**
