### PR TITLE
New feature: Remember the last strategy created or imported

### PR DESCRIPTION
**Pull request by carlosmiei**
Before submitting this PR, please make sure:

Your code builds clean without any errors or warnings
You are using approved title ("feat/", "fix/", "docs/", "refactor/")

A description of the changes proposed in the pull request:

While using hummingbot, I would start it and stop several times, but most of the time I started it again I wanted to use the previous strategy I had used. Having to import it every time is painful, specially when we have tons of different strategies, and we are not sure what's the strategy name.

To solve this issue, I implemented a feature that uses the global config file to store/retrieve the last strategy created or imported, making things a lot easier :)

This was done simply by saving the name of the strategy every time the user imports or creates a strategy and creating a command ("previous") that can be invoked by the user,  informs the name of the stored strategy, if it exists, and collects the answer (calling the import commands afterwards).

Please let me know what you think about it!

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramv0j) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by dennisocana** [comment]
Thanks @carlosmiei for contributing. We're going to review next week and add comments here.

**Comment by rxlxrxsx** [comment]
Just posting this here to confirm if this is the expected behavior or not. When importing a strategy and chose to cancel midway (using ctrl + x), using the `previous` command seems to not capture the previous strategy created or imported.

Steps to reproduce:
1. Create or import a strategy
2. Exit the instance, or just import any other strategy
2. Run previous command and enter yes
3. Run import command and press ctrl + x when prompted what strategy is going to be imported
4. Run previous command again and it will return "No previous strategy found"

Screen Shot 2021-08-15 at 2 34 17 PM

**Comment by carlosmiei** [comment]
> Just posting this here to confirm if this is the expected behavior or not. When importing a strategy and I choose to cancel midway (using ctrl + x), using the `previous` command afterwards seems to not capture the previous strategy created or imported.
> 
> Steps to reproduce:
> 
> 1. Create or import a strategy
> 2. Exit the instance or just import any other strategy
> 3. Run previous command and enter yes
> 4. Run import command and press ctrl + x when prompted what strategy is going to be imported
> 5. Run previous command again and it will return "No previous strategy found"
> 
> Screen Shot 2021-08-15 at 2 34 17 PM



> Just posting this here to confirm if this is the expected behavior or not. When importing a strategy and I choose to cancel midway (using ctrl + x), using the `previous` command afterwards seems to not capture the previous strategy created or imported.
> 
> Steps to reproduce:
> 
> 1. Create or import a strategy
> 2. Exit the instance or just import any other strategy
> 3. Run previous command and enter yes
> 4. Run import command and press ctrl + x when prompted what strategy is going to be imported
> 5. Run previous command again and it will return "No previous strategy found"
> 
> Screen Shot 2021-08-15 at 2 34 17 PM

Hi @rxlxrxsx, nice catch, this was indeed not expected, and therefore I already fix it. 
fixImportCancelgif

**Review by rxlxrxsx — DISMISSED** [review]
Tested and confirmed working. No other issues found by QA.

**Comment by dennisocana** [comment]
@carlosmiei please add unit tests coverage to pass the requirement so we can review and merge this pull request.

image

**Comment by dennisocana** [comment]
We agreed on creating unit tests as a guide / sample and for the benefit of community contributors going forward. Will have the discussion on this again tonight to finalize.

**Comment by dennisocana** [comment]
@carlosmiei thanks for adding the first unit tests. Please see test results below:

image

**Comment by carlosmiei** [comment]
@dennisocana  welcome, my plan is, when I have the chance, to add all the needed tests to obtain the needed coverage

**Comment by carlosmiei** [comment]
@dennisocana  I finally had the change to add the missing tests. I believe the coverage is now over 80%. Can you please check it out?
image

**Comment by dennisocana** [comment]
Thanks @carlosmiei , we will start reviewing next week

**Comment by carlosmiei** [comment]
@dennisocana any update? it has been a while

**Comment by dennisocana** [comment]
@carlosmiei we haven't started the review process yet due to major tasks the team are working on like strategies and UI rework that needs to be completed before the foundation launch which most of them should be done in the current sprint (Nov. 8 - Nov. 21). We should be able to resume reviewing of pull requests by then.

**Comment by dennisocana** [comment]
@carlosmiei we're heads down setting up the Hummingbot Foundation this month. We will include this pull request in the model that will allow the community to participate in deciding what should be included in every release.

**Comment by phbrgnomo** [comment]
Hello @carlosmiei 

The Hummingbot Foundation just started the governance process for the community to approve or reject Pull Requests through **Pull Request Proposals**.

For more information about how PRP votes work, check this page: https://hummingbot.org/governance/prp/

We want to know if you still have interest in having your Pull Request merged into the main codebase.

If so, please check the following on your Pull Request for our team to be able to open it for community voting:

- Your Pull Request is targeted to the `development` branch
- Your branch is up to date with the current `development` branch
- All GitHub checks have passed
- There is no merging conflicts

If you have any questions or need any help, feel free to reach us out on the #dev-general channel on our Discord (https://discord.gg/HAgZ79nzU4)

----
If you have no interest in merging this PR to our code-base or don't reply to this comment in 30 days, the Foundation team will close this PR.

You can still create a new PR any time you want!

Thank you for contributing to Hummingbot Client!

**Comment by carlosmiei** [comment]
> Hello @carlosmiei
> 
> The Hummingbot Foundation just started the governance process for the community to approve or reject Pull Requests through **Pull Request Proposals**.
> 
> For more information about how PRP votes work, check this page: https://hummingbot.org/governance/prp/
> 
> We want to know if you still have interest in having your Pull Request merged into the main codebase.
> 
> If so, please check the following on your Pull Request for our team to be able to open it for community voting:
> 
> * Your Pull Request is targeted to the `development` branch
> * Your branch is up to date with the current `development` branch
> * All GitHub checks have passed
> * There is no merging conflicts
> 
> If you have any questions or need any help, feel free to reach us out on the #dev-general channel on our Discord (https://discord.gg/HAgZ79nzU4)
> 
> If you have no interest in merging this PR to our code-base or don't reply to this comment in 30 days, the Foundation team will close this PR.
> 
> You can still create a new PR any time you want!
> 
> Thank you for contributing to Hummingbot Client!

@phbrgnomo I'll do that, thanks 🙂

**Comment by carlosmiei** [comment]
@phbrgnomo Do I need to follow any further steps to get this PR admitted as a proposal?

**Comment by phbrgnomo** [comment]
You got some failed tests. Take a look at them, and reach out our team on our Discord on the #dev-general channel if you need some help with them

**Pull request closed without merging**
