### PR TITLE
Fix/okx cancel order error code

### PR DESCRIPTION
**Pull request by huatahhhhh**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

1. Fixed a bug on okx exchange error code handling. When an cancel order API request is sent and the order does not exist. The previously expected error code value is 5140. However, according to okx [documentation](https://www.okx.com/docs-v5/en/#error-code-rest-public), the error codes are 51400 (order does not exist) and 51401 (order has already been cancelled).

2. Added API response data in error log message for easier troubleshooting of data. Previous `cancel_result['msg']` was showing only `"Operation Failed"` which was not very helpful.

**Tests performed by the developer**:
1. Ran the xemm with 2 trading pairs on okx exchange for 6 hours, did not face the cancel order error logs which were showing up before the code changes
2. When troubleshooting issue mentioned in point 1, logging `cancel_result` showed the error code which okx API was returning.

**Tips for QA testing**:
- NA

### CODE REVIEW

**Review by cardosofede — APPROVED** [review]
LGTM

**Review by cardosofede — CHANGES_REQUESTED** [review]
Hi, I think that you are right, the connector is not handling properly the response.
But, I think that if you are receiving a failed to cancel because it was already canceled, you should stop tracking the order too.
Also if you are raising an error, it should be managed by some part of the code. _place_cancel is called inside a safe_ensure_future, so it won't be handled by nobody.

**Comment by rapcmia** [comment]
Hi, @huatahhhhh good day, 
We would like to confirm if the changes requested can be checked this week. Thank you

**Comment by huatahhhhh** [comment]
@cardosofede 

1. the exception thrown was already in the code, I only modified the message to include more details about the response.  Looking at binance_exchange.py as the recommended gold standard [here](https://github.com/hummingbot/hummingbot/blob/8ff27c77fd39fe7edc1c2faffe0b946dbf4632c7/hummingbot/connector/exchange/binance/binance_exchange.py#L196) they do not throw exceptions for unexpected unsuccessful cases. Raising an exception helps log it in the logs. I can replace this with a `self.logger().exception(message)` if that is preferred, would that be better?

2. I am not sure why it was already cancelled as I was running cross exchange strategy. Either there is a bug in the strategy which sends multiple cancels or a bug with the exchange, however by returning true in `_place_cancel()` the order tracker will stop tracking the order.  I am not sure how to proceed with this, please advice

**Comment by cardosofede** [comment]
Hi @huatahhhhh !
1. Yes that will be better.
2. Let's try first with this solution and then check if there is any error in the strategy.

BTW, you have to add test to get >80% coverage:
image

**Comment by JeremyKono** [comment]
Hi @huatahhhhh, are you still going to continue this PR?

**Comment by huatahhhhh** [comment]
@JeremyKono I was waiting for this issue to be classified so that I can get the bounty. https://github.com/hummingbot/hummingbot/issues/5833

**Comment by huatahhhhh** [comment]
@cardosofede 
1. I realised that this particular connector is littered with `raise IOError`, could we leave this for a future refactor?  
2. I have added the tests to meet the required coverage requirements.

**Review by cardosofede — APPROVED** [review]
LGTM

**Comment by nikspz** [comment]
Ran testbot over weekend got the issue we reported earlier here.

Bot ran OKX for 14 hours then flooded with Canceling the limit order *order_id* and failed to cancel order that is not exists on exchange

Steps:

1. Clone and installed fix branch
2. Start the bot instance
3. create simple pureMM strategy using OKX
4. start the strategy and leave it running for a long time

Actual:
Bot ran OKX for ~14 hours then failed to cancel order that is not exists on exchange and `stay flooded with Canceling the limit order *order_id*`

Expected:
Bot be able to  recover and place/refreshing orders according to the strategy


```

2022-11-04 14:29:29,001 - 2875238 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 1 bid orders at (Size, Price): ['0.004 ETH, 1624.54 USDT']
2022-11-04 14:29:29,001 - 2875238 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 1 ask orders at (Size, Price): ['0.004 ETH, 1690.84 USDT']
2022-11-04 14:29:29,195 - 2875238 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER BUY order 93027a12dac34fBCBEHUTa4160e88b4e for 0.004000 ETH-USDT.
2022-11-04 14:29:29,206 - 2875238 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1667572169.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.004000", "price": "1624.54", "order_id": "93027a12dac34fBCBEHUTa4160e88b4e", "creation_timestamp": 1667572169.0, "exchange_order_id": "508769784478212128", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "okx"}
2022-11-04 14:29:29,273 - 2875238 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER SELL order 93027a12dac34fBCSEHUT85c517bec1d for 0.004000 ETH-USDT.
2022-11-04 14:29:29,286 - 2875238 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1667572169.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.004000", "price": "1690.84", "order_id": "93027a12dac34fBCSEHUT85c517bec1d", "creation_timestamp": 1667572169.0, "exchange_order_id": "508769784532738050", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "okx"}
2022-11-04 14:29:47,371 - 2875238 - hummingbot.connector.exchange.okx.okx_api_user_stream_data_source.OkxAPIUserStreamDataSource - WARNING - The websocket connection was closed (The WS connection was closed unexpectedly. Close code = 1006 msg data: None)
2022-11-04 14:29:47,953 - 2875238 - hummingbot.connector.exchange.okx.okx_api_order_book_data_source.OkxAPIOrderBookDataSource - WARNING - The websocket connection was closed (The WS connection was closed unexpectedly. Close code = 1006 msg data: None)
2022-11-04 14:29:47,954 - 2875238 - hummingbot.core.api_throttler.async_request_context_base - INFO - API rate limit on WSConnection (1 calls per 1s) has almost reached. Limits used is 2 in the last 1 seconds
2022-11-04 14:29:48,074 - 2875238 - hummingbot.connector.exchange.okx.okx_api_user_stream_data_source.OkxAPIUserStreamDataSource - WARNING - The websocket connection was closed (The WS connection was closed unexpectedly. Close code = 1006 msg data: None)
2022-11-04 14:29:49,001 - 2875238 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order 93027a12dac34fBCBEHUTa4160e88b4e. [clock=2022-11-04 14:29:49+00:00]
2022-11-04 14:29:49,001 - 2875238 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order 93027a12dac34fBCSEHUT85c517bec1d. [clock=2022-11-04 14:29:49+00:00]
2022-11-04 14:29:49,069 - 2875238 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - ERROR - Failed to cancel order 93027a12dac34fBCBEHUTa4160e88b4e
Traceback (most recent call last):
  File "/home/ubuntu/okx5766/hummingbot/connector/exchange_py_base.py", line 523, in _execute_order_cancel
    cancelled = await self._place_cancel(order.client_order_id, order)
  File "/home/ubuntu/okx5766/hummingbot/connector/exchange/okx/okx_exchange.py", line 203, in _place_cancel
    cancel_result = await self._api_post(
  File "/home/ubuntu/okx5766/hummingbot/connector/exchange_py_base.py", line 849, in _api_post
    return await self._api_request(*args, **kwargs)
  File "/home/ubuntu/okx5766/hummingbot/connector/exchange_py_base.py", line 878, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/ubuntu/okx5766/hummingbot/core/web_assistant/rest_assistant.py", line 67, in execute_request
    response = await self.call(request=request, timeout=timeout)
  File "/home/ubuntu/okx5766/hummingbot/core/web_assistant/rest_assistant.py", line 84, in call
    resp = await wait_for(self._connection.call(request), timeout)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/ubuntu/okx5766/hummingbot/core/web_assistant/connections/rest_connection.py", line 10, in call
    aiohttp_resp = await self._client_session.request(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
2022-11-04 14:29:49,138 - 2875238 - hummingbot.connector.exchange.okx.okx_api_order_book_data_source.OkxAPIOrderBookDataSource - INFO - Subscribed to public order book and trade channels...
2022-11-04 14:30:04,111 - 2875238 - hummingbot.connector.exchange.okx.okx_api_user_stream_data_source.OkxAPIUserStreamDataSource - INFO - Subscribed to private account and orders channels...
2022-11-04 14:30:50,001 - 2875238 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order 93027a12dac34fBCBEHUTa4160e88b4e. [clock=2022-11-04 14:30:50+00:00]
2022-11-04 14:30:50,001 - 2875238 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order 93027a12dac34fBCSEHUT85c517bec1d. [clock=2022-11-04 14:30:50+00:00]
2022-11-04 14:30:50,210 - 2875238 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1667572250.0, "order_id": "93027a12dac34fBCBEHUTa4160e88b4e", "exchange_order_id": "508769784478212128", "event_name": "OrderCancelledEvent", "event_source": "okx"}
2022-11-04 14:30:50,211 - 2875238 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order 93027a12dac34fBCBEHUTa4160e88b4e.
2022-11-04 14:31:51,000 - 2875238 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order 93027a12dac34fBCSEHUT85c517bec1d. [clock=2022-11-04 14:31:51+00:00]
2022-11-04 14:32:52,000 - 2875238 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order 93027a12dac34fBCSEHUT85c517bec1d. [clock=2022-11-04 14:32:52+00:00]
2022-11-04 14:33:53,000 - 2875238 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order 93027a12dac34fBCSEHUT85c517bec1d. [clock=2022-11-04 14:33:53+00:00]
2022-11-04 14:34:54,001 - 2875238 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order 93027a12dac34fBCSEHUT85c517bec1d. [clock=2022-11-04 14:34:54+00:00]
2022-11-04 14:35:55,001 - 2875238 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order 93027a12dac34fBCSEHUT85c517bec1d. [clock=2022-11-04 14:35:55+00:00]
2022-11-04 14:36:56,001 - 2875238 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order 93027a12dac34fBCSEHUT85c517bec1d. [clock=2022-11-04 14:36:56+00:00]
2022-11-04 14:37:57,205 - 2875238 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order 93027a12dac34fBCSEHUT85c517bec1d. [clock=2022-11-04 14:37:57+00:00]
2022-11-04 14:38:01,846 - 2875238 - hummingbot.core.api_throttler.async_request_context_base - INFO - API rate limit on /api/v5/public/time (10 calls per 2s) has almost reached. Limits used is 10 in the last 2 seconds
2022-11-04 14:38:58,000 - 2875238 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order 93027a12dac34fBCSEHUT85c517bec1d. [clock=2022-11-04 14:38:58+00:00]
2022-11-04 14:39:59,000 - 2875238 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order 93027a12dac34fBCSEHUT85c517bec1d. [clock=2022-11-04 14:39:59+00:00]
2022-11-04 14:41:00,000 - 2875238 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order 93027a12dac34fBCSEHUT85c517bec1d. [clock=2022-11-04 14:41:00+00:00]
2022-11-04 14:42:01,001 - 2875238 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order 93027a12dac34fBCSEHUT85c517bec1d. [clock=2022-11-04 14:42:01+00:00]
2022-11-04 14:42:01,646 - 2875238 - hummingbot.core.api_throttler.async_request_context_base - INFO - API rate limit on /api/v5/public/time (10 calls per 2s) has almost reached. Limits used is 10 in the last 2 seconds
```






[conf_pure_mm_1 config.txt](https://github.com/hummingbot/hummingbot/files/9950996/conf_pure_mm_1.config.txt)
[logs_conf_pure_mm_1.log](https://github.com/hummingbot/hummingbot/files/9950993/logs_conf_pure_mm_1.log)
[logs_conf_pure_mm_1-2022-11-03.log](https://github.com/hummingbot/hummingbot/files/9951004/logs_conf_pure_mm_1-2022-11-03.log)
[logs_conf_pure_mm_1-2022-11-04.log.](https://github.com/hummingbot/hummingbot/files/9951010/logs_conf_pure_mm_1-2022-11-04.log)
[logs_conf_pure_mm_1-2022-11-05.log.](https://github.com/hummingbot/hummingbot/files/9951011/logs_conf_pure_mm_1-2022-11-05.log)
[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/9951012/logs_hummingbot.log)
[OKX.zip](https://github.com/hummingbot/hummingbot/files/9951020/OKX.zip)


image

**Comment by huatahhhhh** [comment]
@nikspz thanks for testing, I will take a look into it

**Review by nikspz — APPROVED** [review]
Test performed:
- Cloned and installed feature branch
- Connected OKX API keys successfully
- Created/started strategy using OKX connector
- Imported strategy that using OKX connector
- Checked status and status --live
- Orderbook matched between client and exchange when running --live (status, ticker and orderbook)
- Order creation and cancellation - OK
- Records filled orders - OK
- Handling multiple orders with hanging_orders
- History -verbose, CSV, data log matched with the exchange
- Transactions tracked on Datadog
- Verified fee calculation

Tested on AWS Ubuntu Source and Docker

**Comment by huatahhhhh** [comment]
@nikspz can I just confirm that there are no filled trades in the okx application. Because hummingbot would not have tracked it

**Comment by nikspz** [comment]
@huatahhhhh yes, there's no trades on [conf_pure_mm_1](https://github.com/hummingbot/hummingbot/files/9950996/conf_pure_mm_1.config.txt) config:

[File with SQLite and CSVs for other configs .zip](https://github.com/hummingbot/hummingbot/files/9977081/data-cancel-order.zip)

[OKX Trade Details_ 2022-11-03~2022-11-10.csv](https://github.com/hummingbot/hummingbot/files/9977094/OKX.Trade.Details_.2022-11-03.2022-11-10.csv)

**Pull request merged**
