### PR TITLE
fix/Duration/running time display from the Hummingbot

### PR DESCRIPTION
**Pull request by theomaniac**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
When the Hummingbot runs for more than 1 day, the bottom status on the left, displaying the running time, gets messed up.

It fixes the issue described in https://github.com/hummingbot/hummingbot/issues/5497, also makes the elapsed time more Linux Uptime like

Before:

After:

**Tests performed by the developer**:
Waited 1 day

**Tips for QA testing**:
Wait 1 day ;)

### CODE REVIEW

**Comment by theomaniac** [comment]
Yes, they are added in the opened issue, but will add them here too

**Comment by nikspz** [comment]
@theomaniac Could you please fix [failing tests](https://github.com/hummingbot/hummingbot/actions/runs/3898713451/jobs/6658944529)? thanks

**Comment by theomaniac** [comment]
Have asked multiple times and multiple peoiple, about how those can be fixed.
Got no usable answer.
The test it is failing it should be redone.

**Comment by theomaniac** [comment]
Have anybody looked at the tests it is failing and why ?

**Comment by cardosofede** [comment]
Hi @theomaniac. As I told you before, when you make a change in the code you have to also adapt the test for that.
If you don't know how to do it, another dev can pick the bounty.

**Comment by MementoRC** [comment]
@theomaniac Please, change:
<dev dir>/test/hummingbot/client/ui/test_interface_utils.py - lines 48-49 withthe updated display you are proposing (`Uptime: ...days...`)
```
        self.assertEqual('Duration: 0:00:02', mock_timer.log.call_args_list[0].args[0])
        self.assertEqual('Duration: 0:00:03', mock_timer.log.call_args_list[1].args[0])
```

It is necessary and very helpful to reviewers and co-developers to implement the appropriate tests to validate the changes made in the PR - modifying existing tests, adding extra tests, removing obsolete tests, etc...
Tests and coverage (which ensure that new code have test evaluating them) can be run with `make test` before Commit&Push

Hope this helps, thank you for your contribution (I am just a community beginner dev)

**Comment by nikspz** [comment]
Hi @theomaniac Would you please answer if you're able update the PR with tests advised above and be assigned for the bounty [here](https://github.com/hummingbot/hummingbot/issues/5497)?

**Comment by theomaniac** [comment]
Yeah, will look at the tests

**Comment by theomaniac** [comment]
it seems that managed to fix the test, take a look

**Comment by nikspz** [comment]
> it seems that managed to fix the test, take a look

image

**Comment by theomaniac** [comment]
fixed

**Review by nikspz — APPROVED** [review]
Tests performed:
- Cloned and installed feature branch
- Manually created docker image successfully
- Ran the longterm bot for 3 days 
- Reviewed that runtime showing correctly and now displayed days

**Review by cardosofede — APPROVED** [review]
LGTM!

**Pull request merged**
