### PR TITLE
(fix) stop hanging order cancellation endless loop

### PR DESCRIPTION
**Pull request by kolibrie**
When an order is filled, then afterward is added as a hanging order, or when an order is not created by the exchange and instead we receive a MarketOrderFailureEvent, and in the meantime it is added as a hanging order, then when the hanging order tracker detects that the order should be cancelled, it goes into a cancellation loop, attempting to cancel the order every second, forever.

The API call to cancel the order is not made repeatedly because hummingbot knows that the order is not active.  However, a message is added to the logs repeatedly, saying that the order is to be cancelled.

This patch updates the internal state of the hanging orders tracker so that when an inactive order is set to be cancelled, instead of looping forever, the order is removed from the list of hanging orders, as if it had been cancelled.  This prevents the logs from filling up with repeated cancellation lines.

**Before submitting this PR, please make sure**:

- [ x] Your code builds clean without any errors or warnings
- [ x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This patch adds some of the cleanup code from _did_cancel_order() to 
_cancel_multiple_orders_in_strategy() so that orders that should have been cancelled, but were no longer active, still are cleaned up.

**Tests performed by the developer**:
Ran in paper trade mode until an order was filled and then added to the list of hanging orders, and then was marked for cancellation.  Verified that before the change, the log entry to cancel the order was listed every second until the bot was stopped.  Verified that after the change, the log entry was listed once, as well as a new log entry saying: 'Hanging order not in active_orders so skipping cancel', and no further logs about the order were listed.

**Tips for QA testing**:
I ran for a full day before the scenario was triggered one time, and another time it only took about three hours.  To determine that the fix was effective, I collected a list of filled orders from the logs, then grepped that list against the logs for 'Hanging order passed max_distance from price'.  I knew the situation had been met when I was able to find a log entry for max_distance for an order that had been previously filled.  Without the fix, the max_distance log message was repeated hundreds of times, until I stopped the bot.  With the fix, there was only one log line.

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update:
- Test in progress, current testbot had not yet able to reproduce the issue
- Test is being done on Bybit and Kucoin connectors

@kolibrie Good day to you,
We want to confirm if the issue happened when the order was canceled yet the client acknowledged (or failed to determine if this is successfully canceled) that the order is still present resulting in an endless loop? Would it be possible if you can share a log file so we can review the behavior of the issue? Thank you again for your time on this fix

**Comment by kolibrie** [comment]
On Thu, Oct 06, 2022 at 08:35:35PM -0700, rapcmia wrote:
> PR update:
> - Test in progress, current testbot had not yet able to reproduce the issue
> - Test is being done on Bybit and Kucoin connectors
> 
> @kolibrie Good day to you,
> We want to confirm if the issue happened when the order was canceled yet the client acknowledged (or failed to determine if this is successfully canceled) that the order is still present resulting in an endless loop? Would it be possible if you can share a log file so we can review the behavior of the issue? Thank you again for your time on this fix
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/hummingbot/hummingbot/pull/5762#issuecomment-1271072840
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>

There are two scenarios I was seeing:

- Order filled before hummingbot tries to turn it into a hanging order
- Order never created on exchange

Here are some example logs from each:

Order filled before hummingbot tries to turn it into a hanging order:

grep x-XEKWYICXSBCUD5e88d3e9fd402ad70 logs/logs_conf_pure_mm_binance_BTC-USD_20220909.log.2022-09-13 | grep -v 'Original' | grep -v 'Equivalent' | grep -v 'max_distance' | less
2022-09-13 11:23:44,218 - 142006 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER SELL order x-XEKWYICXSBCUD5e88d3e9fd402ad70 for 0.00400000 BTC-USD.
2022-09-13 11:23:44,233 - 142006 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1663068223.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "BTC-USD", "amount": "0.00400000", "price": "22682.3500", "order_id": "x-XEKWYICXSBCUD5e88d3e9fd402ad70", "creation_timestamp": 1663068222.0, "exchange_order_id": "1296126701", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "binance_us"}
2022-09-13 11:25:08,236 - 142006 - hummingbot.connector.client_order_tracker - INFO - The SELL order x-XEKWYICXSBCUD5e88d3e9fd402ad70 amounting to 0.00400000/0.00400000 BTC has been filled.
2022-09-13 11:25:08,434 - 142006 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1663068308.0, "order_id": "x-XEKWYICXSBCUD5e88d3e9fd402ad70", "trading_pair": "BTC-USD", "trade_type": "TradeType.SELL", "order_type": "OrderType.LIMIT_MAKER", "price": "22682.3500", "amount": "0.00400000", "trade_fee": {"percent": "0", "percent_token": "BNB", "flat_fees": [{"token": "BNB", "amount": "0E-8"}]}, "exchange_trade_id": "47979075", "leverage": 1, "position": "NIL", "event_name": "OrderFilledEvent", "event_source": "binance_us"}
2022-09-13 11:25:08,436 - 142006 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BTC-USD) Maker sell order x-XEKWYICXSBCUD5e88d3e9fd402ad70 (0.00400000 BTC @ 22682.350000 USD) has been completely filled. [clock=2022-09-13 11:25:08+00:00]
2022-09-13 11:25:08,452 - 142006 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1663068308.0, "order_id": "x-XEKWYICXSBCUD5e88d3e9fd402ad70", "base_asset": "BTC", "quote_asset": "USD", "base_asset_amount": "0.00400000", "quote_asset_amount": "90.729400000000", "order_type": "OrderType.LIMIT_MAKER", "exchange_order_id": "1296126701", "event_name": "SellOrderCompletedEvent", "event_source": "binance_us"}
2022-09-13 11:25:08,453 - 142006 - hummingbot.connector.client_order_tracker - INFO - SELL order x-XEKWYICXSBCUD5e88d3e9fd402ad70 completely filled.
2022-09-13 11:25:33,037 - 142006 - hummingbot.strategy.hanging_orders_tracker - INFO - Need to create: frozenset({HangingOrder(order_id='x-XEKWYICXSBCUD5e88d3e9fd402ad70', trading_pair='BTC-USD', is_buy=False, price=Decimal('22682.350000'), amount=Decimal('0.00400000'), creation_timestamp=1663068222.0), HangingOrder(order_id='x-XEKWYICXSBCUD5e88d44fcc358ad70', trading_pair='BTC-USD', is_buy=False, price=Decimal('22682.590000'), amount=Decimal('0.00400000'), creation_timestamp=1663068329.0)})

After that, this line is repeated thousands of times:
grep x-XEKWYICXSBCUD5e88d3e9fd402ad70 logs/logs_conf_pure_mm_binance_BTC-USD_20220909.log.2022-09-13 | grep max_distance | head
2022-09-13 12:48:56,098 - 142006 - hummingbot.strategy.hanging_orders_tracker - INFO - Hanging order passed max_distance from price=5.00% LimitOrder('x-XEKWYICXSBCUD5e88d3e9fd402ad70', 'BTC-USD', False, 'BTC', 'USD', 22682.350000, 0.00400000, NaN, 1663068222000000). Removing...
2022-09-13 12:48:57,869 - 142006 - hummingbot.strategy.hanging_orders_tracker - INFO - Hanging order passed max_distance from price=5.00% LimitOrder('x-XEKWYICXSBCUD5e88d3e9fd402ad70', 'BTC-USD', False, 'BTC', 'USD', 22682.350000, 0.00400000, NaN, 1663068222000000). Removing...
2022-09-13 12:48:58,892 - 142006 - hummingbot.strategy.hanging_orders_tracker - INFO - Hanging order passed max_distance from price=5.00% LimitOrder('x-XEKWYICXSBCUD5e88d3e9fd402ad70', 'BTC-USD', False, 'BTC', 'USD', 22682.350000, 0.00400000, NaN, 1663068222000000). Removing...


Order never created on exchange:

2022-09-13 15:35:16,469 - 142006 - hummingbot.strategy.hanging_orders_tracker - INFO - Need to create: frozenset({HangingOrder(order_id='x-XEKWYICXSBCUD5e890c2140631ad70', trading_pair='BTC-USD', is_buy=False, price=Decimal('20992.040000'), amount=Decimal('0.00400000'), creation_timestamp=1663083310.0)})
2022-09-13 15:35:29,102 - 142006 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1663083328.0, "order_id": "x-XEKWYICXSBCUD5e890c2140631ad70", "order_type": "OrderType.LIMIT_MAKER", "event_name": "MarketOrderFailureEvent", "event_source": "binance_us"}
2022-09-13 15:35:29,102 - 142006 - hummingbot.connector.client_order_tracker - INFO - Order x-XEKWYICXSBCUD5e890c2140631ad70 has failed. Order Update: OrderUpdate(trading_pair='BTC-USD', update_timestamp=1663083328.0, new_state=<OrderState.FAILED: 6>, client_order_id='x-XEKWYICXSBCUD5e890c2140631ad70', exchange_order_id=None, misc_updates=None)

And then the repeated line, thousands of times:
2022-09-13 21:42:35,002 - 142006 - hummingbot.strategy.hanging_orders_tracker - INFO - Hanging order passed max_distance from price=5.00% LimitOrder('x-XEKWYICXSBCUD5e890c2140631ad70', 'BTC-USD', False, 'BTC', 'USD', 20992.040000, 0.00400000, NaN, 1663083310000000). Removing...
2022-09-13 21:42:37,173 - 142006 - hummingbot.strategy.hanging_orders_tracker - INFO - Hanging order passed max_distance from price=5.00% LimitOrder('x-XEKWYICXSBCUD5e890c2140631ad70', 'BTC-USD', False, 'BTC', 'USD', 20992.040000, 0.00400000, NaN, 1663083310000000). Removing...
2022-09-13 21:42:39,018 - 142006 - hummingbot.strategy.hanging_orders_tracker - INFO - Hanging order passed max_distance from price=5.00% LimitOrder('x-XEKWYICXSBCUD5e890c2140631ad70', 'BTC-USD', False, 'BTC', 'USD', 20992.040000, 0.00400000, NaN, 1663083310000000). Removing...

**Comment by rapcmia** [comment]
PR update:
> * Test in progress, current testbot had not yet able to reproduce the issue
> * Test is being done on Bybit and Kucoin connectors
- Not able to replicate on Bybit and Kucoin long term bots 
- Setup Binance connector using the steps to reproduce provided by user 
- Monitoring overnight

**Comment by rapcmia** [comment]
PR update:
- Ran PR on long term bot for couple of days with hanging orders enabled:
   - Spreads enough to execute order
   - max_order_age with short filled_order_delay
- Review log files and does not indicate any endless loop nor error on renewal and cancellation of hanging order due to set cancel pct
- Monitoring live bot running locally specially on filled order events and hanging order renewals, all ok 

@kolibrie we tried to reproduce the issue but had no luck on our selected connectors `Bybit, Kucoin and Binance` and we moved on testing the PR and seems to be working as expected for PMM and Avellaneda. However our GitHub validation is having some failures based on the screenshot below:

image

**Comment by kolibrie** [comment]
On Wed, Oct 12, 2022 at 10:09:07PM -0700, rapcmia wrote:
> PR update:
> - Ran PR on long term bot for couple of days with hanging orders enabled:
>    - Spreads enough to execute order
>    - max_order_age with short filled_order_delay
> - Review log files and does not indicate any endless loop nor error on renewal and cancellation of hanging order due to set cancel pct
> - Monitoring live bot running locally specially on filled order events and hanging order renewals, all ok 
> 
> @kolibrie we tried to reproduce the issue but had no luck on our selected connectors `Bybit, Kucoin and Binance` and we moved on testing the PR and seems to be working as expected for PMM and Avellaneda. However our GitHub validation is having some failures based on the screenshot below:
> 
> image

I'm surprised you did not encounter the endless loop I
encountered.  I'll look to see what settings I had.

From the screenshot you sent, it seems that the GitHub validation
is failing because lack of test coverage.

I would love to run the tests and add more coverage, but I have
not been able to figure out how to do that.  Is there
documentation about how to run and add tests?  I have not been
able to find any on the hummingbot site.

**Comment by haroon123456789** [comment]
kolibrie:fix/hanging_order_cancel_loop

**Review by cardosofede — APPROVED** [review]
LGTM

**Review by cardosofede — CHANGES_REQUESTED** [review]
You should add the test for this change:
image

**Comment by kolibrie** [comment]
> You should add the test for this change: image

I would love to add tests.  I'm not sure how to do that.  I have never run the hummingbot tests and do not know how to do that.  Can you point me to some documentation on how to create and run hummingbot tests?

**Comment by rapcmia** [comment]
> I would love to add tests. I'm not sure how to do that. I have never run the hummingbot tests and do not know how to do that. Can you point me to some documentation on how to create and run hummingbot tests?

Hi @kolibrie apologies for the late response, this is [doc ](https://docs.hummingbot.org/developers/connectors/debug/#option-1-unit-test-cases)I found on our website and the sample unit tests you can check can be found on [/test](https://github.com/hummingbot/hummingbot/tree/development/test) folder of your repo

**Comment by rapcmia** [comment]
Hi @kolibrie good day to you.
Just want to confirm if you still need to work on this PR? would you be able to provide us a timeframe of the next possible commit? thank you

> Hi @kolibrie apologies for the late response, this is [doc ](https://docs.hummingbot.org/developers/connectors/debug/#option-1-unit-test-cases)I found on our website and the sample unit tests you can check can be found on [/test](https://github.com/hummingbot/hummingbot/tree/development/test) folder of your repo

**Comment by rapcmia** [comment]
Hi @kolibrie Good day to you,
We have not received any response from previous comment, we are closing this PR for now however in the event that you are available and continue to work on it please feel free to reopen. Thank you

**Pull request closed without merging**
