### PR TITLE
added triangular arbitrage strategy

### PR DESCRIPTION
**Pull request by trkoneill18**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

A Triangular Arbitrage Strategy

**Tests performed by the developer**:

- unit tests for each class (not included in submission)
- short-term tests of functionality with fabricated data (data not included in submission)
- long-term tests of strategy left unattended

**Tips for QA testing**:
It may take quite some time to see any trades. Moderately popular trading pairs are probably optimal.

### CODE REVIEW

**Review by CryptoGGytrs52 — DISMISSED** [review]

**Comment by phbrgnomo** [comment]
Hello @trkoneill18,

The Foundation was looking to add your PR to be voted following our governance proccess (https://snapshot.org/#/hbot.eth).

Could you take some time to update this PR to the current main version, and check the current test errors?

Feel free to reach me out on our Discord if you have an questions.

**Comment by phbrgnomo** [comment]
Hello @trkoneill18 

The Hummingbot Foundation just started the governance process for the community to approve or reject Pull Requests through **Pull Request Proposals**.

For more information about how PRP votes work, check this page: https://hummingbot.org/governance/prp/

We want to know if you still have interest in having your Pull Request merged into the main codebase.

If so, please check the following on your Pull Request for our team to be able to open it for community voting:

- Your Pull Request is targeted to the `development` branch
- Your branch is up to date with the current `development` branch
- All GitHub checks have passed
- There is no merging conflicts

If you have any questions or need any help, feel free to reach us out on the #dev-general channel on our Discord (https://discord.gg/HAgZ79nzU4)

----
If you have no interest in merging this PR to our code-base or don't reply to this comment in 30 days, the Foundation team will close this PR.

You can still create a new PR any time you want!

Thank you for contributing to Hummingbot Client!

**Comment by dennisocana** [comment]
We think this is a good addition to the list of strategies. A lot of users from the community have been asking about this however, CoinAlpha did not have enough bandwidth to create and maintain new strategies for Hummingbot.

**Comment by JeremyKono** [comment]
Hi @trkoneill18, please update this PR and create a HIP first, then please create a PRP so we can add this to the next release. Thanks!

**Pull request closed without merging**
