### PR TITLE
fix/user balance failure for time synchronizer

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Change in the logic that gets the user balance for Binance and Binance Perpetual. Since the exchange requires the time to be synchronized before any interaction, with this PR we add logic to the _update_balances() function to ensure the TimeSynchronizer has been initialized before requesting the balance.

**Tests performed by the developer**:
Added unit tests.

**Test summary**:
- Install the feature branch and start the Hummingbot client without any issues
- Adjust the machine time ahead by 10 minutes or more and connect the Binance and Binance perpetual API keys successfully
- Checked the balance and confirmed that balances are displayed
- Adjust the machine time by delaying it for about 10 minutes or more and rechecking the API key connections and confirming that keys are still confirmed.
- Started perpetual market-making and pure market-making strategies using the two connectors without any more issues or errors.
- Open the Binance exchange and check the timestamps of the open orders and confirmed that orders are using the Binance server time
- After an order gets filled or a position is opened and closed, checked the timestamp in the order history or trade history and confirmed that they used the Binance server time.

**Tips for QA testing**:
Run the balance command in a client instance with Binance and Binance Perpetual connectors correctly configured, and the machine time delayed 10 minutes.
Please consider that Binance and Binance Perpetual connectors can still sometimes cause an error when trying to process trade fills with fees in BNB. This error will keep happening until this PR is merged: https://github.com/hummingbot/hummingbot/pull/5160

This PR comes from https://github.com/CoinAlpha/hummingbot/pull/107

### CODE REVIEW

**Comment by dennisocana** [comment]
Proposal created: https://snapshot.org/#/hbot-prp.eth/proposal/0x2fbd38d3d00b395498daa595f4536d8719a0213a02a2cfb6d5ab99548fb70d5b

**Comment by JeremyKono** [comment]
Please resolve branch conflicts in this PR @aarmoa

**Comment by aarmoa** [comment]
@JeremyKono all issues have been fixed

**Comment by nikspz** [comment]
got an error `WARNING - Could not refresh server time. Check network connection.`
`ERROR - There was an error requesting exchange info`


Env: Win10 WSL Source, Ubuntu 18.04 LTS, Gitbash Source.

Steps to reproduce:
0. Install the feature branch
1. Adjust system time forward then test (12:39 pm)
(Start the Hummingbot client
Connect Binance API key
Connect Binance Perpetual API key
Run the balance command
Exit from the client and delete the encrypted json files of the exchanges)
2. Adjust system time backward then test  (12:19 pm)
(Start the Hummingbot client
Connect Binance API key
Connect Binance Perpetual API key
Run the balance command
Exit from the client and delete the encrypted json files of the exchanges)
3. Adjust system time forward  (12:39 pm)
(Start the Hummingbot client
Connect Binance API key
Connect Binance Perpetual API key
Run the balance command
Exit from the client and delete the encrypted json files of the exchanges)
4. Adjust system time  to correct time then test (12:29 pm)
Start the Hummingbot client and check the logs
Restart the bot and try to run the strategy

Actual:
After last restart got an errors that's `ongoing after restart the bot and clean re-install of PR`
WARNING - Could not refresh server time. Check network connection.
ERROR - There was an error requesting exchange info

Expected:
No error messages showing,
Bot's okay with trade fills and Filled trade records

[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/8242290/logs_hummingbot.log)

```
2022-03-14 12:57:31,515 - 8927 - hummingbot.connector.time_synchronizer - NETWORK - Error getting server time.
Traceback (most recent call last):
  File "/home/comp1/5165-lts/hummingbot/connector/time_synchronizer.py", line 58, in update_server_time_offset_with_time_provider
    server_time_ms: float = await time_provider
  File "/home/comp1/5165-lts/hummingbot/connector/exchange/binance/binance_web_utils.py", line 126, in get_current_server_time
    response = await api_request(
  File "/home/comp1/5165-lts/hummingbot/connector/exchange/binance/binance_web_utils.py", line 107, in api_request
    error_response = await response.json()
  File "/home/comp1/5165-lts/hummingbot/core/web_assistant/connections/data_types.py", line 110, in json
    json_ = await self._aiohttp_response.json()
  File "/home/comp1/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.binance.us/api/v3/time')
2022-03-14 12:57:31,517 - 8927 - hummingbot.connector.time_synchronizer - WARNING - Could not refresh server time. Check network connection.
2022-03-14 12:57:31,768 - 8927 - hummingbot.connector.exchange.binance.binance_api_order_book_data_source - ERROR - There was an error requesting exchange info (0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.binance.us/api/v3/exchangeInfo'))
```
image

After restart same issue

image
tried to clean reinstall:
image

**Comment by nikspz** [comment]
@aarmoa Upon crosschecking, team couldn't reproduce the issue on windows. 
We will retest latest commit on Ubuntu/VM and review.

**Review by nikspz — APPROVED** [review]
Test performed
 - Install the feature branch
 - Adjust system backwards by around 5 to 10 mins
 - Start the Hummingbot client
 - Connect Binance and Binance Perpetual API keys
 - Run the balance command
 - Exit from the client and delete the encrypted json files of the exchanges
 - Adjust system time forward by around to 5 to 10 min ahead
 - Reconnect Binance and Binance Perpetual API keys
 - Run the balance command
 - Create and start Pure market making strategy using Binance
 - Adjust system time either backwards or forward while the strategy runs
 - Restore correct time and create and start a perpetual market making strategy
 - Adjust system time either backwards or forward while the strategy runs
 - Filled trade records for Binance and Binance perpetual

**Pull request merged**
