### PR TITLE
feat/enable anonymous metrics in all branches

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Refactor of the logic that collects anonymous trade volume metrics and sends the information to Hummingbot Foundation. The previous logic that associated metrics collection to processing the logs has been removed. The new logic associates the trades volume metrics collection directly to the connectors, and used the events to gather trades (or order fills).
The configuration value `heartbeat_enabled` was renamed to `anonymized_metrics_enabled`.
The configuration value `heartbeat_interval_min` was renamed to `anonymized_metrics_interval_min`.

**Tests performed by the developer**:
Added new unit tests.
Executed a Pure Market Making strategy connected to Binance spot. I validated that the metrics appeared correctly in Datadog dashboard for metric `filled_usdt_volume`

**Test summary**:
- Created a pure_mm strategy and went through initial prompts successfully
- Confirmed wallet and exchange balances are reflecting correct
- Started the strategy without issues, confirmed orders are created and cancelled based on config
- Ran a test bot for hours without errors
- Confirmed in logs that there are no errors when orders are filled
- Trade information are correct (price, size) based on history command output
- Compared trades in client and exchange matched.
- Confirm metrics are being captured and converted to USD
- Confirmed metric interval is working as expected.
- Confirm rate_oracle are working as expected.
- Repeat steps and apply different strategies and connectors that are supported, and confirmed working as well.
- Confirmed working on USDT and non-USDT assets.
- Confirmed working on partial and full filled orders.

**Tips for QA testing**:
Check that metrics collection is active (`anonymized_metrics_enabled` should be configured with value True). The collection frequency can be increased by reducing the value of `anonymized_metrics_interval_min` (set it to 0.2 for example). You will need the value of the configuration `instance_id` to filter results in Datadog dashboard.

This PR comes from https://github.com/CoinAlpha/hummingbot/pull/129

### CODE REVIEW

**Comment by aarmoa** [comment]
Created proposal: https://snapshot.org/#/hbot-prp.eth/proposal/0xa40a145f9c6ea1d4e3adbf5394da0cf89ae78843c2483b6f8e3d8fcd8163d2e2

**Comment by mifeng** [comment]
This fixes a bug that prevents bots running the `master` branch from reporting anonymized, aggregate volume by exchange, which is important for the Foundation to enter into partnerships with exchanges that sustain it. Therefore, Hummingbot Foundation will merge in this PR as a hotfix.

**Review by mifeng — DISMISSED** [review]

**Comment by aarmoa** [comment]
@mifeng This PR should be merged in development independently of the hotfix PR that will be merged into master branch. The changes in this PR include the cleanup of no longer used components. The cleanup was not added in the hotfix PR pointing to master to reduce the risk of introducing errors in the production version.

**Review by rapcmia — APPROVED** [review]

**Comment by JeremyKono** [comment]
Hi, @aarmoa. The PR seems to have unrelated commits. Please fix the branch accordingly.

**Comment by rapcmia** [comment]
Partially tested the PR, getting an error when running the bot on source. Tried to recompile and crosscheck on AWS but still getting the same error

image

Steps to reproduce:
1. Clone the PR to Linux/Ubuntu18lts local or AWS
2. Run bin/hummingbot.py

**Comment by aarmoa** [comment]
> Hi, @aarmoa. The PR seems to have unrelated commits. Please fix the branch accordingly.

@JeremyKono the PR that has been merged into master with the hotfix was also merged into this branch. That will allow to solve merging issues between development branch and master branch when this PR is merged. I did that to prevent errors on your side when releasing the next development version, and that is why you see all the unrelated commits. Are you sure you want me to undo that?

**Comment by aarmoa** [comment]
@rapcmia I have pushed a fix to solve the issue. But please consider that just executing a .py file is not the correct way of starting a Pythong program. You should be executing `python3 bin/hummingbot.py`

**Comment by rapcmia** [comment]
@aarmoa the latest commit fix the reported issue on starting the client and moving forward will use `python3 bin/hummingbot.py`, thank you

PR update: ongoing test
Tested: 
- Beaxy, Binance, Ascendex, Kucoin, Gateio, Binance_f, Bybit_perp and dYdX_perp (full and partial fills)
- PMM, Avellaneda, LM, Arbitrage, PERP and XEMM
- Pending: Other spot and derivative connectors, strategies and partial fills

**Comment by rapcmia** [comment]
PR update: 
- Tested Huobi, Okex, Bittrex, Bitmart, Blocktane, CoinbasePro, Coinzoom, Crypto_com, Digifinex, and FTX
- Tested Hedge, Aroon_Oscillator, Spot-Arbitrage perpetual
- Pending: AMM_arb, protocol connectors and partial fills for other spot connectors

**Review by rapcmia — APPROVED** [review]
Test performed
- Create simple config for supported strategies
- Set anonymized_metrics_interval_min: 0.2s
- Tested all spot connectors mostly using Pure MM
- Tested all derivative connectors using Perpetual MM
- Set spreads tight enough for full and partial fills
- Compare trades from history, CSV and exchange trade history, all ok
- Checked datadog > hummingbot.filled_usdt_volume, all ok
- Confirmed metrics are being captured and converted to USD
- Confirmed metric interval is working as expected.
- Repeat steps and apply to different strategies and connectors that are supported, all ok

**Pull request merged**
