### PR TITLE
Feat/ displays gateway balance command so that it displays token balances by network rather than dex

### PR DESCRIPTION
**Pull request by isreallee82**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

- [ ] introduced a new class to create and get data from json file used  to save chain_network for gateway connector_tokens completer
- [ ] refactored balance to Get balances from chain_network
- [ ] remove unused Parameters and functionalities
- [ ] refactored the balance and connector_token display for chain_network feature

**Tests performed by the developer**:

- [x] connected chain and network ✅
- [x] ran gateway connector_tokens successfully ✅
- [x] gateway command balances displayed as proposed ✅

**Tips for QA testing**:

### CODE REVIEW

**Comment by isreallee82** [comment]
@nikspz working on gateway connector_tokens currently

**Comment by nikspz** [comment]
A) Currently connector-tokens not showing in total balance if added 

Steps:

1. connected quickswap_polygon_mainnet and uniswap_polygon_mainnet
2. Added different connector-tokens for polygon_mainnet
3. check gateway balance

Actual:
Not showing both tokens added

Expected:
Please modify the `gateway connector-tokens` command so that it accepts `chain_network` instead of exchange_chain_network

```
2023-12-05 15:30:56,912 - 2225040 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/home/nikita/gwbalance2chains/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/nikita/gwbalance2chains/hummingbot/client/command/gateway_command.py", line 633, in _update_gateway_connector_tokens
    conf: Optional[Dict[str, str]] = GatewayConnectionSetting.get_connector_spec_from_market_name(chain_network)
  File "/home/nikita/gwbalance2chains/hummingbot/client/settings.py", line 121, in get_connector_spec_from_market_name
    connector, network = market_name.split(f"_{chain}_")
ValueError: not enough values to unpack (expected 2, got 1)

```
image

B) I guess we should change from Exchange to `Chain_Network`

image

**Comment by isreallee82** [comment]
I think its ready for a review now @nikspz @fengtality

**Comment by nikspz** [comment]
@isreallee82 

A) Expected: 
drop-down list for chain_network available (polygon_mainnet ethereum mainnet etc), as previously available for exchanges

image

B)
Expected:
Please modify the gateway connector-tokens command so that it accepts chain_network instead of exchange_chain_network

image

**Comment by isreallee82** [comment]
a min @nikspz checking that currently

**Comment by isreallee82** [comment]
I see! I have to make few modifications battery is down should push in few hours

**Comment by isreallee82** [comment]
hi @nikspz @rapcmia my discord was hacked yesterday and used to send spam messages but I already reset all keys and removed all unauthorised applications, but currently I can't access hummingbot discord channel, is there anything I can do about that

**Comment by nikspz** [comment]
@isreallee82 check now

**Review by fengtality — APPROVED** [review]

**Pull request merged**
