### PR TITLE
(refactor) Create&updates Bitcom perpetual to the latest standards

### PR DESCRIPTION
**Pull request by yancong001**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR create BitCom connector to the latest standards.

**Tests performed by the developer**:
Test cases for the new code

**Tips for QA testing**:
Normal QA test for Perpetuals connectors.

### CODE REVIEW

**Comment by yancong001** [comment]
please run the ci again, I ran it correctly before @rapcmia

**Comment by rapcmia** [comment]
PR update:
- Account created on both mainnet and testnet
- APi keys are successfully connected
- Ran tests on bitcom tesnet https://beta.bitexch.dev/
- Setup simple Perp-MM using ETH-USDT

We are able to submit buy order however for sell its a no go getting the error below:

image

```
2023-03-30 10:43:37,268 - 44284 - hummingbot.connector.derivative.bit_com_perpetual.bit_com_perpetual_derivative.BitComPerpetualDerivative - NETWORK - Error submitting sell LIMIT order to Bit_com_perpetual for 0.10000000 ETH-USD 1785.35000000.
Traceback (most recent call last):
  File "/Users/ralphcomia/hbot/github/hummingbot/6154/hummingbot/connector/exchange_py_base.py", line 484, in _create_order
    exchange_order_id = await self._place_order_and_process_update(order=order, **kwargs,)
  File "/Users/ralphcomia/hbot/github/hummingbot/6154/hummingbot/connector/exchange_py_base.py", line 502, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/Users/ralphcomia/hbot/github/hummingbot/6154/hummingbot/connector/derivative/bit_com_perpetual/bit_com_perpetual_derivative.py", line 273, in _place_order
    o_id = str(order_result['data']["order_id"])
TypeError: 'NoneType' object is not subscriptable
```

Observed that we are getting `Unexpected error while processing event 200` and `Unexpected error while processing event 201`

```
2023-03-30 10:42:36,231 - 44284 - hummingbot.connector.derivative.bit_com_perpetual.bit_com_perpetual_derivative.BitComPerpetualDerivative - ERROR - Unexpected error while processing event 200.
Traceback (most recent call last):
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: Order.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
    self(arg)
  File "/Users/ralphcomia/hbot/github/hummingbot/6154/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/Users/ralphcomia/hbot/github/hummingbot/6154/hummingbot/connector/markets_recorder.py", line 223, in _did_create_order
    self.save_market_states(self._config_file_path, market, session=session)
  File "/Users/ralphcomia/hbot/github/hummingbot/6154/hummingbot/connector/markets_recorder.py", line 156, in save_market_states
    market_states: Optional[MarketState] = self.get_market_states(config_file_path, market, session=session)
  File "/Users/ralphcomia/hbot/github/hummingbot/6154/hummingbot/connector/markets_recorder.py", line 184, in get_market_states
    market_states: Optional[MarketState] = query.one_or_none()
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1662, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 312, in orm_pre_session_exec
    session._autoflush()
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2259, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2248, in _autoflush
    self.flush()
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3444, in flush
    self._flush(objects)
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3584, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3544, in _flush
    flush_context.execute()
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1097, in _emit_insert_statements
    c = connection._execute_20(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: Order.id
[SQL: INSERT INTO "Order" (id, config_file_path, strategy, market, symbol, base_asset, quote_asset, creation_timestamp, order_type, amount, leverage, price, last_status, last_update_timestamp, exchange_order_id, position) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('HBOTBEHUD5f8150b9714c7ca9a776104', 'perp-bitcom-testnet.yml', 'perpetual_market_making', 'bit_com_perpetual', 'ETH-USD', 'ETH', 'USD', 1680144156000, 'LIMIT', 100000, 1, 1749997000, 'BuyOrderCreated', 1680144156000, '59281611', 'OPEN')]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

```
2023-03-30 10:31:58,174 - 42352 - hummingbot.connector.derivative.bit_com_perpetual.bit_com_perpetual_derivative.BitComPerpetualDerivative - ERROR - Unexpected error while processing event 201.
Traceback (most recent call last):
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: Order.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
    self(arg)
  File "/Users/ralphcomia/hbot/github/hummingbot/6154/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/Users/ralphcomia/hbot/github/hummingbot/6154/hummingbot/connector/markets_recorder.py", line 223, in _did_create_order
    self.save_market_states(self._config_file_path, market, session=session)
  File "/Users/ralphcomia/hbot/github/hummingbot/6154/hummingbot/connector/markets_recorder.py", line 156, in save_market_states
    market_states: Optional[MarketState] = self.get_market_states(config_file_path, market, session=session)
  File "/Users/ralphcomia/hbot/github/hummingbot/6154/hummingbot/connector/markets_recorder.py", line 184, in get_market_states
    market_states: Optional[MarketState] = query.one_or_none()
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1662, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 312, in orm_pre_session_exec
    session._autoflush()
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2259, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2248, in _autoflush
    self.flush()
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3444, in flush
    self._flush(objects)
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3584, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3544, in _flush
    flush_context.execute()
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1097, in _emit_insert_statements
    c = connection._execute_20(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/ralphcomia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: Order.id
[SQL: INSERT INTO "Order" (id, config_file_path, strategy, market, symbol, base_asset, quote_asset, creation_timestamp, order_type, amount, leverage, price, last_status, last_update_timestamp, exchange_order_id, position) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('HBOTSEHUD5f814e59002f93f46d91aac', 'perp-bitcom-testnet.yml', 'perpetual_market_making', 'bit_com_perpetual', 'ETH-USD', 'ETH', 'USD', 1680143518000, 'LIMIT', 100000, 1, 1785350000, 'SellOrderCreated', 1680143518000, '59281372', 'OPEN')]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

Pending:
- Connector behavior for:
  - Creating take-profit order for short and long position
  - stop-loss order creation
  
[6154.zip](https://github.com/hummingbot/hummingbot/files/11107312/6154.zip)

**Comment by yancong001** [comment]
fixed @rapcmia

**Comment by rapcmia** [comment]
PR update:
- Setup on AWS using `bit_com_perpetual_testnet`
- Order create and cancelation are ok at 60s
- There are instances of the exchange returning `Error executing request GET https://betaapi.bitexch.dev/linear/v1/orders. HTTP status is 429. Error: Too many requests, Please try again later. path: /linear/v1/orders`
  image
  - No indication that it has been canceled and the order on exchange is also not available 
  - Tried to setup a config with tight spreads to open position but still ending up with the same issue and eventually orders were considered lost
  image

Steps to reproduce:
- Setup perp-mm using bit_com perpetual_testnet
- Observe connector behavior when there are active orders

Pending: 
- Position open and take-profit/stop-loss order created
- Position closed and take-profit/stop-loss order filled
- Filled order events

[6154.zip](https://github.com/hummingbot/hummingbot/files/11135152/6154.zip)

**Comment by yancong001** [comment]
I've optimized the query for trades, and if 429 Error continues to appear, I'll consider lowering its limit. @rapcmia

**Review by rapcmia — APPROVED** [review]
- API setup on both live and testnet all ok 
- Observe orderbook in both client and connector, ok 
- Most of the tests done on testnet using eth-usd and btc-usd
	- order create/cancel, ok 
	- position opened {long,short} and take-profit/stop-loss order created
	- position closed after tp/sl order filled
	- position retrieved? yes 

Note: We are working on improvements for bronze / new community connectors. Please be advised that this connector has not been fully tested on mainnet and community can submit a bug report and inform the developer if necessary. Thank you

**Review by cardosofede — APPROVED** [review]
LGTM!

**Review by cardosofede — APPROVED** [review]
LGTM!

**Comment by yancong001** [comment]
added
https://github.com/hummingbot/hummingbot-site/pull/182
@david-hummingbot

**Pull request merged**
