### PR TITLE
(feat) add side to liquidation data

### PR DESCRIPTION
**Pull request by p-meier**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

I added the side of the liquidations - whether it is the shorts (=buy orders) or longs (=sell orders) that got liquidated. 

**Tests performed by the developer**:

Usage in own strategy with logging (status --live) and adapting the automated tests. 

**Tips for QA testing**:

None

### CODE REVIEW

**Review by cardosofede — APPROVED** [review]
The changes are okey, one thing to review will be instead of using LiquidationSide you can use TradeType.BUY or TradeType.SELL, maybe is better to use the same structure to compare sides in the strategy later on

**Review by nikspz — APPROVED** [review]
image

**Comment by p-meier** [comment]
@cardosofede thanks for the feedback. I thought about that but normally when I hear people talking about liquidations they speak from Long / Short Liquidations and not in which side the forced order was executed.

Therefore I found it easier to grasp by doing the inversion in the LiquidationsFeed instead of later on in the strategy.

However I am also happy to change it if you like.

**Comment by cardosofede** [comment]
> @cardosofede thanks for the feedback. I thought about that but normally when I hear people talking about liquidations they speak from Long / Short Liquidations and not in which side the forced order was executed.
> 
> Therefore I found it easier to grasp by doing the inversion in the LiquidationsFeed instead of later on in the strategy.
> 
> However I am also happy to change it if you like.

yep I agree, seems more descriptive too

**Pull request merged**
