### PR TITLE
refactor/change avellaneda mm reserved to reservation

### PR DESCRIPTION
**Pull request by sisco0**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

The changes stated in https://github.com/hummingbot/hummingbot/issues/4935 have been performed. Modifications were based on function and member variables renaming over  `hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pxd`, `hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx`, and `test/hummingbot/strategy/avellaneda_market_making/test_avellaneda_market_making.py`.

The **documentation was not required for being updated**, as it already contains the same terminology as the referred _Avellaneda_ paper.

**Tests performed by the developer**:

A compilation of the application using `./compile` was performed. Added to that, `make test` has been executed. There were no inconveniences on any of these processes.

**Tips for QA testing**:

No specific treatment should be done, just ensuring that _Avellaneda MM_ works as expected for QA testing specific cases with this new naming convention.

### CODE REVIEW

**Comment by phbrgnomo** [comment]
Hello @sisco0 

A Pull Request Proposal was created related to this PR: https://snapshot.org/#/hbot.eth/proposal/0xda82709e40512662d17bfb8b0aaa229fa3ac5785d8a1906b46e126a369d90c5d

Make sure to keep an eye on community reviews for the following days.

Thank you for contributing with Hummingbot Client!

**Comment by rapcmia** [comment]
PR update: on-going test

**Review by Nullably — APPROVED** [review]
LGTM

**Review by rapcmia — APPROVED** [review]
Tested and approved by QA
Test performed:
- Successfully setup Avellaneda strategy 
- Monitor order create and cancellation with or w/o min_spread 
- Reservation price is now displayed when running the status command
- Tested multiple levels, hanging orders, and order override
- Executed trades and confirmed no issues on trade fill
- Tested on each execution timeframes and monitor closing time 
- Tested on paper trade

**Comment by sisco0** [comment]
> @aarmoa Abel the developer is not answering. Do you know how to solve the branch conflicts in the web editor?

I would be available by tuesday, as I am out of office until then. I have no inconvenience for other project members to contribute to this PR.

**Comment by sisco0** [comment]
@RobHBOT, the merge operation has been solved now, and tests seem to run under the Github Actions 
triggered operation related to this last commit. The PR is updated with latest Avellaneda changes and 
it could be merged without inconvenience.﻿

**Comment by rapcmia** [comment]
PR update: on-going test

**Review by rapcmia — APPROVED** [review]
LGTM

**Pull request merged**
