### PR TITLE
feat/simplify starter scripts

### PR DESCRIPTION
**Pull request by fengtality**
This PR cleans up the `/scripts` directory and basic script examples. Now, there are only 5 scripts that are in `scripts`:

* simple PMM
* simple VWAP
* simple XEMM
* V2 directional RSI
* V2 XEMM
* V2 TWAP
* V2 Funding Rate Arbitrage
* V2 Controller Loader

All the simple scripts accept config files.

Other scripts are located in sub-folders in the main `scripts` directory, no longer nested in `/achived-scripts`.

**Instructions for QA**
- Test each simple script with different connectors
- Test the V2 loader script with each of the V2 controllers

### CODE REVIEW

**Review by rapcmia — APPROVED** [review]
- simple_pmm
    - Setup with Kraken and spreads enough for trade event ok
- simple_xemm
    - Setup with Kraken and Binance
    - Setup with two paper trade connectors ok
- v2_generic_with_controllers
    - Setup with binance perp
        - directional_trading.bollinger_v1
        - market_making.dman_maker
        
---

Pending:
- simple_rsi
- simple_vwap

**Comment by nikspz** [comment]
commit 8033e91
@fengtality 
need to add leverage for simple_rsi on script config creation

Steps:
1. create --script-config simple_rsi
2. review script config not ask for `leverage`

Actual:
default config created with leverage 1

image
image

**Comment by nikspz** [comment]
@fengtality 
commit 40d1c0f,

issue with config creation fixed ✔

simple_rsi

Client not created order to `OPEN short` position for upper bound,  ❌
not created order to `OPEN long` position on lower bound ❌

Steps to reproduce:
1. Clone PR7011 commit 40d1c0f
2. connect binance_perpetual
3. use config provided (

Actual:
Review no orders OPENed for bound upper than 70 and below 30 


```
script_file_name: simple_rsi.py
exchange: binance_perpetual
trading_pair: DOGE-USDT
candles_exchange: binance_perpetual
candles_pair: DOGE-USDT
candles_interval: 1m
candles_length: 60
order_amount_usd: 20
leverage: 10
rsi_low: 30.0
rsi_high: 70.0
```


[conf_simple_rsi_1.yml.txt](https://github.com/hummingbot/hummingbot/files/15245508/conf_simple_rsi_1.yml.txt)
[70118may.zip](https://github.com/hummingbot/hummingbot/files/15245503/70118may.zip)

Client should place OPEN order for simple_rsi
rsi should place buy order

image

**Comment by fengtality** [comment]
Thanks @nikspz. I think that simple_rsi script is outdated. I decided to use the V2 directional script instead, which should fix the issues you saw. I also moved the other V2 scripts into the base scripts folder but I don't think you need to re-test them.

**Comment by nikspz** [comment]
- Created / started script config
    - simple_pmm: successfully
    - simple_vwap: ok
- Created  —script-config v2_simple_directional_rsi
- started v2_directional_rsi with —conf, got error
    - ModuleNotFoundError: No module named 'hummingbot.smart_components'

[logs_conf_v2_simple_directional_rsi_1.log](https://github.com/hummingbot/hummingbot/files/15305014/logs_conf_v2_simple_directional_rsi_1.log)

[7011.zip](https://github.com/hummingbot/hummingbot/files/15305011/7011.zip)

```
2024-05-14 07:44:34,442 - 1900408 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: No module named 'hummingbot.smart_components'
Traceback (most recent call last):
  File "/home/nikita/simpled7011/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/nikita/simpled7011/hummingbot/client/command/start_command.py", line 125, in start_check
    self._initialize_strategy(self.strategy_name)
  File "/home/nikita/simpled7011/hummingbot/client/command/start_command.py", line 280, in _initialize_strategy
    self.start_script_strategy()
  File "/home/nikita/simpled7011/hummingbot/client/command/start_command.py", line 191, in start_script_strategy
    script_strategy, config = self.load_script_class()
  File "/home/nikita/simpled7011/hummingbot/client/command/start_command.py", line 213, in load_script_class
    script_module = importlib.import_module(f".{script_name}", package=settings.SCRIPT_STRATEGIES_MODULE)
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nikita/simpled7011/scripts/v2_directional_rsi.py", line 13, in <module>
    from hummingbot.smart_components.executors.position_executor.data_types import (
ModuleNotFoundError: No module named 'hummingbot.smart_components'
```
image

**Comment by fengtality** [comment]
@nikspz The library import issue should be fixed now

**Comment by fengtality** [comment]
@nikspz I'd like to merge this in so we can wrap up the Vega video

**Review by nikspz — APPROVED** [review]
- simple_pmm: ok
- simple_xemm: ok
    - Setup with Kraken and Binance
    - Setup with two paper trade connectors ok
- v2_with_controllers: ok
- simple_vwap: ok
- v2_directional_rsi: ok

**Pull request merged**
