### PR TITLE
Feat/Adapt Trade Intensity Indicator to Use Trade Events 

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Stores the most recent trades in the order book class and makes them available to strategies.
Replaces simulation in trading intensity with real trades from the exchange.
Update of the Avellaneda-Stoikov strategy to use the new sampling.

**Tests performed by the developer**:

Ran the Avellaneda-Stoikov strategy in this branch side by side with the version in the development branch and compared their behavior as well as calculated trading intensity variables.
Ran unit tests.

**Tips for QA testing**:

The version in this branch should give roughly the same results as the version in the development branch, but not necessarily exactly the same. Namely the orders placed in the market should be roughly the same, and the variables `order_book_intensity_factor` and `order_book_depth_factor` should be roughly the same.

### CODE REVIEW

**Comment by aarmoa** [comment]
PRP: https://snapshot.org/#/hbot-prp.eth/proposal/0x645eab7e59b4b1de4e9ef69e67451ab4f09ace92f8568b8c659d3c42adc4d382

**Comment by JeremyKono** [comment]
Hi @mhrvth, please fix github tests which are failing. Thanks!

**Comment by mhrvth** [comment]
@JeremyKono  Hi, it's fixed now.

**Review by rapcmia — APPROVED** [review]
Test performed:
- Install feature branch, ok
- Setup two testbots running Avellaneda on same connector/markets on development and this PR
- Configure trading intense parameter similar to each of the testbots
- Started strategy and monitor client behavior, all ok
- Compare risk_factor, order_book_intensity, order_book_depth_factor
- Compare orders created, close enough
- Compare status after filled trades on each instance, all ok

**Pull request merged**
