### PR TITLE
Feat/injective protocol

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

On the client side, this PR introduces the generalized CLOB connector and the injective api data source.

Please see the [associated Gateway PR](https://github.com/hummingbot/gateway/pull/19) for more details on how to setup the connector with Gateway.

## Tips for QA
 
Please test the full extent of the new injective connector. This connector should connect to Gateway as a regular DEX connector, but should behave as a spot connector as far as the strategies are concerned. This means that it should populate the order book and work with any strategy that uses spot connectors.

Please also test running a strategy with a regular Gateway connector (including connection setup), and running a strategy with a regular spot connector (including connection setup).

Please also ensure we have tested one strategy using legacy configs (e.g. PMM) and one strategy using Pydantic configs (e.g. AMM).

Finally, please test running a strategy with an existing spot connector. No need to test this thoroughly — a couple of cycles should suffice.

Link to the associated PRP: https://snapshot.org/#/hbot-prp.eth/proposal/0xb49a91cc0b9b65948b8bb408cb5269dff42fde73bb6c4127b6c31dccf560016e
Link to associated Gateway PR: https://github.com/hummingbot/gateway/pull/19

### CODE REVIEW

**Review by cardosofede — APPROVED** [review]
LGTM!

**Comment by rapcmia** [comment]
PR update: 
- PR has been tested on `AWS (ubuntu20.04) source client + source gateway build`
- Setup this PR and gateway PR#19 and both successfully connected, `gateway list` shows `Injective protocol`
   image
- Connected wallet and balance displayed ok 
- Setup a PMM for INJ/USDT and with 30s refresh time
  - Orders are created and cancelled successfully
  - There are events of `failed to fetch trade updates` at the start of the bot
  ```
  2023-02-27 12:13:35,817 - 939243 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
  2023-02-27 12:13:40,789 - 939243 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - NETWORK - Error fetching status update for the order BIJUT5f5ad68813f219103e828e07df9e327f4638cb3b43b65: <AioRpcError of RPC that terminated with:
	  status = StatusCode.NOT_FOUND
	  details = "object not found"
	  debug_error_string = "UNKNOWN:Error received from peer ipv4:34.138.231.254:443 {grpc_message:"object not found", grpc_status:5, created_time:"2023-02-27T12:13:40.78953993+00:00"}"
  >.
  2023-02-27 12:13:40,790 - 939243 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - WARNING - Failed to fetch status update for the order BIJUT5f5ad68813f219103e828e07df9e327f4638cb3b43b65.
  2023-02-27 12:13:41,352 - 939243 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - NETWORK - Error fetching status update for the order SIJUT5f5ad688140209103e828e07df9e327f4638cb3b43b65: <AioRpcError of RPC that terminated with:
	  status = StatusCode.NOT_FOUND
	  details = "object not found"
	  debug_error_string = "UNKNOWN:Error received from peer ipv4:34.138.231.254:443 {grpc_message:"object not found", grpc_status:5, created_time:"2023-02-27T12:13:41.351806509+00:00"}"
  >.
  2023-02-27 12:13:41,352 - 939243 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - WARNING - Failed to fetch status update for the order SIJUT5f5ad688140209103e828e07df9e327f4638cb3b43b65.
  2023-02-27 12:13:42,170 - 939243 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER BUY order BIJUT5f5ad68813f219103e828e07df9e327f4638cb3b43b65 for 1.000000000000000000 INJ-USDT.
  2023-02-27 12:13:42,182 - 939243 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1677500022.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "INJ-USDT", "amount": "1.000000000000000000", "price": "3.601", "order_id": "BIJUT5f5ad68813f219103e828e07df9e327f4638cb3b43b65", "creation_timestamp": 1677500015.0, "exchange_order_id": "0x66f539321fe51d398529d82f500d53f7d4627c3c387a5426da47ab2a6689f872", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "injective_injective_mainnet"}
  2023-02-27 12:13:43,019 - 939243 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER SELL order SIJUT5f5ad688140209103e828e07df9e327f4638cb3b43b65 for 1.000000000000000000 INJ-USDT.
  2023-02-27 12:13:43,029 - 939243 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1677500023.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "INJ-USDT", "amount": "1.000000000000000000", "price": "3.824", "order_id": "SIJUT5f5ad688140209103e828e07df9e327f4638cb3b43b65", "creation_timestamp": 1677500015.0, "exchange_order_id": "0xc6989a35e17f2a536dd28ac54120906b6995bf8bac39be1da4d02a793b9e4bfc", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "injective_injective_mainnet"}
  ```
- Observed `unhandled error in background task: No update found for order...`
  - It seems a client delayed on recognizing the `order_id` but still the client successfully create and cancel at the set order refresh time
  ```
    2023-02-27 12:19:40,754 - 939385 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: No update found for order SIJUT5f5ad7e05af3b7e23e4b41fb107570a4f64fd5307de42
    Traceback (most recent call last):
      File "/home/ubuntu/6068/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
        return await c
      File "/home/ubuntu/6068/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 421, in get_order_status_update
        raise IOError(f"No update found for order {in_flight_order.client_order_id}")
    OSError: No update found for order SIJUT5f5ad7e05af3b7e23e4b41fb107570a4f64fd5307de42
    2023-02-27 12:19:40,794 - 939385 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER SELL order SIJUT5f5ad7e05af3b7e23e4b41fb107570a4f64fd5307de42 for 1.000000000000000000 INJ-USDT.
    2023-02-27 12:19:40,804 - 939385 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1677500380.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "INJ-USDT", "amount": "1.000000000000000000", "price": "3.826", "order_id": "SIJUT5f5ad7e05af3b7e23e4b41fb107570a4f64fd5307de42", "creation_timestamp": 1677500376.0, "exchange_order_id": "0xf11614963c7544befe595fc74e8b158be64e36ce6ca800bc939215ad2f57d349", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "injective_injective_mainnet"}
    2023-02-27 12:20:06,044 - 939385 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (INJ-USDT) Canceling the limit order BIJUT5f5ad7e05ae5d7e23e4b41fb107570a4f64fd5307de42. [clock=2023-02-27 12:20:06+00:00]
    2023-02-27 12:20:06,044 - 939385 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (INJ-USDT) Canceling the limit order SIJUT5f5ad7e05af3b7e23e4b41fb107570a4f64fd5307de42. [clock=2023-02-27 12:20:06+00:00]
    2023-02-27 12:20:08,912 - 939385 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1677500408.0, "order_id": "BIJUT5f5ad7e05ae5d7e23e4b41fb107570a4f64fd5307de42", "exchange_order_id": "0xe8a23c87d157b2d2d67ebb3c03a18f1fe0fc7b9e95a410b54f07dd931b208879", "event_name": "OrderCancelledEvent", "event_source": "injective_injective_mainnet"}
    2023-02-27 12:20:08,912 - 939385 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order BIJUT5f5ad7e05ae5d7e23e4b41fb107570a4f64fd5307de42.
    2023-02-27 12:20:09,992 - 939385 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1677500409.0, "order_id": "SIJUT5f5ad7e05af3b7e23e4b41fb107570a4f64fd5307de42", "exchange_order_id": "0xf11614963c7544befe595fc74e8b158be64e36ce6ca800bc939215ad2f57d349", "event_name": "OrderCancelledEvent", "event_source": "injective_injective_mainnet"}
    2023-02-27 12:20:09,992 - 939385 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order SIJUT5f5ad7e05af3b7e23e4b41fb107570a4f64fd5307de42.
- While monitoring for more than 30mins we found some instances of `Failed to cancel order`
    - Error happened at the set refresh time (30s)
    ```
    # Created order
    2023-02-27 12:21:57,779 - 939385 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER SELL order SIJUT5f5ad864f02447e23e4b41fb107570a4f64fd5307de42 for 1.000000000000000000 INJ-USDT.
    
    2023-02-27 12:21:57,789 - 939385 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1677500517.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "INJ-USDT", "amount": "1.000000000000000000", "price": "3.819", "order_id": "SIJUT5f5ad864f02447e23e4b41fb107570a4f64fd5307de42", "creation_timestamp": 1677500515.0, "exchange_order_id": "0xf53d2e6bdfe48478456abb82f08bea3f3ca83f2d7f945f27ef6e032d8b2f2edf", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "injective_injective_mainnet"}
    2023-02-27 12:21:57,791 - 939385 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER BUY order BIJUT5f5ad864f015d7e23e4b41fb107570a4f64fd5307de42 for 1.000000000000000000 INJ-USDT.
    2023-02-27 12:21:57,800 - 939385 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1677500517.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "INJ-USDT", "amount": "1.000000000000000000", "price": "3.597", "order_id": "BIJUT5f5ad864f015d7e23e4b41fb107570a4f64fd5307de42", "creation_timestamp": 1677500515.0, "exchange_order_id": "0x22b444f67e5e7bee6419b1aa77445c1998d61647e07e68a4159f98f53bef8d2e", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "injective_injective_mainnet"}
    2023-02-27 12:22:25,001 - 939385 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (INJ-USDT) Canceling the limit order BIJUT5f5ad864f015d7e23e4b41fb107570a4f64fd5307de42. [clock=2023-02-27 12:22:25+00:00]
    2023-02-27 12:22:25,001 - 939385 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (INJ-USDT) Canceling the limit order SIJUT5f5ad864f02447e23e4b41fb107570a4f64fd5307de42. [clock=2023-02-27 12:22:25+00:00]
    
    # Error occurred
    2023-02-27 12:22:31,528 - 939385 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15888/clob/orders failed. See logs for more details.
    2023-02-27 12:22:31,529 - 939385 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - ERROR - Failed to cancel order SIJUT5f5ad864f02447e23e4b41fb107570a4f64fd5307de42
    Traceback (most recent call last):
      File "/home/ubuntu/6068/hummingbot/connector/exchange_py_base.py", line 551, in _execute_order_cancel
        cancelled = await self._execute_order_cancel_and_process_update(order=order)
      File "/home/ubuntu/6068/hummingbot/connector/gateway/clob_spot/gateway_clob_spot.py", line 340, in _execute_order_cancel_and_process_update
        cancelled, misc_order_updates = await self._api_data_source.cancel_order(order=order)
      File "/home/ubuntu/6068/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 232, in cancel_order
        cancelation_result = await self._get_gateway_instance().clob_cancel_order(
      File "/home/ubuntu/6068/hummingbot/core/gateway/gateway_http_client.py", line 1221, in clob_cancel_order
        return await self.api_request("delete", "clob/orders", request_payload)
      File "/home/ubuntu/6068/hummingbot/core/gateway/gateway_http_client.py", line 217, in api_request
        raise e
      File "/home/ubuntu/6068/hummingbot/core/gateway/gateway_http_client.py", line 205, in api_request
        raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
    ValueError: Error on DELETE https://localhost:15888/clob/orders Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': 'Error: Request failed with status code 503\n    at createError (/home/ubuntu/19/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/home/ubuntu/19/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/home/ubuntu/19/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)'}
    2023-02-27 12:22:32,574 - 939385 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1677500552.0, "order_id": "BIJUT5f5ad864f015d7e23e4b41fb107570a4f64fd5307de42", "exchange_order_id": "0x22b444f67e5e7bee6419b1aa77445c1998d61647e07e68a4159f98f53bef8d2e", "event_name": "OrderCancelledEvent", "event_source": "injective_injective_mainnet"}
    2023-02-27 12:22:32,574 - 939385 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order BIJUT5f5ad864f015d7e23e4b41fb107570a4f64fd5307de42.
    2023-02-27 12:23:26,001 - 939385 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (INJ-USDT) Canceling the limit order SIJUT5f5ad864f02447e23e4b41fb107570a4f64fd5307de42. [clock=2023-02-27 12:23:26+00:00]
    2023-02-27 12:23:29,019 - 939385 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1677500609.0, "order_id": "SIJUT5f5ad864f02447e23e4b41fb107570a4f64fd5307de42", "exchange_order_id": "0xf53d2e6bdfe48478456abb82f08bea3f3ca83f2d7f945f27ef6e032d8b2f2edf", "event_name": "OrderCancelledEvent", "event_source": "injective_injective_mainnet"}
    2023-02-27 12:23:29,019 - 939385 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order SIJUT5f5ad864f02447e23e4b41fb107570a4f64fd5307de42.
    ```
- Filled orders are recorded and trade data matched between history, CSV and connector trade history.

Steps to reproduce:
1. setup client and gateway on source build
2. setup PMM and observe behavior on order create, cancellation and filled events

[6068.zip](https://github.com/hummingbot/hummingbot/files/10840283/6068.zip)

Pending
- AMM strategy

**Comment by nikspz** [comment]
Env: `docker client + docker gateway`
Tests performed:
- Cloned and installed feature branch
- Created docker image of PR6068 manually
- Created image of gwPR19 manually
- Set up/started injective gateway + injective client PR using docker
- connected injective: ok, however got an error about `couldn't find the time zone configuration` (warning said bot will use default UTC)
- checked balance: ok
- created/ran pureMM strategy: ok
- Reviewed orders created/refreshing on exchange: ok
- Checked order_book/status: ok, matched with exchange
- Filled orders recorded in data folder: ok, however `no txhash in CSV/docker logs recorded` 
- curl tests:
    - port: ok
    - wallet/add: ok
    - /injective/balances: ok, returns balance
    - injective/poll: ok
    - clob/orders: ok
    - clob/orders delete: ok
        - deleted order from the exchange
    - clob/orders POST: ok
        - order created on the exchange
    - /injective/transfer/to/bank and /injective/transfer/to/sub - was able to do the curl commands, but not sure if it’s still needed since there’s only account wallet here
    
Issue showed on connecting injective wallet (used docker client + docker gateway):
image

**Comment by petioptrv** [comment]
Thank you for testing.

@rapcmia, the errors you have reported are due to the nature of the blockchain. The transactions have to be included into a block before we can successfully obtain an order status update. In that time, we get those errors. I don't think we should hide the errors since it will make it difficult to diagnose real issues with the order status fetching in the future. 

@nikspz, from the screenshot you shared, it sounds like the tz issue needs to be [addressed at the system level](https://github.com/PrefectHQ/prefect/issues/3061). For the missing txhash in the csv files, can you share the logs and the CSV for that session please?

**Comment by petioptrv** [comment]
@rapcmia, I think you already confirmed this, but to re-iterate, the crucial part in terms of order status updates is to ensure that the history we are logging is the same as what we see on the exchange. Also, of course, that we don't get any orphan orders on either side

**Comment by nikspz** [comment]
> 
> For the missing txhash in the csv files, can you share the logs and the CSV for that session please?
@petioptrv 

Here for pureMM and Amm-arb:
[New228-logs.zip](https://github.com/hummingbot/hummingbot/files/10848311/New228-logs.zip)
[New228-data.zip](https://github.com/hummingbot/hummingbot/files/10848312/New228-data.zip)
Also no txhash address showed in gw logs. You could check only filled order_id in SQLite file

Also noticed amm-arb placed/filled only one side orders

**Comment by petioptrv** [comment]
@cardosofede, @nikspz, @rapcmia, I've added a change to include the transaction hashes into order status updates in the latest commit.

**Review by nikspz — APPROVED** [review]
- Setup PR and gwPR19 for tests
- Setup source and docker build on AWS (ubuntu20.04)
- Connect wallet successfully and balance only display trading account balance 
- Setup simple PMM strategy and AMM-arbitrage
- Orders are successfully created, cancelled and filled
- There are noticeable logs for failed fetch or not updated orders but no instance of stuck order
- Filled order event records trade data successfully and matched between history, CSV and exchange trade history
- Ran long term bot and monitor behavior with options hanging order, cancel percentage and max order age: ok

**Review by cardosofede — APPROVED** [review]
LGTM!

**Pull request merged**
