### PR TITLE
Feat/Tegro Connector

### PR DESCRIPTION
**Pull request by isreallee82**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
A description of the changes proposed in the pull request:

This pull request introduces the Tegro connector exchange integration into the Hummingbot codebase.
The key features include:

Methods for creating, tracking, and updating orders.
Approve allowance functionality for tokens on a decentralized exchange.
Tests performed by the developer:

Unit tests for the classes to ensure proper authentication.
Integration tests for order creation, tracking, and updating to verify state transitions.
Approval allowance functionality was tested with different tokens to ensure correct handling and transaction signing.
Setup mmm strategy:
places orders and cancelled orders successful
orderbook feed works fine
balance works fine

Tips for QA testing:

**Tests performed by the developer**:
testnet - https://testnet.tegro.com
mainnet - https://tegro.com

**Tips for QA testing**:

### CODE REVIEW

**Comment by fengtality** [comment]
Hi @isreallee82 unfortunately we no longer accept new Gateway CLOB connectors. This PR would need to be entirely Hummingbot with no Gateway dependency for the Foundation to accept this into the codebase.

**Comment by isreallee82** [comment]
NCP is submitted: 

https://snapshot.org/#/hbot-ncp.eth/proposal/0xa03af5815eabc39b9fa6947842348a211ffb7ead61b2b716d61fd2463a602087

**Comment by nikspz** [comment]
dc54267

@isreallee82 

Test performed:
- Cloned and installed PR7148
- connected eth wallet using `base` (review no dropdown (available) chains showed on connect)
- review correct balance reported, matched with wallet
- created pureMM using tegro mainnet connector
- review price in Client and price in Exchange do not match



[7148tegro.zip](https://github.com/user-attachments/files/17396061/7148tegro.zip)
[logs_tegro.log](https://github.com/user-attachments/files/17396063/logs_tegro.log)


no dropdown available chains:
image

price not match Client/exchange
image
image

**Comment by isreallee82** [comment]
okay moment @nikspz

**Comment by isreallee82** [comment]
i think its okay for a review @nikspz

**Review by nikspz — APPROVED** [review]
Test performed:
- Connecting an Wallet/ pkey: OK
- Pulling the balance: OK
- Market availability during the strategy creation: OK
- Compatibility with the available strategies: OK
- status, order_book and status --live updates: OK
- Order submission and cancellation: OK
- Fast, Long refresh rate: OK
- Data integrity: OK
- Filled event: OK
Note: review low liquidity on WETH-USDC so used manual orders to fill Client limit orders

**Comment by isreallee82** [comment]
Alright sure

**Comment by isreallee82** [comment]
@david-hummingbot https://github.com/hummingbot/hummingbot-site/pull/409

**Review by cardosofede — APPROVED** [review]
great work @isreallee82 since hte connector was not so standard!

**Pull request merged**
