### PR TITLE
Feat/ftx perpetual

### PR DESCRIPTION
**Pull request by cardosofede**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Implementation of the FTX Perpetual Connector based on the CEX Connector Revamp initiative.
Important: FTX uses as collateral the value in USD of all the tokens so the value of the balance is the total collateral  of the account.

**Tests performed by the developer**:

- Connect API Keys
- Show balance
- Run Perpetual Market Making Strategy
- Compare OrderBook --live with Exchange UI
- Execute orders

**Tips for QA testing**:
Normal QA test for Perpetuals connectors.

### CODE REVIEW

**Comment by nikspz** [comment]
Not sure is that expected that ftx_perpetual not showing correct USD balance here? (total instead of USD):

Steps:
1. connect API keys
2. check balance
3. start the strategy and check status
4. pay attention to USD balance in the bot, compare to exchange


image

image
image
image

**Comment by cardosofede** [comment]
Exactly! In the description I mentioned that the FTX Perpetual uses all the collateral available. @nikspz

**Comment by nikspz** [comment]
Test performed:

- Cloned and compiled feature branch
- Started bot and created password
- Connected Ftx API Keys and checked balance
- Created Perpetual_mm
- Integrity synced with exchange
- Multiple orders working as expected
- Position retrieval working as expected
- History/-verbose, CSV data logs match exchange filled positions
- Tested on Source AWS



@cardosofede there's no info on funding payment in the bot after hour passes.
Ftx perpetual futures have [funding payments every hour.](https://help.ftx.com/hc/en-us/articles/360027946571-Funding)

Steps to reproduce:
1. Clone and install feature branch
2. Create/start perpetualMM strategy using FTX perpetual
3. On the start of the hour pay attention to the log pane

Actual:
no message logged about funding payment received or paid

Expected:
Funding payment should be logged if receiving or paying

image
image
image
image

**Review by nikspz — APPROVED** [review]
Test performed:

- Cloned and installed feature branch
- Started bot and created password
- Connected FTX API Keys and checked balance
- Created/Started Perpetual_mm and Spot_Perp_Arbitrage strategy
- Checked Status, status -live updating
- Data Integrity (ticker, status, order_book --live) synced with exchange
- Multiple order levels = OK
- Opened and Closed positions, filled orders = OK
- Position retrieval = OK
- History/-verbose, CSV data logs matched with exchange
- No issues during Overnight run
- Funding payment logged during Overnight run
- Tested on AWS Source and Docker

**Pull request closed without merging**
