### PR TITLE
Fix/avellaneda validation fix

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Fixes Avellaneda's validation of the execution time parameter when `execution_timeframe` is set to `infinite`. It also adds a typo-fix to the `setup.py` requirements list.

**Tests performed by the developer**:
Adds a test for the Avellaneda parameter validation.

**Tips for QA testing**:
Test summary:
- Create an Avellaneda MM strategy
- Set execution_timeframe to use infinite
- Start the strategy and confirmed no issue was encountered during the start process
- Confirmed that orders are canceled and created according to the order refresh time.
- Reconfigure execution_timeframe and set from_date_to_date / daily_between_times and restart the strategy.
- Reconfigure execution_timeframe again and return to infinite then restart the strategy and confirmed no issue using the parameter.

### CODE REVIEW

**Comment by phbrgnomo** [comment]
@petioptrv Tests failing. Please check it before the proposal is open for voting.

**Comment by petioptrv** [comment]
> @petioptrv Tests failing. Please check it before the proposal is open for voting.

@phbrgnomo, this is a sporadic failure of the pipeline. If you restart the pipeline, it will most likely pass. It failed three times before finally passing without any changes in the code on my tables formatting PR. From CoinAlpha, we have one [PR](https://github.com/hummingbot/hummingbot/pull/5090) already submitted that will address part of the the issue, and we have another task lined up that will fix the remainder of the issue.

**Review by Nullably — APPROVED** [review]

**Comment by petioptrv** [comment]
@RobHBOT failure is not due to this PR. The revert ends up outputting the same error. Will try to pin-point what happened

**Comment by petioptrv** [comment]
After investigation, this is the error that Abel brought up this morning. It was actually introduced by two of my previous PRs that were merged some time apart (the PnL fix for the history command and the table formatting PR)

**Pull request merged**
