### PR TITLE
(fix) update bybit perp balance fetching

### PR DESCRIPTION
**Pull request by tomasgaudino**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Fix https://github.com/hummingbot/hummingbot/issues/7267, due to bybit permamently deletetion of contract account type, which was on balance update endpoint

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by nikspz** [comment]
2f4263a
- Test performed:
    - Cloned and installed PR 7279
    - connected bybit_perpetual successfully
    - checked balance successfully
    - created/started perpetualMM strategy successfully, review orders placed on exchange with same amount / price
    - created/ started macd_bb v2 strategy using bybit_perpetual, successfully ran for ~17 hours
        - successfully closed with time_limit, take profit orders - ok
    Pending:
    - ongoing run Bollinger V1 strategy using bybit_perpetual

**Comment by nikspz** [comment]
Could you please try to fix tests issue / add coverage when you have time 🙏 ? @tomasgaudino 
https://github.com/hummingbot/hummingbot/actions/runs/11666669542/job/32519291239

**Review by nikspz — APPROVED** [review]
2f4263a
- Test performed:
    - Cloned and installed PR 7279
    - connected bybit_perpetual successfully
    - checked balance successfully
    - created/started perpetualMM strategy successfully, review orders placed on exchange with same amount / price
    - created/ started macd_bb v2 strategy using bybit_perpetual, successfully ran for ~17 hours
        - successfully closed with time_limit, take profit orders - ok
    - ran Bollinger V1 strategy using bybit_perpetual - ok

**Review by cardosofede — APPROVED** [review]
LGTM!

**Pull request merged**
