### PR TITLE
Fix balance fetch for Injective Spot connector

### PR DESCRIPTION
**Pull request by keithbaum**
Change consists of utilizing the latest pyinjective-sdk method for fetching the portfolio balance described in guide
https://www.notion.so/injective/The-new-trading-logic-to-be-introduced-in-v1-10-8b422f7bec6c4cac96459d558e917b6d?pvs=4

This includes treating bank and sub account balances separately with their own stream for update events and method get_account_portfolio for both bank and subaccount balances.

For testing the following code, please include gateway code from this PR https://github.com/hummingbot/gateway/pull/67

This fix addresses issue reported in gateway repo https://github.com/hummingbot/gateway/issues/70

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update:
- Successfully setup this PR and gateway [development](https://github.com/hummingbot/gateway/tree/development) branch
- Successfully setup wallet 
- Balance command now displays wallet assets 
- Data matched between client and exchange portfolio

We setup a simple PMM strategy just to test since we had not able to due to wallet issue and found some so we created a ticket https://github.com/hummingbot/gateway/issues/73

**Review by rapcmia — DISMISSED** [review]
LGTM

**Comment by rapcmia** [comment]
Hi @keithbaum we tried to rerun but it seems its stuck on `stable tests and calculate coverages` for 38mins now and taking longer that usual.. please advise if this is expected or would need fix. Thank you

image

**Comment by keithbaum** [comment]
Hi @rapcmia this is because some tests need to be modified to include new balance streams mock.
Will work on this today

**Review by rapcmia — APPROVED** [review]

**Comment by rapcmia** [comment]
Hey @keithbaum no worries and thanks for the update 🙇

**Pull request merged**
