### PR TITLE
feat/ Integrate fixed_rate_conversion into amm_arb strategy

### PR DESCRIPTION
**Pull request by srirambandi**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This is a PR(Draft) to solve #6209. Integrate fixed_rate_conversion into `amm_arb` strategy

**Tests performed by the developer**:

NA

**Tips for QA testing**:

NA

### CODE REVIEW

**Review by fengtality — CHANGES_REQUESTED** [review]
Looks good overall!

I think you can simplify this by having 2 params:
- `rate_oracle_enabled`: bool, default False
- `fixed_conversion_rate`: float, default 1

You can make the first question "Do you want to use the rate oracle?" and the 2nd question works well.

I believe these changes would result in a better user experience.

**Comment by srirambandi** [comment]
Got it! Will push with new changes. Thanks for the quick review!

**Review by fengtality — CHANGES_REQUESTED** [review]
These changes looks good to me.

I also think we should handle the case where the user need to convert the base tokens. If the user is converting base tokens, 

Therefore, please revise the logic to:

1. If either base-base or quote-quote symbols are different
2. For each one, if there is a difference, ask user if they want to use rate oracle to handle each conversion (default = No)
3. If user confirms No, then ask user to define fixed rate

I believe this allow the strategy to handle both base and quote conversions.

In addition, please add unit tests to check that this works correctly under different conditions, such as:
1. base tokens are different, conversion rate is fixed
2. quote tokens are different, conversion rate is fixed
etc

**Comment by rapcmia** [comment]
> These changes looks good to me.
> 
> I also think we should handle the case where the user need to convert the base tokens. If the user is converting base tokens,
> 
> Therefore, please revise the logic to:
> 
> 1. If either base-base or quote-quote symbols are different
> 2. For each one, if there is a difference, ask user if they want to use rate oracle to handle each conversion (default = No)
> 3. If user confirms No, then ask user to define fixed rate
> 
> I believe this allow the strategy to handle both base and quote conversions.
> 
> In addition, please add unit tests to check that this works correctly under different conditions, such as:
> 
> 1. base tokens are different, conversion rate is fixed
> 2. quote tokens are different, conversion rate is fixed
>    etc

Hi @srirambandi good day to you
Can you please update base on requested changes so we can have a look? thank you

**Comment by nikspz** [comment]
Closing this PR since there're no response from the developer after a week

**Pull request closed without merging**
