### PR TITLE
Fix/ci

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This pr fixes broken workflow for both client and gateway.

### CODE REVIEW

**Review by aarmoa — APPROVED** [review]
The changes look good to me.

-- Reviewed in representation of Hummingbot Foundation Technical DAO

**Review by JeremyKono — APPROVED** [review]

**Comment by rapcmia** [comment]
When checking the guide for [gateway unit testing](https://github.com/CoinAlpha/hummingbot/blob/fix/ci/gateway/docs/testing.md), when running `yarn jest test/app.test.ts` we are getting this error:

image

Test completed and marked `passed` on the following: 
- Generate certs, create manual docker image: ok 
- Setup env variable: ok 
- Test curl
	- test walet endpoint
	- test add wallet endpoint
	- test check price endpoint
- Build docker image of gateway-v2
- yarn jest chain/ethereum/ethereum/*.ts: 
- yarn jest chain/ethereum/avalanche/*.ts
- yarn jest test/services/*.ts
- yarn jest test/amm/*.ts
- yarn jest test/connectors/*.ts
- yarn jest test/network/*.ts
- yarn jest test/postman/*.ts

**Comment by aarmoa** [comment]
@vic-en please check @rapcmia comment to verify if documentation is out of date or there is an error we need to fix

**Comment by vic-en** [comment]
image

@rapcmia I don't have any issue with that test on my end.
You don't even need to update any conf file for that test to pass like you can see in my screenshot

**Comment by aarmoa** [comment]
@rapcmia In any case you can see the evidence that the validation workflow is running without errors in this same PR. No need to run anything on other environments.

**Review by rapcmia — APPROVED** [review]
Test performed:
- Generate certs, create manual docker image all ok 
- Tested on source / docker build
- Setup env variable and test curl commands: Wallet, add wallet and check price 
- Run test suites available on /gateway/test folder: amm, chains, connectors, etc.. all ok

**Pull request merged**
