### PR TITLE
Remove legacy Solana/CLOB connector code

### PR DESCRIPTION
**Pull request by fengtality**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

- Removes the legacy `clob` Gateway connector, since we now have `clob_spot` and `clob_perp`
- Removes code related to Solana and Serum DEX
- Removes related tests

**Tests performed by the developer**:
- All tests pass, except for ones related to Injective library

**Tips for QA testing**:

### CODE REVIEW

**Review by cardosofede — APPROVED** [review]
LGTM!

**Comment by cardosofede** [comment]
@fengtality test are failing I think that there is an error with one import.

**Review by cardosofede — CHANGES_REQUESTED** [review]
Some test are failing

**Review by nikspz — APPROVED** [review]
Tests performed:
- Cloned and installed feat branch and gateway development
- Review removed files
- Connected dexalot/injective to gateway
- Created/run pureMM using dexalot/injective, review order created on the dexalot exchange

**Review by cardosofede — APPROVED** [review]
LGTM!

**Pull request merged**
