### PR TITLE
Fix/TWAP status order order, order spread

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

- fixes order of orders in status. Before orders were displayed without any ordering and it happened that order furthest from the mid price was on position 0, and an order on level 0 was on the last position. It was confusing. Now orders are displayed based on their distance from the mid price, with orders at level 0 being on position 0.

- fixes order spread in status. Order spread wasn't calculated at all, and mid price wasn't taken into account at all, the displayed spread was always 0.

**Tests performed by the developer**:

- ran strategy with binance paper
- ran unit test

### CODE REVIEW

**Comment by dennisocana** [comment]
Proposal created: https://snapshot.org/#/hbot-prp.eth/proposal/0x4c53bce197963231b44ca59320012d73b6c536e3c1f473e6ec2edb77398934f0

**Comment by JeremyKono** [comment]
Hi, @mhrvth. Please resolve conflicts in this PR. Thanks!

**Comment by nikspz** [comment]
Win Source Gitbash:
    - Blocked with https://github.com/hummingbot/hummingbot/issues/5162 on development
Ubuntu Source:
    - Check status = OK
    - Check spread if updating = OK
    - Check order arrangement = OK
    - Set up start_datetime = OK
    - Set up end_datetime - Failed (replicated on development branch)
Win Docker:
    - Check status = OK
    - Check spread if updating = OK
    - Check order arrangement = OK
    - Set up start_datetime = OK
    - Set up end_datetime - Failed (replicated on development branch)

**Review by rapcmia — APPROVED** [review]
Test performed:
- Setup simple TWAP strategy
- No errors on start of the strategy
- Status shows active orders in correct arrangement and match the exchange orders
- `Status --live` shows changes on spread

**Pull request merged**
