### PR TITLE
Solves Binance rate limits, frequent almost reached, missing limit maker orders

### PR DESCRIPTION
**Pull request by abduramann**
**Solution to Binance rate limit for ORDERS endpoint**
https://github.com/hummingbot/hummingbot/issues/5473 
https://github.com/hummingbot/hummingbot/issues/5491 

**Solution to missing LIMIT MAKER orders in Binance** 
https://github.com/hummingbot/hummingbot/issues/5502
https://github.com/hummingbot/hummingbot/issues/5503 
New value of ORDER_NOT_FOUND_COUNT_LIMIT may be reverted. It was just easy workaround. Github does not allow cherry picking in UI.

**Solution to frequent "API rate limit has almost reached" message**
https://github.com/hummingbot/hummingbot/issues/5505

### CODE REVIEW

**Comment by cardosofede** [comment]
@abduramann please follow the [contribution guidelines](https://hummingbot.org/developers/contributions/) you are pointing your PR to the master branch.

**Comment by abduramann** [comment]
Thanks for pointing out. I have a question. "7. Create a pull request proposal in Snapshot" has confused me a little. Does each PR require a voting?

**Comment by JeremyKono** [comment]
Hi @abduramann, yes PRs require voting before they are added in the codebase.

**Comment by rapcmia** [comment]
Closing ticket, most of the issues found have been fix since version 1.8.0

**Pull request closed without merging**
