### PR TITLE
fix/ kucoin perpetual incorrect pozition size for market order

### PR DESCRIPTION
**Pull request by yancong001**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Review by cardosofede — APPROVED** [review]
LGTM!

**Comment by cardosofede** [comment]
@yancong001 check that the isort is complaining for use type(something) == str instead of isinstance(something, str)

**Comment by nikspz** [comment]
Currently tested with this script
[kucoin_perp_3.py.txt](https://github.com/hummingbot/hummingbot/files/12699425/kucoin_perp_3.py.txt)
 got flooded with Could not fetch last fee payment for BCH-USD. Check network connection. and 
hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for BCH-USD.

same thing using same script on latest development 1.20.0 (PerpetualMM on development works however)

pending script from the user

image

```
2023-09-22 09:08:32,649 - 410480 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2023-09-22 09:08:32,909 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2023-09-22 09:08:33,001 - 410480 - hummingbot.strategy.script_strategy_base - WARNING - kucoin_perpetual is not ready. Please wait...
2023-09-22 09:08:34,001 - 410480 - hummingbot.strategy.script_strategy_base - WARNING - kucoin_perpetual is not ready. Please wait...
2023-09-22 09:08:34,726 - 410480 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'BCH-USD'
Traceback (most recent call last):
  File "/home/nikita/kucperpfix/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/nikita/kucperpfix/hummingbot/core/data_type/order_book_tracker.py", line 180, in _init_order_books
    self._order_books[trading_pair] = await self._initial_order_book_for_trading_pair(trading_pair)
  File "/home/nikita/kucperpfix/hummingbot/core/data_type/order_book_tracker.py", line 173, in _initial_order_book_for_trading_pair
    return await self._data_source.get_new_order_book(trading_pair)
  File "/home/nikita/kucperpfix/hummingbot/core/data_type/order_book_tracker_data_source.py", line 65, in get_new_order_book
    snapshot_msg: OrderBookMessage = await self._order_book_snapshot(trading_pair=trading_pair)
  File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_order_book_data_source.py", line 205, in _order_book_snapshot
    exchange_symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair),
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
    return self._fwdm[key]
KeyError: 'BCH-USD'
2023-09-22 09:08:34,729 - 410480 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'BCH-USD'
Traceback (most recent call last):
  File "/home/nikita/kucperpfix/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/nikita/kucperpfix/hummingbot/connector/perpetual_derivative_py_base.py", line 364, in _listen_for_funding_info
    await self._init_funding_info()
  File "/home/nikita/kucperpfix/hummingbot/connector/perpetual_derivative_py_base.py", line 371, in _init_funding_info
    funding_info = await self._orderbook_ds.get_funding_info(trading_pair)
  File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_order_book_data_source.py", line 43, in get_funding_info
    funding_info_response = await self._request_complete_funding_info(trading_pair)
  File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_order_book_data_source.py", line 192, in _request_complete_funding_info
    exchange_symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair),
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
    return self._fwdm[key]
KeyError: 'BCH-USD'
2023-09-22 09:08:34,731 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for BCH-USD.
Traceback (most recent call last):
  File "/home/nikita/kucperpfix/hummingbot/connector/perpetual_derivative_py_base.py", line 414, in _update_funding_payment
    timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 885, in _fetch_last_fee_payment
    exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
    return self._fwdm[key]
KeyError: 'BCH-USD'
2023-09-22 09:08:34,732 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - WARNING - Could not fetch last fee payment for BCH-USD. Check network connection.
2023-09-22 09:08:34,872 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_api_order_book_data_source.KucoinPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_order_book_data_source.py", line 59, in _subscribe_channels
    symbols = ",".join([await self._connector.exchange_symbol_associated_to_pair(trading_pair=pair)
  File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_order_book_data_source.py", line 59, in <listcomp>
    symbols = ",".join([await self._connector.exchange_symbol_associated_to_pair(trading_pair=pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
    return self._fwdm[key]
KeyError: 'BCH-USD'
2023-09-22 09:08:34,873 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_api_order_book_data_source.KucoinPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/nikita/kucperpfix/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_order_book_data_source.py", line 59, in _subscribe_channels
    symbols = ",".join([await self._connector.exchange_symbol_associated_to_pair(trading_pair=pair)
  File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_order_book_data_source.py", line 59, in <listcomp>
    symbols = ",".join([await self._connector.exchange_symbol_associated_to_pair(trading_pair=pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
    return self._fwdm[key]
KeyError: 'BCH-USD'
2023-09-22 09:08:34,939 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_api_user_stream_data_source.KucoinPerpetualAPIUserStreamDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams wss://stream.kucoin.com/realtime_private...
Traceback (most recent call last):
  File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_user_stream_data_source.py", line 120, in _subscribe_to_channels
    symbols = [
  File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_user_stream_data_source.py", line 121, in <listcomp>
    await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
    return self._fwdm[key]
KeyError: 'BCH-USD'
2023-09-22 09:08:34,939 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_api_user_stream_data_source.KucoinPerpetualAPIUserStreamDataSource - ERROR - Unexpected error while listening to user stream wss://stream.kucoin.com/realtime_private. Retrying after 5 seconds...
Traceback (most recent call last):
  File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_user_stream_data_source.py", line 86, in _listen_for_user_stream_on_url
    await self._subscribe_to_channels(ws, url, self._trading_pairs)
  File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_user_stream_data_source.py", line 120, in _subscribe_to_channels
    symbols = [
  File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_user_stream_data_source.py", line 121, in <listcomp>
    await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
    return self._fwdm[key]
KeyError: 'BCH-USD'
2023-09-22 09:08:35,030 - 410480 - hummingbot.strategy.script_strategy_base - WARNING - kucoin_perpetual is not ready. Please wait...
2023-09-22 09:08:35,033 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for BCH-USD.
Traceback (most recent call last):
  File "/home/nikita/kucperpfix/hummingbot/connector/perpetual_derivative_py_base.py", line 414, in _update_funding_payment
    timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 885, in _fetch_last_fee_payment
    exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
    return self._fwdm[key]
KeyError: 'BCH-USD'
2023-09-22 09:08:35,034 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - WARNING - Could not fetch last fee payment for BCH-USD. Check network connection.
2023-09-22 09:08:35,034 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for BCH-USD.
Traceback (most recent call last):
  File "/home/nikita/kucperpfix/hummingbot/connector/perpetual_derivative_py_base.py", line 414, in _update_funding_payment
    timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 885, in _fetch_last_fee_payment
    exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
    return self._fwdm[key]
KeyError: 'BCH-USD'
2023-09-22 09:08:35,035 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - WARNING - Could not fetch last fee payment for BCH-USD. Check network connection.

```

**Comment by yancong001** [comment]
> Currently tested with this script [kucoin_perp_3.py.txt](https://github.com/hummingbot/hummingbot/files/12699425/kucoin_perp_3.py.txt) got flooded with Could not fetch last fee payment for BCH-USD. Check network connection. and hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for BCH-USD.
> 
> same thing using same script on latest development 1.20.0 (PerpetualMM on development works however)
> 
> pending script from the user
> 
> image
> 
> ```
> 2023-09-22 09:08:32,649 - 410480 - hummingbot.client.hummingbot_application - INFO - start command initiated.
> 2023-09-22 09:08:32,909 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
> 2023-09-22 09:08:33,001 - 410480 - hummingbot.strategy.script_strategy_base - WARNING - kucoin_perpetual is not ready. Please wait...
> 2023-09-22 09:08:34,001 - 410480 - hummingbot.strategy.script_strategy_base - WARNING - kucoin_perpetual is not ready. Please wait...
> 2023-09-22 09:08:34,726 - 410480 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'BCH-USD'
> Traceback (most recent call last):
>   File "/home/nikita/kucperpfix/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
>     return await c
>   File "/home/nikita/kucperpfix/hummingbot/core/data_type/order_book_tracker.py", line 180, in _init_order_books
>     self._order_books[trading_pair] = await self._initial_order_book_for_trading_pair(trading_pair)
>   File "/home/nikita/kucperpfix/hummingbot/core/data_type/order_book_tracker.py", line 173, in _initial_order_book_for_trading_pair
>     return await self._data_source.get_new_order_book(trading_pair)
>   File "/home/nikita/kucperpfix/hummingbot/core/data_type/order_book_tracker_data_source.py", line 65, in get_new_order_book
>     snapshot_msg: OrderBookMessage = await self._order_book_snapshot(trading_pair=trading_pair)
>   File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_order_book_data_source.py", line 205, in _order_book_snapshot
>     exchange_symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair),
>   File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
>     return symbol_map.inverse[trading_pair]
>   File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
>     return self._fwdm[key]
> KeyError: 'BCH-USD'
> 2023-09-22 09:08:34,729 - 410480 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'BCH-USD'
> Traceback (most recent call last):
>   File "/home/nikita/kucperpfix/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
>     return await c
>   File "/home/nikita/kucperpfix/hummingbot/connector/perpetual_derivative_py_base.py", line 364, in _listen_for_funding_info
>     await self._init_funding_info()
>   File "/home/nikita/kucperpfix/hummingbot/connector/perpetual_derivative_py_base.py", line 371, in _init_funding_info
>     funding_info = await self._orderbook_ds.get_funding_info(trading_pair)
>   File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_order_book_data_source.py", line 43, in get_funding_info
>     funding_info_response = await self._request_complete_funding_info(trading_pair)
>   File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_order_book_data_source.py", line 192, in _request_complete_funding_info
>     exchange_symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair),
>   File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
>     return symbol_map.inverse[trading_pair]
>   File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
>     return self._fwdm[key]
> KeyError: 'BCH-USD'
> 2023-09-22 09:08:34,731 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for BCH-USD.
> Traceback (most recent call last):
>   File "/home/nikita/kucperpfix/hummingbot/connector/perpetual_derivative_py_base.py", line 414, in _update_funding_payment
>     timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
>   File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 885, in _fetch_last_fee_payment
>     exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
>   File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
>     return symbol_map.inverse[trading_pair]
>   File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
>     return self._fwdm[key]
> KeyError: 'BCH-USD'
> 2023-09-22 09:08:34,732 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - WARNING - Could not fetch last fee payment for BCH-USD. Check network connection.
> 2023-09-22 09:08:34,872 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_api_order_book_data_source.KucoinPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
> Traceback (most recent call last):
>   File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_order_book_data_source.py", line 59, in _subscribe_channels
>     symbols = ",".join([await self._connector.exchange_symbol_associated_to_pair(trading_pair=pair)
>   File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_order_book_data_source.py", line 59, in <listcomp>
>     symbols = ",".join([await self._connector.exchange_symbol_associated_to_pair(trading_pair=pair)
>   File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
>     return symbol_map.inverse[trading_pair]
>   File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
>     return self._fwdm[key]
> KeyError: 'BCH-USD'
> 2023-09-22 09:08:34,873 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_api_order_book_data_source.KucoinPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
> Traceback (most recent call last):
>   File "/home/nikita/kucperpfix/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
>     await self._subscribe_channels(ws)
>   File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_order_book_data_source.py", line 59, in _subscribe_channels
>     symbols = ",".join([await self._connector.exchange_symbol_associated_to_pair(trading_pair=pair)
>   File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_order_book_data_source.py", line 59, in <listcomp>
>     symbols = ",".join([await self._connector.exchange_symbol_associated_to_pair(trading_pair=pair)
>   File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
>     return symbol_map.inverse[trading_pair]
>   File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
>     return self._fwdm[key]
> KeyError: 'BCH-USD'
> 2023-09-22 09:08:34,939 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_api_user_stream_data_source.KucoinPerpetualAPIUserStreamDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams wss://stream.kucoin.com/realtime_private...
> Traceback (most recent call last):
>   File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_user_stream_data_source.py", line 120, in _subscribe_to_channels
>     symbols = [
>   File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_user_stream_data_source.py", line 121, in <listcomp>
>     await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
>   File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
>     return symbol_map.inverse[trading_pair]
>   File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
>     return self._fwdm[key]
> KeyError: 'BCH-USD'
> 2023-09-22 09:08:34,939 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_api_user_stream_data_source.KucoinPerpetualAPIUserStreamDataSource - ERROR - Unexpected error while listening to user stream wss://stream.kucoin.com/realtime_private. Retrying after 5 seconds...
> Traceback (most recent call last):
>   File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_user_stream_data_source.py", line 86, in _listen_for_user_stream_on_url
>     await self._subscribe_to_channels(ws, url, self._trading_pairs)
>   File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_user_stream_data_source.py", line 120, in _subscribe_to_channels
>     symbols = [
>   File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_api_user_stream_data_source.py", line 121, in <listcomp>
>     await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
>   File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
>     return symbol_map.inverse[trading_pair]
>   File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
>     return self._fwdm[key]
> KeyError: 'BCH-USD'
> 2023-09-22 09:08:35,030 - 410480 - hummingbot.strategy.script_strategy_base - WARNING - kucoin_perpetual is not ready. Please wait...
> 2023-09-22 09:08:35,033 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for BCH-USD.
> Traceback (most recent call last):
>   File "/home/nikita/kucperpfix/hummingbot/connector/perpetual_derivative_py_base.py", line 414, in _update_funding_payment
>     timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
>   File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 885, in _fetch_last_fee_payment
>     exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
>   File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
>     return symbol_map.inverse[trading_pair]
>   File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
>     return self._fwdm[key]
> KeyError: 'BCH-USD'
> 2023-09-22 09:08:35,034 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - WARNING - Could not fetch last fee payment for BCH-USD. Check network connection.
> 2023-09-22 09:08:35,034 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - NETWORK - Unexpected error while fetching last fee payment for BCH-USD.
> Traceback (most recent call last):
>   File "/home/nikita/kucperpfix/hummingbot/connector/perpetual_derivative_py_base.py", line 414, in _update_funding_payment
>     timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
>   File "/home/nikita/kucperpfix/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 885, in _fetch_last_fee_payment
>     exchange_symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
>   File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
>     return symbol_map.inverse[trading_pair]
>   File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
>     return self._fwdm[key]
> KeyError: 'BCH-USD'
> 2023-09-22 09:08:35,035 - 410480 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - WARNING - Could not fetch last fee payment for BCH-USD. Check network connection.
> ```

please test BCH-USDT  instead of BCH-USD

**Comment by yancong001** [comment]
> @yancong001 check that the isort is complaining for use type(something) == str instead of isinstance(something, str)

fixed

**Comment by nikspz** [comment]
@yancong001 Thanks, Ran successfully using BCH-USDT

[6578.zip](https://github.com/hummingbot/hummingbot/files/12700100/6578.zip)
[logs_kucoin_perp_3fixed.log](https://github.com/hummingbot/hummingbot/files/12700101/logs_kucoin_perp_3fixed.log)



however failed to reproduce issue on development using my script, will wait for updates from user.
image

**Comment by nikspz** [comment]
Could you check failing unit tests? @yancong001

**Comment by nikspz** [comment]
https://github.com/hummingbot/hummingbot/issues/6567#issuecomment-1731574085
Reproduced issue #6567 on development using perpetualMM strategy.

Currently can't reproduce using this PR, after orders OPENED bot placed correct amount, ongoing test

**Comment by yancong001** [comment]
i will fix unittest tomorrow

**Comment by yancong001** [comment]
fixed

**Review by nikspz — APPROVED** [review]
- Cloned and install fix branch
- Create perpetualMM using kucoin perpetual, BCH-USDT and order amount 0.05
- Review issue are not reproduced
- Manually built docker image successfully

**Pull request merged**
