### PR TITLE
Feat/bybit perpetual v5 upgrade

### PR DESCRIPTION
**Pull request by tomasgaudino**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Update all REST endpoints and WS channels to V5
- Implement perpetual inverse candles in respective candle feed

[WIP] Add tests

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by tomasgaudino** [comment]
@nikspz @rapcmia @cardosofede technically we can start testing new connector behaviour, however tests are pending. it won't pass through github workflow until i finish them

**Review by nikspz — APPROVED** [review]
- Cloned PR 
- Started the client Successfully
- Manually built docker image successfully
- Connected the bybit_perpetual connector API keys successfully
- Balance output: ok
- Create/Import/Start a strategy: ok
- Check status and status --live match with exchange: ok
- Order cancellation: ok
- Order filled events handling: ok
- Vertify fees recorded: ok
- start/run on perpetualMM using bybit_perpetual: ok
- longrun test on bollinger_v1 using bybit_perpetual with binance_perpetual candles: ok

**Comment by Chebaoshan** [comment]
hi sir@tomasgaudino Do you have any plan to submit pr about upgrading bybit spot api to v5 ?

**Comment by tomasgaudino** [comment]
hello there @Chebaoshan , perhaps i'm wrong but i think i saw something related here https://github.com/hummingbot/hummingbot/pull/7062

**Comment by nikspz** [comment]
> upgrading bybit spot api to v5 ?

Already available in the latest 2.0.1 Release

**Review by cardosofede — APPROVED** [review]
Great work Drupman !

**Comment by halink0803** [comment]
It seems merged changes is not available on latest release 2.0.1? when will the next release? If I want to use the bybit with the latest api v5, I have to build image from the code myself, right?

**Comment by nikspz** [comment]
hi @halink0803  you could clone development branch for (source) or development image there
https://hub.docker.com/r/hummingbot/hummingbot/tags

**Pull request merged**
