### PR TITLE
(fix) Coin Gecko rate oracle exceeds rate limit

### PR DESCRIPTION
**Pull request by MementoRC**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Resolves: https://github.com/hummingbot/hummingbot/issues/5806
The proposal is to re-architect the algorithm to gather the assets prices. Coin Gecko returns only 50 results when a category is provided (tested on their web API testbench). Additionally, categories have different sizes, they have different number of pages. The algorithm proposed:
   - Query all the categories in `gather`
   - Iterate only the categories that still have entries (which have not returned less than 50 entries)
   - Limit the number of iteration to 10 (currently all the categories return less than 10 pages)
   - The approximate number of entries with this setting is ~950

Additional features were added, like a detection of a rate limit breach (likely due to time sync) and cool-off
Reuse of the DataFeed Throttler (not sure why RateOracle is not simply a DataFeeder, it does seemingly the same thing)

**Tests performed by the developer**:
Live testing and observation of less rate limit warnings (actually none) - Note that this is only possible with the other PR: https://github.com/hummingbot/hummingbot/pull/5820
Ran the testsuite - Failed locally if the timeout is not increased to 300s - Did not use IsolatedAsyncioTestCase

**Tips for QA testing**:

### CODE REVIEW

**Review by nikspz — APPROVED** [review]
Tests performed:
 - Cloned and installed fix branch
 - Successfully manually created docker image
 - Set up coingecko as rate oracle source
 - Set up and ran Pure MM strategy
 - Set up and ran Avellaneda MM for any connector	
 - Set up and ran XEMM for any connector	
 - Set up and ran AMM strategy for uniswap using extra tokens on Coingecko
Stress and monitoring tests on strategies above:
 - Set up a hummingbot strategies successfully	
 - Reviewed no order failed events	
 - Reviewed no unhandled or unexpected errors	
 - Reviewed no stuck orders	
 - Checked orderbook integrity is okay	
 - Checked bot could handle hanging orders
 - Order executions're okay, no issues
Overnight monitoring: 
 - Set up a strategy that will run overnight	
 - Reviewed log files: Network reconnection	
 - Reviewed log files: Order failed submit	
 - Reviewed log files: Unexpected errors or Warnings	
 - Order executions're okay, no issues

 Tested on AWS Ubuntu Source and Docker

**Comment by cardosofede** [comment]
Hi @MementoRC seems like the big change is in #5820 and the changes of this PR are more related to the TTL on the method, do you think that this is the best approach?
The prices now will be updated in more than 1 minute.

**Comment by MementoRC** [comment]
@cardosofede Correct, https://github.com/hummingbot/hummingbot/pull/5820 should resolve a big part of the issue. This PR findings were actually made before realizing that the rate issue was in the throttler.
This PR, however, fixes fundamental issues with the logic in the code, the current code actually wastes requests by requesting empty data. The max data size per calls is 4 times smaller than what the current logic expects, so it may actually never get all the prices, even though it breaks the list per categories. The rate limit is so low that there should not be an expectation for speed, but rather completeness.
No ideas as to whether this is the `best` approach, I would simply agree that it may not solve an obvious issue that users would file a report for

**Comment by cardosofede** [comment]
@MementoRC what about to only use some of the categories due this restriction?

**Comment by MementoRC** [comment]
@rapcmia @cardosofede This is unexpected, this error from coingecko could get a user banned. I don't understand why it keeps sending requests to coingecko after the first fail, I thought I put a timeout, but maybe not at the correct place. THe error with coingecko seems bound to happen, I noticed it with a 5% margin and set a 10%, but yet you got it after one day!
@cardosofede The categories are needed, otherwise you'd get lots of tokens that are not relevant, coingecko has tons of tokens listed, we are using only some of the categories, or maybe I don't get what you mean

**Comment by cardosofede** [comment]
@MementoRC the thing is that:
- TTL is 30
- Categories are 6
- requests per category 3

Total request every 30 seconds == 18 --> 36 request/60 seconds

We should have a problem inside the class. Probably the best way will be start with an script and debug what is happening inside the rate oracle.

**Comment by MementoRC** [comment]
> 

That does not seem correct. TTL should be 72 and the request per categories is capped at 10, one of them being filled only after 9 requests.
It still seems that the primary issue is that coingecko may have time slippage, otherwise it is not an issue with that oracle, but the Throttler, which has a fair amount of various tests and was recently looked at

**Comment by cardosofede** [comment]
@MementoRC I was talking about the initial scenario

**Comment by MementoRC** [comment]
Oh, ok, the initial scenario should work then - I thought we were talking about this PR

**Comment by cardosofede** [comment]
@MementoRC yes, the thing is that probably something is broken because we should be sending less requests than the rate limit, or the rate limit is wrong.

**Comment by nikspz** [comment]
Reviewing this PR again since it's in priority issues.
Hey @MementoRC Coingecko decreased their free Rate limit per minute from 10-50 to 10-30.
Could you please check this PR again and do changes?
Check new Coingecko rate limits here: https://www.coingecko.com/en/api/pricing#general


Issue that I found: There's a delay checking extra_token (HBOT)
after that bot reached rate limit really fast (when checked rate --token HBOT for 2nd time)

Steps:
1. Clone and install feature branch
2. Start the instance 
3. change rate_oracle_source to coingecko
4. add `humminbot` to extra_tokens (https://www.coingecko.com/en/coins/hummingbot)
5. check rate --token HBOT
6. crosscheck with the development branch

Actual:
1. There's a delay checking rate --token HBOT using the PR5821
2. Bot not throwing any error/warning message when rate oracle limit is exceeded 

Expected:
No delay on checking extra token rate
Bot is throwing the warning message when rate oracle limit is exceeded

**Comment by MementoRC** [comment]
@nikspz I do not see the change in rates, the changelog does not indicate that change. This is what I see:
```
Our free API has a rate limit of 10-50 calls per minute, if you exceed that limit you will be blocked until the next 1 minute window. Do revise your queries to ensure that you do not exceed our limits should that happen.
```
By the way, what does 10-50 means? On their doc, I can't see a reference of rate for particular endpoints.

**Comment by MementoRC** [comment]
@nikspz @cardosofede I am working on the PR. There are a couple of things that need to be changed:
   - Filling the list of prices takes a long time: Users could resubmit queries ending up clogging the rate limit
   - Error handling from the exchange: With the gather, we end-up continuing to query after the first fail
   - The query strategy may need to be changed if the rate limit is really that stringent: Less queries with larger results
   - Query of a given token need to wait for the query round to complete before returning: Yes it can take that long (few mns)

I am active on it now, I should start making commits soon, but it will likely take a week or so

**Comment by MementoRC** [comment]
@nikspz @cardosofede The few things that I have changed so far:
   - Added a asyncio.Lock() to prevent resubmitting a get_prices() list of awaitables (that leads to funny things like querying the same set many times)
   - Added a asyncio.Event() to block the awaitables on the loop whenever the first exchange error occurs and wait for 1mn (cool-off from the doc)
   -

**Comment by MementoRC** [comment]
Updates: The logic has to be reverted to making queries that return 250 (max) entries. The outcome is that only tokens with market cap > ~500K can be retrieved. An example of `rate --token HBOT` that takes at least 3s to return:
```
2023-02-16 11:31:43,799 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO - Fetching extra tokens from CoinGecko: ['HBOT', 'HBOT-ETH', 'HBOT-BTC']
2023-02-16 11:31:43,799 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Cleared to call: ['HBOT', 'HBOT-ETH', 'HBOT-BTC']
2023-02-16 11:31:43,882 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO - Fetching price by page from CoinGecko, page 1, category None
2023-02-16 11:31:43,882 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Cleared to call price by page
2023-02-16 11:31:43,922 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Done with page 1:1
2023-02-16 11:31:43,922 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO - Fetching price by page from CoinGecko, page 2, category None
2023-02-16 11:31:43,922 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Cleared to call price by page
2023-02-16 11:31:43,975 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Done with page 2:1
2023-02-16 11:31:43,976 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO - Fetching price by page from CoinGecko, page 3, category None
2023-02-16 11:31:43,976 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Cleared to call price by page
2023-02-16 11:31:44,028 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Done with page 3:1
2023-02-16 11:31:44,028 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO - Fetching price by page from CoinGecko, page 4, category None
2023-02-16 11:31:44,029 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Cleared to call price by page
2023-02-16 11:31:44,077 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Done with page 4:1
2023-02-16 11:31:44,077 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO - Fetching price by page from CoinGecko, page 5, category None
2023-02-16 11:31:44,077 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Cleared to call price by page
2023-02-16 11:31:44,117 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Done with page 5:1
2023-02-16 11:31:44,117 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO - Fetching price by page from CoinGecko, page 6, category None
2023-02-16 11:31:44,117 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Cleared to call price by page
2023-02-16 11:31:44,288 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Done with page 6:1
2023-02-16 11:31:44,288 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO - Fetching price by page from CoinGecko, page 7, category None
2023-02-16 11:31:44,288 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Cleared to call price by page
2023-02-16 11:31:44,328 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Done with page 7:1
2023-02-16 11:31:44,329 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO - Fetching price by page from CoinGecko, page 8, category None
2023-02-16 11:31:44,329 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Cleared to call price by page
2023-02-16 11:31:44,374 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Done with page 8:1
2023-02-16 11:31:44,374 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO - Fetching price by page from CoinGecko, page 9, category None
2023-02-16 11:31:44,374 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Cleared to call price by page
2023-02-16 11:31:44,374 - 1255398 - hummingbot.core.api_throttler.async_request_context_base - INFO - API rate limit on coin_gecko_rest_rate_limit_id (10 calls per 60s) has almost reached. Limits used is 10 in the last 60 seconds
2023-02-16 11:32:15,900 - 1255398 - hummingbot.core.api_throttler.async_request_context_base - INFO - API rate limit on coin_gecko_rest_rate_limit_id (10 calls per 60s) has almost reached. Limits used is 10 in the last 60 seconds
2023-02-16 11:32:47,705 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Done with page 9:1
2023-02-16 11:32:47,705 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO - Fetching price by page from CoinGecko, page 10, category None
2023-02-16 11:32:47,706 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Cleared to call price by page
2023-02-16 11:32:47,855 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO -    Done with page 10:1
2023-02-16 11:32:47,855 - 1255398 - hummingbot.core.rate_oracle.sources.rate_source_base - INFO - Done fetching prices from CoinGecko for USD
```

**Comment by MementoRC** [comment]
This commit only shows the proposed changes, it addresses the concerns and bugs, but the tests have not yet been updated.

**Comment by nikspz** [comment]
hi @MementoRC upon checking latest commit delay on checking rate for --token increased to ~1 min and more

Test performed:
rate --token BTC - 1 min delay before rate showed
rate --token ETH- 1 min delay
rate --token HBOT nad TNDR - 1 min delay
balance command - 1 min delay before showing balance

**Comment by MementoRC** [comment]
@nikspz Thank you for looking into this so quickly.
The first time (or after every expiration of the cache) calling for any token will have to await the completion of the collection of all the tokens, this rate limit of 10calls/mn does not allow to gather all the tokens in the first call. We can change that with limiting the amount of data to ~2000 assets: Do we prefer to do that? In this case HBOT cannot be collected unless added to the extra tokens
Note that if someone also uses the coin_gecko as a data_feed, then all bets are off in the sense that the rate-limit will be unknown when a `rate` is called

The `balance` behavior is unexpected, I will take a look

There is possibly another remedy to the `rate` cli command, it could be de-coupled from the `get_price` and only rely upon the stored prices by the oracle, this way it will respond quickly but the data may be 1mn old

**Comment by MementoRC** [comment]
Darn it, I forgot to remove the IsolatedAsyncioTestCase, back to the drawing board

**Review by cardosofede — APPROVED** [review]
LGTM! but I don't think that the rate oracle with coin gecko source is useful since the price is cached every 1 minute

**Review by nikspz — APPROVED** [review]
Tests performed:
- Cloned and installed feature branch
- Changed rate oracle source to coin_gecko and successfully added extra_tokens needed
- Checked tokens rate successfully using rate --token TOKEN
- Checked balance on the connected exchange shows correcly
- Created/started/ran simple pureMM strategy: ok
- Created/started/ran amm_arb strategy using uniswap_ethereum_optimism, review bot successfully showed OETH rate, not throwing errors


I agreed with cardosofede on this one, with the current free set up coingecko reaches rate limit really fast on development branch. 
This PR looks better on using amm_arb on optimism, however currently it reaches rate limit after ~15 minutes of bot running. The behavior on development branch bot just reaches rate limit almost immediately. 

I'll create a separate issue of `reconnecting rate oracle after rate limit reached on coingecko`

**Comment by nikspz** [comment]
In behalf of Foundation team we merged this PR to development for the upcoming Hummingbot release

**Pull request merged**
