### PR TITLE
Feat/gateway balance commands

### PR DESCRIPTION
**Pull request by isreallee82**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This is a PR to solve https://github.com/hummingbot/hummingbot/issues/6395 . Add gateway balance command

Removal of display of DEX balances from balance command.
Addittion of a new gateway balance command that reports balances and allowances of connected wallets.
Reafctor of all the necessary function to make the command work, including util funcs like like df building funcs

**Tests performed by the developer**:
Added few exchanges tor the client
pangolin_avalanche_avalanche ✅
uniswarp_ethereum_mainet ✅
uniswap_ethereum_arbitrum_one ✅
uniswap_polygon_mainet ✅

**Tips for QA testing**:

### CODE REVIEW

**Comment by nikspz** [comment]
@isreallee82 
amm_arb strategy now not showing balances at start

image

Steps to reproduce:
1. Clone and install PR6629 and latest develoment gateway
2. gateway connect uniswap or other connector
3. create/start amm_arb using this connector

Actual:
Initial checks showing empty balances line

Expected: 
balances line report balance

**Comment by isreallee82** [comment]
ohh I see @nikspz will quickly debug to see what might be wrong

**Comment by isreallee82** [comment]
sorry did a real check haven't update the start command @nikspz will push that in few mins

**Comment by isreallee82** [comment]
That should be it @nikspz for all display for cex vs dex

**Review by rapcmia — DISMISSED** [review]
LGTM:
- Ran tests on local macOs
- Install from source with latest gateway development version 
- Connect multiple dex connector wallets
- Run `gateway balance`
  - new command is available on `gateway -h`
  - The more connectors added, increases time for the command to pull the balances 
- Disconnect from gateway and run gateway command, not possible 
- Disconnect from gateway then run balance, does not show any error
- Reconnected from gateway then run balance, no action from gateway logs
- Setup simple amm-arb strategy, start displays balances of the market selected
- Test adding `connector-tokens`, works and displays added tokens to balance
- Ran the same test on docker build, all ok

**Comment by nikspz** [comment]
https://hummingbot.org/client/history/
history command failed to show trade perfomance, There's the error: TypeError: GatewayCommand.all_balance() missing 1 required positional argument: 'exchange'

Steps:

1. Clone and install feature brach + latest gateway
2. Connected gw exchange 
3. Created/started amm_arb startegy using gw exchange
4. Get some trades
5. Check history

Actual:
There's the error: TypeError: GatewayCommand.all_balance() missing 1 required positional argument: 'exchange'
trades and assets and performance info failed to show


[logs_amm-arbitrum1.log](https://github.com/hummingbot/hummingbot/files/13278893/logs_amm-arbitrum1.log)

```
2023-11-07 10:35:56,509 - 3531077 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: GatewayCommand.all_balance() missing 1 required positional argument: 'exchange'
Traceback (most recent call last):
  File "/home/nikita/gwbalance6629/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/nikita/gwbalance6629/hummingbot/client/command/history_command.py", line 81, in history_report
    cur_balances = await asyncio.wait_for(self.get_current_balances(market), network_timeout)
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/home/nikita/gwbalance6629/hummingbot/client/command/history_command.py", line 108, in get_current_balances
    return GatewayCommand.all_balance(market)
TypeError: GatewayCommand.all_balance() missing 1 required positional argument: 'exchange'
```

history gwcommandallbalance missing argument

**Comment by isreallee82** [comment]
done @nikspz

**Review by fengtality — APPROVED** [review]

**Comment by fengtality** [comment]
LGTM

**Review by nikspz — APPROVED** [review]
Tests performed:
- Cloned and installed PR6629 and latest development gateway
- Review gateway status ONLINE
- Manually built docker image from PR6629 and latest gateway, used docker compose, review gateway is ONLINE
- connected dexalot_avalanche_avalanche, uniswap_ethereum_mainnet, uniswap_ethereum_polygon, uniswap_ethereum_arbitrum, pancakeswap_bsc_mainnet successfully ✅
- added all gateway connector-tokens to the connectors ✅
- reviewed correct balance showed for all of the connected chains and tokens ✅
- review gold and silver CEX balance not affected ✅
- amm_arb strategy created/started successfully ✅
- review order execution is okay on uniswap arbitrum ✅
- review history and history --verbose command now showing trades / assets / performance ✅

**Pull request merged**
