### PR TITLE
(fix) conf_fee_overrides erased at startup

### PR DESCRIPTION
**Pull request by MementoRC**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
When conf_fee_overrides_TEMPLATE.yml does not contain the same list of exchanges supported by hummingbot, load_yml_into_cm mechanic does not update the ConfigVar with the values from the user's conf_fee_overrides.yml and the save ends-up erasing the value set by the user in his file
The quick fix is to populate TEMPLATE with the correct list. The rest of the files are to add test methods

**Tests performed by the developer**:
Added tests to the suite. Verified that the conf_fee_overrides.yml no longer gets erased with default values but keep the modified values

**Tips for QA testing**:

### CODE REVIEW

**Comment by MementoRC** [comment]
Attempt to address reviewer's concerns of previous PR:
https://github.com/hummingbot/hummingbot/pull/5330

**Comment by MementoRC** [comment]
Possibly helping with this: https://github.com/hummingbot/hummingbot/issues/5210

**Review by nikspz — APPROVED** [review]
Test performed
 - Install feature branch - OK
 - Create a simple Pure market making strategy using the connector - OK
 - Used a connector with estimated fees - OK
 - Exit the client, open conf_fee_overrides.yml and set values - OK
 - Start the bot again and check the conf_fee_overrides.yml file - OK
 - Tested on Source - OK
 - Tested on Docker - OK

**Review by aarmoa — APPROVED** [review]
The code change adds the missing fee configuration keys for all connectors in the `conf_fee_overrides_TEMPLATE.yml`, as the description specifies.

-- Reviewed in representation of the Hummingbot Foundation Technical DAO

**Comment by aarmoa** [comment]
@MementoRC please add a link to the PRP in the PR

**Comment by MementoRC** [comment]
Linkt to PRP:
https://snapshot.org/#/hbot-prp.eth/proposal/0xd7f87c4cfbe00a804a1152fdf3699ca5a363bd58ff87ea2b18fa631a5bf13198

**Pull request merged**
