### PR TITLE
fix gateio market order wrong amount

### PR DESCRIPTION
**Pull request by yancong001**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Some users reported that there was a problem with the market order of gateio in discord, and the amount actually traded was inconsistent with the amount placed.
image
image
image
image

My solution: When calculating the amount parameter, use get_price_for_volume instead of BestAsk or BestBid price

image

**Tests performed by the developer**:
unittest

**Tips for QA testing**:
Modify the script to test the gateio exchange. Note that for a very illiquid symbol, such as XDC_USDT, the order_amount parameter needs to be set larger (beyond the first step of ask and bid). Observe whether the number of orders is consistent with the number of filled.
 ( https://gist.github.com/cardosofede/d928c52503ef0b945ae140971f8fbbf3 )

### CODE REVIEW

**Comment by nikspz** [comment]
Test performed:
- Used script on PR 6530, unable to perform first trade to BUY:

```
2023-08-21 13:05:58,010 - 666460 - hummingbot.connector.exchange.gate_io.gate_io_exchange.GateIoExchange - NETWORK - Error submitting buy MARKET order to Gate_io for 130.000 XDC-USDT NaN.
Traceback (most recent call last):
  File "/home/nikita/gate6530/hummingbot/connector/exchange_py_base.py", line 453, in _create_order
    exchange_order_id = await self._place_order_and_process_update(order=order, **kwargs,)
  File "/home/nikita/gate6530/hummingbot/connector/exchange_py_base.py", line 470, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/home/nikita/gate6530/hummingbot/connector/exchange/gate_io/gate_io_exchange.py", line 226, in _place_order
    "amount": f"{price * amount:f}",
TypeError: unsupported operand type(s) for *: 'hummingbot.core.data_type.order_book_query_result.ClientOrderBookQueryResult' and 'decimal.Decimal'
2023-08-21 13:05:58,011 - 666460 - hummingbot.connector.exchange.gate_io.gate_io_exchange.GateIoExchange - WARNING - Failed to submit BUY order to Gate_io. Check API key and network connection.
2023-08-21 13:05:58,020 - 666460 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1692623158.0, "order_id": "t-HBOTBXCUT6036e8a125fbbb4b042", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "gate_io"}
2023-08-21 13:05:58,020 - 666460 - hummingbot.connector.client_order_tracker - INFO - Order t-HBOTBXCUT6036e8a125fbbb4b042 has failed. Order Update: OrderUpdate(trading_pair='XDC-USDT', update_timestamp=1692623158.0, new_state=<OrderState.FAILED: 6>, client_order_id='t-HBOTBXCUT6036e8a125fbbb4b042', exchange_order_id=None, misc_updates=None)
```

[logs_market_orders_test_gate_i2.log](https://github.com/hummingbot/hummingbot/files/12397417/logs_market_orders_test_gate_i2.log)
[logs_market_orders_test_gate_io.log](https://github.com/hummingbot/hummingbot/files/12397419/logs_market_orders_test_gate_io.log)
[logs_market_orders_test_gate_io-eth.log](https://github.com/hummingbot/hummingbot/files/12397420/logs_market_orders_test_gate_io-eth.log)
[6530.zip](https://github.com/hummingbot/hummingbot/files/12397429/6530.zip)


- Crosschecked on `latest development` used market_orders_test_gate_i2 script successfully
got the issue on delay updating available balance (https://github.com/hummingbot/hummingbot/issues/6238) when got only USDT balance
However when `balance is sufficient for both, after that ran script, filled buy and sell successfully on latest development`
[logs_market_orders_test_gate_i2.log](https://github.com/hummingbot/hummingbot/files/12397878/logs_market_orders_test_gate_i2.log)


image

**Review by cardosofede — DISMISSED** [review]
LGTM!

**Comment by cardosofede** [comment]
@yancong001 seems like there is an import error in the workflow

**Comment by yancong001** [comment]
fixed

**Review by nikspz — APPROVED** [review]
Test performed:
- Cloned and install Fix branch
- Manually built docker image successfully
- Set up pureMM strategy was able to trade, got Filled orders for LIMIT_MAKER type
- Used MARKET order script for gate.io successfully BUY and SELL trades for XDC-USDT, ETH-USDT

image

**Review by cardosofede — APPROVED** [review]
LGTM

**Comment by nikspz** [comment]
The fix has been deployed on development branch and next
hummingbot version 1.20.0.

**Pull request merged**
