### PR TITLE
Fix/Setup order of the mocked API responses

### PR DESCRIPTION
**Pull request by Jbekker**
Changed the order of setting up the mocked responses, this is useful for connectors where _request_order_status and _all_trade_updates_for_order are using the same HTTP endpoint with only a different request body like for example https://www.bitstamp.net/api/#tag/Orders/operation/GetOrderStatus

Also fixed the few tests that started failing after this change, they were already wrong but my change exposed this.

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by cardosofede** [comment]
@Jbekker will review this late this week

**Comment by cardosofede** [comment]
hey @Jbekker I reviewed your changes but I think that the order shouldn't matter for exchange connector test, probably the changes for HTX and BTC markets are necessary.
Did you debugged the code and found discrepancy on the results given by the mock api?

this is one of the implementations for the configuration of the mock api:
image

and this is the code that we are testing:
image

when you configure the mock api, should return the response only if the specific URL is requested, and if you configure the api for trade fills and orders before you run that the update orders, when the orders url is requested the orders response should be returned and if the trades url is requested the response of trades should arrive.

Let me know if my explanation was clear and if you found that when debugging the order is altered

**Comment by Jbekker** [comment]
@cardosofede , I agree that it normally shouldn't matter as long as the URL is different but for Bitstamp I'm using the same endpoint for both. So what ends of happening is that the _all_trade_updates_for_order is getting the response without the transactions.

```python
    async def _all_trade_updates_for_order(self, order: InFlightOrder) -> List[TradeUpdate]:
        all_fills_response = await self._api_post(
            path_url=CONSTANTS.ORDER_STATUS_URL,
            data={
                "client_order_id": order.client_order_id,
                "omit_transactions": "false",
            },
            is_auth_required=True
        )
```

and this for the order status:
```python
    async def _request_order_status(self, tracked_order: InFlightOrder) -> OrderUpdate:
        updated_order_data = await self._api_post(
            path_url=CONSTANTS.ORDER_STATUS_URL,
            data={
                "client_order_id": tracked_order.client_order_id,
                "omit_transactions": "true"
            },
            is_auth_required = True
        )
```

**Review by cardosofede — APPROVED** [review]
Based on your last comment, this change makes sense if the same endpoint is used since first is queried the trade fills and then the orders. Good work!

**Comment by cardosofede** [comment]
@rapcmia @nikspz to test this solution, checkout to this PR, deactivate the internet and run the unittest for all the connectors

**Comment by Jbekker** [comment]
I see one failing test that I missed, let me debug this first.

**Comment by Jbekker** [comment]
> I see one failing test that I missed, let me debug this first.

That one is fixed as well

**Comment by nikspz** [comment]
> @rapcmia @nikspz to test this solution, checkout to this PR, deactivate the internet and run the unittest for all the connectors

make test (offline) returns 4 errors:

[maketestoffine.log](https://github.com/user-attachments/files/16162774/maketestoffine.log)

```
ERROR: test_listening_process_logs_exception_during_events_subscription (test.hummingbot.connector.exchange.bitmart.test_bitmart_api_user_stream_data_source.BitmartAPIUserStreamDataSourceTests)

ERROR: test_listen_for_user_stream_iter_message_throws_exception (test.hummingbot.connector.derivative.bit_com_perpetual.test_bit_com_perpetual_user_stream_data_source.TestBitComPerpetualAPIUserStreamDataSource)


ERROR: test_update_order_status_marks_order_with_no_exchange_id_as_not_found (test.hummingbot.connector.exchange.kucoin.test_kucoin_exchange.KucoinExchangeTests)

ERROR: test_listen_for_subscriptions_logs_exception_details (test.hummingbot.data_feed.candles_feed.kucoin_spot_candles.test_kucoin_spot_candles.TestKucoinSpotCandles)

FAIL: test_market_became_wider (test.hummingbot.strategy.cross_exchange_market_making.test_cross_exchange_market_making_gateway.HedgedMarketMakingUnitTest)

```


image


make test (wifi on) - no errors

[maketestonline.log](https://github.com/user-attachments/files/16162791/maketestonline.log)
image

**Comment by Jbekker** [comment]
> > @rapcmia @nikspz to test this solution, checkout to this PR, deactivate the internet and run the unittest for all the connectors
> 
> [6c9835a](https://github.com/hummingbot/hummingbot/commit/6c9835ac817fb035b2210526dd1e1b1b6b2da1ce)
> 
> make test (offline) returns 4 errors:

@nikspz would it be possible to do the same test with the development branch? I doubt that these issues are related to my changes but I agree that they will need to be fixed.

**Comment by rapcmia** [comment]
- Ran tests locally on macOS M1
- Clone PR and run `make test` offline 3/3 all ok 
 image
- Compare with development branch and run same test offline 3/3 all ok

**Review by rapcmia — APPROVED** [review]

**Comment by rapcmia** [comment]
PR update:
- Ran tests on WSL Ubuntu22.04 LTS 
- Run same `make test` while offline on both this PR and development branch and compare 
- Both return same error:
  ```
  ERROR: test_listen_for_user_stream_iter_message_throws_exception (test.hummingbot.connector.derivative.bit_com_perpetual.test_bit_com_perpetual_user_stream_data_source.TestBitComPerpetualAPIUserStreamDataSource)
  ...
  ERROR: test_listening_process_logs_exception_during_events_subscription (test.hummingbot.connector.exchange.bitmart.test_bitmart_api_user_stream_data_source.BitmartAPIUserStreamDataSourceTests)
  ...
  ERROR: test_update_order_status_marks_order_with_no_exchange_id_as_not_found (test.hummingbot.connector.exchange.kucoin.test_kucoin_exchange.KucoinExchangeTests)
  ```
  - Copied from terminal:
    ```
    test_set_loggers_other_logger (test.test_logger_mixin_for_test.TestTestLoggerMixin) ... ok
    test_set_loggers_single_logger (test.test_logger_mixin_for_test.TestTestLoggerMixin) ... ok
    test_set_loggers_some_none (test.test_logger_mixin_for_test.TestTestLoggerMixin) ... ok
    test_wait_for_logged (test.test_logger_mixin_for_test.TestTestLoggerMixin) ... ok
    test_wait_for_logged_partial (test.test_logger_mixin_for_test.TestTestLoggerMixin) ... ok
    
    ======================================================================
    ERROR: test_listen_for_user_stream_iter_message_throws_exception (test.hummingbot.connector.derivative.bit_com_perpetual.test_bit_com_perpetual_user_stream_data_source.TestBitComPerpetualAPIUserStreamDataSource)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/unittest/mock.py", line 1379, in patched
        return func(*newargs, **newkeywargs)
      File "/home/rapcomia/github/hummingbot/7095/test/hummingbot/connector/derivative/bit_com_perpetual/test_bit_com_perpetual_user_stream_data_source.py", line 388, in test_listen_for_user_stream_iter_message_throws_exception
        self.async_run_with_timeout(self.data_source.listen_for_user_stream(msg_queue))
      File "/home/rapcomia/github/hummingbot/7095/test/hummingbot/connector/derivative/bit_com_perpetual/test_bit_com_perpetual_user_stream_data_source.py", line 87, in async_run_with_timeout
        ret = self.ev_loop.run_until_complete(asyncio.wait_for(coroutine, timeout))
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
        return future.result()
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
        raise exceptions.TimeoutError() from exc
    asyncio.exceptions.TimeoutError:
    -------------------- >> begin captured logging << --------------------
    asyncio: DEBUG: Get address info api.bit.com:443, type=<SocketKind.SOCK_STREAM: 1>, flags=<AddressInfo.AI_ADDRCONFIG: 32>
    --------------------- >> end captured logging << ---------------------
    
    ======================================================================
    ERROR: test_listening_process_logs_exception_during_events_subscription (test.hummingbot.connector.exchange.bitmart.test_bitmart_api_user_stream_data_source.BitmartAPIUserStreamDataSourceTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/core/data_type/user_stream_tracker_data_source.py", line 46, in listen_for_user_stream
        await self._subscribe_channels(websocket_assistant=self._ws_assistant)
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/connector/exchange/bitmart/bitmart_api_user_stream_data_source.py", line 64, in _subscribe_channels
        symbols = [await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/connector/exchange/bitmart/bitmart_api_user_stream_data_source.py", line 64, in <listcomp>
        symbols = [await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
      File "hummingbot/connector/exchange_base.pyx", line 96, in exchange_symbol_associated_to_pair
        symbol_map = await self.trading_pair_symbol_map()
      File "hummingbot/connector/exchange_base.pyx", line 65, in trading_pair_symbol_map
        async with self._mapping_initialization_lock:
      File "hummingbot/connector/exchange_base.pyx", line 67, in hummingbot.connector.exchange_base.ExchangeBase.trading_pair_symbol_map
        await self._initialize_trading_pair_symbol_map()
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/connector/exchange_py_base.py", line 1074, in _initialize_trading_pair_symbol_map
        exchange_info = await self._make_trading_pairs_request()
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/connector/exchange_py_base.py", line 1087, in _make_trading_pairs_request
        exchange_info = await self._api_get(path_url=self.trading_pairs_request_path)
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/connector/exchange_py_base.py", line 863, in _api_get
        return await self._api_request(*args, **kwargs)
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/connector/exchange_py_base.py", line 906, in _api_request
        request_result = await rest_assistant.execute_request(
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
        response = await self.execute_request_and_get_response(
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/core/web_assistant/rest_assistant.py", line 94, in execute_request_and_get_response
        response = await self.call(request=request, timeout=timeout)
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/core/web_assistant/rest_assistant.py", line 106, in call
        request = await self._pre_process_request(request)
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/core/web_assistant/rest_assistant.py", line 114, in _pre_process_request
        request = await pre_processor.pre_process(request)
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/connector/utils.py", line 106, in pre_process
        await self._synchronizer.update_server_time_if_not_initialized(time_provider=self._time_provider())
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/connector/time_synchronizer.py", line 84, in update_server_time_if_not_initialized
        await self.update_server_time_offset_with_time_provider(time_provider)
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/connector/time_synchronizer.py", line 65, in update_server_time_offset_with_time_provider
        server_time_ms: float = await time_provider
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/connector/exchange/bitmart/bitmart_web_utils.py", line 59, in get_current_server_time
        response = await rest_assistant.execute_request(
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
        response = await self.execute_request_and_get_response(
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/core/web_assistant/rest_assistant.py", line 94, in execute_request_and_get_response
        response = await self.call(request=request, timeout=timeout)
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/core/web_assistant/rest_assistant.py", line 108, in call
        resp = await wait_for(self._connection.call(request), timeout)
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
        return await fut
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/core/web_assistant/connections/rest_connection.py", line 10, in call
        aiohttp_resp = await self._client_session.request(
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/client.py", line 581, in _request
        conn = await self._connector.connect(
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
        proto = await self._create_connection(req, traces, timeout)
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 944, in _create_connection
        _, proto = await self._create_direct_connection(req, traces, timeout)
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 1203, in _create_direct_connection
        hosts = await self._resolve_host(host, port, traces=traces)
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
        return await asyncio.shield(resolved_host_task)
    asyncio.exceptions.CancelledError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
        return fut.result()
    asyncio.exceptions.CancelledError
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/unittest/mock.py", line 1379, in patched
        return func(*newargs, **newkeywargs)
      File "/home/rapcomia/github/hummingbot/7095/test/hummingbot/connector/exchange/bitmart/test_bitmart_api_user_stream_data_source.py", line 281, in test_listening_process_logs_exception_during_events_subscription
        self.async_run_with_timeout(self.listening_task, timeout=3)
      File "/home/rapcomia/github/hummingbot/7095/test/hummingbot/connector/exchange/bitmart/test_bitmart_api_user_stream_data_source.py", line 79, in async_run_with_timeout
        ret = self.ev_loop.run_until_complete(asyncio.wait_for(coroutine, timeout))
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
        return future.result()
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
        raise exceptions.TimeoutError() from exc
    asyncio.exceptions.TimeoutError
    
    ======================================================================
    ERROR: test_update_order_status_marks_order_with_no_exchange_id_as_not_found (test.hummingbot.connector.exchange.kucoin.test_kucoin_exchange.KucoinExchangeTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/connector/exchange_py_base.py", line 1016, in _update_order_status
        await self._update_orders_fills(orders=list(self._order_tracker.all_fillable_orders.values()))
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/connector/exchange/kucoin/kucoin_exchange.py", line 391, in _update_orders_fills
        all_trades_updates: List[TradeUpdate] = await self._all_trades_updates(orders)
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/connector/exchange/kucoin/kucoin_exchange.py", line 414, in _all_trades_updates
        all_fills_response = await self._api_get(
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/connector/exchange_py_base.py", line 863, in _api_get
        return await self._api_request(*args, **kwargs)
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/connector/exchange_py_base.py", line 906, in _api_request
        request_result = await rest_assistant.execute_request(
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
        response = await self.execute_request_and_get_response(
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/core/web_assistant/rest_assistant.py", line 94, in execute_request_and_get_response
        response = await self.call(request=request, timeout=timeout)
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/core/web_assistant/rest_assistant.py", line 108, in call
        resp = await wait_for(self._connection.call(request), timeout)
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
        return await fut
      File "/home/rapcomia/github/hummingbot/7095/hummingbot/core/web_assistant/connections/rest_connection.py", line 10, in call
        aiohttp_resp = await self._client_session.request(
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/client.py", line 581, in _request
        conn = await self._connector.connect(
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
        proto = await self._create_connection(req, traces, timeout)
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 944, in _create_connection
        _, proto = await self._create_direct_connection(req, traces, timeout)
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 1203, in _create_direct_connection
        hosts = await self._resolve_host(host, port, traces=traces)
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
        return await asyncio.shield(resolved_host_task)
    asyncio.exceptions.CancelledError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
        return fut.result()
    asyncio.exceptions.CancelledError
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/rapcomia/github/hummingbot/7095/test/hummingbot/connector/exchange/kucoin/test_kucoin_exchange.py", line 2267, in test_update_order_status_marks_order_with_no_exchange_id_as_not_found
        self.async_run_with_timeout(self.exchange._update_order_status(), timeout=2)
      File "/home/rapcomia/github/hummingbot/7095/test/hummingbot/connector/exchange/kucoin/test_kucoin_exchange.py", line 111, in async_run_with_timeout
        ret = self.ev_loop.run_until_complete(asyncio.wait_for(coroutine, timeout))
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
        return future.result()
      File "/home/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
        raise exceptions.TimeoutError() from exc
    asyncio.exceptions.TimeoutError
    
    ----------------------------------------------------------------------
    Ran 4296 tests in 394.612s
    
    FAILED (errors=3)
    make: *** [Makefile:13: test] Error 1
    ```
[07112024-PR7095.log](https://github.com/user-attachments/files/16171750/07112024-PR7095.log)
[07112024-development.log](https://github.com/user-attachments/files/16171751/07112024-development.log)

**Comment by Jbekker** [comment]
While these issues are unrelated to my change in `hummingbot/connector/test_support/exchange_connector_test.py`, the fixes were small enough to include in this PR.
I also fixed one additional test that had a unnecessary 30 second sleep in it.

**Comment by rapcmia** [comment]
- Ran same tests on lates commit `ebc0791b78ae42b3dfeb0bd13dca1a1ae1921071` on WSL Ubuntu22.04LTS, all ok
- Ran 3/3 tests, all ok. 

[output.log](https://github.com/user-attachments/files/16176163/output.log)

**Pull request merged**
