### PR TITLE
Feat/broker performance report

### PR DESCRIPTION
**Pull request by cardosofede**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
PR to include performance report through the broker

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by nikspz** [comment]
1. Binance now showing as default rate oracle ✅

image

2. pmm_simple now able to do backtesting ✅


3. pmm_dynamic failed to do backtesting with this error

Backend API log:
[log.txt](https://github.com/hummingbot/hummingbot/files/15422553/log.txt)

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/dashboard/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/home/dashboard/frontend/pages/config/pmm_dynamic/app.py", line 69, in <module>
    bt_results = backtesting_section(inputs, backend_api_client)
  File "/home/dashboard/frontend/components/backtesting.py", line 25, in backtesting_section
    backtesting_results = backend_api_client.run_backtesting(
  File "/home/dashboard/backend/services/backend_api_client.py", line 201, in run_backtesting
    backtesting_results = response.json()
  File "/opt/conda/envs/dashboard/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-05-23 20:43:11.532 Uncaught app exception
Traceback (most recent call last):
  File "/opt/conda/envs/dashboard/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/conda/envs/dashboard/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/envs/dashboard/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/opt/conda/envs/dashboard/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:
```

Backend API
```
INFO:     Started server process [16]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     172.22.0.2:37362 - "GET /is-docker-running HTTP/1.1" 200 OK
INFO:     172.22.0.2:37364 - "GET /get-active-bots-status HTTP/1.1" 404 Not Found
2024-05-23 20:36:09,363 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f12a459cb50>
2024-05-23 20:36:09,363 - asyncio - ERROR - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f12a454f5e0>, 32822.485388624)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f12a459cbe0>
INFO:     172.22.0.2:37374 - "POST /historical-candles HTTP/1.1" 200 OK
2024-05-23 20:36:22,235 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f12a32e7640>
2024-05-23 20:36:22,235 - asyncio - ERROR - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f12a32c28c0>, 32835.361230494)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f12a32e7670>
2024-05-23 20:36:24,044 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f12a32e7640>
2024-05-23 20:36:24,045 - asyncio - ERROR - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f12a32c2c20>, 32837.171175841)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f12a32e7760>
/backend-api/bots/controllers/market_making/pmm_dynamic.py:114: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  candles["spread_multiplier"] = natr
/backend-api/bots/controllers/market_making/pmm_dynamic.py:115: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  candles["reference_price"] = candles["close"] * (1 + price_multiplier)
INFO:     172.22.0.2:37386 - "POST /run-backtesting HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/routing.py", line 296, in app
    content = await serialize_response(
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/routing.py", line 180, in serialize_response
    return jsonable_encoder(response_content)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 289, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 303, in jsonable_encoder
    jsonable_encoder(
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 235, in jsonable_encoder
    return jsonable_encoder(
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 289, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 289, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 318, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 52, in decimal_encoder
    if dec_value.as_tuple().exponent >= 0:  # type: ignore[operator]
TypeError: '>=' not supported between instances of 'str' and 'int'
INFO:     172.22.0.2:37520 - "POST /run-backtesting HTTP/1.1" 200 OK
2024-05-23 20:39:37,217 - apscheduler.executors.default - WARNING - Run time of job "update_active_bots (trigger: interval[0:00:10], next run at: 2024-05-23 20:39:43 UTC)" was missed by 0:00:04.178534
2024-05-23 20:42:47,006 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f12a3150190>
2024-05-23 20:42:47,007 - asyncio - ERROR - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f12a2bb9ba0>, 33220.133394127)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f12a31500d0>
INFO:     172.22.0.2:37658 - "POST /historical-candles HTTP/1.1" 200 OK
2024-05-23 20:43:04,601 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f12a32e70d0>
2024-05-23 20:43:04,602 - asyncio - ERROR - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f12a2bbbf40>, 33237.723193709)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f12a32e6fb0>
2024-05-23 20:43:05,213 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f12a31b8cd0>
2024-05-23 20:43:05,213 - asyncio - ERROR - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f12a2bbb220>, 33238.333347182)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f12a31b8b50>
/backend-api/bots/controllers/market_making/pmm_dynamic.py:114: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  candles["spread_multiplier"] = natr
/backend-api/bots/controllers/market_making/pmm_dynamic.py:115: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  candles["reference_price"] = candles["close"] * (1 + price_multiplier)
INFO:     172.22.0.2:37674 - "POST /run-backtesting HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/routing.py", line 296, in app
    content = await serialize_response(
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/routing.py", line 180, in serialize_response
    return jsonable_encoder(response_content)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 289, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 303, in jsonable_encoder
    jsonable_encoder(
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 235, in jsonable_encoder
    return jsonable_encoder(
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 289, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 289, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 318, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 52, in decimal_encoder
    if dec_value.as_tuple().exponent >= 0:  # type: ignore[operator]
TypeError: '>=' not supported between instances of 'str' and 'int'
2024-05-23 20:47:02,749 - root - ERROR - Error writing configs: [Errno 2] No such file or directory: '/opt/conda/envs/backend-api/lib/python3.10/site-packages/conf/conf_client.yml'
Traceback (most recent call last):
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/hummingbot/client/config/config_helpers.py", line 876, in save_to_yml
    with open(yml_path, "w", encoding="utf-8") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/envs/backend-api/lib/python3.10/site-packages/conf/conf_client.yml'
2024-05-23 20:50:20,643 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f12a290b6a0>
2024-05-23 20:50:20,644 - asyncio - ERROR - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f12a28f7be0>, 33673.769980701)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f12a290b6d0>
2024-05-23 20:50:23,228 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f12a290b550>
2024-05-23 20:50:23,228 - asyncio - ERROR - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f12a28f5120>, 33676.354604938)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f12a290b580>
/backend-api/bots/controllers/market_making/pmm_dynamic.py:114: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  candles["spread_multiplier"] = natr
/backend-api/bots/controllers/market_making/pmm_dynamic.py:115: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  candles["reference_price"] = candles["close"] * (1 + price_multiplier)
INFO:     172.22.0.2:38002 - "POST /run-backtesting HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/routing.py", line 296, in app
    content = await serialize_response(
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/routing.py", line 180, in serialize_response
    return jsonable_encoder(response_content)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 289, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 303, in jsonable_encoder
    jsonable_encoder(
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 235, in jsonable_encoder
    return jsonable_encoder(
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 289, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 289, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 318, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File "/opt/conda/envs/backend-api/lib/python3.10/site-packages/fastapi/encoders.py", line 52, in decimal_encoder
    if dec_value.as_tuple().exponent >= 0:  # type: ignore[operator]
TypeError: '>=' not supported between instances of 'str' and 'int'

```
pmm dynamic

**Comment by rapcmia** [comment]
Ran test commit `dce6e2d0b548c30820a175ea66e6d004290e59fa`
- When running controller configs `market_making.pmm_simple` and `generic.xemm_multiple_levels.py` orders are placed but getting `unexpected error clock tick`
```
2024-05-24 23:25:09,095 - 88691 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order HUMBOTBFOUT61934c5d8ebdcc8d9f804 for 7.48 FIRO-USDT.
2024-05-24 23:25:09,103 - 88691 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1716564309.0, "type": "OrderType.LIMIT", "trading_pair": "FIRO-USDT", "amount": "7.48", "price": "1.722", "order_id": "HUMBOTBFOUT61934c5d8ebdcc8d9f804", "creation_timestamp": 1716564308.0, "exchange_order_id": "C02__422710653707444225049", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "mexc"}
2024-05-24 23:25:09,103 - 88691 - hummingbot.strategy_v2.executors.xemm_executor.xemm_executor - INFO - Maker order HUMBOTBFOUT61934c5d8ebdcc8d9f804 created.
2024-05-24 23:25:09,218 - 88691 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order HUMBOTSFOUT61934c5d8ee78c8d9f804 for 7.48 FIRO-USDT.
2024-05-24 23:25:09,218 - 88691 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1716564309.0, "type": "OrderType.LIMIT", "trading_pair": "FIRO-USDT", "amount": "7.48", "price": "1.749", "order_id": "HUMBOTSFOUT61934c5d8ee78c8d9f804", "creation_timestamp": 1716564308.0, "exchange_order_id": "C02__422710654185594880049", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "mexc"}
2024-05-24 23:25:09,221 - 88691 - hummingbot.strategy_v2.executors.xemm_executor.xemm_executor - INFO - Maker order HUMBOTSFOUT61934c5d8ee78c8d9f804 created.
2024-05-24 23:25:09,854 - 88691 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-05-24 23:25:10,008 - 88691 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/strategy_py_base.pyx", line 44, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_tick
    self.tick(timestamp)
  File "/Users/rapcomia/github/hummingbot/7046/hummingbot/strategy/script_strategy_base.py", line 75, in tick
    self.on_tick()
  File "/Users/rapcomia/github/hummingbot/7046/scripts/v2_with_controllers.py", line 64, in on_tick
    self.send_performance_report()
  File "/Users/rapcomia/github/hummingbot/7046/scripts/v2_with_controllers.py", line 69, in send_performance_report
    self._pub(performance_reports)
TypeError: 'NoneType' object is not callable
```
- Crosscheck with staging and its issue does not occur
- Do fresh install of the PR still getting same error

--- 

Steps to reproduce:
1. Create default controller-configs for market_making.pmm_simple and generic.xemm_multiple_airs
2. Start the script-config and observe the error when orders are being placed to exchange 

[logs_conf_v2_simple_pmm_1.log](https://github.com/hummingbot/hummingbot/files/15436815/logs_conf_v2_simple_pmm_1.log)
[logs_conf_v2_with_controllers_1.log](https://github.com/hummingbot/hummingbot/files/15436817/logs_conf_v2_with_controllers_1.log)

**Comment by nikspz** [comment]
Pmm Dynamic - Failed to increase order levels

Steps:

- on PMM Dynamic
- ~~use lower amount for `total amount of Quote`~~
- increase order levels
- review the issue

```jsx
2024-05-27 15:22:20.488 Uncaught app exception
Traceback (most recent call last):
  File "/opt/conda/envs/dashboard/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/home/dashboard/frontend/pages/config/pmm_dynamic/app.py", line 69, in <module>
    fig = create_executors_distribution_traces(buy_spreads, sell_spreads, inputs["buy_amounts_pct"], inputs["sell_amounts_pct"], inputs["total_amount_quote"])
  File "/home/dashboard/frontend/visualization/executors_distribution.py", line 54, in create_executors_distribution_traces
    x=sell_spread_distributions[i],
IndexError: list index out of range
2024-05-27 15:22:22.632 Uncaught app exception
Traceback (most recent call last):
  File "/opt/conda/envs/dashboard/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/home/dashboard/frontend/pages/config/pmm_dynamic/app.py", line 69, in <module>
    fig = create_executors_distribution_traces(buy_spreads, sell_spreads, inputs["buy_amounts_pct"], inputs["sell_amounts_pct"], inputs["total_amount_quote"])
  File "/home/dashboard/frontend/visualization/executors_distribution.py", line 54, in create_executors_distribution_traces
    x=sell_spread_distributions[i],
IndexError: list index out of range
```

https://www.notion.so/hummingbot-foundation/Hummingbot-2-0-Launch-5b41fb83ec7d445fa23d143bd44c3ffb

**Comment by rapcmia** [comment]
Ran tests on commit `4ff58e5c13769071779380050760e3206c4ea11b`
- Ran tests with latest hummingbot-deploy ✅ 
- Overview of recent commits 👀 
   - Test in progress on ongoing issues to check if this can fix `pending`

---

Age issue still exist, not sure if this is expected atm ❌
image
image
- Attached screenshots from `pmm_simple` and `bollinger_v1`
- Compare `config generator` and the config saved from the instances folder, time matched when converted to seconds ✅
- Observed that when the open executor reaches set `time_limit` nothing happens ❌
    - See screen recording here  https://www.loom.com/share/040a800a49b84d04931e91032a74d168
    - It is expected that the executor will be closed in favor of TIME_LIMIT but no go

Steps to reproduce for `time_limit` bug
- Deploy a config with short time_limit value and observe that the active executor will not be terminated.

**Review by rapcmia — APPROVED** [review]
- Reported issues on this PR has been fixed by dev
- Ran tests on the following v2 strategies using binance and mexc spot connector
  - market_making.pmm_simple
  - market_making.dman_maker_v2
  - market_making.pmm_dynamic
  - generic.xemm_multiple_pairs
 - Opened issues not related to PR ✅ 
 
 ---
 
 Pending:
 - Nikita testing directional trading controllers

**Review by nikspz — APPROVED** [review]
- Reported issues on this PR has been fixed by dev
- Ran tests on the following v2 strategies using binance and mexc spot connector
  - market_making.pmm_simple
  - market_making.dman_maker_v2
  - market_making.pmm_dynamic
  - generic.xemm_multiple_pairs
 - Opened issues not related to PR ✅ 
- Ran the following v2 strategies successfully using binance_perpetual connector:
    - directional_trading.bollinger_v1
    - directional_trading.dman_v3
    - directional_trading.macd_bb_v1
    - directional_trading.supertrend_v1

**Pull request merged**
