### PR TITLE
(fix) okx perpetual orders with wrong amount

### PR DESCRIPTION
**Pull request by tomasgaudino**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Since order creation and cancelation amounts are expressed in contracts and trading rules doesn't support this value, a local attribute was defined in order to handle this and translate correctly between amounts and sizes

**Tests performed by the developer**:
`coverage run --source=hummingbot/connector/derivative/okx_perpetual -m nose test/hummingbot/connector/derivative/okx_perpetual/test_okx_perpetual_derivative.py && coverage report --include="*/okx_perpetual_derivative.py" -m`

**Tips for QA testing**:
- Run any v2 strategy and verify that amounts are well sized. Trading pairs suggested: `XRP-USDT`, `MATIC-USDT`, `FLOKI-USDT`, etc.

### CODE REVIEW

**Comment by tomasgaudino** [comment]
@nikspz we have detected with @cardosofede that in certain markets the amounts weren't expressed correctly. this fix solves this issue

**Comment by nikspz** [comment]
Test performed:
- Cloned and installed PR7002
- Set up Dman-v3 using okx_perpetual over ~6 hours using WIF-USDT pair
- Reviewed order amount is correct for OPEN and CLOSE orders

Pending: review dman-v3 on other pairs

**Review by cardosofede — APPROVED** [review]

**Comment by nikspz** [comment]
@tomasgaudino could you please review again?



```
2024-05-02 21:11:47,326 - 3726996 - hummingbot.client.hummingbot_application - INFO - Creating the clock with tick size: 1.0
2024-05-02 21:11:47,335 - 3726996 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2024-05-02 21:11:47,613 - 3726996 - hummingbot.connector.derivative.okx_perpetual.okx_perpetual_derivative.OkxPerpetualDerivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-05-02 21:11:47,697 - 3726996 - hummingbot.connector.derivative.okx_perpetual.okx_perpetual_derivative.OkxPerpetualDerivative - INFO - Leverage for XRP-USDT successfully set to 10.
2024-05-02 21:11:47,929 - 3726996 - hummingbot.connector.derivative.okx_perpetual.okx_perpetual_api_order_book_data_source.OkxPerpetualAPIOrderBookDataSource - INFO - Subscribed to public order book, trade and funding info channels...
2024-05-02 21:11:47,984 - 3726996 - hummingbot.connector.derivative.okx_perpetual.okx_perpetual_user_stream_data_source.OkxPerpetualUserStreamDataSource - INFO - Subscribed to private account and orders channels wss://ws.okx.com:8443/ws/v5/private...
2024-05-02 21:11:48,046 - 3726996 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
2024-05-02 21:11:49,443 - 3726996 - hummingbot.strategy.script_strategy_base - INFO - Creating XRP-USDT sell order: price: 0.5217705922450562178761760552 amount: 47.91377737950097220354345680.
2024-05-02 21:11:49,517 - 3726996 - hummingbot.connector.client_order_tracker - INFO - The SELL order 93027a12dac34fBCSXPUT1640102fc2d amounting to 40.0/40.0 XRP has been filled.
2024-05-02 21:11:49,540 - 3726996 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1714684309.0, "order_id": "93027a12dac34fBCSXPUT1640102fc2d", "trading_pair": "XRP-USDT", "trade_type": "TradeType.SELL", "order_type": "OrderType.LIMIT", "price": "0.5217", "amount": "40.0", "trade_fee": {"percent": "0", "percent_token": "USDT", "flat_fees": [{"token": "USDT", "amount": "0.010434"}]}, "exchange_trade_id": "182863723", "exchange_order_id": "1415390013308944385", "leverage": 10, "position": "OPEN", "event_name": "OrderFilledEvent", "event_source": "okx_perpetual"}
2024-05-02 21:11:49,541 - 3726996 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order 93027a12dac34fBCSXPUT1640102fc2d for 40.0 to OPEN a XRP-USDT position.
2024-05-02 21:11:49,565 - 3726996 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1714684309.0, "type": "OrderType.LIMIT", "trading_pair": "XRP-USDT", "amount": "40.0", "price": "0.5217", "order_id": "93027a12dac34fBCSXPUT1640102fc2d", "creation_timestamp": 1714684309.0, "exchange_order_id": "1415390013308944385", "leverage": 10, "position": "OPEN", "event_name": "SellOrderCreatedEvent", "event_source": "okx_perpetual"}
2024-05-02 21:11:49,577 - 3726996 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1714684309.0, "order_id": "93027a12dac34fBCSXPUT1640102fc2d", "base_asset": "XRP", "quote_asset": "USDT", "base_asset_amount": "40.0", "quote_asset_amount": "20.86800", "order_type": "OrderType.LIMIT", "exchange_order_id": "1415390013308944385", "event_name": "SellOrderCompletedEvent", "event_source": "okx_perpetual"}
2024-05-02 21:11:49,578 - 3726996 - hummingbot.connector.client_order_tracker - INFO - SELL order 93027a12dac34fBCSXPUT1640102fc2d completely filled.
2024-05-02 21:11:50,458 - 3726996 - hummingbot.strategy.script_strategy_base - INFO - Creating XRP-USDT sell order: price: 0.5221206604110119217711689920 amount: 47.88165245236622126382386927.
2024-05-02 21:11:50,568 - 3726996 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order 93027a12dac34fBCSXPUTf7123c5afa8 for 40.0 to OPEN a XRP-USDT position.
2024-05-02 21:11:50,581 - 3726996 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1714684310.0, "type": "OrderType.LIMIT", "trading_pair": "XRP-USDT", "amount": "40.0", "price": "0.5221", "order_id": "93027a12dac34fBCSXPUTf7123c5afa8", "creation_timestamp": 1714684310.0, "exchange_order_id": "1415390047299584000", "leverage": 10, "position": "OPEN", "event_name": "SellOrderCreatedEvent", "event_source": "okx_perpetual"}
2024-05-02 21:11:51,474 - 3726996 - hummingbot.strategy.script_strategy_base - INFO - Creating XRP-USDT sell order: price: 0.5248388367584326814264082672 amount: 47.63367008891290938745410036.
2024-05-02 21:11:51,535 - 3726996 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order 93027a12dac34fBCSXPUT17f5cbd33af for 40.0 to OPEN a XRP-USDT position.
2024-05-02 21:11:51,545 - 3726996 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1714684311.0, "type": "OrderType.LIMIT", "trading_pair": "XRP-USDT", "amount": "40.0", "price": "0.5248", "order_id": "93027a12dac34fBCSXPUT17f5cbd33af", "creation_timestamp": 1714684311.0, "exchange_order_id": "1415390081424441344", "leverage": 10, "position": "OPEN", "event_name": "SellOrderCreatedEvent", "event_source": "okx_perpetual"}
2024-05-02 21:11:52,488 - 3726996 - hummingbot.strategy.script_strategy_base - INFO - Creating XRP-USDT sell order: price: 0.5268980612640544690440137788 amount: 47.44750804363137228564852326.
2024-05-02 21:11:52,548 - 3726996 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order 93027a12dac34fBCSXPUT1f0948a7701 for 40.0 to OPEN a XRP-USDT position.
2024-05-02 21:11:52,558 - 3726996 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1714684312.0, "type": "OrderType.LIMIT", "trading_pair": "XRP-USDT", "amount": "40.0", "price": "0.5268", "order_id": "93027a12dac34fBCSXPUT1f0948a7701", "creation_timestamp": 1714684312.0, "exchange_order_id": "1415390115515744256", "leverage": 10, "position": "OPEN", "event_name": "SellOrderCreatedEvent", "event_source": "okx_perpetual"}

```
image
image
image

**Comment by tomasgaudino** [comment]
@nikspz according to trading rules the scenario is the following:

1) XRP-USDT: step size (min base amount increment) is of 10 according to [okx perpetuals info](https://www.okx.com/trade-market/info/swap). That's why hummingbot attempts to create a 47.881 order and then effectively gets a position for 40 instead. The connector forces the orders to enter to the nearest lower possible value.

image

2) MATIC-USDT: the order placed manually for 15 MATIC is in spot, for perpetuals it doesn't allow it (check right side panel)
 
image

**Comment by nikspz** [comment]
> according to trading rules the scenario is the following:
> 
> 1. XRP-USDT: step size (min base amount increment) is of 10 according to [okx perpetuals info](https://www.okx.com/trade-market/info/swap). That's why hummingbot attempts to create a 47.881 order and then effectively gets a position for 40 instead. The connector forces the orders to enter to the nearest lower possible value.
> 

Thanks, got it, checking MATIC-USDT on dman-v3 behavior now

**Review by nikspz — APPROVED** [review]
Test performed:
- Cloned and installed PR7002
- Set up Dman-v3 using okx_perpetual over ~6 hours using MATIC-USDT pair
- Reviewed order amount is correct for OPEN and CLOSE orders

**Pull request merged**
