### PR TITLE
Feat/position executor improvements

### PR DESCRIPTION
**Pull request by cardosofede**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Refactor on Position executor:
- Create smart components base class
- Test for smart components base
- Refactor position executor: 
      1. Spot + Perp trading
      2. Trailing Stop
      3. Control logic
- Test for position executor
- Refactor strategies that are using the directional framework

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update:
- Setup ok on source, docker and docker-compose
- Overview on directional_strategy and available scripts 
   - stop_loss `no results yet`
   - take_profit `no results yet`
   - time_limit: When reached, creates order to close position
- Ran some test with `directional_strategy_rsi` and observed expected behaviors
   - Results based on default setup, successfully creates Long or Short position.

Pending:
- Plan for other user case scenario for the strategy
- Run long term bots and observe behavior
- Compare results to development branch if necessary

**Comment by nikspz** [comment]
@cardosofede 
current advanced_directional_strategy_example by default config are not able to start, flooded with  ERROR - Unexpected error running clock tick.
Crosscheck with Ralph - got same behavior.
Tried to change pairs, order amount and position mode - didn't help.


Steps to reproduce:
1. Clone and install feature branch
2. connect binance_perpetual
3. Start the advanced_directional_strategy_example.py script
4. Wait for 5-15 minutes after script starts

Actual:
Bot flooded with ERROR - Unexpected error running clock tick.

Expected: 
Script started successfully without errors



[logs_advanced_directional_strategy_example.log](https://github.com/hummingbot/hummingbot/files/11602636/logs_advanced_directional_strategy_example.log)

[advanced_directional_strategy_example.zip](https://github.com/hummingbot/hummingbot/files/11602635/advanced_directional_strategy_example.zip)


```
2023-05-30 17:06:04,030 - 572561 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/strategy_py_base.pyx", line 44, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_tick
    self.tick(timestamp)
  File "/home/ubuntu/6322posex/hummingbot/strategy/script_strategy_base.py", line 60, in tick
    self.on_tick()
  File "/home/ubuntu/6322posex/scripts/advanced_directional_strategy_example3.py", line 106, in on_tick
    position_config=PositionConfig(
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PositionConfig
side
  value is not a valid enumeration member; permitted: 1, 2, 3 (type=type_error.enum; enum_values=[<TradeType.BUY: 1>, <TradeType.SELL: 2>, <TradeType.RANGE: 3>])
2023-05-30 17:06:05,030 - 572561 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/strategy_py_base.pyx", line 44, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_tick
    self.tick(timestamp)
  File "/home/ubuntu/6322posex/hummingbot/strategy/script_strategy_base.py", line 60, in tick
    self.on_tick()
  File "/home/ubuntu/6322posex/scripts/advanced_directional_strategy_example3.py", line 106, in on_tick
    position_config=PositionConfig(
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PositionConfig
side
  value is not a valid enumeration member; permitted: 1, 2, 3 (type=type_error.enum; enum_values=[<TradeType.BUY: 1>, <TradeType.SELL: 2>, <TradeType.RANGE: 3>])

```

image

**Comment by rapcmia** [comment]
PR update:
- Test latest commit `13e33941a4fc4`
- **directional_strategy_rsi_spot**
    - Use default setup run for 45mins, all ok
    - Change RSI from different values {60,40}, {20,30} and {30,30}
    - When insufficient balance, it also recorded on the RSI CSV file with `CloseType.INSUFFICIENT_BALANCE`
- **pmm_with_position_executor** 
    - position executor created with type:
        - `CloseType.Expired` if not filled
        - `CloseType.INSUFFICIENT_BALANCE` if less asset
            - Logs also display `“Not enough budget to open position”` when on PMM strategy which we assume that something to do with `“not enough budget to open order”` ?
        - `CloseType.None` if filled with position_executor UI
        - Orders are cancelled at the set refresh time ✅
    - Signal ID is created and match when epoch converted
 - **The link created on dashboard does not let us access**
    image
    image

**Comment by rapcmia** [comment]
PR update
- Test on local WSL ubuntu 20.04, source build
- Test latest commit `0ebf6cb788efcbf2d6d2d66c6fa72d05ea04643d`
    - Test `directional_strategi_rsi_spot`
        - Same behavior when insufficient balance, signal id created with `CloseType.INSUFFICIENT_BALANCE`
           image
           - When either of base and quote does not have enough asset, we are flooded by `not enough budget to open position` and signal_ids with close type `INSUFFICIENT_BALANCE` will be expected behavior @cardosofede? thanks
    - Change time_limit to 30s to observe behavior when there is a active executor, closes by getting the other side with close type `TIME_LIMIT`
    - Value is updated when reached the set RSI (-1 sell, 1 buy and 0 for neutral)
    - Observed close types: TIME_LIMIT, EXPIRED and TRAILING_STOP ✅
    - Trade data compared between history, CSV and exchange trade history ok 
    - Check RSI CSV downloaded candle and review trade data and timeframes, matched on the client/exchange
    
 Pending:
- pmm_with_position_executor
- mac_bb_directional_strategy

**Comment by cardosofede** [comment]
@rapcmia it's the expected behavior. Basically, the position executor now has the ability to adjust the order to the budget and understand if has enough money to place the order or not. So if you are trying to place an order but don't have enough balance, it will close the executor. The thing is that the strategy should be handling the rest.

**Comment by rapcmia** [comment]
PR update
- Due to ongoing issue on development branch, checkout last commit applied by dev for the PR using `0ebf6cb788efcbf2d6d2d66c6fa72d05ea04643d`
- Test `pmm_with_position_executor`
   - Modified the script pmm parameters and observe behavior 👀 
   - Creates buy and sell order for entry price 
      - Observed on status `Active Bids` and `Active Asks`
      - If insufficient, same behavior for position executor` not enough budget to open position`, every tick will try to resubmit ✅ 
        image
    - Modified `time_limit` and `executor_refresh_time` to observe behavior 
      - Creates new order by cancel the current when `executor_refresh_time` is reached with close type `EXPIRED`
        image
      - If `time_limit` is reached over `executor_refresh_time`? same behavior but with added logs `removing open order by time limit`
        image
        - `TIME_LIMIT` close type is applied when there is a open position executor and reaches the set `time_limit` value
        - Assuming expected behavior would be that the `executor_refresh_time` must not be more than `time_limit` 
     - Compare trade data between close executors and history command
        image
        - Observed that the initial buy and sell orders are the entry price. The behavior is related to hedge where it creates orders for the close price.
        - When bot buy and sell entry price are closed, it recreate a new set of orders
        - Unfortunately unable to trigger the trailing stop, stop loss and take profit close type 🙇

**Review by nikspz — APPROVED** [review]
Test performed:
- directional_strategy_bb_rsi_multi_timeframe: ok
Triggered Stop-loss ✅ 
Triggered Trailing stop✅ 
- directional_strategy_macd_bb: ok
Triggered Stop-loss ✅ 
Triggered time_limit ✅ 
Triggered Trailing stop✅ 
- directional_strategy_rsi: ok
- directional_strategy_rsi_spot, ok
- pmm_with_position_executor, ok 

  - Observed logs related to perpetual market making when there is insufficient funds
  - Signal ID created and match when epoch converted

Note: Noticed default values need to be improved for users want to generate profit
Note: noticed that csv files cut the whole file name like:
image

**Pull request merged**
