### PR TITLE
feat / improve notification about status of gateway

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This pr adds logging when gateway is starting/stopped.

**Tests performed by the developer:**
- Started client then stopped and started gateway docker and confirmed new log messages.
- Repeated about but with gateway from source and confirmed new log messages as well.

**Tips for QA testing:**
- Run client then make gateway docker start and stop the confirm that appropriate log is shown in log panel each time.
- Repeat above step but with gateway from source.

### CODE REVIEW

**Comment by vic-en** [comment]
PRP: https://snapshot.org/#/hbot-prp.eth/proposal/0x876f459e3697491f8fa9d8a6f64ba4ed520d0a2abca179f47bb8bd25546572f7

**Comment by JeremyKono** [comment]
Hi @vic-en please resolve conflicts in this PR

**Review by nikspz — DISMISSED** [review]
### Test performed:
- Cloned feature branch and started client with no issues
- Built docker images and generated gateway docker container
- No errors when creating Docker image and container
- Generated certificate and called on gateway create with no errors
- Verified no issues when starting and stop Gateway
- Notification in log pane is clear when Gateway is running or not
- Tested on Source and Docker

**Comment by aarmoa** [comment]
@vic-en please solve the merging conflicts in this PR

**Review by nikspz — APPROVED** [review]

**Pull request merged**
