### PR TITLE
Fix: (dYdX perpetual) Cancel order on failed events

### PR DESCRIPTION
**Pull request by harjas27**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Fixes https://github.com/hummingbot/hummingbot/issues/6716
Cause - After a failed order event, the order is removed from the active orders dict. Thus, on the next tick - that order is not cancelled. This leads to the order getting stuck on the exchange, causing potential issues like insufficient balance and being at risk of liquidation.
Fix - After receiving a failed order event, the order will be cancelled. 

**Tests performed by the developer**:
Adds a unit test `test_orders_are_cancelled_in_case_of_failure` to check that the order corresponding to the failed event is cancelled.

**Tips for QA testing**:

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update:
- Ran initial tests on v1 strategy perpetual market making for couple of hours and review logs ✅ 
- Setup v2 strategy using multple-exchanges script `wip`
 - Review logs and observe unexpected errors possible related to server disconnection
    ```
    2024-03-05 20:19:14,619 - 4127 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_user_stream_data_source - INFO - Connecting to wss://api.dydx.exchange/v3/ws
    2024-03-05 20:19:15,079 - 4127 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_user_stream_data_source - INFO - Authenticated user stream...
    2024-03-05 20:19:15,623 - 4127 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative.DydxPerpetualDerivative - ERROR - Unexpected error in user stream listener loop.
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/6880/hummingbot/connector/derivative/dydx_perpetual/dydx_perpetual_derivative.py", line 436, in _user_stream_event_listener
        * self._margin_fractions[trading_pair]["initial"]
    UnboundLocalError: local variable 'trading_pair' referenced before assignment
    ```
     - Compare tests on development `pending`

**Comment by cardosofede** [comment]
@harjas27 thanks for the contribution but I don't think that this is a solution for DyDX.
If you receive a failed order event means that the order has failed and it's not active, so how can you cancel it if was failed?

I think that the main issue here to resolve is why the DyDx connector marks this order as failed if it's not really failed, so the event is not going to be triggered

**Comment by harjas27** [comment]
@cardosofede the focus of this fix was to prevent the order to be stuck on the exchange in case of the failure event (which was happening in the logs shared in the issue - https://github.com/hummingbot/hummingbot/issues/6716) 
If it is ok, I would like to give this another shot and look into the cause of why the order is being marked as failed.

**Comment by harjas27** [comment]
```
2023-12-14 13:22:02,002 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (LINK-USD) Creating 2 LIMIT bid orders at (Size, Price): ['1.6 LINK, 14.617 USD', '1.6 LINK, 14.47 USD'] to OPEN position.
2023-12-14 13:22:02,002 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (LINK-USD) Creating 2  LIMIT ask orders at (Size, Price): ['1.6 LINK, 14.913 USD', '1.6 LINK, 15.06 USD'] to OPEN position.
2023-12-14 13:22:02,423 - 9983 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order HummingbotSLKUD60c7176aabe6fed184d098c22 for 1.6 to OPEN a LINK-USD position.
2023-12-14 13:22:02,423 - 9983 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702531322.0, "type": "OrderType.LIMIT", "trading_pair": "LINK-USD", "amount": "1.6", "price": "14.913", "order_id": "HummingbotSLKUD60c7176aabe6fed184d098c22", "creation_timestamp": 1702531322.0, "exchange_order_id": "1f73be6e95dfc2db0699e088ba08b4c0b679bfae214dc86a30dc9df3fff2acb", "leverage": 10, "position": "OPEN", "event_name": "SellOrderCreatedEvent", "event_source": "dydx_perpetual"}
2023-12-14 13:22:02,427 - 9983 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order HummingbotSLKUD60c7176aabe8aed184d098c22 for 1.6 to OPEN a LINK-USD position.
2023-12-14 13:22:02,427 - 9983 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702531322.0, "type": "OrderType.LIMIT", "trading_pair": "LINK-USD", "amount": "1.6", "price": "15.060", "order_id": "HummingbotSLKUD60c7176aabe8aed184d098c22", "creation_timestamp": 1702531322.0, "exchange_order_id": null, "leverage": 10, "position": "OPEN", "event_name": "SellOrderCreatedEvent", "event_source": "dydx_perpetual"}
2023-12-14 13:22:02,595 - 9983 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order HummingbotBLKUD60c7176aabdc7ed184d098c22 for 1.6 to OPEN a LINK-USD position.
2023-12-14 13:22:02,596 - 9983 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702531322.0, "type": "OrderType.LIMIT", "trading_pair": "LINK-USD", "amount": "1.6", "price": "14.617", "order_id": "HummingbotBLKUD60c7176aabdc7ed184d098c22", "creation_timestamp": 1702531322.0, "exchange_order_id": null, "leverage": 10, "position": "OPEN", "event_name": "BuyOrderCreatedEvent", "event_source": "dydx_perpetual"}
2023-12-14 13:22:02,626 - 9983 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order HummingbotBLKUD60c7176aabdffed184d098c22 for 1.6 to OPEN a LINK-USD position.
2023-12-14 13:22:02,626 - 9983 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702531322.0, "type": "OrderType.LIMIT", "trading_pair": "LINK-USD", "amount": "1.6", "price": "14.470", "order_id": "HummingbotBLKUD60c7176aabdffed184d098c22", "creation_timestamp": 1702531322.0, "exchange_order_id": null, "leverage": 10, "position": "OPEN", "event_name": "BuyOrderCreatedEvent", "event_source": "dydx_perpetual"}
2023-12-14 13:22:02,771 - 9983 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702531322.0, "order_id": "HummingbotBLKUD60c7176aabdc7ed184d098c22", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "dydx_perpetual"}
2023-12-14 13:22:02,775 - 9983 - hummingbot.connector.client_order_tracker - INFO - Order HummingbotBLKUD60c7176aabdc7ed184d098c22 has failed. Order Update: OrderUpdate(trading_pair='LINK-USD', update_timestamp=1702531322.0, new_state=<OrderState.FAILED: 6>, client_order_id='HummingbotBLKUD60c7176aabdc7ed184d098c22', exchange_order_id=None, misc_updates=None)
2023-12-14 13:22:02,775 - 9983 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702531322.0, "order_id": "HummingbotBLKUD60c7176aabdffed184d098c22", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "dydx_perpetual"}
2023-12-14 13:22:02,778 - 9983 - hummingbot.connector.client_order_tracker - INFO - Order HummingbotBLKUD60c7176aabdffed184d098c22 has failed. Order Update: OrderUpdate(trading_pair='LINK-USD', update_timestamp=1702531322.0, new_state=<OrderState.FAILED: 6>, client_order_id='HummingbotBLKUD60c7176aabdffed184d098c22', exchange_order_id=None, misc_updates=None)

2023-12-14 13:23:02,004 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (LINK-USD) Canceling the limit order HummingbotSLKUD60c7176aabe6fed184d098c22. [clock=2023-12-14 05:23:02+00:00]
2023-12-14 13:23:02,006 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Canceling active order HummingbotSLKUD60c7176aabe6fed184d098c22.
2023-12-14 13:23:02,006 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (LINK-USD) Canceling the limit order HummingbotSLKUD60c7176aabe8aed184d098c22. [clock=2023-12-14 05:23:02+00:00]
2023-12-14 13:23:02,006 - 9983 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Canceling active order HummingbotSLKUD60c7176aabe8aed184d098c22.
2023-12-14 13:23:02,176 - 9983 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702531382.0, "order_id": "HummingbotSLKUD60c7176aabe8aed184d098c22", "exchange_order_id": "437ddf47e6afea32c18a15758c015f27bca0e0e2e62df33fe7906d17eccebe9", "event_name": "OrderCancelledEvent", "event_source": "dydx_perpetual"}
2023-12-14 13:23:02,182 - 9983 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order HummingbotSLKUD60c7176aabe8aed184d098c22.
2023-12-14 13:23:02,483 - 9983 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702531382.0, "order_id": "HummingbotSLKUD60c7176aabe6fed184d098c22", "exchange_order_id": "1f73be6e95dfc2db0699e088ba08b4c0b679bfae214dc86a30dc9df3fff2acb", "event_name": "OrderCancelledEvent", "event_source": "dydx_perpetual"}
```
Going through the logs from the issue, these are my observations:
1. 4 orders are created, but only 1 of them has `exchange_order_id` in the creation event (SELL HummingbotSLKUD60c7176aabe6fed184d098c22)
2. Both the buy orders are failed because of no exchange_order_id. https://github.com/hummingbot/hummingbot/blob/30f134577ced692a1cf303d5fc648f37818bb43c/hummingbot/connector/derivative/dydx_perpetual/dydx_perpetual_derivative.py#L679-L687
3. The second SELL order which got cancelled (HummingbotSLKUD60c7176aabe8aed184d098c22) has  `exchange_order_id` in the cancellation event

**Comment by nikspz** [comment]
Closing this PR since it's changing perpetualMM strategy files, (the fix should be done to dYdX connector files)

The fix for the issue / issue recheck is pending till dydx upgrade to v4 https://github.com/hummingbot/hummingbot/issues/6897

**Pull request closed without merging**
