### PR TITLE
(fix) handle status code 503 and server overloaded error

### PR DESCRIPTION
**Pull request by cardosofede**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR solves the issue #6033 for Binance and Binance Perpetual.

**Tests performed by the developer**:
Unit test and run a PMM strategy

**Tips for QA testing**:
Run a long term bot in Binance Perpetuals Testnet with the simple or advanced directional strategy example

### CODE REVIEW

**Comment by nikspz** [comment]
Tests performed:
- Cloned and installed fix branch
- `Failed to start script` simple or advanced directional strategy `using` binance perpetual `testnet`
- Ran longterm bot 2 times using `binance perpetual (live)` and `advanced directional strategy`
- Reviewed the `logs` of advanced directional strategy, there's `no error with status 503`, no server overloaded error, however have received 

`Error executing request POST /order. HTTP status is 400. Error: {"code":-2022,"msg":"ReduceOnly Order is rejected."}`
and 
`Error executing request DELETE /order. HTTP status is 400. Error: {"code":-2011,"msg":"Unknown order sent."}`
 
- Ran longterm bot using `Perpetual Market making` and binance perpetual `testnet`
- Catched 503 error `Error executing request DELETE /order. HTTP status is 503. Error: {"timestamp":1677838680041,"path":"/fapi/v1/order","msg":"Unknown error, please check your request or try again later."}`

Steps to reproduce:
Clone and install fix branch
Ran longterm bot using `Perpetual Market making` and binance perpetual `testnet`
Review the logs

Actual:
```
2023-03-03 10:17:49 Created SELL and BUY orders to OPEN
2023-03-03 10:17:53 SELL order to OPEN filled
2023-03-03 10:17:54 Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:17:54,001 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:17:54,001 - 1015998 - Creating 1 LIMIT buy to CLOSE position.
2023-03-03 10:17:55,000 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:17:56,001 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:17:57,001 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:17:58,001 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:17:59,001 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:18:00,001 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:18:00,077 - Failed to Cancel BUY OPEN order (HTTP status is 503. "msg":"Unknown error, please check your request or try again later.)
2023-03-03 10:18:01,000 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:18:02,001 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:18:03,000 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:18:04,001 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:18:05,001 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:18:06,001 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:18:07,000 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:18:08,000 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:18:09,001 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:18:10,001 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:18:11,001 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:18:12,001 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:18:13,000 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:18:14,000 - 1015998 - Bot trying to Cancel BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9
2023-03-03 10:18:14,282 - 1015998 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1677838694.0, "order_id": "x-3QreWesyBBCUT5f5fc41db32c138f9", "exchange_order_id": "3296967598", "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2023-03-03 10:18:14,283 - 1015998 - Successfully canceled BUY OPEN order x-3QreWesyBBCUT5f5fc41db32c138f9.
2023-03-03 10:18:14,322 - 1015998 - The BUY order to CLOSE  has been filled.
```


```
2023-03-03 10:17:49,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (BTC-USDT) Creating 1 LIMIT bid orders at (Size, Price): ['0.001 BTC, 22515.4 USDT'] to OPEN position.
2023-03-03 10:17:49,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (BTC-USDT) Creating 1  LIMIT ask orders at (Size, Price): ['0.001 BTC, 22605.6 USDT'] to OPEN position.
2023-03-03 10:17:49,080 - 1015998 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order x-3QreWesyBBCUT5f5fc41db32c138f9 for 0.001 to OPEN a BTC-USDT position.
2023-03-03 10:17:49,089 - 1015998 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1677838669.0, "type": "OrderType.LIMIT", "trading_pair": "BTC-USDT", "amount": "0.001", "price": "22515.40", "order_id": "x-3QreWesyBBCUT5f5fc41db32c138f9", "creation_timestamp": 1677838669.0, "exchange_order_id": "3296967598", "leverage": 1, "position": "OPEN", "event_name": "BuyOrderCreatedEvent", "event_source": "binance_perpetual"}
2023-03-03 10:17:49,132 - 1015998 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order x-3QreWesySBCUT5f5fc41db33b738f9 for 0.001 to OPEN a BTC-USDT position.
2023-03-03 10:17:49,141 - 1015998 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1677838669.0, "type": "OrderType.LIMIT", "trading_pair": "BTC-USDT", "amount": "0.001", "price": "22605.60", "order_id": "x-3QreWesySBCUT5f5fc41db33b738f9", "creation_timestamp": 1677838669.0, "exchange_order_id": "3296967600", "leverage": 1, "position": "OPEN", "event_name": "SellOrderCreatedEvent", "event_source": "binance_perpetual"}
2023-03-03 10:17:53,331 - 1015998 - hummingbot.connector.client_order_tracker - INFO - The SELL order x-3QreWesySBCUT5f5fc41db33b738f9 amounting to 0.001/0.001 BTC has been filled.
2023-03-03 10:17:53,331 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (BTC-USDT) Maker sell order of 0.001 BTC filled. [clock=2023-03-03 10:17:53+00:00]
2023-03-03 10:17:53,348 - 1015998 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1677838673.0, "order_id": "x-3QreWesySBCUT5f5fc41db33b738f9", "trading_pair": "BTC-USDT", "trade_type": "TradeType.SELL", "order_type": "OrderType.LIMIT", "price": "22605.60", "amount": "0.001", "trade_fee": {"percent": "0", "percent_token": "USDT", "flat_fees": [{"token": "USDT", "amount": "0.00452112"}]}, "exchange_trade_id": "253282165", "exchange_order_id": "3296967600", "leverage": 1, "position": "OPEN", "event_name": "OrderFilledEvent", "event_source": "binance_perpetual"}
2023-03-03 10:17:53,349 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (BTC-USDT) Maker sell order x-3QreWesySBCUT5f5fc41db33b738f9 (0.001 BTC @ 22605.60 USDT) has been completely filled. [clock=2023-03-03 10:17:53+00:00]
2023-03-03 10:17:53,358 - 1015998 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1677838673.0, "order_id": "x-3QreWesySBCUT5f5fc41db33b738f9", "base_asset": "BTC", "quote_asset": "USDT", "base_asset_amount": "0.001", "quote_asset_amount": "22.60560", "order_type": "OrderType.LIMIT", "exchange_order_id": "3296967600", "event_name": "SellOrderCompletedEvent", "event_source": "binance_perpetual"}
2023-03-03 10:17:53,358 - 1015998 - hummingbot.connector.client_order_tracker - INFO - SELL order x-3QreWesySBCUT5f5fc41db33b738f9 completely filled.
2023-03-03 10:17:54,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (BTC-USDT) Canceling the limit order x-3QreWesyBBCUT5f5fc41db32c138f9. [clock=2023-03-03 10:17:54+00:00]
2023-03-03 10:17:54,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:17:54,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (BTC-USDT) Creating 1 LIMIT bid orders at (Size, Price): ['0.001 BTC, 22560.3 USDT'] to CLOSE position.
2023-03-03 10:17:55,000 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:17:56,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:17:57,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:17:58,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:17:59,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:18:00,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:18:00,077 - 1015998 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - ERROR - Failed to cancel order x-3QreWesyBBCUT5f5fc41db32c138f9
Traceback (most recent call last):
  File "/home/ubuntu/6123-bin503/hummingbot/connector/exchange_py_base.py", line 551, in _execute_order_cancel
    cancelled = await self._execute_order_cancel_and_process_update(order=order)
  File "/home/ubuntu/6123-bin503/hummingbot/connector/exchange_py_base.py", line 567, in _execute_order_cancel_and_process_update
    cancelled = await self._place_cancel(order.client_order_id, order)
  File "/home/ubuntu/6123-bin503/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 209, in _place_cancel
    cancel_result = await self._api_delete(
  File "/home/ubuntu/6123-bin503/hummingbot/connector/exchange_py_base.py", line 899, in _api_delete
    return await self._api_request(*args, **kwargs)
  File "/home/ubuntu/6123-bin503/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 826, in _api_request
    raise IOError(f"Error executing request {method.name} {path_url}. "
OSError: Error executing request DELETE /order. HTTP status is 503. Error: {"timestamp":1677838680041,"path":"/fapi/v1/order","msg":"Unknown error, please check your request or try again later."}
2023-03-03 10:18:00,119 - 1015998 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order x-3QreWesyBBCUT5f5fc4227803238f9 for 0.001 to CLOSE a BTC-USDT position.
2023-03-03 10:18:00,128 - 1015998 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1677838680.0, "type": "OrderType.LIMIT", "trading_pair": "BTC-USDT", "amount": "0.001", "price": "22560.30", "order_id": "x-3QreWesyBBCUT5f5fc4227803238f9", "creation_timestamp": 1677838674.0, "exchange_order_id": "UNKNOWN", "leverage": 1, "position": "CLOSE", "event_name": "BuyOrderCreatedEvent", "event_source": "binance_perpetual"}
2023-03-03 10:18:01,000 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:18:02,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:18:03,000 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:18:04,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:18:05,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:18:06,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:18:07,000 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:18:08,000 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:18:09,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:18:10,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:18:11,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:18:12,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:18:13,000 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:18:14,000 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Initiated cancelation of buy order x-3QreWesyBBCUT5f5fc41db32c138f9 in favour of take profit order.
2023-03-03 10:18:14,282 - 1015998 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1677838694.0, "order_id": "x-3QreWesyBBCUT5f5fc41db32c138f9", "exchange_order_id": "3296967598", "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2023-03-03 10:18:14,283 - 1015998 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-3QreWesyBBCUT5f5fc41db32c138f9.
2023-03-03 10:18:14,322 - 1015998 - hummingbot.connector.client_order_tracker - INFO - The BUY order x-3QreWesyBBCUT5f5fc4227803238f9 amounting to 0.001/0.001 BTC has been filled.
2023-03-03 10:18:14,323 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (BTC-USDT) Maker buy order of 0.001 BTC filled. [clock=2023-03-03 10:18:14+00:00]
2023-03-03 10:18:14,340 - 1015998 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1677838694.0, "order_id": "x-3QreWesyBBCUT5f5fc4227803238f9", "trading_pair": "BTC-USDT", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT", "price": "22560.30", "amount": "0.001", "trade_fee": {"percent": "0", "percent_token": "USDT", "flat_fees": [{"token": "USDT", "amount": "0.00451206"}]}, "exchange_trade_id": "253282168", "exchange_order_id": "3296967617", "leverage": 1, "position": "CLOSE", "event_name": "OrderFilledEvent", "event_source": "binance_perpetual"}
2023-03-03 10:18:14,341 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (BTC-USDT) Maker buy order x-3QreWesyBBCUT5f5fc4227803238f9 (0.001 BTC @ 22560.30 USDT) has been completely filled. [clock=2023-03-03 10:18:14+00:00]
2023-03-03 10:18:14,350 - 1015998 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1677838694.0, "order_id": "x-3QreWesyBBCUT5f5fc4227803238f9", "base_asset": "BTC", "quote_asset": "USDT", "base_asset_amount": "0.001", "quote_asset_amount": "22.56030", "order_type": "OrderType.LIMIT", "exchange_order_id": "UNKNOWN", "event_name": "BuyOrderCompletedEvent", "event_source": "binance_perpetual"}
2023-03-03 10:18:14,350 - 1015998 - hummingbot.connector.client_order_tracker - INFO - BUY order x-3QreWesyBBCUT5f5fc4227803238f9 completely filled.
2023-03-03 10:19:15,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (BTC-USDT) Creating 1 LIMIT bid orders at (Size, Price): ['0.001 BTC, 22514.9 USDT'] to OPEN position.
2023-03-03 10:19:15,001 - 1015998 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (BTC-USDT) Creating 1  LIMIT ask orders at (Size, Price): ['0.001 BTC, 22605.1 USDT'] to OPEN position.

```
[6123.zip](https://github.com/hummingbot/hummingbot/files/10881524/6123.zip)
[Perpetual MM testnet.zip](https://github.com/hummingbot/hummingbot/files/10881531/Perpetual.MM.testnet.zip)

**Comment by cardosofede** [comment]
@nikspz nice!
Seems like it's working as expected since this PR is addressing the error 503 but just for creating orders.
We can let the bot run for 1 day and search if we have any ERROR 503 when Creating orders. If not is good to go.

**Review by nikspz — APPROVED** [review]
Tests performed:

- Cloned and installed fix branch
- Ran longterm bot 2 times using binance perpetual (live) and advanced directional strategy
- Ran longterm bot using Perpetual Market making and binance perpetual testnet
- Ran longterm bot using Perpetual Market making and binance perpetual live
- Reviewed no 503 error messages showed on order creation

**Comment by nikspz** [comment]
In behalf of Foundation team we merged this PR to development for the upcoming Hummingbot version 1.14.0

**Pull request merged**
