### PR TITLE
Feat/ Revamp hedge

### PR DESCRIPTION
**Pull request by leastchaos**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Revamp of the current hedge strategy
1. Cython → Python: Simplified code for easier improvements in the future.
2. One exchange → Multiple Exchange: Allow hedging of multiple assets at multiple exchanges at the same time
3. Hedge by amount → Hedge by amount or value: Allow hedge based on the current asset value in quote asset.
4. Remove restriction on spot/perp on both maker and taker: Able to select both spot and perpetual for both monitored market and hedge market
5. Added fixed offset : Allow maintaining of a fixed net amount of asset amount/value.

All expected functionality of the strategy are fully implemented although there are some expected issue which is not within the control of this strategy.

If there is any issue in using this strategy, feel free to report the issue under this pr or contact me on discord.

More details on https://hummingbot.discourse.group/t/hip-revamp-hedge-strategy/176/5
**Tests performed by the developer**:

**Tips for QA testing**:
Expected issues:

- ~binance_perpetual as hedge market will cause excessive selling/buying: require https://github.com/hummingbot/hummingbot/issues/5076  to be fixed~
- Setting more than 10 markets is not allowed due to https://github.com/hummingbot/hummingbot/issues/5545
- gate io cannot be used due to total balance delay bug
- potential issue with dydx

### CODE REVIEW

**Comment by nikspz** [comment]
@leastchaos Could you please check tests that's failing? Thank you
https://github.com/hummingbot/hummingbot/actions/runs/3587531756/jobs/6037992895

**Comment by rapcmia** [comment]
PR update:
- Test latest commit `91b1a1f`
- Setup simple Hedge strategy based on new parameters
- Set hedge_connector as derivative connector 
- When creating config, hedge strategy prompts user to setup connectors_0 to connector_4
- Setup is based on test_config.yml file while using binance_perpetual and binance
- Ran start command
   - Getting prompt below about `BinancePerpetualDerivative object at... is set to false`
   image
   - Another is that `it does not work if there is a position open` when the atm we dont have any OPEN position on the perp connector 
   - While this is observed on the client, the bot managed to have an order fill on perp connector create a position on ONEWAY mode 
   - Position retrieval works as expected
   - Hedge order cadindate and adjust order candidate has been observed 
   - Left longterm bot run for ~2hrs did not notice any unexpected errors. 
   
 Hi @leastchaos can you confirm if its expected for `hedge_connector` parameter that it also displays spot connectors on the autocomplete list? If yes the I assume this can be good to be approved. 
 
 Would also some  fixing the failed GitHUb CI:
image

**Comment by leastchaos** [comment]
> PR update:
> 
> * Test latest commit `91b1a1f`
> * Setup simple Hedge strategy based on new parameters
> * Set hedge_connector as derivative connector
> * When creating config, hedge strategy prompts user to setup connectors_0 to connector_4
> * Setup is based on test_config.yml file while using binance_perpetual and binance
> * Ran start command
>   
>   * Getting prompt below about `BinancePerpetualDerivative object at... is set to false`
>     image
>   * Another is that `it does not work if there is a position open` when the atm we dont have any OPEN position on the perp connector
>   * While this is observed on the client, the bot managed to have an order fill on perp connector create a position on ONEWAY mode
>   * Position retrieval works as expected
>   * Hedge order cadindate and adjust order candidate has been observed
>   * Left longterm bot run for ~2hrs did not notice any unexpected errors.
> 
> Hi @leastchaos can you confirm if its expected for `hedge_connector` parameter that it also displays spot connectors on the autocomplete list? If yes the I assume this can be good to be approved.
> 
> Would also some fixing the failed GitHUb CI: image

yes, its expected to show spot connector. 
i will fix it.

**Review by nikspz — APPROVED** [review]
```Test summary
- Overview on revamped Hedge strategy 
- Setup simple config based on sample template using Bybit perpetual
- Observed that value mode "True" would only support 1 market pair
    - "False" would enable multiple market feature to hedge
- `hedge_connector` autocomplete would show spot connector 
- Initial setup would prompt connector_0 to _4 (max of 5 connectors)
    - User has option to cancel or select `n`
- Monitor testbot with runtime of 1-2hrs
    - Note: bot increase memory usage after 1-2 hrs of usage
    - Observed that strategy checks other and update hedge candidates based on set `hedge_internval`
    - Position created successfully
    - Stop, exit and start the client again. Import strategy and position retrieved successfully 
    - Not able to get the opportunity to close position 

- Tests Performed on both source and docker build on MacOS and AWS Ubuntu instance

**Review by cardosofede — APPROVED** [review]
Nice PR! Good job.

**Comment by nikspz** [comment]
In behalf of Foundation team we merged this PR to development for the upcoming Hummingbot version 1.11.0

**Comment by carlitogetaladajr** [comment]
Hi @leastchaos, please fill up & submit the AML Policy Form via this link: https://forms.gle/fw89MmiCnwLizbHNA
This is a one-time process for each ETH Address used to receive HBOT bounty.

**Comment by leastchaos** [comment]
> Hi @leastchaos, please fill up & submit the AML Policy Form via this link: https://forms.gle/fw89MmiCnwLizbHNA This is a one-time process for each ETH Address used to receive HBOT bounty.

submitted. thanks.

**Comment by JeremyKono** [comment]
Hi @leastchaos, is there any docs needed for this PR? if so, please commit your changes here: https://github.com/hummingbot/hummingbot-site/pull/155

**Pull request merged**
