### PR TITLE
(fix) adds gas variables to amm_arb strategy

### PR DESCRIPTION
**Pull request by fengtality**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

- Adds `gas_token` and `gas_price`params to the `amm_arb` strategy
- This allows client to calculate transaction costs when user doesn't use the rate oracle

**Tests performed by the developer**:

- tested with the following configs:

```
connector_1: uniswap_ethereum_base
market_1: BAI-USDC
connector_2: mexc
market_2: BAI-USDT
order_amount: 3.0
rate_oracle_enabled: false

# What is the fixed_rate used to convert quote assets?
quote_conversion_rate: 1.0

# Specify a pool to swap with on the AMM connector
pool_id: ''

# What is the symbol of the token used to pay gas?
gas_token: ETH

# What is the gas price, expressed in the quote asset?
gas_price: 3500.0
```

- verified that error is thrown when `gas_token` is changed to `BNB`

### CODE REVIEW

**Comment by nikspz** [comment]
commit 3945a20

amm_arb strategy not asking for the gas price during the process of creation

Steps:
1. clone 7319 + gateway latest development
2. start instance
3. connect uniswap
4. create amm_arb strategy
5. check that `amm_arb strategy not asking for the gas price during the process of creation`
6. create strategy

Actual:
`amm_arb strategy not asking for the gas price during the process of creation`
default token is ETH and price is 3500

Expected:
user could set up during the strategy creation (depending on price and token)

image
image

**Comment by nikspz** [comment]
commit 3945a20

failed to start amm_arb strategy:  async_utils - Unhandled error in background task: 'RateOracle'

[logs_arb.log](https://github.com/user-attachments/files/17951199/logs_arb.log)
[arb.zip](https://github.com/user-attachments/files/17951206/arb.zip)


```
2024-11-28 17:46:26,503 - 1993347 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'RateOracle' object has no attribute 'add_rate'
Traceback (most recent call last):
  File "/home/hbot02/nikita/fix-add-gas7319/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hbot02/nikita/fix-add-gas7319/hummingbot/client/command/start_command.py", line 125, in start_check
    self._initialize_strategy(self.strategy_name)
  File "/home/hbot02/nikita/fix-add-gas7319/hummingbot/client/command/start_command.py", line 275, in _initialize_strategy
    start_strategy(self)
  File "/home/hbot02/nikita/fix-add-gas7319/hummingbot/strategy/amm_arb/start.py", line 84, in start
    rate_source.add_rate(f"{gas_token}-{quote_1}", Decimal(str(gas_price)))
AttributeError: 'RateOracle' object has no attribute 'add_rate'. Did you mean: 'get_rate'?
```

image

**Comment by fengtality** [comment]
it doesn't ask since rate oracle is enabled by default. users can disable
it by running config rate_oracled_enabled.

check the config map for the amm arb strategy. you should understand the
strategy defaults.

**Comment by nikspz** [comment]
> it doesn't ask since rate oracle is enabled by default. users can disable it by running config rate_oracled_enabled. check the config map for the amm arb strategy. you should understand the strategy defaults.


Failed to start using `config rate_oracled_enabled True` (async_utils - Unhandled error in background task: 'RateOracle')

Yes, could start using `config rate_oracled_enabled False`
image

**Comment by fengtality** [comment]
@nikspz I realized there was actually a bug in my code. I fixed it so it should work even when user enables or disables rate oracle.

**Comment by nikspz** [comment]
- Test performed:
    - Cloned and installed PR 7319 and latest development branch
    - created amm_arb using pancakeswap_bsc_mainnet
    - using rate oracle enabled True
        - started amm_arb successfully
        - order execution: ok
    - created amm_arb using BAI on uniswap ethereum base
    - added BAI to base tokens list
        - started using rate oracle enabled True
            - failed to start with data_types - The arbitrage proposal profitability could not be calculated due to a missing rate (BAI-BAI=1, USDC-USDT=None)
        - changed to using rate oracle enabled False
            - started successfully
            - order execution: ok

**Review by nikspz — APPROVED** [review]

**Review by cardosofede — APPROVED** [review]

**Pull request merged**
