### PR TITLE
Feat/Avellaneda - A multiplier to normalize the risk factor for all assets

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

The paper seems to contain another mistake. Fixing this will by itself lead to normalization of the risk_factor for all price ranges and across all assets. There was therefore in fact no need to implement any special feature. The risk_factor now is a fraction / percentage / multiplier of the asset's volatility (defined as a standard deviation), its typical value range is now between 0 and 100 for all assets, although it still remains unrestricted and it's possible to set it to even 1000000 if desired.

**Tests performed by the developer**:

- Ran tests with binance paper for multiple assets with various price ranges and equal settings, including risk_factors. In all cases the strategy was able to reach its target portfolio. I also plotted the important variables and visually verified the strategy behavior for all the tested assets.
- Ran unit tests

**Tips for QA testing**:

- As before with this strategy, the values in tests have to be taken as they are because they come from an estimation and measurement of a stochastic process.

### CODE REVIEW

**Comment by dennisocana** [comment]
Proposal created: https://snapshot.org/#/hbot-prp.eth/proposal/0xeb6423158e62986fa18ca0732a6358ca2bfe404c28b4766fd7bc81a3278c7280

**Review by Nullably — APPROVED** [review]
LGTM

**Comment by JeremyKono** [comment]
Hi @mhrvth, please resolve the conflicts in the PR so we can continue to review and merge. Thanks!

**Comment by rapcmia** [comment]
PR update: on-going test

**Review by rapcmia — APPROVED** [review]
Tested and confirmed working by QA
Test performed: 
- Setup Avellaneda strategy, ok 
- Setup multiple bots running on same or different markets and exchange 
- Set different risk factors (0.5, 1 and 1.5)
- Monitor bot performance and trade fill events 
- Spreads are adjusted accordingly depending on set inventory target
- Review long term bot logs, all ok

**Pull request merged**
