### PR TITLE
Feat/strategy_v2

### PR DESCRIPTION
**Pull request by cardosofede**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

In this PR I'm adding a level of abstraction to improve the user experience for people that want to develop directional and market making strategies.

**Introduce StrategiesV2**
Has two main components to make it scalable:
- ExecutorHandler: manage the smart components based on logic defined in the control_task.
- Controllers: provides the signals and conditions that the meta executor is using to take actions 

**Market Making Framework:**
- Market Making executor
- Market Making strategy base

**Directional Trading Framework:**
- Directional Trading executor
- Directional Trading strategy base

**Controllers introduced:**
- dman_v1.
- dman_v2.
- macd_bb_v1.

**Scripts**
- market_making_dman_v1.py --> uses dman_v1
- market_making_dman_v2.py --> uses dman_v2
- market_making_dman_composed.py --> combine the two strategies
- directional_trading_macd_bb_v1.py --> uses macd_bb_v1

Link to presentation: https://www.canva.com/design/DAFrPVxI3cQ/9i8M5dxFI9BS0lw5g8WVeg/edit?utm_content=DAFrPVxI3cQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Link to video: https://www.youtube.com/watch?v=GhvTaIWHqrU

Missing steps before we merge this in:
- Define what to do with old style directional strategies
- Generate scripts that let you run the same controller in multiple trading pairs

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update:
- Test `4eb2abf108f7`
- Observe script behavior when running multiple order levels with position_executors:
  - directional_strategy_widening_ema_bands.py ✅
  - directional_trading_macd_bb.py ✅
  - download_candles.py ✅
  - macd_bb_directional_strategy.py ✅
  - pmm_with_position_executor.py ✅ 
  - Build docker image ✅ 

Pending:
- market_making_dman_composed.py 
- market_making_dman_v2.py

**Comment by nikspz** [comment]
- market_making_dman_composed.py

Client failed to Close the position after stop command, got 
```
Market object for buy order is not in the whitelisted markets set.
```
Also got same for sell order using `market_making_dman_v1,py`
Could be an issue since default leverage is 25

Steps to reproduce:
1. Clone and install feature branch
2. start the market_making_dman_composed or market_making_dman_v1 script
3. run the script for a while and make sure you have an OPENED position
4. stop the bot and review logs

Actual:
Bot cancelled all opened orders
Position remain uncancelled



[logs_market_making_dman_composed2.log](https://github.com/hummingbot/hummingbot/files/12515846/logs_market_making_dman_composed2.log)
[market_making_dman_composed2 - Copy.txt](https://github.com/hummingbot/hummingbot/files/12515851/market_making_dman_composed2.-.Copy.txt)

```
2023-09-04 17:01:09,238 - 61411 - hummingbot.strategy.script_strategy_base - INFO - Creating HBAR-USDT buy order: price: 0.04840781102771029287686032709 amount: 144.2109600329625057045295250.
2023-09-04 17:01:09,239 - 61411 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing open order
2023-09-04 17:01:09,295 - 61411 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order x-3QreWesyBHRUT6048b74f1e4e5f7a8 for 144 to OPEN a HBAR-USDT position.
2023-09-04 17:01:09,295 - 61411 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Open Order Created
2023-09-04 17:01:09,307 - 61411 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1693846869.0, "type": "OrderType.LIMIT", "trading_pair": "HBAR-USDT", "amount": "144", "price": "0.04840", "order_id": "x-3QreWesyBHRUT6048b74f1e4e5f7a8", "creation_timestamp": 1693846869.0, "exchange_order_id": "3789645960", "leverage": 25, "position": "OPEN", "event_name": "BuyOrderCreatedEvent", "event_source": "binance_perpetual"}
2023-09-04 17:02:08,516 - 61411 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2023-09-04 17:02:08,646 - 61411 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1693846928.0, "order_id": "x-3QreWesySHRUT6048b198ea47ff7a8", "exchange_order_id": "3789616452", "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2023-09-04 17:02:08,647 - 61411 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-3QreWesySHRUT6048b198ea47ff7a8.
2023-09-04 17:02:08,675 - 61411 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1693846928.0, "order_id": "x-3QreWesySHRUT6048b2c54144af7a8", "exchange_order_id": "3789623061", "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2023-09-04 17:02:08,676 - 61411 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-3QreWesySHRUT6048b2c54144af7a8.
2023-09-04 17:02:08,685 - 61411 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1693846928.0, "order_id": "x-3QreWesyBHRUT6048b3da58333f7a8", "exchange_order_id": "3789628382", "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2023-09-04 17:02:08,686 - 61411 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-3QreWesyBHRUT6048b3da58333f7a8.
2023-09-04 17:02:08,693 - 61411 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1693846928.0, "order_id": "x-3QreWesyBHRUT6048b415c2a31f7a8", "exchange_order_id": "3789629483", "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2023-09-04 17:02:08,694 - 61411 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-3QreWesyBHRUT6048b415c2a31f7a8.
2023-09-04 17:02:08,700 - 61411 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1693846928.0, "order_id": "x-3QreWesyBHRUT6048b54f5ffe6f7a8", "exchange_order_id": "3789635885", "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2023-09-04 17:02:08,701 - 61411 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-3QreWesyBHRUT6048b54f5ffe6f7a8.
2023-09-04 17:02:08,708 - 61411 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1693846928.0, "order_id": "x-3QreWesySHRUT6048b5505ee06f7a8", "exchange_order_id": "3789635908", "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2023-09-04 17:02:08,708 - 61411 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-3QreWesySHRUT6048b5505ee06f7a8.
2023-09-04 17:02:08,714 - 61411 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1693846928.0, "order_id": "x-3QreWesySHRUT6048b55251486f7a8", "exchange_order_id": "3789635947", "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2023-09-04 17:02:08,715 - 61411 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-3QreWesySHRUT6048b55251486f7a8.
2023-09-04 17:02:08,723 - 61411 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1693846928.0, "order_id": "x-3QreWesyBHRUT6048b55817bb6f7a8", "exchange_order_id": "3789636011", "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2023-09-04 17:02:08,724 - 61411 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-3QreWesyBHRUT6048b55817bb6f7a8.
2023-09-04 17:02:08,731 - 61411 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1693846928.0, "order_id": "x-3QreWesyBHRUT6048b72f79b79f7a8", "exchange_order_id": "3789644962", "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2023-09-04 17:02:08,731 - 61411 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-3QreWesyBHRUT6048b72f79b79f7a8.
2023-09-04 17:02:08,739 - 61411 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1693846928.0, "order_id": "x-3QreWesyBHRUT6048b74f1e4e5f7a8", "exchange_order_id": "3789645960", "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2023-09-04 17:02:08,739 - 61411 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-3QreWesyBHRUT6048b74f1e4e5f7a8.
2023-09-04 17:02:08,804 - 61411 - hummingbot.strategy.script_strategy_base - INFO - Creating HBAR-USDT buy order: price: 0.048525 amount: 310.
2023-09-04 17:02:08,805 - 61411 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Market object for buy order is not in the whitelisted markets set.
Traceback (most recent call last):
  File "/home/nikita/fede6520/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/nikita/fede6520/hummingbot/smart_components/strategy_frameworks/executor_handler_base.py", line 100, in control_loop
    self.on_stop()
  File "/home/nikita/fede6520/hummingbot/smart_components/strategy_frameworks/market_making/market_making_executor_handler.py", line 17, in on_stop
    self.close_open_positions(connector_name=self.controller.config.exchange, trading_pair=self.controller.config.trading_pair)
  File "/home/nikita/fede6520/hummingbot/smart_components/strategy_frameworks/executor_handler_base.py", line 113, in close_open_positions
    action(connector_name=connector_name,
  File "/home/nikita/fede6520/hummingbot/strategy/script_strategy_base.py", line 93, in buy
    return self.buy_with_specific_market(market_pair, amount, order_type, price, position_action=position_action)
  File "hummingbot/strategy/strategy_base.pyx", line 505, in hummingbot.strategy.strategy_base.StrategyBase.buy_with_specific_market
    return self.c_buy_with_specific_market(market_trading_pair_tuple, amount,
  File "hummingbot/strategy/strategy_base.pyx", line 528, in hummingbot.strategy.strategy_base.StrategyBase.c_buy_with_specific_market
    raise ValueError(f"Market object for buy order is not in the whitelisted markets set.")
ValueError: Market object for buy order is not in the whitelisted markets set.
2023-09-04 17:02:08,809 - 61411 - hummingbot.strategy.script_strategy_base - INFO - Creating HBAR-USDT buy order: price: 0.048525 amount: 310.
2023-09-04 17:02:08,810 - 61411 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Market object for buy order is not in the whitelisted markets set.
Traceback (most recent call last):
  File "/home/nikita/fede6520/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/nikita/fede6520/hummingbot/smart_components/strategy_frameworks/executor_handler_base.py", line 100, in control_loop
    self.on_stop()
  File "/home/nikita/fede6520/hummingbot/smart_components/strategy_frameworks/market_making/market_making_executor_handler.py", line 17, in on_stop
    self.close_open_positions(connector_name=self.controller.config.exchange, trading_pair=self.controller.config.trading_pair)
  File "/home/nikita/fede6520/hummingbot/smart_components/strategy_frameworks/executor_handler_base.py", line 113, in close_open_positions
    action(connector_name=connector_name,
  File "/home/nikita/fede6520/hummingbot/strategy/script_strategy_base.py", line 93, in buy
    return self.buy_with_specific_market(market_pair, amount, order_type, price, position_action=position_action)
  File "hummingbot/strategy/strategy_base.pyx", line 505, in hummingbot.strategy.strategy_base.StrategyBase.buy_with_specific_market
    return self.c_buy_with_specific_market(market_trading_pair_tuple, amount,
  File "hummingbot/strategy/strategy_base.pyx", line 528, in hummingbot.strategy.strategy_base.StrategyBase.c_buy_with_specific_market
    raise ValueError(f"Market object for buy order is not in the whitelisted markets set.")
ValueError: Market object for buy order is not in the whitelisted markets set.
```

market making dman composed2, failed to CLOSE position left unclosed after stop command  error
image
image

**Comment by cardosofede** [comment]
@rapcmia @nikspz @david-hummingbot @fengtality this is ready to test!!

**Comment by rapcmia** [comment]
Test latest commit `7f11bad1a5499d0a6d03be25e39b7ca7db4ef939`
- Orders are recreated on the set order_refresh_time
- When orders are filled, open position successfully
- When stopped while there is a position opened from the script
   image
   - Still returns `Returns an unhandled error in background task: market object for buy orrder isn ot in the whitelisted markets set`
     - Crosschecking this on development branch
        - Opened a position then stop ✅
        - Opened a position an switch to 6520 then start/stop script, not getting the error ✅
        - Test on position execution scripts, not possible since position will close when stop command is called ✅ 
        - Error only happens on the PR 

---

Modified script to run two market pairs `{XRP-USDT, LINK-USDT}` using `market_making_dmanv2`
- Order create and cancellation ✅ 
- Position created when successful fill trade however:
  image
     - Observed on the screenshot the error again when stopping the script with an open position
     - Two unhandled error occurred due to two different market pairs is open on the exchange 
    ```
    023-09-19 20:38:55,721 - 19047 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
    2023-09-19 20:38:55,972 - 19047 - hummingbot.strategy.script_strategy_base - INFO - Creating XRP-USDT sell order: price: 0.50805 amount: 47.0.
    2023-09-19 20:38:55,974 - 19047 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Market object for sell order is not in the whitelisted markets set.
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/6520/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
        return await c
      File "/Users/rapcomia/github/hummingbot/6520/hummingbot/smart_components/strategy_frameworks/executor_handler_base.py", line 100, in control_loop
        self.on_stop()
      File "/Users/rapcomia/github/hummingbot/6520/hummingbot/smart_components/strategy_frameworks/market_making/market_making_executor_handler.py", line 17, in on_stop
        self.close_open_positions(connector_name=self.controller.config.exchange, trading_pair=self.controller.config.trading_pair)
      File "/Users/rapcomia/github/hummingbot/6520/hummingbot/smart_components/strategy_frameworks/executor_handler_base.py", line 113, in close_open_positions
        action(connector_name=connector_name,
      File "/Users/rapcomia/github/hummingbot/6520/hummingbot/strategy/script_strategy_base.py", line 116, in sell
        return self.sell_with_specific_market(market_pair, amount, order_type, price, position_action=position_action)
      File "hummingbot/strategy/strategy_base.pyx", line 550, in hummingbot.strategy.strategy_base.StrategyBase.sell_with_specific_market
        return self.c_sell_with_specific_market(market_trading_pair_tuple, amount,
      File "hummingbot/strategy/strategy_base.pyx", line 573, in hummingbot.strategy.strategy_base.StrategyBase.c_sell_with_specific_market
        raise ValueError(f"Market object for sell order is not in the whitelisted markets set.")
    ValueError: Market object for sell order is not in the whitelisted markets set.
    2023-09-19 20:38:55,977 - 19047 - hummingbot.strategy.script_strategy_base - INFO - Creating LINK-USDT sell order: price: 6.7335 amount: 3.54.
    2023-09-19 20:38:55,977 - 19047 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Market object for sell order is not in the whitelisted markets set.
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/6520/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
        return await c
      File "/Users/rapcomia/github/hummingbot/6520/hummingbot/smart_components/strategy_frameworks/executor_handler_base.py", line 100, in control_loop
        self.on_stop()
      File "/Users/rapcomia/github/hummingbot/6520/hummingbot/smart_components/strategy_frameworks/market_making/market_making_executor_handler.py", line 17, in on_stop
        self.close_open_positions(connector_name=self.controller.config.exchange, trading_pair=self.controller.config.trading_pair)
      File "/Users/rapcomia/github/hummingbot/6520/hummingbot/smart_components/strategy_frameworks/executor_handler_base.py", line 113, in close_open_positions
        action(connector_name=connector_name,
      File "/Users/rapcomia/github/hummingbot/6520/hummingbot/strategy/script_strategy_base.py", line 116, in sell
        return self.sell_with_specific_market(market_pair, amount, order_type, price, position_action=position_action)
      File "hummingbot/strategy/strategy_base.pyx", line 550, in hummingbot.strategy.strategy_base.StrategyBase.sell_with_specific_market
        return self.c_sell_with_specific_market(market_trading_pair_tuple, amount,
      File "hummingbot/strategy/strategy_base.pyx", line 573, in hummingbot.strategy.strategy_base.StrategyBase.c_sell_with_specific_market
        raise ValueError(f"Market object for sell order is not in the whitelisted markets set.")
    ValueError: Market object for sell order is not in the whitelisted markets set.
    ```

Steps to reproduce:
1. Run any script that supports dmanv2 or dmanv1
2. When a position is opened, stop the script and observe log panel

[logs_test01.log](https://github.com/hummingbot/hummingbot/files/12659999/logs_test01.log)

---

When starting the hummingbot client on this PR
image

- When starting the this commit `7f11bad1a5499d0a6`, getting the error on both platforms osx64 and arm64 on mbp
- Tried to uninstall and remove hummingbot env still getting the warning
- Checking the latest development branch not able to reproduce
- No log file to support warning

**Comment by cardosofede** [comment]
@rapcmia will fix today, btw are you sure that the positions that were open are related to the same trading pair that you were trading?

**Comment by nikspz** [comment]
commit 7f11bad
I recorded the video of the issue here:

Bot failed to close the position after stop command
https://www.loom.com/share/2af2f1ee5f4d4089a49651d64afe4559

**Comment by nikspz** [comment]
The same issue on the diffrent account:

0. (no position on other pairs/script pair opened before the start)
1. Start the script
2. Position opened by the bot
3. stop command
4. Bot failed to close the position after stop command 

https://www.loom.com/share/f2d0cbc5657e470c9c6e3e7cedea0945

log file:
[logs_market_making_dman_v4.log](https://github.com/hummingbot/hummingbot/files/12670382/logs_market_making_dman_v4.log)

**Comment by nikspz** [comment]
Commit ab984ee

0. (no position on other pairs/script pair opened before the start)
1. Start the script
2.  XRP-USDT Position opened by the bot
3. stop command

Actual:
position not CLOSED after stop command
No errors showing

Expected: 
Closing the OPENED XRP-USDT position

6520 Position not closed

**Comment by rapcmia** [comment]
Test latest commit `ab984ee8a89ac9`
- Position opened on the script wont close after `stop` command

https://github.com/hummingbot/hummingbot/assets/73840223/0d50d2ca-b71a-4ba0-ac86-5570f5d9c1a1


---

> When starting the hummingbot client on this PR image
> 
> * When starting the this commit `7f11bad1a5499d0a6`, getting the error on both platforms osx64 and arm64 on mbp

- This is fixed

---

> When stopped while there is a position opened from the script
> image
> * Still returns `Returns an unhandled error in background task: market object for buy orrder isn ot in the whitelisted markets set`

- Error when `stop` command is executed and a position is opened on a script does not occur, fixed on this commit

**Review by rapcmia — APPROVED** [review]
Test summary:
- Overview of the market_maker_base
- Ran tests on following scripts:
	- market_maker_dman_v1
  - market_maker_dman_v2
  - market_making_multiple_controllers
  - Other updated scripts 
- Ran tests using binance perp on single and multiple markets 
- Modifed scripts to run multiple market pairs
- Orders are refreshed at set order_refresh_time
- Multiple orders matched on client and exchange 
- Position successfully open and close
- Build docker image

**Review by nikspz — APPROVED** [review]

**Comment by rapcmia** [comment]
Merged to development and will be part of `version 1.20.0`

**Pull request merged**
