### PR TITLE
fix/remove duplicated property in PMM strategy

### PR DESCRIPTION
**Pull request by takuya29**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
I found that property and setter of `filled_order_delay` are doubly defined in `pure_market_making.pyx`.

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by phbrgnomo** [comment]
Hello @29Takuya 

The Hummingbot Foundation just started the governance process for the community to approve or reject Pull Requests through **Pull Request Proposals**.

For more information about how PRP votes work, check this page: https://hummingbot.org/governance/prp/

We want to know if you still have interest in having your Pull Request merged into the main codebase.

If so, please check the following on your Pull Request for our team to be able to open it for community voting:

- Your Pull Request is targeted to the `development` branch
- Your branch is up to date with the current `development` branch
- All GitHub checks have passed
- There is no merging conflicts

If you have any questions or need any help, feel free to reach us out on the #dev-general channel on our Discord (https://discord.gg/HAgZ79nzU4)

----
If you have no interest in merging this PR to our code-base or don't reply to this comment in 30 days, the Foundation team will close this PR.

You can still create a new PR any time you want!

Thank you for contributing to Hummingbot Client!

**Comment by 29Takuya** [comment]
Hi @phbrgnomo,

Thank you for letting me know about the new governance process!

I confirmed that three out of four points are satisfied:
- [x] Your Pull Request is targeted to the development branch
- [x] Your branch is up to date with the current development branch
- [ ] All GitHub checks have passed
- [x] There is no merging conflicts

It seems that GitHub checks don't run on this PR since I am a first-time contributor.
Could you approve this?

**Comment by phbrgnomo** [comment]
Since this was your first PR, i hade to manually start the tests. Check back later to see if all of them passed.

**Comment by 29Takuya** [comment]
Thank you! I confirmed that all checks have passed.

**Comment by 29Takuya** [comment]
@RobHBOT Sorry, not yet. Could you create it on my behalf?

**Comment by JeremyKono** [comment]
Hi @29Takuya, are you still willing to work on this PR?

**Comment by 29Takuya** [comment]
Hi @JeremyKono, I am willing to work on this. 
The latest `development` branch still has the same issue.

Would it be possible for you to share what I need to merge this PR?

**Comment by 29Takuya** [comment]
@cardosofede Thank you for your help!
I rebased with the latest `development` branch.

**Review by cardosofede — DISMISSED** [review]
LGTM

**Comment by nikspz** [comment]
Should update with latest dev branch changes and good to go

**Review by nikspz — APPROVED** [review]

**Review by nikspz — DISMISSED** [review]
Filled order delay not affected, need to update with latest dev branch and good to go

**Comment by 29Takuya** [comment]
@cardosofede @nikspz Thank you for your reviews! I updated this PR with the latest dev branch.

**Review by nikspz — APPROVED** [review]
Filled order delay not affected
LGTM

**Comment by nikspz** [comment]
In behalf of Foundation team we merged this PR to development for the upcoming Hummingbot version 1.12.0

**Pull request merged**
