### PR TITLE
fix/AroonOscillatorIndicator

### PR DESCRIPTION
**Pull request by tramchamploo**
So that indicator value ranges from 0 to 100 as is described.

### CODE REVIEW

**Review by mhrvth — DISMISSED** [review]
LGTM

-- Review submitted in representation of the Hummingbot Foundation Technical DAO

**Comment by cardosofede** [comment]
@tramchamploo please rebase the branch and we are going to review this pr

**Comment by tramchamploo** [comment]
So many conficts to resolve, I did a git reset to development branch and recommit with the stashed change. Do you have a better way doing this? Maybe cherrypick?

**Comment by mifeng** [comment]
> So many conficts to resolve, I did a git reset to development branch and recommit with the stashed change. Do you have a better way doing this? Maybe cherrypick?

Thanks - the PR looks clean now from the changed files!

**Pull request merged**
