### PR TITLE
fix/set codec to utf-8 when opening config files

### PR DESCRIPTION
**Pull request by JasonSPH**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
When running from source on Windows and the default encoding is not `utf-8`, the  error (similar to https://github.com/hummingbot/hummingbot/issues/5112) will happen:

> 2022-04-17 15:17:50,323 - 3564 - root - ERROR - Error loading configs. Your config file may be corrupt. 'gbk' codec can't decode byte 0xac in position 2829: illegal multibyte sequence
Traceback (most recent call last):
  File "\hummingbot\hummingbot\client\config\config_helpers.py", line 248, in load_yml_into_cm
    data = yaml_parser.load(stream) or {}
...
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 2829: illegal multibyte sequence

Set the encoding to always `utf-8` will solve this issue.

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by aarmoa** [comment]
@JasonSPH please remember to create the PRP (https://hummingbot.org/governance/proposals/prp/) and add a link here

**Comment by JasonSPH** [comment]
> @JasonSPH please remember to create the PRP (https://hummingbot.org/governance/proposals/prp/) and add a link here

PRP link:
https://snapshot.org/#/hbot-prp.eth/proposal/0x444bded1b57dd87785b9f0f46e03149865ab92053b80bc26260b65cd16f1f591

**Comment by JasonSPH** [comment]
@aarmoa Hi, the PRP has been voted as approved, please process to next steps.

**Review by aarmoa — COMMENTED** [review]
The changes look good to me.

-- Reviewed in representation of the Hummingbot Technical DAO

**Comment by rapcmia** [comment]
While waiting for the github validation fix, we tested by running the script and manual installation on Windows WSL and worked all ok.

**Review by cardosofede — APPROVED** [review]
Changes look good to me

**Comment by cardosofede** [comment]
Hi @JasonSPH, hope you're doing well. Could you rebase to development?

**Comment by JasonSPH** [comment]
> Hi @JasonSPH, hope you're doing well. Could you rebase to development?
@cardosofede Done.

**Review by rapcmia — APPROVED** [review]
Test performed
- Install branch successfully
- Tested using manual installation via Windows WSL and Ubuntu18LTS terminal
- Tested by modifying the installation scripts using this PR
- Run simple pure market making strategy, all ok
- Start, stop and import strategy, all ok

**Pull request merged**
