### PR TITLE
feat/add gateway balance

### PR DESCRIPTION
**Pull request by hbotdev8675309**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

- Removed display of DEX balances from balance command.
- Added a new gateway balance command that reports balances of connected wallets.

**Tests performed by the developer**:

- I connected several wallets to my Hummingbot instance after sending them small amounts of crypto on different chains. I then ran "gateway balance" and confirmed that all of the coins were displayed with the appropriate amount.

**Tips for QA testing**:

N/A

### CODE REVIEW

**Comment by hbotdev8675309** [comment]
This PR is for part 1 of this issue: https://github.com/hummingbot/hummingbot/issues/6395

**Comment by nikspz** [comment]
- Test performed:
    - Cloned and installed feature branch and
        - connected binance_perpetual only:
            - `gateway balance command displays `No existing gateway connection.` ✅
            - balance command displays binance_perpetual balance
        - connected uniswap arbitrum:
            - `gateway balance command displays uniswap arbitrum balance ✅
            - balance command displays binance_perpetual balance connected before ✅
            - gateway balance displayed correct amount after `gateway connector-tokens uniswap_ethereum_arbitrum USDC,USDC.e,WETH` ✅
            - connected uniswap mainnet: balance showed succesfully, delay getting balance for ethereum mainnet
            - connected dexalot: `failed to show balance` ❌ 
            
Steps: 
connect uniswap arbitrum, uniswap mainnet and dexalot avalanche
check `gateway balance`

Actual:
connected dexalot: `failed to show balance` ❌

gateway balance PR6598

[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/12789354/logs_hummingbot.log)

```
2023-10-03 06:01:14,984 - 1837429 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15888/chain/balances failed. See logs for more details.
2023-10-03 06:01:14,985 - 1837429 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Error on POST https://localhost:15888/chain/balances Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': 'Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="balanceOf(address)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (/home/nikita/gateway-dev/node_modules/@ethersproject/logger/lib/index.js:238:21)\n    at Logger.throwError (/home/nikita/gateway-dev/node_modules/@ethersproject/logger/lib/index.js:247:20)\n    at Interface.decodeFunctionResult (/home/nikita/gateway-dev/node_modules/@ethersproject/abi/lib/interface.js:388:23)\n    at Contract.<anonymous> (/home/nikita/gateway-dev/node_modules/@ethersproject/contracts/lib/index.js:395:56)\n    at step (/home/nikita/gateway-dev/node_modules/@ethersproject/contracts/lib/index.js:48:23)\n    at Object.next (/home/nikita/gateway-dev/node_modules/@ethersproject/contracts/lib/index.js:29:53)\n    at fulfilled (/home/nikita/gateway-dev/node_modules/@ethersproject/contracts/lib/index.js:20:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'}
Traceback (most recent call last):
  File "/home/nikita/gwbalance6598/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/nikita/gwbalance6598/hummingbot/client/command/gateway_command.py", line 424, in _gateway_balance
    token_balances: Dict[str, Any] = await self._get_gateway_instance().get_balances(
  File "/home/nikita/gwbalance6598/hummingbot/core/gateway/gateway_http_client.py", line 289, in get_balances
    return await self.api_request(
  File "/home/nikita/gwbalance6598/hummingbot/core/gateway/gateway_http_client.py", line 218, in api_request
    raise e
  File "/home/nikita/gwbalance6598/hummingbot/core/gateway/gateway_http_client.py", line 206, in api_request
    raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
ValueError: Error on POST https://localhost:15888/chain/balances Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': 'Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="balanceOf(address)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (/home/nikita/gateway-dev/node_modules/@ethersproject/logger/lib/index.js:238:21)\n    at Logger.throwError (/home/nikita/gateway-dev/node_modules/@ethersproject/logger/lib/index.js:247:20)\n    at Interface.decodeFunctionResult (/home/nikita/gateway-dev/node_modules/@ethersproject/abi/lib/interface.js:388:23)\n    at Contract.<anonymous> (/home/nikita/gateway-dev/node_modules/@ethersproject/contracts/lib/index.js:395:56)\n    at step (/home/nikita/gateway-dev/node_modules/@ethersproject/contracts/lib/index.js:48:23)\n    at Object.next (/home/nikita/gateway-dev/node_modules/@ethersproject/contracts/lib/index.js:29:53)\n    at fulfilled (/home/nikita/gateway-dev/node_modules/@ethersproject/contracts/lib/index.js:20:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'}
```

image

gateway balance PR6598

**Comment by hbotdev8675309** [comment]
> * Test performed:
>   
>   * Cloned and installed feature branch and
>     
>     * connected binance_perpetual only:
>       
>       * `gateway balance command displays `No existing gateway connection.` ✅
>       * balance command displays binance_perpetual balance
>     * connected uniswap arbitrum:
>       
>       * `gateway balance command displays uniswap arbitrum balance ✅
>       * balance command displays binance_perpetual balance connected before ✅
>       * gateway balance displayed correct amount after `gateway connector-tokens uniswap_ethereum_arbitrum USDC,USDC.e,WETH` ✅
>       * connected uniswap mainnet: balance showed succesfully, delay getting balance for ethereum mainnet
>       * connected dexalot: `failed to show balance` ❌
> 
> Steps: connect uniswap arbitrum, uniswap mainnet and dexalot avalanche check `gateway balance`
> 
> Actual: connected dexalot: `failed to show balance` ❌
> 
> gateway balance PR6598 [ gateway balance PR6598 ](https://user-images.githubusercontent.com/83953535/272168602-439245e5-bc4e-40a9-b293-a93979081ae9.gif) [ ](https://user-images.githubusercontent.com/83953535/272168602-439245e5-bc4e-40a9-b293-a93979081ae9.gif)
> 
> [logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/12789354/logs_hummingbot.log)
> 
> ```
> 2023-10-03 06:01:14,984 - 1837429 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15888/chain/balances failed. See logs for more details.
> 2023-10-03 06:01:14,985 - 1837429 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Error on POST https://localhost:15888/chain/balances Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': 'Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="balanceOf(address)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (/home/nikita/gateway-dev/node_modules/@ethersproject/logger/lib/index.js:238:21)\n    at Logger.throwError (/home/nikita/gateway-dev/node_modules/@ethersproject/logger/lib/index.js:247:20)\n    at Interface.decodeFunctionResult (/home/nikita/gateway-dev/node_modules/@ethersproject/abi/lib/interface.js:388:23)\n    at Contract.<anonymous> (/home/nikita/gateway-dev/node_modules/@ethersproject/contracts/lib/index.js:395:56)\n    at step (/home/nikita/gateway-dev/node_modules/@ethersproject/contracts/lib/index.js:48:23)\n    at Object.next (/home/nikita/gateway-dev/node_modules/@ethersproject/contracts/lib/index.js:29:53)\n    at fulfilled (/home/nikita/gateway-dev/node_modules/@ethersproject/contracts/lib/index.js:20:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'}
> Traceback (most recent call last):
>   File "/home/nikita/gwbalance6598/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
>     return await c
>   File "/home/nikita/gwbalance6598/hummingbot/client/command/gateway_command.py", line 424, in _gateway_balance
>     token_balances: Dict[str, Any] = await self._get_gateway_instance().get_balances(
>   File "/home/nikita/gwbalance6598/hummingbot/core/gateway/gateway_http_client.py", line 289, in get_balances
>     return await self.api_request(
>   File "/home/nikita/gwbalance6598/hummingbot/core/gateway/gateway_http_client.py", line 218, in api_request
>     raise e
>   File "/home/nikita/gwbalance6598/hummingbot/core/gateway/gateway_http_client.py", line 206, in api_request
>     raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
> ValueError: Error on POST https://localhost:15888/chain/balances Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': 'Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="balanceOf(address)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (/home/nikita/gateway-dev/node_modules/@ethersproject/logger/lib/index.js:238:21)\n    at Logger.throwError (/home/nikita/gateway-dev/node_modules/@ethersproject/logger/lib/index.js:247:20)\n    at Interface.decodeFunctionResult (/home/nikita/gateway-dev/node_modules/@ethersproject/abi/lib/interface.js:388:23)\n    at Contract.<anonymous> (/home/nikita/gateway-dev/node_modules/@ethersproject/contracts/lib/index.js:395:56)\n    at step (/home/nikita/gateway-dev/node_modules/@ethersproject/contracts/lib/index.js:48:23)\n    at Object.next (/home/nikita/gateway-dev/node_modules/@ethersproject/contracts/lib/index.js:29:53)\n    at fulfilled (/home/nikita/gateway-dev/node_modules/@ethersproject/contracts/lib/index.js:20:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'}
> ```
> 
> image
> 
> gateway balance PR6598 [ gateway balance PR6598 ](https://user-images.githubusercontent.com/83953535/272168707-29587d00-471f-472e-94fc-3b9c53a9d815.gif) [ ](https://user-images.githubusercontent.com/83953535/272168707-29587d00-471f-472e-94fc-3b9c53a9d815.gif)
> 
> On development was able check all 3 balances successfully
> 
> gateway balance development works VS PR6598 [ gateway balance development works VS PR6598 ](https://user-images.githubusercontent.com/83953535/272169731-f92c0486-dbc3-460f-93be-56cdc3b1716c.gif) [ ](https://user-images.githubusercontent.com/83953535/272169731-f92c0486-dbc3-460f-93be-56cdc3b1716c.gif)

Thank you for the detailed testing results! I will begin digging into this issue with dexalot immediately and will have new changes to review ASAP.

**Comment by rapcmia** [comment]
When running `balance` command on this PR, it seems that its still trying to run endpoints from gateway resulting to error like on the screenshot below when gateway is offline 

image

Below is a recording of Client behavior on this PR after `balance` command, maybe it should stop calling the balance endpoint and only works when using `gateway balance`:

https://github.com/hummingbot/hummingbot/assets/73840223/28519f03-f15c-4eb3-a925-64af1fe83117

Steps to reproduce:
1. Setup this PR with latest development gateway 
2. Connect multiple supported DEX connectors (uniswap on different layer2, tradejoe, pangolin, quickswap, dexalot, injective, etc...)
3. Run `balance` and `gateway balance` command, observe client behavior
4. Next, stop gateway connection and relaunch client.
5. Repeat step 3

[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/12812875/logs_hummingbot.log)

**Comment by hbotdev8675309** [comment]
@rapcmia Thank you for providing all of the detail on that, I will address this issue as well.

**Comment by hbotdev8675309** [comment]
Please assign these bounties to someone else. Thank you.

**Pull request closed without merging**
