### PR TITLE
feat/ Upgrade Crypto.com Connector

### PR DESCRIPTION
**Pull request by manibandi**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This is a PR(Draft) to solve #6023. Crypto.com Connector being upgraded to the latest version of Hummingbot using the latest Crypto.com API, being developed by @srirambandi and me.

**Tests performed by the developer**:

NA

**Tips for QA testing**:

NA

### CODE REVIEW

**Comment by nikspz** [comment]
hi @srirambandi, how's it going? Could you please add your updates here?

**Comment by srirambandi** [comment]
Hey @nikspz, finished with connector logic, added the commits here. About midway through unit tests. 

We were having difficulties getting api keys to test this ourselves, were getting stuck at our account verification(face verification failing). Can you help resolve this by providing us with any test keys?

Will add the unit tests by this weekend.

**Comment by bonez56** [comment]
> Hey @nikspz, finished with connector logic, added the commits here. About midway through unit tests.
> 
> We were having difficulties getting api keys to test this ourselves, were getting stuck at our account verification(face verification failing). Can you help resolve this by providing us with any test keys? EDIT: We will try the verification again today for api keys.
> 
> Will add the unit tests by this weekend.

If you still need api keys to test, I can help.

**Comment by srirambandi** [comment]
Hey @bonez56, yes that would help test this connector. Can you help? Here's my discord userid: srirambandi#9334

**Comment by bonez56** [comment]
> Hey @bonez56, yes that would help test this connector. Can you help? Here's my discord userid: srirambandi#9334

I have sent you a friend request on Discord.

**Comment by nikspz** [comment]
@srirambandi We had to force push development back to old commit, could you please resolve branch conflicts?

**Comment by srirambandi** [comment]
Okay sure, I’ll do it 🙌

**Comment by nikspz** [comment]
FYI: This PR will be closed since it's still on draft and not updated.
The bounty https://github.com/hummingbot/hummingbot/issues/6023 will be closed as well, the reason is Crypto.com connector not get 100K HBOT Votes in  https://snapshot.org/#/hbot.eth/proposal/0x231e942b5f23b406d409f2b12319891ab3c92605e367f75e56015061e905d56e and most likely will be excluded from the maintained connectors of HBF.

**Comment by nikspz** [comment]
Closing this PR since the bounty PR since developer's not being responsive / provided updates on the simple fix after the week and the PR is not ready after more than 2 month period of development. Crypto.com connector is currently removed from the list of maintained connectors (https://snapshot.org/#/hbot.eth/proposal/0x231e942b5f23b406d409f2b12319891ab3c92605e367f75e56015061e905d56e)

**Pull request closed without merging**
