### PR TITLE
feat/enable anonymous metrics in all branches hotfix master

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Refactor of the logic that collects anonymous trade volume metrics and sends the information to Hummingbot Foundation. The previous logic that associated metrics collection to processing the logs has been removed. The new logic associates the trades volume metrics collection directly to the connectors, and uses the events to gather trades (or order fills).
The configuration value `heartbeat_enabled` was renamed to `anonymized_metrics_enabled`.
The configuration value 'heartbeat_interval_min` was renamed to `anonymized_metrics_interval_min`.

**Tests performed by the developer**:
Added new unit tests.
Executed a Pure Market Making strategy connected to Binance spot. I validated that the metrics appeared correctly in Datadog dashboard for metric `filled_usdt_volume`

**Tips for QA testing**:
Check that metrics collection is active (`anonymized_metrics_enabled` should be configured with value True). The collection frequency can be increased by reducing the value of `anonymized_metrics_interval_min` (set it to 0.2 for example). You will need the value of the configuration `instance_id` to filter results in Datadog dashboard.

NOTE: This PR comes from https://github.com/CoinAlpha/hummingbot/pull/129. But the changes have been integrated into `master` branch for the Foundation to be able to apply the change as a hot fix into the production version.
The other PR created on top of the current `development` branch will be sent also to be merged in development as soon as the prerequisite (https://github.com/hummingbot/hummingbot/pull/5160) is merged. The PR to development branch will include all the cleanup that has been excluded from this PR (to reduce the number of changes applied directly to production).

### CODE REVIEW

**Comment by nikspz** [comment]
Upon checking,
Got `Unexpected error while retrieving rates` or `ERROR - Unhandled error in background task: [<class 'decimal.DivisionUndefined'>]` when checking balance issue on Win10 Docker. 

Env: Win10, Docker installation

Steps to reproduce
1. Cloning and installing 5173 branch
2. Create and run docker image on Win10 (or 'rate_oracle_source coingecko' AWS ubuntu)
3. Set up 'rate_oracle_source coingecko' or `rate_oracle_source binance`
4 .connect 3 or more exchanges (my example is crypto_com, digifinex, ftx)
5. Try to check `balance`

Actual:
Showing balance only for first exchange connected (alphabetically)
`Unexpected error while retrieving rates` or `ERROR - Unhandled error in background task: [<class 'decimal.DivisionUndefined'>]`

Expected: 
Bot showing balance for all connected exchanges
No errors showing


[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/8229647/logs_hummingbot.log)
[5173.zip](https://github.com/hummingbot/hummingbot/files/8229651/5173.zip)
```
2022-03-10 16:49:02,497 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: [<class 'decimal.DivisionUndefined'>]
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/client/command/balance_command.py", line 114, in show_balances
    self._notify(f"\n  Total: {RateOracle.global_token_symbol} {PerformanceMetrics.smart_round(df[total_col_name].sum())}    "
decimal.InvalidOperation: [<class 'decimal.DivisionUndefined'>]
```

image
image


May it be related to falling unit tests for rate oracle source?

**Comment by aarmoa** [comment]
Hello @nikspz. Checking the logs I could not find any relationship between the changes in the current PR and the error. It seems to be related to a problem with the k2 connector configuration in that client instance. Could you please validate if the error also happens in the current master version? If that is the case then the problem would not be related to the PR.

**Comment by rapcmia** [comment]
PR update: on-going test
We have pending HitBTC, dYdX_perp, and Ndax left for connectors and some partial filled trade to test

**Review by rapcmia — APPROVED** [review]
Test performed:
- Create simple config for supported strategies
- Tested all spot connectors mostly using Pure MM
- Tested all derivative connectors using Perpetual MM
- Set spreads tight enough for full and partial fills
- Compare trades from history, CSV and connector trade history, all ok 
- Checked datadog > hummingbot.filled_usdt_volume, all ok
- Confirmed metrics are being captured and converted to USD
- Confirmed metric interval is working as expected.
- Repeat steps and apply to different strategies and connectors that are supported, all ok

**Review by mifeng — APPROVED** [review]
This fixes a bug that prevents bots running the `master` branch from reporting anonymized, aggregate volume by exchange, which is important for the Foundation to enter into partnerships with exchanges that sustain it. Therefore, Hummingbot Foundation will merge in this PR as a hotfix.

**Review by nikspz — DISMISSED** [review]
LGTM
Tested and approved by QA

**Review by JeremyKono — APPROVED** [review]
LGTM

**Review by nikspz — APPROVED** [review]

**Review by mifeng — APPROVED** [review]

**Pull request merged**
