### PR TITLE
Feat/update injective to lb

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This pr updates the Injective deps and also the network to LB.

**Tests performed by the developer**:
- End-to-end testing between client and gateway

**Tips for QA testing**:
- Do an end-to-end testing between client and gateway pr - https://github.com/hummingbot/gateway/pull/92

### CODE REVIEW

**Comment by nikspz** [comment]
@vic-en latest commit [21198ce](https://github.com/hummingbot/hummingbot/pull/6255/commits/21198ce712abce5d2dcb3d0e1b6420891ee67694)

Steps:
Clone and install PR6255 and latest dev gateway
Create/starte the pureMM strategy using injective spot

Actual:
Can't start pureMM strategy using injective spot, got flooded with `hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task` and `hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - ERROR - Unexpected error in user stream listener loop.`



[logs_pureinj4localubuntu.log](https://github.com/hummingbot/hummingbot/files/11367745/logs_pureinj4localubuntu.log)
[injectiveLB.zip](https://github.com/hummingbot/hummingbot/files/11367754/injectiveLB.zip)

```
2023-05-02 02:44:47,023 - 9147 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2023-05-02 02:44:47,279 - 9147 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2023-05-02 02:44:51,508 - 9147 - root - INFO - chain session cookie saved to disk
2023-05-02 02:44:52,436 - 9147 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown method Orderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-05-02T02:44:52.435778496+07:00", grpc_status:12, grpc_message:"unknown method Orderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC"}"
>
Traceback (most recent call last):
  File "/home/etozhe/injective6255/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/etozhe/injective6255/hummingbot/core/data_type/order_book_tracker.py", line 180, in _init_order_books
    self._order_books[trading_pair] = await self._initial_order_book_for_trading_pair(trading_pair)
  File "/home/etozhe/injective6255/hummingbot/core/data_type/order_book_tracker.py", line 173, in _initial_order_book_for_trading_pair
    return await self._data_source.get_new_order_book(trading_pair)
  File "/home/etozhe/injective6255/hummingbot/core/data_type/order_book_tracker_data_source.py", line 65, in get_new_order_book
    snapshot_msg: OrderBookMessage = await self._order_book_snapshot(trading_pair=trading_pair)
  File "/home/etozhe/injective6255/hummingbot/connector/gateway/clob_spot/gateway_clob_api_order_book_data_source.py", line 68, in _order_book_snapshot
    snapshot = await self._api_data_source.get_order_book_snapshot(trading_pair=trading_pair)
  File "/home/etozhe/injective6255/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 335, in get_order_book_snapshot
    order_book_response = await self._client.get_spot_orderbook(market_id=market.market_id)
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/pyinjective/async_client.py", line 637, in get_spot_orderbook
    return await self.stubSpotExchange.Orderbook(req)
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown method Orderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-05-02T02:44:52.435778496+07:00", grpc_status:12, grpc_message:"unknown method Orderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC"}"
>
2023-05-02 02:44:52,485 - 9147 - hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "/home/etozhe/injective6255/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 818, in _listen_to_order_books_stream
    async for order_book_update in stream:
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 326, in _fetch_stream_responses
    await self._raise_for_status()
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 236, in _raise_for_status
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown method StreamOrderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-05-02T02:44:52.481925881+07:00", grpc_status:12, grpc_message:"unknown method StreamOrderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC"}"
>
2023-05-02 02:44:52,485 - 9147 - hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - INFO - Restarting order books stream.
2023-05-02 02:44:52,799 - 9147 - hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "/home/etozhe/injective6255/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 818, in _listen_to_order_books_stream
    async for order_book_update in stream:
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 326, in _fetch_stream_responses
    await self._raise_for_status()
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 236, in _raise_for_status
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown method StreamOrderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"unknown method StreamOrderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC", grpc_status:12, created_time:"2023-05-02T02:44:52.798343022+07:00"}"
>
2023-05-02 02:44:52,800 - 9147 - hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - INFO - Restarting order books stream.
2023-05-02 02:44:52,910 - 9147 - hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "/home/etozhe/injective6255/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 818, in _listen_to_order_books_stream
    async for order_book_update in stream:
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 326, in _fetch_stream_responses
    await self._raise_for_status()
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 236, in _raise_for_status
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown method StreamOrderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-05-02T02:44:52.909975248+07:00", grpc_status:12, grpc_message:"unknown method StreamOrderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC"}"
>
2023-05-02 02:44:52,911 - 9147 - hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - INFO - Restarting order books stream.
2023-05-02 02:44:53,022 - 9147 - hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "/home/etozhe/injective6255/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 818, in _listen_to_order_books_stream
    async for order_book_update in stream:
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 326, in _fetch_stream_responses
    await self._raise_for_status()
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 236, in _raise_for_status
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown method StreamOrderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-05-02T02:44:53.020896106+07:00", grpc_status:12, grpc_message:"unknown method StreamOrderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC"}"
>
2023-05-02 02:44:53,023 - 9147 - hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - INFO - Restarting order books stream.
2023-05-02 02:44:53,140 - 9147 - hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "/home/etozhe/injective6255/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 818, in _listen_to_order_books_stream
    async for order_book_update in stream:
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 326, in _fetch_stream_responses
    await self._raise_for_status()
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 236, in _raise_for_status
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown method StreamOrderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"unknown method StreamOrderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC", grpc_status:12, created_time:"2023-05-02T02:44:53.139258321+07:00"}"
>
2023-05-02 02:44:53,140 - 9147 - hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - INFO - Restarting order books stream.
2023-05-02 02:44:53,291 - 9147 - hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "/home/etozhe/injective6255/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 818, in _listen_to_order_books_stream
    async for order_book_update in stream:
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 326, in _fetch_stream_responses
    await self._raise_for_status()
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 236, in _raise_for_status
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown method StreamOrderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-05-02T02:44:53.248724472+07:00", grpc_status:12, grpc_message:"unknown method StreamOrderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC"}"
>
2023-05-02 02:44:53,291 - 9147 - hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - INFO - Restarting order books stream.
2023-05-02 02:44:53,405 - 9147 - hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "/home/etozhe/injective6255/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 818, in _listen_to_order_books_stream
    async for order_book_update in stream:
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 326, in _fetch_stream_responses
    await self._raise_for_status()
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 236, in _raise_for_status
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown method StreamOrderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"unknown method StreamOrderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC", grpc_status:12, created_time:"2023-05-02T02:44:53.403928367+07:00"}"
>
2023-05-02 02:44:53,405 - 9147 - hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - INFO - Restarting order books stream.
2023-05-02 02:44:53,528 - 9147 - hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "/home/etozhe/injective6255/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 818, in _listen_to_order_books_stream
    async for order_book_update in stream:
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 326, in _fetch_stream_responses
    await self._raise_for_status()
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 236, in _raise_for_status
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown method StreamOrderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"unknown method StreamOrderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC", grpc_status:12, created_time:"2023-05-02T02:44:53.527212046+07:00"}"
>
2023-05-02 02:44:53,528 - 9147 - hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - INFO - Restarting order books stream.
2023-05-02 02:44:53,640 - 9147 - hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "/home/etozhe/injective6255/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 818, in _listen_to_order_books_stream
    async for order_book_update in stream:
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 326, in _fetch_stream_responses
    await self._raise_for_status()
  File "/home/etozhe/miniconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 236, in _raise_for_status
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown method StreamOrderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-05-02T02:44:53.639101734+07:00", grpc_status:12, grpc_message:"unknown method StreamOrderbook for service injective_spot_exchange_rpc.InjectiveSpotExchangeRPC"}"
>
```

image

**Comment by rapcmia** [comment]
PR update:
- Tested Injective perp
    - Order and cancellation ok
        - Observed there are errors related to insufficient gas or timeout errors yet the bot managed to recover
    - Short/Long position opened and TP/SL created
    - TP/SL created, position closed. Then orders to open position are created
        - Observed there are delay on creating/cancellation of orders too but able to recover and no stuck orders
    - Trade data between client CSV, history and exchange trade history matched
        - Fees paid and timestamps ok
        
For Injective protocol's spot, im getting the same reported issue by Nikita

**Comment by keithbaum** [comment]
Hi @rapcmia @nikspz , you should first merge PR with OrderbookV2 change to spot before testing this

**Comment by rapcmia** [comment]
Hi @keithbaum good day, 
We successfully merged 6187, can you please have a look with the branch conflicts? thank you

**Comment by rapcmia** [comment]
> Can't start pureMM strategy using injective spot, got flooded with `hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task` and `hummingbot.connector.gateway.clob_spot.data_sources.injective.injective_api_data_source.InjectiveAPIDataSource - ERROR - Unexpected error in user stream listener loop.`



After merged of #6187 this issue still occur using Pure-MM
image

**Comment by keithbaum** [comment]
Can you please upload the logs @rapcmia ?

**Comment by rapcmia** [comment]
> Can you please upload the logs @rapcmia ?

Please see attached: [logs_pmm-injective.log](https://github.com/hummingbot/hummingbot/files/11403410/logs_pmm-injective.log)

**Comment by nikspz** [comment]
Tests perfromed
- Cloned and installed feature branch + gateway development
- Start the bot and gateway development successfully
- Ran Injective spot and perpetual still have issues mentioned in previous PR
    - [https://www.loom.com/share/12b30c4283ba4ac08749380b2e17193e](https://www.loom.com/share/12b30c4283ba4ac08749380b2e17193e)
        - Injective spot fialed to place one part of orders (SELL or BUY order)
        
[logs_injspot5523.log](https://github.com/hummingbot/hummingbot/files/11408257/logs_injspot5523.log)
[injspot.zip](https://github.com/hummingbot/hummingbot/files/11408258/injspot.zip)

        - Injective perpetual not place SELL order, then stuck on failed to cancel order
        
[injperp.zip](https://github.com/hummingbot/hummingbot/files/11408265/injperp.zip)

[logs_injperp5523.log](https://github.com/hummingbot/hummingbot/files/11408260/logs_injperp5523.log)

**Comment by vic-en** [comment]
@rapcmia @keithbaum 
I don't think those reported issues can be solved by the changes here because the changes in the diff(as shown in the pr diff) can basically be ignored after I rebased with development.

I'll be closing this pr because pr https://github.com/hummingbot/hummingbot/pull/6187 coincidentally made similar changes.

**Pull request closed without merging**
