### PR TITLE
Feat/add support for more ethereum networks for uniswap

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This pr adds support for arbitrum_one and optimism mainnet for uniswap.
Hence, amm_arb and uniswap LP strategy should be able to use connectors that have been connected to those networks using `gateway connect`

**Tests performed by the developer**:
- Created connection to those newly added networks using `gateway connect uniswap` and `gateway connect uniswapLP`
- Created uniswapLP strategy and configuring to use newly connected entries.

**Tips for QA testing**:
- Create connection to those newly added networks using `gateway connect uniswap` and `gateway connect uniswapLP`
- Create uniswapLP strategy and configuring to use newly connected entries.
- Create amm_arb strategy and configuring to use newly connected entries.

**Note**
This pr also address issue reported in https://github.com/hummingbot/hummingbot/pull/5462#issuecomment-1203691989 where networks of chain not being configure are allowed on the client.

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update:
- gateway connect uniswap-optimsim
- Setup simple amm-arbitrage for uniswap-optimism, ok
- Setup min_profitability to trigger `no arbitrage opportunity`, ok 
- Token approval tested on different tokens on uniswap-optimism: WETH,USDC,LINK,THALES
- Test order execution

While we confirm that that the client was able to trigger `no arbitrage opportunity`, executing arbitrage seems getting some errors related to `invalid hexlify value..`
image

Client logs
```
2022-08-08 12:36:45,812 - 6712 - GatewayEVMAMM - ERROR - Error submitting SELL swap order to uniswap on optimism for 0.003000000000000 WETH-USDC 1693.054440000000000.
Traceback (most recent call last):
  File "/home/rapcmia/github/5565/hummingbot/connector/gateway_EVM_AMM.py", line 525, in _create_order
    order_result: Dict[str, Any] = await self._get_gateway_instance().amm_trade(
  File "/home/rapcmia/github/5565/hummingbot/core/gateway/gateway_http_client.py", line 453, in amm_trade
    return await self.api_request("post", "amm/trade", request_payload)
  File "/home/rapcmia/github/5565/hummingbot/core/gateway/gateway_http_client.py", line 194, in api_request
    raise e
  File "/home/rapcmia/github/5565/hummingbot/core/gateway/gateway_http_client.py", line 182, in api_request
    raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
ValueError: Error on POST https://localhost:20922/amm/trade Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': 'Error: invalid hexlify value (argument="value", value="1000000", code=INVALID_ARGUMENT, version=bytes/5.6.1)\n    at Logger.makeError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:233:21)\n    at Logger.throwError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:242:20)\n    at Logger.throwArgumentError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:245:21)\n    at hexlify (/usr/src/app/node_modules/@ethersproject/bytes/lib/index.js:200:19)\n    at /usr/src/app/node_modules/@ethersproject/transactions/lib/index.js:181:59\n    at Array.forEach (<anonymous>)\n    at _serialize (/usr/src/app/node_modules/@ethersproject/transactions/lib/index.js:175:23)\n    at serialize (/usr/src/app/node_modules/@ethersproject/transactions/lib/index.js:246:16)\n    at /usr/src/app/node_modules/@ethersproject/wallet/lib/index.js:163:116\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)'}
2022-08-08 12:36:45,814 - 6712 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1659933405.0, "order_id": "sell-WETH-USDC-1659933395284107", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "uniswap_ethereum_optimism"}
```

Docker logs:
```
2022-08-08 05:56:10 | info | 	Expected execution price is 1710.156000, limit price is 1693.054440000000000. | undefined
2022-08-08 05:56:12 | error | 	invalid hexlify value (argument="value", value="1000000", code=INVALID_ARGUMENT, version=bytes/5.6.1) | Error: invalid hexlify value (argument="value", value="1000000", code=INVALID_ARGUMENT, version=bytes/5.6.1)
    at Logger.makeError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at Logger.throwArgumentError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:245:21)
    at hexlify (/usr/src/app/node_modules/@ethersproject/bytes/lib/index.js:200:19)
    at /usr/src/app/node_modules/@ethersproject/transactions/lib/index.js:181:59
    at Array.forEach (<anonymous>)
    at _serialize (/usr/src/app/node_modules/@ethersproject/transactions/lib/index.js:175:23)
    at serialize (/usr/src/app/node_modules/@ethersproject/transactions/lib/index.js:246:16)
    at /usr/src/app/node_modules/@ethersproject/wallet/lib/index.js:163:116
    at runMicrotasks (<anonymous>)
```

Tested on order_amounts 0.003, 0.005 and 0.01 getting the same error

Steps to reproduce:
1. Setup AMM arb for uniswap-optimism
2. Set min_profitability to -1 value to execute trades
3. Monitor log panel for error

[amm-uniswap-optimism.zip](https://github.com/hummingbot/hummingbot/files/9278823/amm-uniswap-optimism.zip)

**Comment by rapcmia** [comment]
PR update:
- Test commit `c7fe053eb9ca`
- Clone and install successfully
- Manually create docker gateway image for testing from /gateway folder 
   - Setup `gateway config ethereum.networks.optimism.nodeURL xxx`
   - Setup `gateway connect perp`
   
We noticed that when connecting wallet, the client would prompt us to enter the nodeURL again when its already configured. Tried to enter and it seems it doesn't let us reconnect by running `gateway start` and getting `Error: unable to restart gateway. Try again after gateway is running` resulting to another prompt to enter the nodeURL again. Screen recording below:

https://user-images.githubusercontent.com/73840223/185034324-29c9c19a-cbbe-45ad-907a-418a5008a6f7.mp4

Checked the other connectors on the PR specially uniswap and avalanche and now getting the same behavior. Noticeable that its returning a `invalid choice...` error when selecting the chains 

Screenshot 2022-08-17 105957

Screenshot 2022-08-17 105848

Tried to `ctrl+x` and it seems to accept the private key however it seems that its displaying on the output panel a part of the bot that its trying to `cancel orders` when we are only setting up the wallet. Balance checking seems to be working as expected. Screen recording available:

https://user-images.githubusercontent.com/73840223/185035513-56120dc9-7d3f-45c4-9d93-92f5f5010e1d.mp4

Steps to reproduce:
1. Setup nodeURL for optimism
2. Setup wallet for Perp connector, notice another prompt asking for nodeURL
3. Use `Ctrl+x` to enter pkey and notice that the bot displays like its trying to cancel the orders

[5520.zip](https://github.com/hummingbot/hummingbot/files/9356385/5520.zip)

Pending:
Balance seems to be working fine and we are now testing the order create/execute on spot-perpetual arbitrage

**Comment by vic-en** [comment]
@rapcmia @arnelhbot @JeremyKono 
Aside updating with latest changes from development. I couldn't reproduce any of those issues you've mentioned.
- I suspect related to NoneType error must have been because the gateway_connection.json file was manually updated while client was running. To back it up, I make no changes to the client/python files.
- Issues with error submitting order on gateway could have also been that the override params like the transaction limit was modified incorrectly.
Here are also screenshots from my end:
image

image

**Comment by rapcmia** [comment]
Hi @vic-en thanks for the update, im not sure why kovan is used on the screenshot since the test was for Arbitrum and Optimism for Uniswap and UniswapLP. 
  > This pr adds support for arbitrum_one and optimism mainnet for uniswap.
  > Hence, amm_arb and uniswap LP strategy should be able to use connectors that have been connected to those networks using `gateway connect`
  
We tested the latest commit ` 9099e6c6f797` and still getting the issue when checking the balance for Arbitrum. While we confirm that we are able to setup the Arbitrum wallet we also noticed on the screen recording below that when we use the approach for existing key its displaying the balance: 

https://user-images.githubusercontent.com/73840223/185356094-5c80d801-b3f8-4a1a-8607-8bf244712c55.mp4

Screenshot of balance getting displayed when testing existing key:
image

```
2022-08-18 16:59:39,933 - 16964 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/rapcmia/github/5565/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/rapcmia/github/5565/hummingbot/client/command/balance_command.py", line 85, in show_balances
    all_ex_bals = await asyncio.wait_for(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/home/rapcmia/github/5565/hummingbot/user/user_balances.py", line 130, in all_balances_all_exchanges
    await self.update_exchanges(client_config_map)
  File "/home/rapcmia/github/5565/hummingbot/user/user_balances.py", line 126, in update_exchanges
    results = await safe_gather(*tasks)
  File "/home/rapcmia/github/5565/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/rapcmia/github/5565/hummingbot/user/user_balances.py", line 100, in update_exchange_balance
    return await self.add_exchange(exchange_name, client_config_map, **api_keys)
  File "/home/rapcmia/github/5565/hummingbot/user/user_balances.py", line 76, in add_exchange
    market = UserBalances.connect_market(exchange, client_config_map, **api_details)
  File "/home/rapcmia/github/5565/hummingbot/user/user_balances.py", line 23, in connect_market
    init_params = conn_setting.conn_init_parameters(api_details)
  File "/home/rapcmia/github/5565/hummingbot/client/settings.py", line 202, in conn_init_parameters
    connector_name=connector_spec["connector"],
TypeError: 'NoneType' object is not subscriptable
```


We also tried to check the endpoints and try to modify the network and balances by setting the json file to ethereum and arbitrum, arbitrum_one or arbitrum-mainnet but no good
```
curl -s -X GET -k --key $GATEWAY_KEY --cert $GATEWAY_CERT https://localhost:5000/network/status?chain=ethereum&network=arbitrum-mainnet | jq

curl -s -X POST -k --key $GATEWAY_KEY --cert $GATEWAY_CERT -H "Content-Type: application/json" -d "$(envsubst < ./requests/network_balances.json)" https://localhost:5000/network/balances | jq
```
image

**Comment by vic-en** [comment]
@arnelhbot 
Pls test this again...

**Comment by rapcmia** [comment]
PR update:
- Test latest commit `0342725ff64`
- Tested `arbitrum_one` and we are still getting the same behavior when adding the correct nodeURL
   > While we confirm that we are able to setup the Arbitrum wallet we also noticed on the screen recording below that when we use the approach for existing key its displaying the balance:
   > 
   >  WindowsTerminal_EoSV0zkWzr.mp4 
   > Screenshot of balance getting displayed when testing existing key: image
- Continued curl test and the following seems to be running ok 
   - Changed the network to `arbitrum_one`
   - wallet/add ok 
   - network/balances ok
   - evm/approve (using WETH, USDC, APE, etc.. ), ok 
   - evm/allowances ok 
   - amm/trade
  	This is where we are getting the same error like on the optimism. Where we tried to run trade but getting an error of `invalid hexlify value (argument="value", value="168107541", code=INVALID_ARGUMENT, version=bytes/5.6.1)` We tried amounts `0.005, 0.009` but getting the same error 
        image
        
 
[logs_gateway_app.log.2022-08-19.log](https://github.com/hummingbot/hummingbot/files/9380456/logs_gateway_app.log.2022-08-19.log)

**Comment by vic-en** [comment]
@arnelhbot @rapcmia 
pls test this again...
You may have to change node url as it appears that infura nodes aren't responding fast and returning timeout errs at the time of making this comment.
Lastly, pls expands scope to include uniswapLp as well. Thanks.

**Comment by rapcmia** [comment]
PR update:
- Test commit `ee12b2498d` on AWS for `Arbitrum connector`
- Confirmed **the issue on nodeURL for arbitrum has been fixed**. `Balance` command now display the wallet balance
   image

Would it be possible to add the `arbitrum_rinkeby` testnet on the uniswap-ethereum list?
   image  
   image
   image

- Initially tested on client with binance_paper and `uniswap_ethereum_arbitrum_one` with order amount set to `0.009`
   - Setup simple AMM arbitrage strategy, ok 
   - Setup min_profitability, `no arbitrage opportunity` displays ok
   - Order execution:

Noticed that there have been errors of `Failed to fetch transaction status..` for two instances of arbitrage opportunity
image

Chekced the docker logs its returning an error on the txhash created of `Fail with error 'Too much requested'`
1st attempt: [0xb6a9fc07abb64e9795486e5d5a6ac5ac00d658de1d7ec7bfad9bd81da8086bd0](https://arbiscan.io/tx/0xb6a9fc07abb64e9795486e5d5a6ac5ac00d658de1d7ec7bfad9bd81da8086bd0)
2nd attempt: [0xb6a9fc07abb64e9795486e5d5a6ac5ac00d658de1d7ec7bfad9bd81da8086bd0](https://arbiscan.io/tx/0xb6a9fc07abb64e9795486e5d5a6ac5ac00d658de1d7ec7bfad9bd81da8086bd0)
```
2022-08-22 09:21:33 | info | 	Trade has been executed, txHash is 0x715fdf790958d518f21fd5131431f28d513a2f4281cf733a74696f1a7785887b, nonce is 14, gasPrice is 0.099175487. | undefined
2022-08-22 09:21:34 | info | 	Poll arbitrum_one, txHash 0x715fdf790958d518f21fd5131431f28d513a2f4281cf733a74696f1a7785887b, status 1. | undefined
2022-08-22 09:21:35 | info | 	Poll arbitrum_one, txHash 0x715fdf790958d518f21fd5131431f28d513a2f4281cf733a74696f1a7785887b, status 1. | undefined
2022-08-22 09:21:37 | info | 	Requesting balance for owner 0x08940dc9B5a19FAb9319b77C61DDA7B8067E6843. | undefined
2022-08-22 09:21:37 | info | 	Requesting balance for owner 0x08940dc9B5a19FAb9319b77C61DDA7B8067E6843. | undefined
2022-08-22 09:21:37 | info | 	Raw balance of 0x82aF49447D8a07e3bd95BD0d56f35241523fBab1 for 0x08940dc9B5a19FAb9319b77C61DDA7B8067E6843: 12001183819247636 | undefined
2022-08-22 09:21:37 | info | 	Raw balance of 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8 for 0x08940dc9B5a19FAb9319b77C61DDA7B8067E6843: 16043770 | undefined
2022-08-22 09:21:38 | info | 	Poll arbitrum_one, txHash 0x715fdf790958d518f21fd5131431f28d513a2f4281cf733a74696f1a7785887b, status 1. | undefined
2022-08-22 09:21:39 | info | 	Poll arbitrum_one, txHash 0x715fdf790958d518f21fd5131431f28d513a2f4281cf733a74696f1a7785887b, status 1. | undefined
2022-08-22 09:21:40 | info | 	Poll arbitrum_one, txHash 0x715fdf790958d518f21fd5131431f28d513a2f4281cf733a74696f1a7785887b, status 1. | undefined
2022-08-22 09:21:41 | info | 	Poll arbitrum_one, txHash 0x715fdf790958d518f21fd5131431f28d513a2f4281cf733a74696f1a7785887b, status 1. | undefined
2022-08-22 09:21:42 | info | 	Poll arbitrum_one, txHash 0x715fdf790958d518f21fd5131431f28d513a2f4281cf733a74696f1a7785887b, status 1. | undefined
2022-08-22 09:21:43 | info | 	Poll arbitrum_one, txHash 0x715fdf790958d518f21fd5131431f28d513a2f4281cf733a74696f1a7785887b, status 1. | undefined
2022-08-22 09:21:44 | info | 	Poll arbitrum_one, txHash 0x715fdf790958d518f21fd5131431f28d513a2f4281cf733a74696f1a7785887b, status 1. | undefined
2022-08-22 09:21:45 | info | 	Poll arbitrum_one, txHash 0x715fdf790958d518f21fd5131431f28d513a2f4281cf733a74696f1a7785887b, status 1. | undefined
2022-08-22 09:21:46 | info | 	Poll arbitrum_one, txHash 0x715fdf790958d518f21fd5131431f28d513a2f4281cf733a74696f1a7785887b, status 1. | undefined
2022-08-22 09:21:47 | info | 	Fetching pair data for 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8-0x82aF49447D8a07e3bd95BD0d56f35241523fBab1. | undefined
2022-08-22 09:21:50 | info | 	Best trade for 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8-0x82aF49447D8a07e3bd95BD0d56f35241523fBab1: 1557.044111 WETH. | undefined
2022-08-22 09:21:50 | info | 	Fetching pair data for 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8-0x82aF49447D8a07e3bd95BD0d56f35241523fBab1. | undefined
2022-08-22 09:21:54 | info | 	Best trade for 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8-0x82aF49447D8a07e3bd95BD0d56f35241523fBab1: 1557.044111 WETH. | undefined
2022-08-22 09:21:54 | info | 	Fetching trade data for 0x82aF49447D8a07e3bd95BD0d56f35241523fBab1-0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8. | undefined
2022-08-22 09:21:59 | info | 	Best trade for 0x82aF49447D8a07e3bd95BD0d56f35241523fBab1-0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8: 1555.480778WETH. | undefined
2022-08-22 09:21:59 | info | 	Fetching trade data for 0x82aF49447D8a07e3bd95BD0d56f35241523fBab1-0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8. | undefined
2022-08-22 09:22:03 | info | 	Best trade for 0x82aF49447D8a07e3bd95BD0d56f35241523fBab1-0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8: 1555.618667WETH. | undefined
2022-08-22 09:22:05 | info | 	Fetching pair data for 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8-0x82aF49447D8a07e3bd95BD0d56f35241523fBab1. | undefined
2022-08-22 09:22:10 | info | 	Best trade for 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8-0x82aF49447D8a07e3bd95BD0d56f35241523fBab1: 1554.180556 WETH. | undefined
2022-08-22 09:22:10 | info | 	[object Object] | undefined

2022-08-22 09:22:10 | info | 	Trade has been executed, txHash is 0xb6a9fc07abb64e9795486e5d5a6ac5ac00d658de1d7ec7bfad9bd81da8086bd0, nonce is 15, gasPrice is 0.099175487. | undefined
2022-08-22 09:22:11 | info | 	Poll arbitrum_one, txHash 0xb6a9fc07abb64e9795486e5d5a6ac5ac00d658de1d7ec7bfad9bd81da8086bd0, status 1. | undefined
2022-08-22 09:22:12 | info | 	Poll arbitrum_one, txHash 0xb6a9fc07abb64e9795486e5d5a6ac5ac00d658de1d7ec7bfad9bd81da8086bd0, status 1. | undefined
```
Compare test results using endpoints using curl for `uniswap`
- evm/approve ok 
- evm/allowances ok
- amm/price for BUY and SELL, ok 
- amm/trade 
   - Sell -> https://arbiscan.io/tx/0x4a678aae19a385763278bac8b5b240d163ca1e3b73c7501decc3e38c90787c38 ok
   - However for Buy we are getting an error of `Fail with error 'STF'` on two instances
	   - https://arbiscan.io/tx/0x2e2f2a4580da6ce370396a9561b5f757f7dd4de2a35bef0d29c417a8c76a2524 
	   - https://arbiscan.io/tx/0x5c3479fd32a38fb303665fe54aae1d892cc5dd6659c949b3a52a62a91e4db3cd
           Screenshot 2022-08-22 165050

Tested `uniswapLP` endpoints 
- evm/approve ok 
- evm/allowances ok

Tried to setup arbitrum_one using the sample perp-curi curl test template but kept on getting `unknown error`. Just want to clarify if we are using the correct setup for testing uniswalpLP since the sample test are from perp-curie, thank you
image
image

Pending:
UniswapLP test on client 
UniswapLP for optimism

**Comment by nikspz** [comment]
Test latest commit [ee12b24](https://github.com/hummingbot/hummingbot/pull/5565/commits/ee12b2498d26ae8b48dc37f76a90c0910ed57f7a)
Tested arbitrum_one, 
- for `amm_arb` strategy
    - Bot failed to perform arbitrage cycle (did the trades only for uniswap_ethereum_arbitrum_one connector and did Not for connector_2)
    
Steps to reproduce:
1. clone and install feature branch
2. create docker image manually from gateway folder
3. gateway generate certs/create
4. add arbitrum node url with gateway config ethereum.networks.arbitrum_one.nodeURL 
5. create amm_arb strategy using uniswap_ethereum_arbitrum_one and CEX/paper trade connector
6. set up min_profitability to -10 to trigger arbitrage

Actual:
Bot created orders only for uniswap_ethereum_arbitrum_one, failed to create for connector_2

Expected:
Bot could perform an arbitrage using both exchanges
    
[logs_conf_amm_arb_2.log](https://github.com/hummingbot/hummingbot/files/9393587/logs_conf_amm_arb_2.log)
[conf_amm_arb_2 - Copy.txt](https://github.com/hummingbot/hummingbot/files/9393590/conf_amm_arb_2.-.Copy.txt)
[strategies.zip](https://github.com/hummingbot/hummingbot/files/9393675/strategies.zip)
image
uniswap arbitrum WETH-USDC

- uniswap LP strategy arbitrum_one
    - running bot for continious time
    - bot creating positions
    - short time past after creation showing WARNING - Call to [https://localhost:31333/amm/liquidity/position](https://localhost:31333/amm/liquidity/position) failed.
    - after strategy stopped positions left on uniswap


[logs_conf_uniswap_v3_lp_2.log](https://github.com/hummingbot/hummingbot/files/9393673/logs_conf_uniswap_v3_lp_2.log)
[strategies.zip](https://github.com/hummingbot/hummingbot/files/9393675/strategies.zip)
image
image
uniswapLP arbitrum WETH-USDC wait 1

**Review by rapcmia — APPROVED** [review]
Test performed:
- Clone and install successfully
- Managed to setup using the correct nodeURLs for Arbitrum and Optimism
- Successfully added connector wallets and balance are displayed ok 
- Test endpoints for uniswap for both Arbitrum and Optimism
- Setup simple AMM arbitrage and UniswapLP for both Arbitrum and Optimism, ok 
- Test on source and docker build

Notes:
- There were noticeable errors for Arbitrum that does not happened for other networks such as Uniswap and UniswapLP. A separate ticket will be created to fix issues discovered
- Optimism Uniswap was working accordingly however, instances of connector not ready for uniswapLP was observed

**Pull request merged**
