### PR TITLE
new connector feat/openware

### PR DESCRIPTION
**Pull request by Dmdv**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by JeremyKono** [comment]
Thank you for your contribution to the community. Please create a PRP (https://hummingbot.org/governance/proposals/prp/) for the PR to be approved.

**Comment by aarmoa** [comment]
Hello @Dmdv. The PR does not have any description at all. Please provide all required details or it will be closed.

**Comment by Dmdv** [comment]
@aarmoa Hi Abel, sorry. noticed your message just now.
Sure, I will updated it soon

**Comment by Dmdv** [comment]
@aarmoa Where I can get the most help regarding hummingbot development?
Discord or other ?

**Comment by aarmoa** [comment]
@Dmdv The developers channel in Discord is the best place to ask questions

**Pull request closed without merging**
