### PR TITLE
Fix/kucoin perpetual issues

### PR DESCRIPTION
**Pull request by yancong001**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
fix kucoin trade, order, fee issues

**Tests performed by the developer**:

issues: 6226, 6182, 6161, 6163

**Tips for QA testing**:

### CODE REVIEW

**Comment by nikspz** [comment]
commit [6768406](https://github.com/hummingbot/hummingbot/pull/6235/commits/676840629036e1cec8e2ffb73dd965e0dcd4f906)

Client cancel stop-loss order to CLOSE position immediately after trying to place

Steps to reproduce:
clone and install fix
create/start strategy using kucoin_perpetual and tight spread to fill order to OPEN
wait bot start to create orders to close position with stop-loss
pay attention to the logs and exchange

Actual:
Bot failed to place order to CLOSE position, stuck with cancel it after trying to place

Expected:
Bot CLOSE position according to stop loss spread and 

if bot take profit then according to take profit spread 





```
2023-04-18 16:14:55,000 - 2061457 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (XRP-USDT) Creating 1  LIMIT ask orders at (Size, Price): ['2E+1 XRP, 0.5198 USDT'] to CLOSE position.
2023-04-18 16:14:55,140 - 2061457 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1681834495.0, "order_id": "HummingbotSXPUT5f99e9ba54200c122f032c89e", "exchange_order_id": "643ec1ff9e64b60001c46044", "event_name": "OrderCancelledEvent", "event_source": "kucoin_perpetual"}
2023-04-18 16:14:55,140 - 2061457 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order HummingbotSXPUT5f99e9ba54200c122f032c89e.
2023-04-18 16:15:55,000 - 2061457 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (XRP-USDT) Creating 1  LIMIT ask orders at (Size, Price): ['2E+1 XRP, 0.5198 USDT'] to CLOSE position.
2023-04-18 16:15:55,145 - 2061457 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1681834555.0, "order_id": "HummingbotSXPUT5f99e9f38c82bc122f032c89e", "exchange_order_id": "643ec23b012e750001bc94bb", "event_name": "OrderCancelledEvent", "event_source": "kucoin_perpetual"}
2023-04-18 16:15:55,145 - 2061457 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order HummingbotSXPUT5f99e9f38c82bc122f032c89e.
2023-04-18 16:16:55,000 - 2061457 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (XRP-USDT) Creating 1  LIMIT ask orders at (Size, Price): ['2E+1 XRP, 0.5198 USDT'] to CLOSE position.
2023-04-18 16:16:55,131 - 2061457 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1681834615.0, "order_id": "HummingbotSXPUT5f99ea2cc50b4c122f032c89e", "exchange_order_id": "643ec2772cf3d90001100499", "event_name": "OrderCancelledEvent", "event_source": "kucoin_perpetual"}
2023-04-18 16:16:55,131 - 2061457 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order HummingbotSXPUT5f99ea2cc50b4c122f032c89e.
2023-04-18 16:17:55,002 - 2061457 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (XRP-USDT) Creating 1  LIMIT ask orders at (Size, Price): ['2E+1 XRP, 0.5198 USDT'] to CLOSE position.
2023-04-18 16:17:55,129 - 2061457 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1681834675.0, "order_id": "HummingbotSXPUT5f99ea65fdcfdc122f032c89e", "exchange_order_id": "643ec2b31fe5600001754828", "event_name": "OrderCancelledEvent", "event_source": "kucoin_perpetual"}
2023-04-18 16:17:55,129 - 2061457 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order HummingbotSXPUT5f99ea65fdcfdc122f032c89e.
```


[logs_kucperp1xrp.log](https://github.com/hummingbot/hummingbot/files/11265329/logs_kucperp1xrp.log)

[6235kucperp.zip](https://github.com/hummingbot/hummingbot/files/11265328/6235kucperp.zip)

image

**Comment by rapcmia** [comment]
PR update:
- Tested on local WSL ubuntu20.04, Installation ✅
- Order create/cancel order on {60s, 900s}✅
- **Open long position, create buy take-profit order** ✅
    - Other side of the order is canceled in favor of take-profit order
    - Take-profit order is refreshed based on the set `time_between_stop_loss_orders`
    - Crosscheck client and kucoin perpetual exchange orderbook, active take-profit order and open long position, all are ok
    - Check position retrieved successfully? yes
    - Close position and take-profit order filled. Client create orders to open position again
    - Stop loss order records the fill price on the client, matched on exchange ✅
    - Check trade data between client/csv and exchange history
      image
      - How can we check the fees paid on kucoin perpetual?
      - The percent on CSV file is incorrect, should be orders to open position use `0.02%`?
- **Open short position, create sell take-profit order**
    - SL triggered but it seems to be stuck   
      image
      - Stop the client and relaunch to check if position is retrieved
        image
    - Modified SL spread and check connector behavior on creating TP orders
      image
      - Observed for short position the unrealized PnL seems incorrect. Wait for couple of minutes but no avail
      - Relaunch client, still the same behavior

Steps to reproduce:
1. Setup kucoin perpetual on perpetual_market-making
2. Observed connector on openng and closing long/short position with tp/sl orders

[6235.zip](https://github.com/hummingbot/hummingbot/files/11270681/6235.zip)

**Comment by yancong001** [comment]
fixed @nikspz @rapcmia

**Comment by yancong001** [comment]
It seems that a fee of less than 0.01 is not shown specifically @rapcmia

**Comment by rapcmia** [comment]
PR update:
- Test latest commit `ba8da0a49`
    - Issue on CSV has been fixed
    - Unrealized PnL fixed for short position
    - Observed Stop loss for long/short position, issue fixed 

Pending:
- Observe behavior on long term bot

**Comment by rapcmia** [comment]
- Review long term bot running for 5hrs now
    - Open position and take-profit or stop-loss created
        - For stop loss orders are immediately filled and most likely due to the spread we used but all recorded (adjusted for remaining hours)
    - Checked trade data between history, CSV and kucoin_perp trade history, all matched (sometimes check the fill price)
        image
        - Fee percentage matched
        - Assuming fees displayed on bot are estimated since kucoin_perpetual wont display values below 0.01
        - Partial fills are recorded as well
        
Pending
- Long term bot running for few more hours to observe connector behavior. PR is good to be approved 🙇🏼

**Pull request merged**
