### PR TITLE
(fix) fix incorrect_websocket_account_position

### PR DESCRIPTION
**Pull request by yancong001**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
The connector attempted to delete a key in an non-existent attribute of the class and place order with incorrect amount. Partially addressing hummingbot https://github.com/hummingbot/hummingbot/issues/6032

**Tests performed by the developer**:
Run perpetual market making strategy
Bot able to retrieving the data of the open position.
Bot able to place order to CLOSE with correct amount

**Tips for QA testing**:

### CODE REVIEW

**Comment by rapcmia** [comment]
Hi @yancong001 good day
PR is good for approval, would you please take a look on the GitHub failed tests. Thank you 
image

**Comment by yancong001** [comment]
> Hi @yancong001 good day PR is good for approval, would you please take a look on the GitHub failed tests. Thank you image

fixed

**Review by rapcmia — APPROVED** [review]
LGTM

**Review by cardosofede — APPROVED** [review]
LGTM!

**Pull request merged**
