### PR TITLE
feat/connector-southxchange

### PR DESCRIPTION
**Pull request by Nicolasjmh789**
**Before submitting this PR, please make sure**:

* [ ] Your code builds clean without any errors or warnings
* [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1t1hm8f) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by Nicolasjmh789** [comment]
Hello @aarmoa @dennisocana I wanted to ask you how to know what is the status of the SouthXchange connector pull request and what are the steps to follow. Thanks

**Comment by dennisocana** [comment]
@Nicolasjmh789 thanks for submitting a pull request. For integrating the connector to the codebase, please notify and send an email to partnerships@hummingbot.io

**Comment by Nicolasjmh789** [comment]
Hi @dennisocana, I wanted to consult you, I sent an email to the address you told me, advising that the pull request was already done to integrate a new connector, but I had no response. Do you know if you have to do something else? Thanks

**Comment by dennisocana** [comment]
@Nicolasjmh789 I will notify them directly to check the email you sent.

**Comment by Nicolasjmh789** [comment]
Thanks very much! @dennisocana

**Comment by Nicolasjmh789** [comment]
Hi @dennisocana , I wanted to ask you if you can run the verifications of the arrangements that were made in the pull request. Thanks

**Comment by dennisocana** [comment]
@Nicolasjmh789 ok done

**Comment by Nicolasjmh789** [comment]
Hi @dennisocana , sorry to bother you but the failure that arises from the verification, when I do the tests does not happen. supposedly there is not southxchange_api_key in ../templates/conf_global_TEMPLATE.yml, and checking if I add it. Any idea what could it be? Thanks very much

**Comment by Nicolasjmh789** [comment]
Hi @dennisocana , I wanted to ask you if you can run the verifications of the arrangements that were made in the pull request. Thanks

**Comment by Nicolasjmh789** [comment]
Hi @dennisocana , I wanted to ask you if you can run the fix checks that were made in the pull request. And I would appreciate if you could guide me in the implementation of the connector. Thanks

**Comment by phbrgnomo** [comment]
Hello @Nicolasjmh789 

The Hummingbot Foundation just started the governance process for the community to approve or reject Pull Requests through **Pull Request Proposals**.

For more information about how PRP votes work, check this page: https://hummingbot.org/governance/prp/

We want to know if you still have interest in having your Pull Request merged into the main codebase.

If so, please check the following on your Pull Request for our team to be able to open it for community voting:

- Your Pull Request is targeted to the `development` branch
- Your branch is up to date with the current `development` branch
- All GitHub checks have passed
- There is no merging conflicts

If you have any questions or need any help, feel free to reach us out on the #dev-general channel on our Discord (https://discord.gg/HAgZ79nzU4)

----
If you have no interest in merging this PR to our code-base or don't reply to this comment in 30 days, the Foundation team will close this PR.

You can still create a new PR any time you want!

Thank you for contributing to Hummingbot Client!

**Comment by Nicolasjmh789** [comment]
Hello @phbrgnomo,
Yes, I am interested in having my Pull Request merged with the main codebase.

My Pull Request I believe has all the requirements for your team to open it for the community to vote on. I just have a question about the requirements:

* All GitHub checks have passed
How would I have to verify it?

**Comment by phbrgnomo** [comment]
Since this was your first contribution to the Repo i had to manually start the tests. Check back later to see if all of them pass.

**Comment by Nicolasjmh789** [comment]
Hi @phbrgnomo , from what I was seeing from the errors, the problem is in the tests of another connector. How can I fix it?

**Comment by phbrgnomo** [comment]
@Nicolasjmh789 reach one of our team members on our discord on the #dev-connectors  channel for help.

**Comment by Nicolasjmh789** [comment]
Hi @phbrgnomo , I commented my problem in the discord channel but I had no luck. the "build + stable tests (pull_request)" can I run them myself? Thanks

**Comment by aarmoa** [comment]
Hello @Nicolasjmh789. To provide the technical approval for the connector it has to be implemented following the latest standards. The reference is the Binance spot connector. Please let us know if it will be possible for you to apply the required changes.

**Comment by Nicolasjmh789** [comment]
Hello @aarmoa , I'm sorry, but I didn't understand what you were saying. Should I rewrite my connector?

**Comment by aarmoa** [comment]
Hello @Nicolasjmh789. Yes, please follow the structure of Binance spot connector.

**Comment by JeremyKono** [comment]
Hi @Nicolasjmh789, please update your PR or we will close this PR as tech review dao already left a comment

**Comment by Nicolasjmh789** [comment]
Hi @JeremyKono, I would like to have more time to update this PR, because I have to study the binance connector.

**Comment by Nicolasjmh789** [comment]
Hi @aarmoa and @JeremyKono , If possible, I would like you to review this PR, the necessary and required modifications would already have been made. I look forward to hearing from you.

**Comment by Nicolasjmh789** [comment]
Hi @rapcmia @nikspz @aarmoa @JeremyKono  , could you please check the new modifications made in this PR. Thanks

**Comment by Nicolasjmh789** [comment]
Hi @rapcmia @nikspz @aarmoa @JeremyKono, sorry for the inconvenience, the error that was occurring has been corrected. Could you please check this PR

**Comment by Nicolasjmh789** [comment]
Hi @rapcmia @nikspz @aarmoa @JeremyKono, I see the PR passed the checks, I would like to know what are the next steps to implement the connector

**Comment by Nicolasjmh789** [comment]
Hi @rapcmia @nikspz, , could you tell me what is the estimated time to approve this pr of connector?

**Comment by JeremyKono** [comment]
Hi @Nicolasjmh789, can you please create a PRP for this? We do not merge in and tests PRs unless a PRP is created.

**Comment by Nicolasjmh789** [comment]
Thank you very much @JeremyKono , now that I did it what should I do?

**Pull request closed without merging**
