### PR TITLE
Fix/mexc modify python connector

### PR DESCRIPTION
**Pull request by MXCDev**
Python-only implementation. Refer to Ndax.
Usage of NetworkMockingAssistant and aioresponses module for unit testing. Refer to Ndax unit tests.
Single websocket connection for public websocket channels. Refer to NdaxAPIOrderBookDataSource.listen_for_order_book_diffs or
CryptoComAPIOrderBookDataSource
Shared aiohttp.ClientSession obj across all components.
Integrate AsyncThrottler into Mexc connector.

### CODE REVIEW

**Comment by dennisocana** [comment]
Requesting for code review from @petioptrv and testing from QA team @RC-13 .

**Review by petioptrv — CHANGES_REQUESTED** [review]
Thank you for making the requested changes. Overall, the code looks great.

I've requested a couple of changes in the test cases. Apologies if those problems exist in the code you have used as template. We are actively working on improving the code, so it's easy for a given piece of code to quickly fall behind the latest practices we are introducing in the codebase.

The `asyncio.sleep` one is particularly important because we want to make sure the tests execute quickly so that developers run them often, but async-sleeping guarantees to add `0.3` seconds to the overall run for each test case using that technique. These, as you can imagine, stack up quickly.

Thank you for your understanding

**Review by RC-13 — APPROVED** [review]
Confirmed working by QA, LGTM!

**Comment by petioptrv** [comment]
@RC-13, the changes I've requested are only in the test cases, so they won't invalidate your approval

**Comment by MXCDev** [comment]
@petioptrv   all fixed.

**Comment by dennisocana** [comment]
@MXCDev please see failing test from Github validation.

image

**Comment by dennisocana** [comment]
@petioptrv I have informed @MXCDev to fix the flake8 error found by Github validation. Please proceed with reviewing the recent commits.

**Review by petioptrv — APPROVED** [review]
Changes LGTM! Thank you for your contribution. This is well written code.

**Review by petioptrv — APPROVED** [review]

**Review by dennisocana — APPROVED** [review]

**Pull request merged**
