### PR TITLE
Feat/add gateio spot perpetual candles

### PR DESCRIPTION
**Pull request by yancong001**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Add gateio spot&perpetual candles following binance structure
Standardize interval management (1m vs 1min vs ...)

**Tests performed by the developer**:

unittest, scripts/candles_example.py

**Tips for QA testing**:
```
For gateio spot
# Replace in scripts/candles_example.py

eth_1m_candles = CandlesFactory.get_candle(connector="gateio",
                                           trading_pair="ETH-USDT",
                                           interval="1m", max_records=50)
eth_1h_candles = CandlesFactory.get_candle(connector="gateio",
                                           trading_pair="ETH-USDT",
                                           interval="1h", max_records=50)
eth_1w_candles = CandlesFactory.get_candle(connector="gateio",
                                           trading_pair="ETH-USDT",
                                           interval="4h", max_records=50)```
For gateio perpetual
# Replace in scripts/candles_example.py

eth_1m_candles = CandlesFactory.get_candle(connector="gateio_perpetual",
                                           trading_pair="ETH-USDT",
                                           interval="1m", max_records=50)
eth_1h_candles = CandlesFactory.get_candle(connector="gateio_perpetual",
                                           trading_pair="ETH-USDT",
                                           interval="1h", max_records=50)
eth_1w_candles = CandlesFactory.get_candle(connector="gateio_perpetual",
                                           trading_pair="ETH-USDT",
                                           interval="4h", max_records=50)```
```

### CODE REVIEW

**Comment by yancong001** [comment]
Now I have two problems.
First,For gateio_perpetual, I changed max_records to 500, which may cause the script to not work properly.
```
eth_1h_candles = CandlesFactory.get_candle(connector="gateio_perpetual",
                                           trading_pair="ETH-USDT",
                                           interval="1h", max_records=500)
```
Second, gateio doesn't have these fields, so what I do is I set them to 0 by default
'n_trades, taker_buy_base_volume, taker_buy_quote_volume, quote_asset_volume'

**Comment by yancong001** [comment]
hi, @nikspz ,about `1m values for gate.io perpetual got incorrect OHLC values`
I have carefully compared and checked the api data and the web data, and I am convinced that the OHLC data display on gateio perpetual web page is sometimes wrong.
I've been in touch with gateioperpetual and raised the display bug on the web page.

Here is the data for 2023-06-02 14:54:00 (UTC+8)
### web page
OHLC：1889.30, 1889.30, 1888.55, 1888.80
volume：150.97
### restful api data
OHLC：1889.90, 1889.10, 1888.55, 1888.75
volume：160.97
### websocket api data
OHLC：1889.90, 1889.10, 1888.55, 1888.80
volume：150.97
image
restful api data:
[{'o': '1888.9', 'v': 16097, 't': 1685688840, 'c': '1888.75', 'l': '1888.55', 'h': '1889.1', 'sum': '304043.5'}]
image

But so far (2023-06-02 15:21:00 (UTC+8)), gateio officials have not given me feedback on the completion of the repair.

Therefore, in my opinion, `1m values for gate.io perpetual got incorrect OHLC values`, which can be ignored for the time being

**Comment by yancong001** [comment]
The following is gateio's official reply

>Hello, the reply I received is that K-line data is aggregated in real time, and ws is not consistent with API and web data query mechanism, so there may be some time difference in aggregation. At some point, the megabytes of data will briefly disagree, but eventually they will agree. Even though the current K-line time range may have run out, there is a second-level delay in updating the data behind it. Check the K-line interval over time, and it'll match.
>And then we're still looking at the specifics of that

**Comment by yancong001** [comment]
So my conclusion is that restful data is accurate, but the real-time 1 minute data we get from websocket  is sometimes not accurate.
The solution I came up with is to temporarily disable 1m interval. Do you have any good ideas? @cardosofede

**Review by cardosofede — CHANGES_REQUESTED** [review]
Hey @yancong001 good job as usual.
Some things to change:
- The name of the candles should match with the connector so probably we should call it gate_io and gate_io_perpetual
image
- I think that we shouldn't disable the 1m timeframe if it's not accurate, as the response of the gate io team is that it will reconcile, at some point the value will be the same. Probably, the best solution is to add a warning in the init of the candle if the timeframe selected is 1m

**Comment by nikspz** [comment]
@yancong001 Could you change `not very accurate` to `not accurate`?
image

**Comment by yancong001** [comment]
fixed

**Review by cardosofede — APPROVED** [review]
LGTM!

**Pull request merged**
