### PR TITLE
feat/woo-x_connector

### PR DESCRIPTION
**Pull request by waterquarks**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Implementation of a `SPOT CLOB CEX` connector for [Woo X](https://woo.org).

API documentation is available at [docs.woo.org](https://docs.woo.org/#general-information).

Click [here](https://snapshot.org/#/hbot-prp.eth/proposal/0x46c15f8b9cbbd97ebc8b83340bd748d5f68e84082d24383b91abdc3d8b9168c6) to see the associated PRP.

**Tests performed by the developer**:

All tests in the "QA" section of the [Spot Connector v2.1 spec](https://hummingbot-foundation.notion.site/Spot-Connector-v2-1-1cc43830938445c9974f43ef861d59f1) were performed successfully excepting the "Multiple orders" entry, as the API rate limit for the `Send order` endpoint is 2 requests per 1 second.

**Tips for QA testing**:

Besides public & private API keys, Woo X requires an application ID for interacting with its API. Instructions on how to create all of these can be found [here](https://support.woo.org/hc/en-001/articles/4410291152793--How-do-I-create-the-API-).

### CODE REVIEW

**Comment by waterquarks** [comment]
Hi @MHHukiewitz thanks for raising this, please know that the proposal has been cancelled. I'll be opening a thread in the #proposals channel @ Hummingbot's Discord so that your concerns and those of the wider community can be addressed transparently; we can try submitting another proposal afterwards. How about we continue our conversation over there?

**Comment by nikspz** [comment]
@waterquarks Could you please fix conflicts on PR?

Currently failed to connect testnet wallet, requested testnet wallet and API keys requisites in discord
image

**Comment by nikspz** [comment]
@waterquarks Could you please fix conflicts and update branch with latest development changes (PR is outdated (dev-1.17.0))

**Comment by nikspz** [comment]
hi @waterquarks Could you please add updates about the updating PR6380 with latest dev branch changes status? Thanks

**Comment by waterquarks** [comment]
Hi @nikspz please know that the pull request has been updated to the latest dev. branch changes.

**Comment by waterquarks** [comment]
> Currently failed to connect testnet wallet, requested testnet wallet and API keys requisites in discord

Just as a heads to readers in this thread, had shared testned credentials for access to the exchange some time ago.

**Review by nikspz — APPROVED** [review]
Tests performed:
- Cloned and installed feature branch
- Start Client without issues related to Woo-x connector
- Connected woo_x_testnet API keys successfully
- Checked balance matched with the exchange
- Created/imported strategy using woo_x_testnet
- Started strategy successfully
- Order execution: ok
- Checked status --live and order_book --live matched with exchange

Note: as bronze tier exchange tested using testnet connector  
pending dev review

**Review by cardosofede — APPROVED** [review]
LGTM!

**Pull request merged**
