### PR TITLE
Update DOCKER.md

### PR DESCRIPTION
**Pull request by notabombe**
The first line under ## Development commands: deploying to Docker Hub could be rephrased to The following commands apply to deploying to Docker Hub.

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Review by fengtality — APPROVED** [review]
LGTM - Thanks for clarifying the instructions!

**Review by notabombe — COMMENTED** [review]
Please reopen the pull request, i closed it without merging please

**Review by nikspz — APPROVED** [review]

**Comment by notabombe** [comment]
Thank you @nikspz

**Comment by notabombe** [comment]
@nikspz please how can i be added a contributor

**Comment by fengtality** [comment]
it will show up after these changes are merged to the master branch in the
next release

**Pull request merged**
