### PR TITLE
Feat/funding rate arb script

### PR DESCRIPTION
**Pull request by cardosofede**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Add the script of funding rate arbitrage.
Explanation: https://notability.com/n/1CHLpIL6O9GuUqTOJ9pHjl

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by fengtality** [comment]
I tried this on Hyperliquid and Kraken (spot). Got the following error in the logs:
```
2024-04-03 15:22:21,000 - 74151 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/strategy_py_base.pyx", line 44, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_tick
    self.tick(timestamp)
  File "/Users/feng/hummingbot/hummingbot/strategy/script_strategy_base.py", line 75, in tick
    self.on_tick()
  File "/Users/feng/hummingbot/hummingbot/strategy/strategy_v2_base.py", line 279, in on_tick
    executor_actions: List[ExecutorAction] = self.determine_executor_actions()
  File "/Users/feng/hummingbot/hummingbot/strategy/strategy_v2_base.py", line 288, in determine_executor_actions
    actions.extend(self.create_actions_proposal())
  File "/Users/feng/hummingbot/scripts/funding_rate_arb.py", line 202, in create_actions_proposal
    funding_info_report = self.get_funding_info_by_token(token)
  File "/Users/feng/hummingbot/scripts/funding_rate_arb.py", line 125, in get_funding_info_by_token
    funding_rates[connector_name] = connector.get_funding_info(trading_pair)
AttributeError: 'KrakenExchange' object has no attribute 'get_funding_info'

```

**Comment by cardosofede** [comment]
> I tried this on Hyperliquid and Kraken (spot). Got the following error in the logs:
> 
> ```
> 2024-04-03 15:22:21,000 - 74151 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
> Traceback (most recent call last):
>   File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
>     child_iterator.c_tick(self._current_tick)
>   File "hummingbot/strategy/strategy_py_base.pyx", line 44, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_tick
>     self.tick(timestamp)
>   File "/Users/feng/hummingbot/hummingbot/strategy/script_strategy_base.py", line 75, in tick
>     self.on_tick()
>   File "/Users/feng/hummingbot/hummingbot/strategy/strategy_v2_base.py", line 279, in on_tick
>     executor_actions: List[ExecutorAction] = self.determine_executor_actions()
>   File "/Users/feng/hummingbot/hummingbot/strategy/strategy_v2_base.py", line 288, in determine_executor_actions
>     actions.extend(self.create_actions_proposal())
>   File "/Users/feng/hummingbot/scripts/funding_rate_arb.py", line 202, in create_actions_proposal
>     funding_info_report = self.get_funding_info_by_token(token)
>   File "/Users/feng/hummingbot/scripts/funding_rate_arb.py", line 125, in get_funding_info_by_token
>     funding_rates[connector_name] = connector.get_funding_info(trading_pair)
> AttributeError: 'KrakenExchange' object has no attribute 'get_funding_info'
> ```

I mentioned that only works between perps, does not support spot-perp

**Comment by rapcmia** [comment]
PR update:
- Setup script on 3 exchanges. Selected markets are not available on one of the exchanges:
  - Script returns `unhandled error` related to the non existing market pair 
  - Script is stuck on exchange not ready ❌ 
  - Does not continue to check the other exchanges that has market pairs ❌ 
  ```
  2024-04-04 12:33:44,962 - 424991 - hummingbot.client.hummingbot_application - INFO - start command initiated.
  2024-04-04 12:33:45,070 - 424991 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - ERROR - Position mode PositionMode.HEDGE is not supported. Mode not set.
  2024-04-04 12:33:45,408 - 424991 - hummingbot.connector.derivative.okx_perpetual.okx_perpetual_derivative.OkxPerpetualDerivative - NETWORK - Error setting leverage 20 for SEI-USDT: ret_code <51001> - Instrument ID doesn't exist
  2024-04-04 12:33:45,421 - 424991 - hummingbot.connector.derivative.okx_perpetual.okx_perpetual_derivative.OkxPerpetualDerivative - NETWORK - Error setting leverage 20 for LOOM-USDT: ret_code <51001> - Instrument ID doesn't exist
  2024-04-04 12:33:45,424 - 424991 - hummingbot.connector.derivative.okx_perpetual.okx_perpetual_derivative.OkxPerpetualDerivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
  2024-04-04 12:33:45,552 - 424991 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'LOOM-USDT-SWAP'
  Traceback (most recent call last):
    File "/home/ralph/github/hummingbot/6943/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
      return await c
    File "/home/ralph/github/hummingbot/6943/hummingbot/core/data_type/order_book_tracker.py", line 180, in _init_order_books
      self._order_books[trading_pair] = await self._initial_order_book_for_trading_pair(trading_pair)
    File "/home/ralph/github/hummingbot/6943/hummingbot/core/data_type/order_book_tracker.py", line 173, in _initial_order_book_for_trading_pair
      return await self._data_source.get_new_order_book(trading_pair)
    File "/home/ralph/github/hummingbot/6943/hummingbot/core/data_type/order_book_tracker_data_source.py", line 65, in get_new_order_book
      snapshot_msg: OrderBookMessage = await self._order_book_snapshot(trading_pair=trading_pair)
    File "/home/ralph/github/hummingbot/6943/hummingbot/connector/derivative/okx_perpetual/okx_perpetual_api_order_book_data_source.py", line 48, in _order_book_snapshot
      ct_val = self._trading_rules[ex_trading_pair]
  KeyError: 'LOOM-USDT-SWAP'
  2024-04-04 12:33:45,594 - 424991 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
  2024-04-04 12:33:46,184 - 424991 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - INFO - Leverage for LOOM-USDT successfully set to 20.
  2024-04-04 12:33:46,185 - 424991 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - INFO - Leverage for SEI-USDT successfully set to 20.
  2024-04-04 12:33:46,186 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:33:46,187 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - kucoin_perpetual is not ready. Please wait...
  2024-04-04 12:33:46,187 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
  2024-04-04 12:33:46,528 - 424991 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: list index out of range
  Traceback (most recent call last):
    File "/home/ralph/github/hummingbot/6943/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
      return await c
    File "/home/ralph/github/hummingbot/6943/hummingbot/connector/perpetual_derivative_py_base.py", line 364, in _listen_for_funding_info
      await self._init_funding_info()
    File "/home/ralph/github/hummingbot/6943/hummingbot/connector/perpetual_derivative_py_base.py", line 371, in _init_funding_info
      funding_info = await self._orderbook_ds.get_funding_info(trading_pair)
    File "/home/ralph/github/hummingbot/6943/hummingbot/connector/derivative/okx_perpetual/okx_perpetual_api_order_book_data_source.py", line 120, in get_funding_info
      index_price = funding_info_response[0]["data"][0]
  IndexError: list index out of range
  2024-04-04 12:33:46,712 - 424991 - hummingbot.connector.derivative.okx_perpetual.okx_perpetual_api_order_book_data_source.OkxPerpetualAPIOrderBookDataSource - INFO - Subscribed to public order book, trade and funding info channels...
  2024-04-04 12:33:46,838 - 424991 - hummingbot.connector.derivative.okx_perpetual.okx_perpetual_user_stream_data_source.OkxPerpetualUserStreamDataSource - INFO - Subscribed to private account and orders channels wss://ws.okx.com:8443/ws/v5/private...
  2024-04-04 12:33:46,842 - 424991 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for LOOM-USDT. 1/2 completed.
  2024-04-04 12:33:47,089 - 424991 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
  2024-04-04 12:33:47,150 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:33:47,151 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - kucoin_perpetual is not ready. Please wait...
  2024-04-04 12:33:47,151 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
  2024-04-04 12:33:47,340 - 424991 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - INFO - Leverage for LOOM-USDT successfully set to 20.
  2024-04-04 12:33:47,658 - 424991 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - INFO - Leverage for SEI-USDT successfully set to 20.
  2024-04-04 12:33:47,755 - 424991 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_user_stream_data_source.BinancePerpetualUserStreamDataSource - INFO - Successfully obtained listen key o1zZqADR1wQCyeZHxOBtqVI7wS6Fi1vfkcE4BSb3mjg9S6nK33ZqHatLmUnuJCOH
  2024-04-04 12:33:47,757 - 424991 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - INFO - Subscribed to public order book, trade and funding info channels...
  2024-04-04 12:33:47,766 - 424991 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for LOOM-USDT. 1/2 completed.
  2024-04-04 12:33:48,002 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:33:48,003 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - kucoin_perpetual is not ready. Please wait...
  2024-04-04 12:33:48,003 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
  2024-04-04 12:33:48,081 - 424991 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for SEI-USDT. 2/2 completed.
  2024-04-04 12:33:48,348 - 424991 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_api_order_book_data_source.KucoinPerpetualAPIOrderBookDataSource - INFO - Subscribed to public order book, trade and funding info channels...
  2024-04-04 12:33:48,697 - 424991 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_api_user_stream_data_source.KucoinPerpetualAPIUserStreamDataSource - INFO - Subscribed to private account and orders channels wss://stream.kucoin.com/realtime_private...
  2024-04-04 12:33:48,862 - 424991 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for SEI-USDT. 2/2 completed.
  2024-04-04 12:33:49,053 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:33:49,053 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - kucoin_perpetual is not ready. Please wait...
  2024-04-04 12:33:49,054 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
  2024-04-04 12:33:50,001 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:33:51,015 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:33:52,043 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:33:53,030 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:33:54,167 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:33:55,001 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:33:56,021 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:33:57,041 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:33:58,046 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:33:59,053 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:34:00,019 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:34:01,061 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:34:02,103 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:34:03,000 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:34:04,077 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:34:05,066 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:34:06,002 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:34:07,001 - 424991 - hummingbot.strategy.script_strategy_base - WARNING - okx_perpetual is not ready. Please wait...
  2024-04-04 12:34:07,529 - 424991 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
  ```

[conf_funding_rate_arb_1a.yml.log](https://github.com/hummingbot/hummingbot/files/14869305/conf_funding_rate_arb_1a.yml.log) `remove .log`


Suggestion: 
  - Would it be possible that to return an error that the markets are not available and automatically stop the script?

**Comment by nikspz** [comment]
Commit 6842f3d

Tests performed:
- Cloned installed PR 6943
- Failed to start arbitrage using min_funding_rate_profitability 0.001

```
min_funding_rate_profitability: 0.001
connectors:
- hyperliquid_perpetual
- binance_perpetual
position_size_quote: 70
profitability_to_take_profit: 0.001
```

- Set tight min_funding_rate_profitability: 0.0001
    - Filled OPEN orders for both binance and hyperliquid perpetual
    
image

    
image

    
- We need to add example in script funding_rate_arb.yml
    - WHY:
        - current status reports in %
            
image

            
        - and we set up as 0.001
            - we need to add that 0.001 here is 0.1%
image

**Comment by nikspz** [comment]
Commit https://github.com/hummingbot/hummingbot/commit/6842f3d0884803479711498f7f724c2b330b29f3

Test performed:
ran the funding rate script with the config:
```
markets: {}
candles_config: []
controllers_config: []
config_update_interval: 60
script_file_name: funding_rate_arb.py
leverage: 10
min_funding_rate_profitability: 0.0001
connectors:
- hyperliquid_perpetual
- binance_perpetual
tokens:
- WIF
- FET
position_size_quote: 70
profitability_to_take_profit: 0.001
```

Review bot OPENed position at 0.01% profit (tight spread)

Get trades on both WIF and FET pairs, 
for FET:
funding fees is ~ same, ~22hours passed (+0.03 on binance vs -0.03 on HPL)
position PNL is `-0.14usdt` (+2.74 - 2.88) `- commisions payments` (open-close fees on both exchanges)

FET pumped on binance at ~6:15pm (UTC+7), so bot closed positions there

for WIF, max leverage available on HPL is 5, however config had 10, so `bot used leverage 1 for trades` (instead of 10)
image

Steps:
1. Create script config with leverage more than exchange supported
2. Start the script with config

Actual:
bot used leverage 1 for trades with leverage more than supported

**Comment by rapcmia** [comment]
PR update
- Review bot running for 8hrs, no opportunity for min_profitability of 0.7% ✅ 
- Latest commit now displays `Min funding Rate Profitability` on status 
   image
- Setup a script with tight min_funding_rate_profitability and profitability_to_take_profit to observe behavior
  - Best combination found and created market orders to open position ✅ 
  - Take profit rate reached and successfully close position ok ✅
- Manually close the positions while the script is running
  - The script did not recognized that the position has been closed by user manually ❌ 
  - Run `stop` command resulted to `OSError: Error submitting order 93027a12dac34fBCSLCUT740b72b1857: Order failed. You don't have any positions in this contract that can be closed.`
    ```
    # stop command initialized
    2024-04-05 07:17:54,449 - 462009 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
    2024-04-05 07:17:54,449 - 462009 - hummingbot.strategy.script_strategy_base - INFO - Creating LTC-USDT sell order: price: NaN amount: 0.30.
    2024-04-05 07:17:54,838 - 462009 - hummingbot.connector.derivative.okx_perpetual.okx_perpetual_derivative.OkxPerpetualDerivative - NETWORK - Error submitting sell MARKET order to Okx_perpetual for 0.3 LTC-USDT NaN.
    Traceback (most recent call last):
      File "/home/ralph/github/hummingbot/6943/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
        await self._place_order_and_process_update(order=order, **kwargs,)
      File "/home/ralph/github/hummingbot/6943/hummingbot/connector/exchange_py_base.py", line 469, in _place_order_and_process_update
        exchange_order_id, update_timestamp = await self._place_order(
      File "/home/ralph/github/hummingbot/6943/hummingbot/connector/derivative/okx_perpetual/okx_perpetual_derivative.py", line 280, in _place_order
        raise IOError(f"Error submitting order {order_id}: {data['sMsg']}")
    OSError: Error submitting order 93027a12dac34fBCSLCUT740b72b1857: Order failed. You don't have any positions in this contract that can be closed. 
    ```
  - Script stuck on creating order until client we `exit` command
    ```
    2024-04-05 07:17:55,473 - 462009 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Open amount: 0.30, Close amount: 0
    2024-04-05 07:17:55,473 - 462009 - hummingbot.strategy.script_strategy_base - INFO - Creating LTC-USDT sell order: price: NaN amount: 0.30.
    2024-04-05 07:17:55,473 - 462009 - hummingbot.smart_components.executors.position_executor.position_executor - ERROR - Market object for sell order is not in the whitelisted markets set.
    Traceback (most recent call last):
      File "/home/ralph/github/hummingbot/6943/hummingbot/smart_components/smart_component_base.py", line 69, in control_loop
        await self.control_task()
      File "/home/ralph/github/hummingbot/6943/hummingbot/smart_components/executors/position_executor/position_executor.py", line 261, in control_task
        await self.control_shutdown_process()
      File "/home/ralph/github/hummingbot/6943/hummingbot/smart_components/executors/position_executor/position_executor.py", line 291, in control_shutdown_process
        self.place_close_order_and_cancel_open_orders(close_type=self.close_type)
      File "/home/ralph/github/hummingbot/6943/hummingbot/smart_components/executors/position_executor/position_executor.py", line 395, in place_close_order_and_cancel_open_orders
        order_id = self.place_order(
      File "/home/ralph/github/hummingbot/6943/hummingbot/smart_components/executors/executor_base.py", line 278, in place_order
        return self._strategy.sell(connector_name, trading_pair, amount, order_type, price, position_action)
      File "/home/ralph/github/hummingbot/6943/hummingbot/strategy/script_strategy_base.py", line 131, in sell
        return self.sell_with_specific_market(market_pair, amount, order_type, price, position_action=position_action)
      File "hummingbot/strategy/strategy_base.pyx", line 550, in hummingbot.strategy.strategy_base.StrategyBase.sell_with_specific_market
        return self.c_sell_with_specific_market(market_trading_pair_tuple, amount,
      File "hummingbot/strategy/strategy_base.pyx", line 573, in hummingbot.strategy.strategy_base.StrategyBase.c_sell_with_specific_market
        raise ValueError(f"Market object for sell order is not in the whitelisted markets set.")
    ValueError: Market object for sell order is not in the whitelisted markets set.
    2024-04-05 07:17:56,543 - 462009 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Open amount: 0.30, Close amount: 0
    2024-04-05 07:17:56,543 - 462009 - hummingbot.strategy.script_strategy_base - INFO - Creating LTC-USDT sell order: price: NaN amount: 0.30.
    2024-04-05 07:17:56,543 - 462009 - hummingbot.smart_components.executors.position_executor.position_executor - ERROR - Market object for sell order is not in the whitelisted markets set.
    Traceback (most recent call last):
      File "/home/ralph/github/hummingbot/6943/hummingbot/smart_components/smart_component_base.py", line 69, in control_loop
        await self.control_task()
      File "/home/ralph/github/hummingbot/6943/hummingbot/smart_components/executors/position_executor/position_executor.py", line 261, in control_task
        await self.control_shutdown_process()
      File "/home/ralph/github/hummingbot/6943/hummingbot/smart_components/executors/position_executor/position_executor.py", line 291, in control_shutdown_process
        self.place_close_order_and_cancel_open_orders(close_type=self.close_type)
      File "/home/ralph/github/hummingbot/6943/hummingbot/smart_components/executors/position_executor/position_executor.py", line 395, in place_close_order_and_cancel_open_orders
        order_id = self.place_order(
      File "/home/ralph/github/hummingbot/6943/hummingbot/smart_components/executors/executor_base.py", line 278, in place_order
        return self._strategy.sell(connector_name, trading_pair, amount, order_type, price, position_action)
      File "/home/ralph/github/hummingbot/6943/hummingbot/strategy/script_strategy_base.py", line 131, in sell
        return self.sell_with_specific_market(market_pair, amount, order_type, price, position_action=position_action)
      File "hummingbot/strategy/strategy_base.pyx", line 550, in hummingbot.strategy.strategy_base.StrategyBase.sell_with_specific_market
        return self.c_sell_with_specific_market(market_trading_pair_tuple, amount,
      File "hummingbot/strategy/strategy_base.pyx", line 573, in hummingbot.strategy.strategy_base.StrategyBase.c_sell_with_specific_market
        raise ValueError(f"Market object for sell order is not in the whitelisted markets set.")
    ValueError: Market object for sell order is not in the whitelisted markets set.
    ```
     - See attach for the logs and script file [04042024a.zip](https://github.com/hummingbot/hummingbot/files/14882835/04042024a.zip)
 - Run script for 20mins and execute `stop` command
     image
      - Stuck on `wating for close order to be filled..`
      - The last two market orders on okx perpetual with open amount of `0.3` and `4` did not have a order filled event and caused this issue 
      - Check OKX trade history:
        - Converted timestamps matched from logs and exchange data, the script seems to missed the filled order form the ex change 
          image
           - The orders on the screenshot is not available on the data folder and CSV file of hummingbot client ❌ 
      - See attach logs and script file [04042024b.zip](https://github.com/hummingbot/hummingbot/files/14883176/04042024b.zip)

---

- Open a separate ticket related to OKX perpetual found when testing this PR https://github.com/hummingbot/hummingbot/issues/6953

**Comment by rapcmia** [comment]
PR update:
- Test commit `aa5b1dd82afa972856250bacda8ea73bbeda8906`
- Recreate script with the new added params for stop loss
- Ran tests using 3 perpetual exchanges
    - Setup rate profitability enough to trigger early best combination
        - Able to get best combination and check orders filled and position open between client logs and exchange, matched ok
    - When take profitability rate is reached, script stops executors by creating a market order to close position, all ok
    - On stop command, creates market order to close open position ✅
- How does `funding_rate_diff_stop_loss` work?
    - Value must be of negative number
    - Ran tests for values -0.001, -0.01 and -0.03 each running for an hour but no go yet
    - `pending`
- When checking status UI:
    image
    - The values on script seems does not match, on status should show 0.07% and 0.1%?

**Comment by nikspz** [comment]
funding_rate_diff_stop_loss

Test performed:
commit 11c4914
Negative funding_rate_diff_stop_loss
- funding_rate_diff_stop_loss: -0.0001 (hyperliquid-binanceperp)
  - not able to trigger stop loss (~1hr run)
- funding_rate_diff_stop_loss: -1.0e-05 (hyperliquid-binanceperp)
  - not able to trigger stop loss (~1.5hr run)
Positive:
- funding_rate_diff_stop_loss: 0.0005 (hyperliquid-binanceperp)
  - stop-loss triggered almost immediately
  - got message Take profit profitability reached, stopping executors (that's the issue, since take profit (1% is not reached)
  - Bot placed redundant orders on Hyperliquid to close the position, since order update was failed 
  - That results 5x more than order_amount position stuck on the exchange, had to close manually
  
[logs_conf_funding_rate_arb_plus0005.log](https://github.com/hummingbot/hummingbot/files/14921890/logs_conf_funding_rate_arb_plus0005.log)

  
Negative funding_rate_diff_stop_loss (okx-binance-perp)
- funding_rate_diff_stop_loss: -1.0e-05 (okx-binance)
  - not able to trigger stop loss (~ 3hr run)
Positive:
- funding_rate_diff_stop_loss: 0.0005 (okx-binance)
  - stop-loss triggered almost immediately, however best rate difference was more than 0.005% (0.018%)
  - bot was able to close positions succesfully
  - after that bot stuck on Take profit profitability reached, stopping executors 

[logs_conf_funding_rate_arb_plus00005stoploss.log](https://github.com/hummingbot/hummingbot/files/14921886/logs_conf_funding_rate_arb_plus00005stoploss.log)

[09-6943.zip](https://github.com/hummingbot/hummingbot/files/14921876/09-6943.zip)
image
stop-loss-0 005percents

**Comment by nikspz** [comment]
> * funding_rate_diff_stop_loss: 0.0005 (hyperliquid-binanceperp)
>   
>   * stop-loss triggered almost immediately
>   * got message Take profit profitability reached, stopping executors (that's the issue, since take profit (1% is not reached)
>   * Bot placed redundant orders on Hyperliquid to close the position, since order update was failed
>   * That results 5x more than order_amount position stuck on the exchange, had to close manually
> 
image

**Review by rapcmia — APPROVED** [review]
- Setup funding_rate_arb.py script with hyperliquid and other supported perp connectors
- Setup with 1 and 2 other perp connectors ok 
- Ran script for couple of days and observe behavior
	- Script looks for the best combination when it comes to funding fees then create market order to open position 
		- Open position matched between client and exchange
		- Trade data is recorded on CSV and exchange trade history
	- Script now looks for `profitability_to_take_profit` and `funding_rate_diff_stop_loss` rates 
		- When reached, script creates market order to close positon 
	- Script also support a condition to enter when:
		- True, both funding and trade proftability must be positive
		- False (default), can enter with positive or negative profitability
	- On `status`
		- min_funding_rate and take profit profitability is displayed
		- Best path, rate, trade pritability, days to trade and tp are displayed 
		- fund payment collected are displayed on a raw list
        - Reported issues has been addressed by developer
- Build docker image, all ok

**Pull request merged**
