### PR TITLE
docs/fees limitation in connectors page

### PR DESCRIPTION
**Pull request by sisco0**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

The changes present in this pull request are referred to the ones submitted at https://github.com/hummingbot/hummingbot/issues/4936. These changes add a new section in beaxy, blocktane, coinzoom, digifinex, kucoin, and okex markdown specific exchange documentation files present in the `documentation/docs/exchanges` path.

**Tests performed by the developer**:

The related changes have been tested to render as expected by using a _MarkDown_ compatible editor/viewer.

**Tips for QA testing**:

No further testing is needed for this specific pull request.

### CODE REVIEW

**Comment by phbrgnomo** [comment]
Hello @sisco0 

A Pull Request Proposal was created related to this PR: https://snapshot.org/#/hbot.eth/proposal/0x750537d889409af2b48decac6d0ae779cd7beb5d73a26af9b39ff608edd02f7f

Make sure to keep an eye on community reviews for the following days.

Thank you for contributing with Hummingbot Client!

**Comment by mifeng** [comment]
I think this section should be more descriptive and describe what the impact is on users. If fees are not available via API, how does that impact the `history` calculation?

**Comment by sisco0** [comment]
Could you kindly answer to the question @dennisocana ?

**Comment by genecheon** [comment]
Closing this PR as we have migrated the documentation repository here: https://github.com/hummingbot/hummingbot-site

**Pull request closed without merging**
