### PR TITLE
(feat) modify start.sh command to use quickstart arguments

### PR DESCRIPTION
**Pull request by david-hummingbot**
references issue - https://github.com/hummingbot/hummingbot/issues/6564

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

- Cloned branch, compiled and started client using the modified `./start` command
- Test `./start` command passing the `-p` password parameter (only works using environment variables)

**Tips for QA testing**:

### CODE REVIEW

**Comment by nikspz** [comment]
- Test performed:
    - Cloned and installed feature branch
    - Created new text+number Pas11 password after ./start, passed successfully
    - Trying to pass using ./start -p Pas11 - Failed (Client asking for password)
    - Trying to pass using ./start -p 'Pas11' - Failed (Client asking for password)
    - Trying to pass using ./start Pas11 - Failed (Client asking for password)
    - Created paper.yml strategy
    - Trying to pass using ./start -f paper.yml -p Pas11 - Failed (Client asking for password)
    - set new env variable pass: `export pass=Pas11`
    - ./start -p pass - Client started successfully
    - ./start -f paper.yml -p pas11 - Client started successfully, strategy do `not started`
    - set new env variable strat: `export CONFIG_FILE_NAME=paper.yml`
    - ./start -f CONFIG_FILE_NAME - Typed password manually, `strategy started successfully`
    - ./start -p pass -f CONFIG_FILE_NAME - Client started successfully, strategy started `successfully`

**Review by cardosofede — APPROVED** [review]
LGTM! good job @david-hummingbot 

did you tried to pass the arguments?

**Comment by nikspz** [comment]
Fresh installation. commit c52846e7d1b4629571734dfb9854731fe9c09d9c
Steps:
Clone and install PR, source installation, ubuntu 
start the client with bin/hummingbot.py Set up password `a`
exit client
try to start the bot with ./start command

Actual: bot failed to start

Expected: bot starts and requests for password

6566 c52846e09d9c

**Comment by nikspz** [comment]
Deleted all previously set variables and retested:

- ./start -p a - success
- ./start - success
- created paper.yml
- ./start -p a -f paper.yml - success
- deleted password verification
- set new apass11
- ./start -p apass11 success

Steps:
0. set up password
1. ./start -p apass (wrong password)

Actual: no indication on wrong password / wrong strategy name

Expected: output in the terminal for wrong password / wrong strategy name


https://www.loom.com/share/ee3ccd788b95480ab216d28652255665

**Review by nikspz — APPROVED** [review]
- test performed:
    - Cloned and installed 
    - set up password `a`
    - ./start -p a - success
    - ./start - success
    - created paper.yml
    - ./start -p a -f paper.yml - success
    - deleted password verification
    - set new `Pa11` password
    - ./start -p Pa11 success
    - ./start -p Pa1123 - incorrect password warning message showing
    - ./start -p Pa11 -p nostrategy.yml - invalid filename provided warning

**Pull request merged**
