### PR TITLE
(feat) Coinbase Advanced Trade  Connector

### PR DESCRIPTION
**Pull request by MementoRC**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Connector to Coinbase Advanced Trade new exchange

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by MementoRC** [comment]
A few things to note:
   - The Exchange class was diced-up in several Mixins, which are not included yet. Additional helper dataclasses are still being thought-thru
       - API requests dice: Handles processing the errors from the Exchange at protocol level and operation (with decorators)
       - Websocket Mixin
       - Orders Mixin
       - Trading pairs Mixin
       - Exchange class takes care of the properties and creating the various composites
       
   - The User stream has been refactored (was awaiting feedback from @cardosofede, but went ahead with the design submission). Basically it is just an intermediate local queuing rather than splitting the subscription and listening
   -
   - The Endpoints re-design is still under work, basically, the endpoints are designed so that they can have a test that verifies their implementation against the web documentation, so the test will fail is the doc changes (however, it is a bit brittle)
   - 
   - Similar redesign is made on the Endpoints Responses, with plans to expand on to the Websockets

Most of that stuff is not yet included for fear of outright rejection if it is not proposed with robust testing. The approach on this dev was kind of "make it work with what exists then re-think what seems hard to implement", the dicing-up of the exchange was the first step, but the testing of the whole has just started

Anyway, submitting now is not ideal, but it will be good to have early feedback

**Comment by nikspz** [comment]
hi @MementoRC how's it going? could you add your updates here?

**Comment by MementoRC** [comment]
Hi @nikspz, the connector is close to be ready for review. The tests are all passing one by one, however when ran together they end-up having some Main event loop issues. It is a bit confusing to me to have to work with a single large file, so I broke up the `exchange` with `super()` call classes, Mixin and Protocols and I ponder whether that is acceptable.

**Comment by MementoRC** [comment]
@cardosofede I would suggest to first review some of the peripherals, like the auth, order_book, data_source. I think I pushed the `Review` button a bit too early. One of the more controversial change is the break-out of the exchange:
    - The exchange is broken out into several pieces (Mixins) like Trading Pairs/Rules, Orders, Websocket
    - The calls to Base classes are listed into SuperCalls classes related to the Mixins, for example APISuperCalls
    - The Mixins subclass the particular SuperCalls that it uses and implements the abstract methods required by ExchangePyBase
    - The exchange itself subclass the Mixins and the ExchangePyBase

This structure seemed much less confusing to me, but I would not be surprised it others think it is more confusing - Ideally, I would have had the knowledge and coding speed of my imagination, alas, such is not the case ... maybe I should do another PR

**Comment by nikspz** [comment]
hi @MementoRC how's it going? is it ready to review? Could you please update it to the latest development?

**Comment by nikspz** [comment]
hi @MementoRC 
Please be informed about hummingbot ongoing migration to python3.10 this week.
The new PR referring to the https://github.com/hummingbot/hummingbot/pull/6389 will be created and merged before all the connectors PRs to prevent connectors conflicts with python3.10 environment

**Comment by nikspz** [comment]
@MementoRC Could you please update the PR with the latest development?

**Comment by nikspz** [comment]
@MementoRC Could you please resolve branch conflicts?

**Comment by MementoRC** [comment]
@nikspz I will fix it locally and commit it rather than try to fix it with `resolve conflict`. Thank you

**Comment by fengtality** [comment]
@MementoRC Did you update the Coinbase authentication in this PR? I noticed that their API keys only have key and secret but not passphrase anymore.

**Comment by MementoRC** [comment]
@fengtality Yes, the authentication should be up-to-date with their documentation. They seems to be actively making changes, from time to time I run a web-scrapper on their documentation (that's how I found some changes they made a few weeks ago and integrated them)

**Comment by fengtality** [comment]
I got this error after adding API keys:

```
2023-07-09 13:29:53,155 - 27738 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: No module named 'hummingbot.connector.exchange.coinbase_advanced_trade.coinbase_advanced_trade_exchange'
Traceback (most recent call last):
  File "/Users/feng/Code/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/feng/Code/hummingbot/hummingbot/client/command/connect_command.py", line 60, in connect_exchange
    await self._perform_connect(connector_config, previous_keys)
  File "/Users/feng/Code/hummingbot/hummingbot/client/command/connect_command.py", line 142, in _perform_connect
    err_msg = await self.validate_n_connect_connector(connector_name)
  File "/Users/feng/Code/hummingbot/hummingbot/client/command/connect_command.py", line 121, in validate_n_connect_connector
    err_msg = await asyncio.wait_for(
  File "/Users/feng/anaconda3/envs/hummingbot/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/Users/feng/Code/hummingbot/hummingbot/user/user_balances.py", line 86, in add_exchange
    market = UserBalances.connect_market(exchange, client_config_map, **api_details)
  File "/Users/feng/Code/hummingbot/hummingbot/user/user_balances.py", line 23, in connect_market
    connector_class = get_connector_class(exchange)
  File "/Users/feng/Code/hummingbot/hummingbot/client/config/config_helpers.py", line 492, in get_connector_class
    mod = __import__(conn_setting.module_path(),
ModuleNotFoundError: No module named 'hummingbot.connector.exchange.coinbase_advanced_trade.coinbase_advanced_trade_exchange'
```

**Comment by MementoRC** [comment]
@fengtality Apologies, the naming convention I used is `cat_exchange.py` since the filenames become so long (i.e. ..._api_order_book_data-source, ...)

I could change the name of the file to alleviate this issue, however, it would be better not to use this connector as of yet. There is another PR that follows the v2.1 more strictly here: https://github.com/hummingbot/hummingbot/pull/6458

Would it be possible to rather use that PR? It also passes all the tests

Apologies for the inconvenience

**Pull request closed without merging**
