### PR TITLE
feat/ add kraken candles

### PR DESCRIPTION
**Pull request by yancong001**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Add ascendex spot candles following binance structure
Standardize interval management (1m vs 1min vs ...)

**Tests performed by the developer**:

unittest

**Tips for QA testing**:
For kraken spot
```# Replace in scripts/archived_scripts/examples_using_data_feeds/candles_example.py

 eth_1m_candles = CandlesFactory.get_candle(CandlesConfig(connector="kraken", trading_pair="ETH-USDT", interval="1m", max_records=720))
    eth_1h_candles = CandlesFactory.get_candle(CandlesConfig(connector="kraken", trading_pair="ETH-USDT", interval="1h", max_records=720))
    eth_1w_candles = CandlesFactory.get_candle(CandlesConfig(connector="kraken", trading_pair="ETH-USDT", interval="1w", max_records=200))

    # The markets are the connectors that you can use to execute all the methods of the scripts strategy base
    # The candlesticks are just a component that provides the information of the candlesticks
    markets = {"kraken": {"SOL-USDT"}}
```

### CODE REVIEW

**Review by cardosofede — APPROVED** [review]
LGTM!

**Comment by rapcmia** [comment]
Ran tests on `f98fd833122f71c`
- Setup ok on source
- Use candles_example.py to test
- Modified the script using kraken then start:
   image
    - Compare results from binance,kucoin and kraken spot candles
    - Kraken returns `No data collected` from different market pairs used
    - Changed max_records and intervals, same result
    - Connected Kraken account, same result
    - Tried other scripts from `examples with smart components` still getting `No data collected`

Steps to reproduce:
1. Setup script using `candles_example.py`
2. Start script

**Comment by rapcmia** [comment]
PR update:
- `No data collected` issue has been fixed as of commit `1df04a8eff`
- Setup `download_candles.py` ✅ 
  - Run default script ok 
  - Run modified days to download from 3 to 7 and 10 ok 
  - CSV available on /data folder
- Modified `candles_examples.py` and compare to other connectors ❌ 
    - 1m interval and observe it skipped timestamps
     image
     image
    - 15m interval and observe the dates are incorrect and skipped timestamps
     image

**Comment by yancong001** [comment]
I believe the problem is caused by max_record, you may have max_record greater than 720 in your test script.
But no problem, I fixed the bug

**Comment by yancong001** [comment]
fixed

**Comment by nikspz** [comment]
@yancong001 Could you please move back okx_ perpetual to candles_factory.py since it was added here https://github.com/hummingbot/hummingbot/pull/6791/files#diff-06ccc774329396b92abe821a6435017c40d3ab335d30602e26caada11c04c06d

**Comment by rapcmia** [comment]
PR update:
- Setup candles_examples and max_record set to 150
- Observed behavior for more than 15mins on intervals 1m, 5m and 15m
  image
  - All interval started still with incorrect timestamps and possible exchange limitation 
    - For 1m, observed that its still not updated per interval
    - Check OHLC data from connector and exchange, close enough 
    - Compare same setup on other spot candles, all ok

Pending:
- Will check with the team how we can proceed with this issue

**Comment by cardosofede** [comment]
@yancong001 I check the docs that you reported and the 720 records counts from the timestamp of the request, I think that that's what you need to use to loop to construct the historical candles. Also, @rapcmia is spotting discrepancies between the times of candles for diff intervals

**Comment by yancong001** [comment]
> @yancong001 I check the docs that you reported and the 720 records counts from the timestamp of the request, I think that that's what you need to use to loop to construct the historical candles. Also, @rapcmia is spotting discrepancies between the times of candles for diff intervals

Historical candles cannot be looped to construct, only the last 720 are returned.

**Comment by yancong001** [comment]
image
image

Websocket does not return every piece of interval data, So we observed that its not updated per interval

**Comment by yancong001** [comment]
Fixed this issue. If there is no push, continue using candle from the last interval

**Comment by yancong001** [comment]
> @yancong001 I check the docs that you reported and the 720 records counts from the timestamp of the request, I think that that's what you need to use to loop to construct the historical candles. Also, @rapcmia is spotting discrepancies between the times of candles for diff intervals

Currently, up to 720 pieces of historical data can be retrieved. If max_len exceeds 720, the remaining data can only be retrieved slowly in the future.

**Comment by yancong001** [comment]
added

**Comment by rapcmia** [comment]
PR update:
- Test on commit 71996711404c36f8ab79a0de40596662d45acd85
    image
    image
    - The issue reported about discrepancy on candles at the start of the script has been fixed ✅
    - Observe delay but it gets the data base on interval ok
        - However base on the screenshot above there are some instances of interval on 1m that skipped
        - 15m and 5m ok
    - Compare the OHLC from exchange and connector ok
- What happen if more than 720?
    image
    - Shows error on log that user would need to set max of 720

**Comment by yancong001** [comment]
> * skipped

fixed

**Comment by yancong001** [comment]
> PR update:
> 
> * Test on commit [7199671](https://github.com/hummingbot/hummingbot/commit/71996711404c36f8ab79a0de40596662d45acd85)
>   image
>   image
>   
>   * The issue reported about discrepancy on candles at the start of the script has been fixed ✅
>   * Observe delay but it gets the data base on interval ok
>     
>     * However base on the screenshot above there are some instances of interval on 1m that skipped
>     * 15m and 5m ok
>   * Compare the OHLC from exchange and connector ok
> * What happen if more than 720?
>   image
>   
>   * Shows error on log that user would need to set max of 720

fixed

**Review by rapcmia — APPROVED** [review]
- Reported kraken candles issues has been fixed by the developer
- Ran test on 1m, 5m and 15m interval and run for 1hr
	- Observe the first 17ms:
	 - There are no skipped intervals 
   - Compare the candles from connector and exchange all ok 
- Due to exchange limitation, the developer added error logs for user to make sure to not exceed `720`
- Ran tests on sample scripts and all ok working as expected

Note: There are significant delays specially for 1m interval but it provides the candle data needed

**Comment by rapcmia** [comment]
Merged to development and part of release version 1.25.0

**Comment by MementoRC** [comment]
@yancong001 I am getting this error:
```
Traceback (most recent call last):
  File "/LocalSpace/Hummingbot/hummingbot/hummingbot/data_feed/candles_feed/candles_base.py", line 264, in fill_historical_candles
    candles: np.ndarray = await self.fetch_candles(end_time=end_timestamp)
  File "/LocalSpace/Hummingbot/hummingbot/hummingbot/data_feed/candles_feed/candles_base.py", line 216, in fetch_candles
    params = self._get_rest_candles_params(start_time, end_time)
  File "/LocalSpace/Hummingbot/hummingbot/hummingbot/data_feed/candles_feed/kraken_spot_candles/kraken_spot_candles.py", line 95, in _get_rest_candles_params
    candles_ago = (int(time.time()) - start_time) // self.interval_in_seconds
```
I am implementing the following code change:
```pythom
    def _get_rest_candles_params(self,
                                 start_time: Optional[int] = None,
                                 end_time: Optional[int] = None,
                                 limit: Optional[int] = CONSTANTS.MAX_RESULTS_PER_CANDLESTICK_REST_REQUEST) -> dict:
        """
        For API documentation, please refer to:
        https://docs.kraken.com/rest/#tag/Spot-Market-Data/operation/getOHLCData

        This endpoint allows you to return up to 3600 candles ago.
        """
        if start_time is None:
            start_time = int(time.time()) - self.interval_in_seconds * self.max_records

```

**Comment by MementoRC** [comment]
@yancong001 I am now getting another error:
```
2024-07-26 16:03:33,963 - 4174933 - hummingbot.data_feed.candles_feed.kraken_spot_candles.kraken_spot_candles - ERROR - Unexpected error occurred when getting historical klines. Retrying in 1 seconds...
Traceback (most recent call last):
  File "/LocalSpace/Hummingbot/hummingbot/hummingbot/data_feed/candles_feed/candles_base.py", line 264, in fill_historical_candles
    candles: np.ndarray = await self.fetch_candles(end_time=end_timestamp)
  File "/LocalSpace/Hummingbot/hummingbot/hummingbot/data_feed/candles_feed/candles_base.py", line 222, in fetch_candles
    arr = self._parse_rest_candles(candles, end_time)
  File "/LocalSpace/Hummingbot/hummingbot/hummingbot/data_feed/candles_feed/kraken_spot_candles/kraken_spot_candles.py", line 105, in _parse_rest_candles
    data: List = next(iter(data["result"].values()))
KeyError: 'result'
```
But this seems to resolve after a while and the strategy seems to work.

**Comment by MementoRC** [comment]
The issue seems to be a rate limit missing, the exchange returns:
```
Traceback (most recent call last):
  File "/LocalSpace/Hummingbot/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/LocalSpace/Hummingbot/hummingbot/hummingbot/data_feed/candles_feed/candles_base.py", line 264, in fill_historical_candles
    candles: np.ndarray = await self.fetch_candles(end_time=end_timestamp)
  File "/LocalSpace/Hummingbot/hummingbot/hummingbot/data_feed/candles_feed/candles_base.py", line 222, in fetch_candles
    arr = self._parse_rest_candles(candles, end_time)
  File "/LocalSpace/Hummingbot/hummingbot/hummingbot/data_feed/candles_feed/kraken_spot_candles/kraken_spot_candles.py", line 106, in _parse_rest_candles
    raise ValueError(f"Error fetching Kraken candles: {data}")
ValueError: Error fetching Kraken candles: {'error': ['EGeneral:Too many requests']}
```

**Comment by c0indev3l** [comment]
Adding Kraken candles doesn't seem to be available through webui

image

**Pull request merged**
