### PR TITLE
(refactor) Create&updates Mexc spot to ths latest standards

### PR DESCRIPTION
**Pull request by yancong001**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This PR create Mexc connector to the latest standards.

**Tests performed by the developer**:
* Test cases for the new code

**Tips for QA testing**:
Normal QA test for Perpetuals connectors.

### CODE REVIEW

**Comment by yancong001** [comment]
There may still be some unitest problems, I will solve them tomorrow

**Comment by nikspz** [comment]
- Test performed:
    - Cloned and installed feature branch
    - Connected MEXC API Keys successfully
    - Created pureMM strategy using MEXC
    - Failed to place order (flooded with ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...)
    
[logs_mexc-xrp.log](https://github.com/hummingbot/hummingbot/files/12372622/logs_mexc-xrp.log)
[mexc-xrp - Copy.txt](https://github.com/hummingbot/hummingbot/files/12372630/mexc-xrp.-.Copy.txt)


```
2023-08-17 18:35:38,144 - 576465 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2023-08-17 18:35:39,191 - 576465 - hummingbot.connector.exchange.mexc.mexc_exchange.MexcExchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2023-08-17 18:35:39,663 - 576465 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Error fetching user stream listen key. Error: Error executing request POST https://api.mexc.com/api/v3/userDataStream. HTTP status is 400. Error: {"code":700004,"msg":"Mandatory parameter 'signature' was not sent, was empty/null, or malformed."}
Traceback (most recent call last):
  File "/home/nikita/mexc6525/hummingbot/connector/exchange/mexc/mexc_api_user_stream_data_source.py", line 65, in _get_listen_key
    data = await rest_assistant.execute_request(
  File "/home/nikita/mexc6525/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request POST https://api.mexc.com/api/v3/userDataStream. HTTP status is 400. Error: {"code":700004,"msg":"Mandatory parameter 'signature' was not sent, was empty/null, or malformed."}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikita/mexc6525/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/nikita/mexc6525/hummingbot/connector/exchange/mexc/mexc_api_user_stream_data_source.py", line 107, in _manage_listen_key_task_loop
    self._current_listen_key = await self._get_listen_key()
  File "/home/nikita/mexc6525/hummingbot/connector/exchange/mexc/mexc_api_user_stream_data_source.py", line 74, in _get_listen_key
    raise IOError(f"Error fetching user stream listen key. Error: {exception}")
OSError: Error fetching user stream listen key. Error: Error executing request POST https://api.mexc.com/api/v3/userDataStream. HTTP status is 400. Error: {"code":700004,"msg":"Mandatory parameter 'signature' was not sent, was empty/null, or malformed."}
2023-08-17 18:35:40,096 - 576465 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for XRP-USDT. 1/1 completed.
2023-08-17 18:35:40,097 - 576465 - hummingbot.connector.exchange.mexc.mexc_api_order_book_data_source.MexcAPIOrderBookDataSource - INFO - Subscribed to public order book and trade channels...
2023-08-17 18:35:40,298 - 576465 - hummingbot.connector.exchange.mexc.mexc_api_order_book_data_source.MexcAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/nikita/mexc6525/hummingbot/core/data_type/order_book_tracker_data_source.py", line 80, in listen_for_subscriptions
    await self._process_websocket_messages(websocket_assistant=ws)
  File "/home/nikita/mexc6525/hummingbot/core/data_type/order_book_tracker_data_source.py", line 236, in _process_websocket_messages
    channel: str = self._channel_originating_message(event_message=data)
  File "/home/nikita/mexc6525/hummingbot/connector/exchange/mexc/mexc_api_order_book_data_source.py", line 138, in _channel_originating_message
    channel = (self._diff_messages_queue_key if CONSTANTS.DIFF_EVENT_TYPE in event_type
TypeError: argument of type 'NoneType' is not iterable
```
image

**Comment by yancong001** [comment]
I finished my testing work and fixed many bugs, please test it again.

**Comment by nikspz** [comment]
commit [4c4efa3](https://github.com/hummingbot/hummingbot/pull/6525/commits/4c4efa3cbdd418a1a8bd1feaba0beb310b390670)

- Test performed:
    - Cloned and installed feature branch
    - Connected MEXC API Keys successfully
    - Created pureMM strategy using MEXC
    - Started strategy using XRP-USDT (Failed to submit order:
        - Traceback: Error executing request POST https://api.mexc.com/api/v3/order. HTTP status is 400. Error: {"code":10007,"msg":"symbol not support api"}
            - API not supported all pairs, supported pairs are here:
                - https://api.mexc.com/api/v3/defaultSymbols
                    - Could be added to MEXC docs
    - Started strategy using WBTC-USDT and place order successfully
        - (order refresh time 20)
    - However get some events (WARNING - Failed to fetch trade updates for order)
```
2023-08-18 11:14:00,745 - 600461 - hummingbot.connector.exchange.mexc.mexc_exchange.MexcExchange - WARNING - Failed to fetch trade updates for order x-XEKWYICXBWCUT603309ec0a1499c41. Error: invalid literal for int() with base 10: 'C01__321178750286848001'
Traceback (most recent call last):
  File "/home/nikita/mexc6525/hummingbot/connector/exchange_py_base.py", line 947, in _update_orders_fills
    trade_updates = await self._all_trade_updates_for_order(order=order)
  File "/home/nikita/mexc6525/hummingbot/connector/exchange/mexc/mexc_exchange.py", line 467, in _all_trade_updates_for_order
    exchange_order_id = int(order.exchange_order_id)
ValueError: invalid literal for int() with base 10: 'C01__321178750286848001'
```
image
Can't restart strategy after that 
image
Restarted Client and Review this issue again

Steps:
Clone and install refactor branch
Create pureMM strategy using MEXC and order refresh time long (I used 300)
start the strategy
review logs

Actual:
got `Failed to fetch trade updates for order`s during the run
Could have failed to cancel after stop of the strategy

[logs_mexcsup3.log](https://github.com/hummingbot/hummingbot/files/12379005/logs_mexcsup3.log)
[logs_mexcsup2.log](https://github.com/hummingbot/hummingbot/files/12379003/logs_mexcsup2.log)
[4c4.zip](https://github.com/hummingbot/hummingbot/files/12379011/4c4.zip)


image
image
image
image

**Comment by yancong001** [comment]
got it , i will fix it soon

**Comment by yancong001** [comment]
fixed

**Comment by nikspz** [comment]
- Test performed:
    - connected mexc successfully
    - checked mexc balance successfully
    - Created/start pureMM strategy using mexc successfully
    - checked status / status — live, orderbook —live successfully
    - Stop strategy caused failed to cancel event, failed to start again without Client restart
    
Steps:
1. Clone and install refactor branch
2. Create pureMM strategy using MEXC and order refresh time long (I used 300)
3. start the strategy and run till orders refreshed
4. stop the bot
5. review logs

Actual:
`failed to cancel the following orders on mexc` message after stop of the strategy

image

Another try:
[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/12395706/logs_hummingbot.log)
[logs_mexc1.log](https://github.com/hummingbot/hummingbot/files/12395707/logs_mexc1.log)
[mexc1.txt](https://github.com/hummingbot/hummingbot/files/12395710/mexc1.txt)

```
2023-08-21 12:02:01,596 - 661880 - hummingbot.connector.exchange.mexc.mexc_exchange.MexcExchange - WARNING - Error fetching status update for the active order x-XEKWYICXBWCUT6036da55e4c633351: Error executing request GET https://api.mexc.com/api/v3/order. HTTP status is 400. Error: {"msg":"Order does not exist.","code":-2013,"_extend":null}.
```
image
image

**Comment by hlxwell** [comment]
@yancong001 Can I ask for help if there is any bug on mexc connector? since I fixed several bugs on mexc, not sure if you handled them or not.

**Comment by yancong001** [comment]
> @yancong001 Can I ask for help if there is any bug on mexc connector? since I fixed several bugs on mexc, not sure if you handled them or not.

yep,you can ask me

**Comment by yancong001** [comment]
Error fixed.

**Comment by yancong001** [comment]
> 

my discord: yancong

**Review by nikspz — APPROVED** [review]
Test performed:
 - Cloned and installed refactor branch
 - Manually built docker image successfully
 - Connected API key successfully	
 - Balance output matches with exchange
 - Create /Import/start a strategy using allowed for API trading pairs (WBTC-USDT, GMX-USDT) successfully
 - Check status, status --live, orderbook --live matches with exchange
 - Filled orders events: ok
 - Order cancellation is okay, orders placed manually not cancelled

**Review by cardosofede — APPROVED** [review]
LGTM!

**Comment by jellebuth** [comment]
You need to add the partially cancelled order state as well. 
image

**Comment by yancong001** [comment]
> partially

This state is not explicitly stated in the official documentation, and I have never encountered it. I don't think this state will affect program operation and trading strategy. If you know what happened to the specific order when this state occurred, please inform me, and I will add it to the code.

**Pull request merged**
