### PR TITLE
feat/enable derivatives in price source for external market in pmm

### PR DESCRIPTION
**Pull request by leastchaos**
**Before submitting this PR, please make sure**:

* [x] Your code builds clean without any errors or warnings
* [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Enable derivates connectors to be used as price source for external markets

**Tests performed by the developer**:
Tested on binance perpetual with spread 2%
image
normal exchange work as normal
image

**Tips for QA testing**:

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0f9t) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by leastchaos** [comment]
hello, any advice on fixing the failing check?
I only changed a single line so that it can be used for derivative

**Comment by leastchaos** [comment]
@dennisocana hello, could you help to review this pull request?

**Comment by phbrgnomo** [comment]
A PRP was created related to this proposal: 

https://snapshot.org/#/hbot.eth/proposal/0x5c24719985ded78fbfb203af75d506ca29bc7f13486dca6b0a13b34a231425f4

Make sure to check it out and be attentive to incoming reviews related to it.

**Review by rapcmia — APPROVED** [review]
Tested and confirmed working by QA
Test performed:
- Setup Pure market-making and use derivative connector as price_source
- Tested on spot connectors and LM connectors
- Best bid and ask orders matched between the client and set derivative connector
- Tested on paper trade 
- There are still ongoing issues for bybit_perpetual for both mainnet/testnet, see issues/4465

**Review by Nullably — APPROVED** [review]
LGTM

**Pull request merged**
