### PR TITLE
feat/Osmosis Chain Connector - add Osmosis to native tokens list 

### PR DESCRIPTION
**Pull request by chasevoorhees**
**Before submitting this PR, please make sure**:

- [ x] Your code builds clean without any errors or warnings
- [ x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Small change to support addition of Osmosis chain/connector via Gateway to Hummingbot client.

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by nikspz** [comment]
gateway PR: https://github.com/hummingbot/gateway/pull/237

**Comment by cardosofede** [comment]
@rapcmia @nikspz is this PR ready to review?

**Comment by nikspz** [comment]
@cardosofede I think the PRs #6685 and https://github.com/hummingbot/gateway/pull/237 needs dev work as for this comment
https://github.com/hummingbot/gateway/pull/237#issuecomment-1853296578

**Comment by chasevoorhees** [comment]
@nikspz @cardosofede 

Hey all, sorry for the delay on this PR - we were blocked by the PR into the Gateway, which has now been moved here:
https://github.com/hummingbot/gateway/pull/277

These are the only 2 files changed in this PR

Add a strat:
https://github.com/pecuniafinance/hummingbot/blob/development/hummingbot/connector/gateway/amm_lp/gateway_osmosis_amm_lp.py

Add to native tokens list:
https://github.com/pecuniafinance/hummingbot/blob/development/hummingbot/core/utils/gateway_config_utils.py

We're talking with Mike for merge approval on the other PR

**Comment by chasevoorhees** [comment]
> @cardosofede I think the PRs #6685 and [hummingbot/gateway#237](https://github.com/hummingbot/gateway/pull/237) needs dev work as for this comment [hummingbot/gateway#237 (comment)](https://github.com/hummingbot/gateway/pull/237#issuecomment-1853296578)
> 
> @chasevoorhees Could you please check the comment and resolve?

Looks like the above comment is from 12/13 - we have definitely fixed the CURL tests issues (fresh/working JSON in them now)

**Review by rapcmia — APPROVED** [review]
Approved but with failing github checks

**Comment by nikspz** [comment]
@chasevoorhees Could you fix failing tests here?

https://github.com/hummingbot/hummingbot/actions/runs/8054583424/job/22015525653?pr=6685

**Pull request merged**
