### PR TITLE
feat/Ensure Localtime and Timezone for host is always in-sync with container

### PR DESCRIPTION
**Pull request by cheemeng**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Map the server's timezone and localtime to container instead

for more info https://www.howtogeek.com/devops/how-to-handle-timezones-in-docker-containers/

### CODE REVIEW

**Comment by vshuraeff** [comment]
you cannot change this file in container, instead you must use i.e `TZ=Europe/Berlin` environment variable for container.

**Comment by cheemeng** [comment]
> you cannot change this file in container, instead you must use i.e `TZ=Europe/Berlin` environment variable for container.

No idea what you mean by "cannot". It was meant to map the things so that the container would always refer to the same timezone settings as the host.

**Comment by fengtality** [comment]
If you want this change reviewed, please re-submit and provide a detailed rationale

**Comment by cheemeng** [comment]
> If you want this change reviewed, please re-submit and provide a detailed rationale

It's alright. Thanks anyway Mike.

**Pull request closed without merging**
