### PR TITLE
Fix/retrieve historical candles

### PR DESCRIPTION
**Pull request by tomasgaudino**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
As continuation of https://github.com/hummingbot/hummingbot/pull/7142, 
- Keep previous features added by @jbekker
- Fix Binance Spot Candles implementation
- Fix kraken "since" param
- Isolate missing records from fetch candles logic to access it either from fill_historical_candles or get_historical_candles

**Tests performed by the developer**:
1. Create a jupyter notebook at hummingbot's root level and run this code, try to download all historical candles through get_historical_candles method and plot them with:
```
import plotly.graph_objects as go
import pandas as pd
import datetime
import time

from hummingbot.data_feed.candles_feed.ascend_ex_spot_candles.ascend_ex_spot_candles import AscendExSpotCandles
from hummingbot.data_feed.candles_feed.binance_perpetual_candles import BinancePerpetualCandles
from hummingbot.data_feed.candles_feed.binance_spot_candles import BinanceSpotCandles
from hummingbot.data_feed.candles_feed.bybit_perpetual_candles.bybit_perpetual_candles import BybitPerpetualCandles
from hummingbot.data_feed.candles_feed.bybit_spot_candles.bybit_spot_candles import BybitSpotCandles
from hummingbot.data_feed.candles_feed.gate_io_perpetual_candles import GateioPerpetualCandles
from hummingbot.data_feed.candles_feed.gate_io_spot_candles import GateioSpotCandles
from hummingbot.data_feed.candles_feed.hyperliquid_perpetual_candles.hyperliquid_perpetual_candles import (
    HyperliquidPerpetualCandles,
)
from hummingbot.data_feed.candles_feed.kraken_spot_candles.kraken_spot_candles import KrakenSpotCandles
from hummingbot.data_feed.candles_feed.kucoin_perpetual_candles.kucoin_perpetual_candles import KucoinPerpetualCandles
from hummingbot.data_feed.candles_feed.kucoin_spot_candles.kucoin_spot_candles import KucoinSpotCandles
from hummingbot.data_feed.candles_feed.mexc_perpetual_candles.mexc_perpetual_candles import MexcPerpetualCandles
from hummingbot.data_feed.candles_feed.mexc_spot_candles.mexc_spot_candles import MexcSpotCandles
from hummingbot.data_feed.candles_feed.okx_perpetual_candles.okx_perpetual_candles import OKXPerpetualCandles
from hummingbot.data_feed.candles_feed.okx_spot_candles.okx_spot_candles import OKXSpotCandles

from hummingbot.data_feed.candles_feed.data_types import HistoricalCandlesConfig

classes = [
    AscendExSpotCandles,
    BinancePerpetualCandles,
    BinanceSpotCandles,
    BybitPerpetualCandles,
    BybitSpotCandles,
    GateioPerpetualCandles,
    GateioSpotCandles,
    HyperliquidPerpetualCandles,
    KrakenSpotCandles,
    KucoinPerpetualCandles,
    KucoinSpotCandles,
    MexcPerpetualCandles,
    MexcSpotCandles,
    OKXPerpetualCandles,
    OKXSpotCandles
]

def date_to_seconds(year, month, day):
    date = datetime.datetime(year, month, day)
    timestamp = time.mktime(date.timetuple())
    return int(timestamp)

trading_pair = "BTC-USDT"
interval = "1h"
start_time_secs = date_to_seconds(2024, 8, 3)
end_time_secs = date_to_seconds(2024, 8, 6)  


df = pd.DataFrame()
for i in range (0, len(classes)):
    print(classes[i].__name__)    
    candles = classes[i](trading_pair, interval)
    config = HistoricalCandlesConfig(connector_name="",
                                     trading_pair=trading_pair,
                                     interval=interval,
                                     start_time=start_time_secs,
                                     end_time=end_time_secs,)

    candles_df = await candles.get_historical_candles(config)
    candles_df['connector_name'] = classes[i].__name__
    candles_df['step'] = ','.join(map(str, [step for step in candles_df.timestamp.diff()[1:].unique().tolist()]))
    candles_df['timestamp'] = pd.to_datetime(candles_df['timestamp'], unit="s")
    df = pd.concat([df, candles_df])
    print(f"Timestamp diff unique: {candles_df.timestamp.diff().unique()}")
    
    fig = go.Figure(data=[go.Candlestick(x=candles_df['timestamp'],
                    open=candles_df['open'],
                    high=candles_df['high'],
                    low=candles_df['low'],
                    close=candles_df['close'])])
    fig.update_layout(xaxis_rangeslider_visible=False)
    fig.show()
```
2. After running previous cell, check for candles consistency in a summarized table with:
```
df.groupby(["connector_name", "step"]).agg({"timestamp": ["first", "last"],
                                  "open": "first",
                                  "high": "first",
                                  "low": "first",
                                  "close": "first"})
```
image

3. For live candles, use the following script and run `status --live` to compare with exchange
```
from typing import Dict

import pandas as pd
import pandas_ta as ta  # noqa: F401

from hummingbot.connector.connector_base import ConnectorBase
from hummingbot.data_feed.candles_feed.candles_factory import CandlesConfig, CandlesFactory
from hummingbot.strategy.script_strategy_base import ScriptStrategyBase


class StreamCandles(ScriptStrategyBase):
    """
    This script is a simple example of how to use the Candles Factory to create a candlestick and start it.
    """
    # Available intervals: |1s|1m|3m|5m|15m|30m|1h|2h|4h|6h|8h|12h|1d|3d|1w|1M|
    # Is possible to use the Candles Factory to create the candlestick that you want, and then you have to start it.
    # Also, you can use the class directly like BinancePerpetualsCandles(trading_pair, interval, max_records), but
    # this approach is better if you want to initialize multiple candles with a list or dict of configurations.
    candles = CandlesFactory.get_candle(CandlesConfig(connector="hyperliquid",
                                                      trading_pair="PURR-USDT",
                                                      interval="1m",
                                                      max_records=200))

    # The markets are the connectors that you can use to execute all the methods of the scripts strategy base
    # The candlesticks are just a component that provides the information of the candlesticks
    markets = {"binance_paper_trade": {"SOL-USDT"}}

    def __init__(self, connectors: Dict[str, ConnectorBase]):
        # Is necessary to start the Candles Feed.
        super().__init__(connectors)
        self.candles.start()

    def on_tick(self):
        pass

    def on_stop(self):
        """
        Without this functionality, the network iterator will continue running forever after stopping the strategy
        That's why is necessary to introduce this new feature to make a custom stop with the strategy.
        :return:
        """
        self.candles.stop()

    def format_status(self) -> str:
        """
        Displays the three candlesticks involved in the script with RSI, BBANDS and EMA.
        """
        if not self.ready_to_trade:
            return "Market connectors are not ready."
        lines = []
        lines.extend(["\n############################################ Market Data ############################################\n"])
        candles_df = self.candles.candles_df
        # Let's add some technical indicators
        candles_df.ta.ema(length=14, offset=None, append=True)
        candles_df["timestamp"] = pd.to_datetime(candles_df["timestamp"], unit="s")
        lines.extend([f"Candles: {self.candles.name} | Interval: {self.candles.interval}"])
        lines.extend(["    " + line for line in candles_df.tail().to_string(index=False).split("\n")])
        lines.extend(["\n-----------------------------------------------------------------------------------------------------------\n"])

        return "\n".join(lines)

```

**Tips for QA testing**:
- All get_historical_candles results must:
    - start and end at the same time (in my case, 3:00am because i'm located at UTC-3)
    - appear only one time, if there are more steps than 3600 for 1h interval is because there are gaps that need to be filled
    - match ohlc values with exchange
    - for hyperliquid spot candles, should import correspondent candle feed and check which markets are available in the exchange, i.e. PURR-USDC

### CODE REVIEW

**Comment by tomasgaudino** [comment]
@nikspz @rapcmia @cardosofede ready for review!

**Comment by rapcmia** [comment]
Test in progress

**Comment by rapcmia** [comment]
PR update using commit `ef4f299245ff517c4b2fbb26b99abdc11165ae00`
- Ran tests on local using macOs(m1) 
- Create jupyter notebook
  - Got an error when running the notebook 
    image
    ```
    Unclosed client session
    client_session: <aiohttp.client.ClientSession object at 0x105c66da0>
    AscendExSpotCandles
    Error fetching historical candles: Cannot connect to host ascendex.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')]
    Traceback (most recent call last):
	      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection
        return await self._loop.create_connection(*args, **kwargs)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1103, in create_connection
        transport, protocol = await self._create_connection_transport(
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1133, in _create_connection_transport
        await waiter
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
        ssldata, appdata = self._sslpipe.feed_ssldata(data)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
        self._sslobj.do_handshake()
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 975, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/7160/hummingbot/data_feed/candles_feed/candles_base.py", line 171, in get_historical_candles
        fetched_candles = await self.fetch_candles(end_time=current_end_time, missing_records=missing_records)
      File "/Users/rapcomia/github/hummingbot/7160/hummingbot/data_feed/candles_feed/candles_base.py", line 229, in fetch_candles
        candles = await rest_assistant.execute_request(url=self.candles_url,
      File "/Users/rapcomia/github/hummingbot/7160/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
        response = await self.execute_request_and_get_response(
      File "/Users/rapcomia/github/hummingbot/7160/hummingbot/core/web_assistant/rest_assistant.py", line 94, in execute_request_and_get_response
        response = await self.call(request=request, timeout=timeout)
      File "/Users/rapcomia/github/hummingbot/7160/hummingbot/core/web_assistant/rest_assistant.py", line 108, in call
        resp = await wait_for(self._connection.call(request), timeout)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
        return await fut
      File "/Users/rapcomia/github/hummingbot/7160/hummingbot/core/web_assistant/connections/rest_connection.py", line 10, in call
        aiohttp_resp = await self._client_session.request(
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/client.py", line 581, in _request
        conn = await self._connector.connect(
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
        proto = await self._create_connection(req, traces, timeout)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 944, in _create_connection
        _, proto = await self._create_direct_connection(req, traces, timeout)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 1257, in _create_direct_connection
        raise last_exc
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 1226, in _create_direct_connection
        transp, proto = await self._wrap_create_connection(
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 1027, in _wrap_create_connection
        raise ClientConnectorCertificateError(req.connection_key, exc) from exc
    aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host ascendex.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')]
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    Cell In[3], line 66
         59 config = HistoricalCandlesConfig(connector_name="",
         60                                  trading_pair=trading_pair,
         61                                  interval=interval,
         62                                  start_time=start_time_secs,
         63                                  end_time=end_time_secs,)
         65 candles_df = await candles.get_historical_candles(config)
    ---> 66 candles_df['connector_name'] = classes[i].__name__
         67 candles_df['step'] = ','.join(map(str, [step for step in candles_df.timestamp.diff()[1:].unique().tolist()]))
         68 candles_df['timestamp'] = pd.to_datetime(candles_df['timestamp'], unit="s")
    
    TypeError: 'NoneType' object does not support item assignment
    ```
     - Same error occurred on other connectors
     - Compared wth @nikspz running on local Windows and seem to work on his end

Steps to reproduce:
1. Conda activate hummingbot and run jupyter notebook on hummingbot root folder
2. Create notebook and select kernel `python 3 (ipykernel)`
3. Run the notebook

---

Run script provided by dev then compare OHLC data from hummingbot and exchanges while on `status --live`
- Run tests 5m and 15ms with candles data of 200, 300 and 1000
- Compare candles data between hummingbot and exchange each interval is completed (3/3)
- Run candles data that exceeds 1000 and observe 
- Connectors tested:
  - Kraken - ok but can only cater max of 720
  - Ascendex - ok 
  - Kucoin spot and perpetual - ok 
  - Mexc spot and perpetual `not started`
  - OKX spot and perpetual `not started`

**Comment by tomasgaudino** [comment]
@rapcmia hmm.. That problem is related to python itself. There might be some steps to troubleshoot that error:

1) check your jupyter notebook is properly setup with hummingbot environment, even being started after `conda activate hummingbot`
2) verify that your hbot environment is up to date, try removing and installing again conda environment

otherwise, i'm afraid that since i'm using a linux machine i can't help :(

**Comment by rapcmia** [comment]
PR update:
- Thanks @tomasgaudino for the help, yep ill have a look tonight about the jupyter notebook
- Re-run tests on kucoin perpetual
  image
  image
  - Rerun tests on kucoin connector and found this behavior on perpetual
  - Compare these behaviors on development, not able to reproduce
  - Screen recording here https://www.loom.com/share/31d239b97a7a404aa35b90f23004dca8

---

Run candles script on `okx`
- For spot, run test on 5m interval 200 records, 15m for 500 records 
  image
  image
  - Both scripts running on 1 and 2 markets return same behavior
      - Observed than when I change the record from 200 → 1000, this behavior occurred.
      - Also observed when running 1 market script candles data getting `..candles are not sorted by timestamp in ascending order.`
      - Compare the results on development branch not able to reproduce this behavior 
        image
- For perpetual, Run test on 5m interval 200 records, 15m for 500 records 
  image
  image
    - Im not getting the behavior from spot but these are not happening as well on development branch when crosschecked using same scripts
    - On single market candles script, we only use records of max_records of `200` and `500`

---

Run candles script on `mexc`
- For spot and perpetual,
  - Compare OHLC data between hummingbot and exchange all matched 
  - Observed `quote_asset_volume` are present and matched as well
  - However comparing this PR with development branch observed:
    - This PR has the most activity of error `The websocket connection was closed (The WS connection was closed unexpectedly. Close code = 1006 msg data: 0)`

Steps to reproduce: `see attached for the scripts`
1. Use single and multi market pair 
2. Observed behavior when using max_records 200, 500 and values more than 1000
3. Compare OHLC data between hummingbot and exchange when running `status --live`

[08082024.zip](https://github.com/user-attachments/files/16539164/08082024.zip)

**Comment by nikspz** [comment]
Jupyter notebook: ok, reviewed showed candles for connectors

@tomasgaudino 
Candles script for dif connectors:
- binance: ok
- binance_perpetual: ok

- bybit spot
    - OHLC matched with exchange ✅
    - no quote asset volume for ETH-USDT ❌

image

- bybit perpetual:
    - OHLC not matched with exchange ❌
    - no quote asset volume for ETH-USDT ❌
image
image

- gate_io spot:
    - OHLC matched with exchange ✅
    - volume shows USDT (not base ETH) for ETH-USDT ❌
image

image
- gate_io perpetual:
    - OHLC not matched with exchange ❌
    - no quote asset volume for ETH-USDT ❌
image
image


- hyperliquid spot/perpetual:
Hyperliquid spot no quote asset volume for PURR-USDC ❌
image
image
image


Hyperliquid perpetual no quote asset volume for BTC-USD ❌

image
image
image


image

**Comment by tomasgaudino** [comment]
Thanks for the feedback @nikspz ,

- As discussed with @cardosofede we will not be including quote volume if the exchange API doesn't offer it. I've checked again the exchange docs mentioned and the param is missing
- Fixed Gate IO spot base/quote volume inversion in websocket
- For mismatched candles, I've checked again and they are working properly

**Comment by tomasgaudino** [comment]
@rapcmia after some checks:

- For kucoin perpetual candles i've disabled start time param leading to a correct behaviour
image

- For OKX i've reproduced every combination you provided and worked fine for me. After reading your logs, the error that you're getting is because apparently the execution exceeded the candles endpoint rate limit. I've checked definition and it's ok since it's the same for spot or perp. Is it possible that you've been running tests in separated instances of hummingbot? It's the only error source that I can imagine for now

image
 
image

- About MEXC the websocket connection might be disconnecting because of the ausence of trades and ping/pong handling, a feature previously discussed with @cardosofede and present in backlog for next PR -this one is time-sensitive due to the release of the next version next week-

> PR update:
> 
> * Thanks @tomasgaudino for the help, yep ill have a look tonight about the jupyter notebook
> * Re-run tests on kucoin perpetual
>   image
>   image
>   
>   * Rerun tests on kucoin connector and found this behavior on perpetual
>   * Compare these behaviors on development, not able to reproduce
>   * Screen recording here https://www.loom.com/share/31d239b97a7a404aa35b90f23004dca8
> 
> Run candles script on `okx`
> 
> * For spot, run test on 5m interval 200 records, 15m for 500 records
>   image
>   image
>   
>   * Both scripts running on 1 and 2 markets return same behavior
>     
>     * Observed than when I change the record from 200 → 1000, this behavior occurred.
>     * Also observed when running 1 market script candles data getting `..candles are not sorted by timestamp in ascending order.`
>     * Compare the results on development branch not able to reproduce this behavior
>       image
> * For perpetual, Run test on 5m interval 200 records, 15m for 500 records
>   image
>   image
>   
>   * Im not getting the behavior from spot but these are not happening as well on development branch when crosschecked using same scripts
>   * On single market candles script, we only use records of max_records of `200` and `500`
> 
> Run candles script on `mexc`
> 
> * For spot and perpetual,
>   
>   * Compare OHLC data between hummingbot and exchange all matched
>   * Observed `quote_asset_volume` are present and matched as well
>   * However comparing this PR with development branch observed:
>     
>     * This PR has the most activity of error `The websocket connection was closed (The WS connection was closed unexpectedly. Close code = 1006 msg data: 0)`
> 
> Steps to reproduce: `see attached for the scripts`
> 
> 1. Use single and multi market pair
> 2. Observed behavior when using max_records 200, 500 and values more than 1000
> 3. Compare OHLC data between hummingbot and exchange when running `status --live`
> 
> [08082024.zip](https://github.com/user-attachments/files/16539164/08082024.zip)
> 
> Todo:
> 
> * Run this PR with ongoing tests on quants-lab `not started`

**Comment by nikspz** [comment]
789a433
Candles script for dif connectors:
- binance: ok
    - OHLC matched with exchange :white_check_mark:
    - volume is correct  :white_check_mark:
- binance_perpetual: ok
    - OHLC matched with exchange :white_check_mark:
    - volume is correct  :white_check_mark:
- bybit spot
    - OHLC matched with exchange :white_check_mark:
    - no quote asset volume for ETH-USDT, base volume is correct :white_check_mark:
- bybit perpetual:
    - OHLC matched with exchange 
    - no quote asset volume for ETH-USDT, base volume is correct :white_check_mark:
- gate_io spot:
    - OHLC matched with exchange :white_check_mark:
    - volume is correct  :white_check_mark:
- gate_io perpetual:
    - OHLC matched with exchange :white_check_mark:
    - no quote asset volume for ETH-USDT, base volume is correct :white_check_mark:
- hyperliquid spot:
    - OHLC matched with exchange :white_check_mark:
    - Hyperliquid spot no quote asset volume for PURR-USDC, base volume is correct :white_check_mark:
- hyperliquid perpetual:
    - OHLC matched with exchange :white_check_mark:
    - Hyperliquid perpetual no quote asset volume for BTC-USD, base volume is correct :white_check_mark:

**Review by nikspz — APPROVED** [review]
Approved, wait for other connectors tested by Ralph

**Review by rapcmia — APPROVED** [review]
Test summary:
- Not able to test on jupyter notebook due to issues with mac ❌
- Run provided script by dev and compare OHLC data between hummingbot and exchange while `status --live`
    - Kraken ok
    - Ascend_ex ok
    - Kucoin spot and perpetual ok
    - Mexc spot and perpetual ok
        - Observed error `The websocket connection was closed (The WS connection was closed unexpectedly. Close code = 1006 msg data: 0` which will be fix on later PR for improvement of connector
    - Okx spot and perpetual ok
        - Connector now returning `unexpected error occurred when getting historyical klines` on random timeframes
            - `OSError: **Error** executing request GET https://www.okx.com/api/v5/market/history-candles. HTTP status is 429. **Error**: {"msg":"Too Many Requests","code":50011}`
- Most of the tests run with 5m and 15m interval with max_records set to 200 and 500
- Wait each interval and compare OHLC data on all exchanges listed ok
- Observed behavior when max_records over 1000

**Review by cardosofede — CHANGES_REQUESTED** [review]
I think that the current implementation adds a lot of code when it is not necessary.
I suggest simplifying the code by removing the need to redefine the method candles_max_result_per_rest_request, if you check all the connectors have the same code, maybe you can abstract in the constants file a general configuration candles where max candles rest request is here or just return that value in the property.
Also, the name missing candles is confusing for a method fetch candles, I suggest using limit

**Review by cardosofede — APPROVED** [review]
Approved for the release but the code needs improvement

**Pull request merged**
