### PR TITLE
(fix) Remove used gateway docker functions from client

### PR DESCRIPTION
**Pull request by fengtality**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

- Removed extraneous Gateway Docker related code from codebase
- Fixes https://github.com/hummingbot/hummingbot/issues/6083

### CODE REVIEW

**Comment by rapcmia** [comment]
Hi @fengtality the `Notice: Hummingbot is unable to communicate with Docker. If you need gateway for DeFi..` is still showing on docker client build.

image

When we tried to look where this line is located it pointed us here `../6141/hummingbot/core/gateway/__init__.py` possible it can help the fix

image

Steps to reproduce:
1. Setup docker build by running `./installation/docker-commands/create.sh`
2. Start docker client using `start.sh`
3. Observed that upon opening the client, there is a notice about `Hummingbot is unable to communicate with Docker`

**Review by cardosofede — CHANGES_REQUESTED** [review]
These changes are OK but as @rapcmia you will probably need to delete the delete all the things relative to docker in the init of the gateway

**Review by rapcmia — APPROVED** [review]
LGTM

- Successfully build docker image 
- Confirm no warning about docker ✅ 
- Confirm no notice on gateway status about docker ✅ 
- Setup simple AMM arb to check changes made, all ok

**Review by cardosofede — APPROVED** [review]
LGTM!

**Pull request merged**
