### PR TITLE
fix/ Docker compose yml file on Client side #6593

### LINKED ISSUE #6593: Docker-Compose Up
### Describe the bug

`docker-compose up` causes the following error.

```
Creating hummingbot ... error

ERROR: for hummingbot  Cannot create container for service hummingbot: invalid JSON: json: cannot unmarshal number into Go struct field LogConfig.HostConfig.LogConfig.Config of type string

ERROR: for hummingbot  Cannot create container for service hummingbot: invalid JSON: json: cannot unmarshal number into Go struct field LogConfig.HostConfig.LogConfig.Config of type string
ERROR: Encountered errors while bringing up the project.
```

### Steps to reproduce

1. Clone the repo
2. Checkout `development` branch.
3. `docker-compose up`

### Release version

development@63f257c

### Type of installation

Source

### Attach required files

_No response_

### PR DESCRIPTION
**Pull request by 0xferit**
Fixes #6593 by converting max-file to a string.

### CODE REVIEW

**Review by nikspz — APPROVED** [review]
Same yml on deploy-examples repository https://github.com/hummingbot/deploy-examples/blob/main/simple_hummingbot_compose/docker-compose.yml
image
LGTM

**Comment by 0xferit** [comment]
Should I fix this on `deploy-examples` too?

**Comment by nikspz** [comment]
@0xferit no, I think, it should work here, but you could take a look.

**Comment by nikspz** [comment]
fix merged to latest development and will be available in 1.21.0 Release

**Pull request merged**
