### PR TITLE
Fix/xemm price conversions

### PR DESCRIPTION
**Pull request by kadirc**
**A description of the changes proposed in the pull request**:

Main issues:

- When getting taker's price, size conversion from maker is wrong, this affects below functions:

Maker: ETH/USDT Taker: BTC/USDT

base_conversion_rate(BTCETH) = 14.7126
quote_conversion_rate(USDTUSDT) = 1.0

Let's say order size is 1 ETH, when getting the price in taker market need to convert ETH to BTC amount. We need to divide by base rate to get BTC equivalent of 1 ETH ( 1/14.7126 = 0.06796 BTC then query taker market price with 0.06796 BTC). Hence this change needed in multiple functions:
image

        get_market_making_size
        get_market_making_price
        calculate_effective_hedging_price
        check_if_sufficient_balance
        check_and_hedge_orders

- Prices were not adjusted for taker to maker (or vice versa):
        strategy should take into account that base or quote (or even both) might be different assets.

- If rate oracle is used, strategy usually starts before rate oracle / conversion rates are not available, then strategy was using 1.0 for conversion rates. Now it should wait until both base and quote conversion rates are available before start trading.

This PR should address: #5068 #5695 

**Tests performed by the developer**:
configuration:
image

waiting rate oracle and orders with correct amounts:
image

orders created:
image

hedging sell:
image

image

Above tests also performed with different base assets except no hedging.

**Tips for QA testing**:

Test with different base assets and different quote assets.
Test with conversion_rate_mode= rate_oracle_conversion_rate and fixed_conversion_rate

### CODE REVIEW

**Comment by nikspz** [comment]
Test performed:

- Cloned and installed fix branch latest commit [46eda6f](https://github.com/hummingbot/hummingbot/pull/5812/commits/46eda6f4344dc9e405cc3345afb0394bdb24519d)
- Created/started XEMM config using different base assets with min_profitability low to check the trades/rates
[logs_conf_xemm_2_diff_base.log](https://github.com/hummingbot/hummingbot/files/9824929/logs_conf_xemm_2_diff_base.log)
[5812xemmdiff.zip](https://github.com/hummingbot/hummingbot/files/9824928/5812xemmdiff.zip)
- Created/started XEMM config using different quote assets with min_profitability low to check the trades/rates
[logs_xemm-quote.log](https://github.com/hummingbot/hummingbot/files/9824936/logs_xemm-quote.log)
[5812xemmdiff.zip](https://github.com/hummingbot/hummingbot/files/9824938/5812xemmdiff.zip)
- Reviewed that bot now able to ran XEMM using different base and quote assets

- Ongoing test...


For some trades for taker connector bot returned message `WARNING - The order fill updates did not arrive on time for *order_id*`. The complete update will be processed with incomplete information.
Then returned `0 ETH has been completely filled.` However in exchange we have filled orders (that not 0 but correct amount)

Config with Different base:
image
image

Config with Different Quote:
image
image

**Comment by nikspz** [comment]
Upon checking `The order fill updates did not arrive on time for *order_id*` issue is not related to the PR.

**Comment by cardosofede** [comment]
@kadirc the test are failing. Please review them and after that we I'm going to do the code review

**Comment by kadirc** [comment]
> @kadirc the test are failing. Please review them and after that we I'm going to do the code review

@cardosofede I had to make a change to a unit test in this case, motivation explained in the commit: 8ec8506347073c99e71b24f985359ebc2135ca5e

**Review by nikspz — APPROVED** [review]
Test performed:
- Cloned and installed fix branch
- Manually created docker image successfully
- Created and started XEMM strategy using `different base` assets
- Review that status showed correct rate conversion and Prices for both exchanges
- Checked order execution using different base assets, filled orders and history
- Created and started XEMM strategy using `different quote` assets
- Review that status showed correct rate conversion and Prices for both exchanges
- Checked order execution, history --verbose filled orders have same amount
- Created and started XEMM strategy using `different base and quote` assets
- Review that status showed correct rate conversion and Prices for both exchanges
- Checked order execution, filled orders and history --verbose
- Created and started XEMM strategy using `same pairs`
- Tested that strategy works as expected using same base and quote assets
- Order execution = OK
- Filled orders matched in history --verbose, exchange and Data folder

**Comment by supervik** [comment]
Please check the line here:
image

`get_price_for_quote_volume` assumes that you provide a quote volume but here is the base size.

I used the config attached and catch the error _<class 'decimal.InvalidOperation'>_ because the calculated `taker_price = None` (the bot tries to calculate the price for 20 BTC but not for 20 XRP)
[conf_xemm_gate_kucoin_XRP_BTC.zip](https://github.com/hummingbot/hummingbot/files/10099190/conf_xemm_gate_kucoin_XRP_BTC.zip)

**Comment by kadirc** [comment]
> Please check the line here: image
> 
> `get_price_for_quote_volume` assumes that you provide a quote volume but here is the base size.
> 
> I used the config attached and catch the error _<class 'decimal.InvalidOperation'>_ because the calculated `taker_price = None` (the bot tries to calculate the price for 20 BTC but not for 20 XRP) [conf_xemm_gate_kucoin_XRP_BTC.zip](https://github.com/hummingbot/hummingbot/files/10099190/conf_xemm_gate_kucoin_XRP_BTC.zip)

@supervik thanks for the finding. I think it should be the quote_amount for an 'estimated' order_size that would be placed on the taker exchange. Because otherwise taker quote balance might be huge, and the queried price might be misleading. 

Created #5921 that should address your point with the way it was before (query by balance).

**Pull request merged**
