### PR TITLE
Feat/binance perpetual v2.1 upgrade

### PR DESCRIPTION
**Pull request by HODLER-CODING**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Upgrade from connector v2.0 ->v2.1
Made BinancePerpetualDerivative a subclass of PerpetualDerivativePyBase but required a lot of changes to the code and other files to be compatible.

**Tests performed by the developer**:
Compiled on Localhost and tested with Perpetual_market_making strat with binanace testnet account
As a bonus, tested the other commands such as balance, orderbook, connection, etc and they seem to be working

**Tips for QA testing**:

### CODE REVIEW

**Comment by HODLER-CODING** [comment]
this is part of the: [Upgrade Binance Perpetuals to v2.1#5795](https://github.com/hummingbot/hummingbot/issues/5795)

**Comment by HODLER-CODING** [comment]
There were errors highlighted during test cases and realized it required major changes.
I'll have some error-free code tomorrow or day after.

**Review by HODLER-CODING — COMMENTED** [review]
more format fixing

**Review by HODLER-CODING — COMMENTED** [review]
more formatting....

**Review by HODLER-CODING — COMMENTED** [review]
more format correction

**Review by HODLER-CODING — COMMENTED** [review]
indentation fixes

**Review by HODLER-CODING — COMMENTED** [review]
flake8 wanted to revert the changes...

**Review by HODLER-CODING — COMMENTED** [review]
changed styling to prevent indentation error

**Review by HODLER-CODING — COMMENTED** [review]
added pre-commit changes

**Comment by nikspz** [comment]
Steps:
1. Cloned and clean installed feature branch
2. Start the bot instance and set up password

Actual:
Bot returns an error `ERROR - There was an error requesting exchange info.`

Expected:
Bot does not return any errors on the start


image

**Comment by nikspz** [comment]
Tests performed:
- connect binance API keys = OK
- checked balance successfully (matched with the exchange) = OK
- create perpetualMM strategy = OK
- start perpetualMM strategy - Failed

Failed to start PerpetualMM strategy

Steps to reproduce:
1. Cloned and clean installed feature branch
2. set up password and Start the bot instance
3. connect valid binance_perpetual API keys
4. create/start perpetualMM strategy using binance_perpetual

Actual:
Bot showed errors on the initial start: 
```
ERROR - Unhandled error in background task: object \
TypeError: object NoneType can't be used in 'await' expression
```
```
ERROR - Unhandled error in background task: 'dualSidePosition'
```
Then bot flooded with 
`ERROR - Unhandled error in background task: 'dualSidePosition'`

Expected:
1. There's no errors showed at the start of the strategy
2. bot placed orders to OPEN the position successfully


```
2022-11-02 23:11:46,387 - 394201 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2022-11-02 23:11:46,452 - 394201 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/ubuntu/binper2/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
TypeError: object NoneType can't be used in 'await' expression
2022-11-02 23:11:46,803 - 394201 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'dualSidePosition'
Traceback (most recent call last):
  File "/home/ubuntu/binper2/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/binper2/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 1301, in _set_position_mode
    initial_mode = await self._get_position_mode()
  File "/home/ubuntu/binper2/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 1357, in _get_position_mode
    self._position_mode = PositionMode.HEDGE if response["dualSidePosition"] else PositionMode.ONEWAY
KeyError: 'dualSidePosition'
2022-11-02 23:11:46,864 - 394201 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2022-11-02 23:11:46,987 - 394201 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'dualSidePosition'
Traceback (most recent call last):
  File "/home/ubuntu/binper2/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "hummingbot/core/network_iterator.pyx", line 112, in _check_network_loop
    await self.start_network()
  File "/home/ubuntu/binper2/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 277, in start_network
    await self._get_position_mode()
  File "/home/ubuntu/binper2/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 1357, in _get_position_mode
    self._position_mode = PositionMode.HEDGE if response["dualSidePosition"] else PositionMode.ONEWAY
KeyError: 'dualSidePosition'
2022-11-02 23:11:47,136 - 394201 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_order_book_tracker - INFO - Initialized order book for XRP-USDT. 1/1 completed.
2022-11-02 23:11:56,256 - 394201 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'dualSidePosition'
Traceback (most recent call last):
  File "/home/ubuntu/binper2/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/binper2/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 1301, in _set_position_mode
    initial_mode = await self._get_position_mode()
  File "/home/ubuntu/binper2/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 1357, in _get_position_mode
    self._position_mode = PositionMode.HEDGE if response["dualSidePosition"] else PositionMode.ONEWAY
KeyError: 'dualSidePosition'
........................................................
2022-11-02 23:12:26,137 - 394201 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'dualSidePosition'
Traceback (most recent call last):
  File "/home/ubuntu/binper2/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/binper2/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 1301, in _set_position_mode
    initial_mode = await self._get_position_mode()
  File "/home/ubuntu/binper2/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 1357, in _get_position_mode
    self._position_mode = PositionMode.HEDGE if response["dualSidePosition"] else PositionMode.ONEWAY
KeyError: 'dualSidePosition'
```

[logs_conf_perpetual_market_making_1.log](https://github.com/hummingbot/hummingbot/files/9924750/logs_conf_perpetual_market_making_1.log)
[5814binper.zip](https://github.com/hummingbot/hummingbot/files/9924747/5814binper.zip)

image

**Comment by rapcmia** [comment]
Hi @HODLER-CODING good day,
We would like to to follow up for updates on this PR? Would you be able to provide us a timeframe of your next possible commit?

**Comment by HODLER-CODING** [comment]
There still two errors I'm stuck on. I should be able to sort it out over this weekend. Does that suit you?

**Comment by rapcmia** [comment]
Thanks for the update. Yes we should be able to check this next week Monday :thumbsup:

**Comment by HODLER-CODING** [comment]
I think there is several issues that already exist that is preventing me from actually completing the upgrade.
I havent really changed the API POST request side of the code yet i'm constantly getting errors.
Is it possible that there are already existing bugs with the code? I hope not, else its impossible to tell whether I should be trying to fix my code or fix the existing code.

**Comment by yancong001** [comment]
I would like to be assigned this bounty and solve the remaining problems.

**Comment by HODLER-CODING** [comment]
I just need someone to point me in the right direction. There's something wrong with how the requests work because I've use postman for the same thing and get correct response, opposed to what's return on the make test.

**Pull request closed without merging**
