### PR TITLE
fix/Status - Unable to display status output on Windows source and binary

### LINKED ISSUE #4339: Status - Unable to display status output on Windows source and binary build
**Describe the bug**
While testing TWAP on the staging branch (dev-0.44.0), the bot was able to create/cancel orders according to config however when checking the `status` it returns an error of `Unhandled error in background task: Python int too large to convert to C long`

```
2021-09-30 15:54:09,423 - 15660 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Python int too large to convert to C long
Traceback (most recent call last):
  File "C:\Users\Ralph\github\staging\hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
    return await c
  File "C:\Users\Ralph\github\staging\hummingbot\client\command\status_command.py", line 137, in status_check_all
    self._notify(await self.strategy_status())
  File "C:\Users\Ralph\github\staging\hummingbot\client\command\status_command.py", line 81, in strategy_status
    st_status = self.strategy.format_status()
  File "C:\Users\Ralph\github\staging\hummingbot\strategy\twap\twap.py", line 168, in format_status
    df = LimitOrder.to_pandas(active_orders)
  File "hummingbot\\core\\data_type\\limit_order.pyx", line 43, in hummingbot.core.data_type.limit_order.LimitOrder.to_pandas
    long now_timestamp = int(time.time() * 1e6) if end_time_order_age == 0 else end_time_order_age
OverflowError: Python int too large to convert to C long
```

Tried to reinstall and change the rate_oracle_source and global_token (from USD to USDT) but still getting the same error. The issue does not happen on Windows docker and Mac's src/docker build. 

**Steps To Reproduce**

1. Create TWAP strategy
1. Disable `is_time_span_execution` (optional if you want to enable it)
1. Wait for the bot to create orders and crosscheck them on the connector
1. Once you are sure that orders match, run the status command

**Screenshots**

Windows binary
status not working

Windows source build
status not working

**Release version**
dev-0.44.0

**Attachments**
[twap.zip](https://github.com/CoinAlpha/hummingbot/files/7258018/twap.zip)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran86w) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by lt7**
… Fixes #4339

**Before submitting this PR, please make sure**:

- [x ] Your code builds clean without any errors or warnings
- [x ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Windows for both 32 and 64 bit uses 4 bytes (32 bits) for int and long, 8 bytes (64 bits) for long long. The difference between Win32 and Win64 is size of pointer (32 bits for Win32 and 64 bits for Win64). (See [Data Type Ranges](http://msdn.microsoft.com/en-us/library/s3f49ktz.aspx)] from MSDN).

Linux uses another model: int is 32 bits for both linux-32 and linux-64, long long is always 64-bit. long and pointers are vary: 32 bits on linux-32 and 64 bits on linux-64.

**Tests performed by the developer**:

Attempted XEMM paper trade strategy on Windows host, throws error on the creation_timestamp

image

After change applied XEMM no longer throws errors.

image

Status command now also works

image

**Tips for QA testing**:

Needs further testing on MacOS/Linux/docker environments to ensure no regression.

### CODE REVIEW

**Comment by JeremyKono** [comment]
Hi, please create a PRP here so the community can vote on the change and can undergo QA testing https://snapshot.org/#/hbot-prp.eth

**Review by aarmoa — COMMENTED** [review]
I agree with the changes. They will not impact mac and linux version, and will fix the issue for windows version. Please include the link to the proposal, so the community can vote for it.

**Comment by lt7** [comment]
> I agree with the changes. They will not impact mac and linux version, and will fix the issue for windows version. Please include the link to the proposal, so the community can vote for it.

https://snapshot.org/#/hbot-prp.eth/proposal/0xe1cddabec1b26b4736761bedb0c9940d97dfe8457464a25c3ba2ad0d90daace8

**Comment by nikspz** [comment]
I think we have a blocker (https://github.com/hummingbot/hummingbot/issues/5162 ) to proper test this PR

**Comment by aarmoa** [comment]
@nikspz According to the logs in #5126 the error is the same and should be fixed by this PR

**Comment by nikspz** [comment]
@lt7 For the latest dev. branch still facing this issue: https://github.com/hummingbot/hummingbot/issues/5162

Latest dev branch commit b30a23ba7c6be512afbe7353254964e6eda34bb3:
[logs_5148gate.log](https://github.com/hummingbot/hummingbot/files/8255441/logs_5148gate.log)
latest dev branch Windows gitbash source 15 03

**Comment by JeremyKono** [comment]
Hi @lt7, please fix accordingly to our QA's comments or this PR will not be merged for the next release. Thanks!

**Comment by lt7** [comment]
@JeremyKono sorry not clear what the comment  with this PR is regarding, #5162 seems to be separate issue?

**Comment by dennisocana** [comment]
@JeremyKono - @nikspz 's comment here https://github.com/hummingbot/hummingbot/pull/5148#issuecomment-1067796550 is not related to this PR nor the issue this PR is trying to fix. I have seen QA tests in several PRs where the reported issues are not related. You guys should just try to test what the PR is trying to address and create separate issues for unrelated bugs.

**Review by rapcmia — APPROVED** [review]
Test performed:
- Install/compile PR successful
- Test issue#5162 and this PR fix the unexpected errors
- Test issue#4339:
	- Test TWAP and XEMM using LM connectors
	- Orders are created and cancelled ok 
	- Check status, there are no errors anymore 
	- Check history after few trades, all ok 
- Tested on Linux (Ubuntu18LTS) and Mac (m1) 
- Setup simple PMM and monitor order create/cancellation, all ok 
- Tested on source and docker build, all ok

**Pull request merged**
