### PR TITLE
Feat/isort

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR adds a pre-commit hook that will run [`isort`](https://pycqa.github.io/isort/) with pre-configured settings to automatically sort the imports of files that were affected by the commit. This will ensure the code has ever more uniform and clean import sections as new commits get merged affecting various parts of the code.

**Tests performed by the developer**:
I simply tested that the hook will get installed on running the `install` script and that the sorting will happen on a commit command.

**Tips for QA testing**:
N/A

### CODE REVIEW

**Review by cardosofede — DISMISSED** [review]
The changes look good to me.

**Comment by JeremyKono** [comment]
@petioptrv can you please resolve conflicts in this PR? Thanks!

**Comment by petioptrv** [comment]
> @petioptrv can you please resolve conflicts in this PR? Thanks!

@JeremyKono done!

**Comment by JeremyKono** [comment]
Hi @petioptrv, there are some failing tests on this PR. Can you please take a look at it and see what the issue is?

**Review by JeremyKono — APPROVED** [review]

**Pull request merged**
