### PR TITLE
feat/ add FTX Perpetual connector

### PR DESCRIPTION
**Pull request by CrimsonJacket**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Move FTX Perpetual connector into Hummingbot Foundation repository.

Refer to the details of this proposal:
[HGP-18 [DG] Add FTX perpetual connector to boost FTX fee rebates](https://snapshot.org/#/hbot.eth/proposal/0xaceb4abefb3bf1788dbed7b73e4c5ceb4608422f4910699003e8b041faa78508)

**Tests performed by the developer**:
Currently there's not unit tests available for FTX Perpetual.

**Tips for QA testing**:
Ensure that FTX Perpetual connector is working as intended.

### CODE REVIEW

**Comment by cardosofede** [comment]
Hi @CrimsonJacket, can you add to the body of the place order request, the key externalReferralProgram with the value "hummingbot1"?
Is already implemented in the spot connector. Line 84 define the class variable | Line 583 add the param to the request.

**Comment by mifeng** [comment]
@rapcmia @nikspz @arnelhbot This PR should be top priority to get into the 1.7 release

**Comment by nikspz** [comment]
the issues showing for PR:
1. error `traiding pairs autometion wont work` on the `initial start`
2. does `not list available ftx perpetual markets` when "tab" on markets parameter
3. Failed to start a perpetualMM strategy, stuck on `unexpected error occurred when listening to orderbook streams`. (don't place orders to OPEN position)

Steps:
Clone and install feature branch
Start the bot

Actual:
Bot showing `ERROR - Connector ftx_perpetual failed to retrieve its trading pairs. Trading pairs autocompletion won't work.`

[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/9157508/logs_hummingbot.log)
```
2022-07-21 06:49:52,871 - 137420 - hummingbot.core.utils.trading_pair_fetcher - ERROR - Connector ftx_perpetual failed to retrieve its trading pairs. Trading pairs autocompletion won't work.
Traceback (most recent call last):
  File "/home/ubuntu/ftxp5438/hummingbot/core/utils/trading_pair_fetcher.py", line 69, in call_fetch_pairs
    pairs = await fetch_fn
  File "hummingbot/connector/exchange_base.pyx", line 85, in all_trading_pairs
    mapping = await self.trading_pair_symbol_map()
  File "hummingbot/connector/exchange_base.pyx", line 65, in trading_pair_symbol_map
    async with self._mapping_initialization_lock:
  File "hummingbot/connector/exchange_base.pyx", line 67, in hummingbot.connector.exchange_base.ExchangeBase.trading_pair_symbol_map
    await self._initialize_trading_pair_symbol_map()
  File "hummingbot/connector/exchange_base.pyx", line 365, in _initialize_trading_pair_symbol_map
    raise NotImplementedError
NotImplementedError
```
image

Steps: 
create a perpetualMM strategy using ftx_perpetual
try to set up market pair for ftx_perpetual

Actual:
does `not list available ftx perpetual markets` when "tab" on markets parameter

Expected:
Bot list available ftx perpetual markets like it showed for other connectors

5438 ftx

Steps: 
create a perpetualMM strategy using ftx_perpetual
set up actual market pair
start the perpetualMM strategy using ftx_perpetual

Actual:
Failed to place an OPEN orders, stuck on `unexpected error occurred when listening to orderbook streams`. 
(tried ETH-USD, ETH-PERP, recommended BTC-USD Pair also)

Expected:
Bot place orders to OPEN position

[logs_conf_perpetual_market_making_2.log](https://github.com/hummingbot/hummingbot/files/9157591/logs_conf_perpetual_market_making_2.log)
[conf_perpetual_market_making_2.zip](https://github.com/hummingbot/hummingbot/files/9157586/conf_perpetual_market_making_2.zip)
```
2022-07-21 07:27:37,112 - 137420 - hummingbot.connector.derivative.ftx_perpetual.ftx_perpetual_api_order_book_data_source - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/ubuntu/ftxp5438/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    ws: WSAssistant = await self._connected_websocket_assistant()
  File "/home/ubuntu/ftxp5438/hummingbot/core/data_type/order_book_tracker_data_source.py", line 182, in _connected_websocket_assistant
    raise NotImplementedError
NotImplementedError
```
image

**Comment by rapcmia** [comment]
PR update:
- Checked the latest commit `82ec19fbf06` but still getting same errors below:
   > * error `traiding pairs autometion wont work` on the `initial start`
   > * does `not list available ftx perpetual markets` when "tab" on markets parameter
   > * Failed to start a perpetualMM strategy, stuck on `unexpected error occurred when listening to orderbook streams`. (don't place orders to OPEN position)

Tagging @mhrvth for possible update this week. Thank you!

**Comment by aarmoa** [comment]
Hello @rapcmia. The connector should now be updated to the latest development branch structure, and should be usable. I have also added more unit tests.

**Comment by nikspz** [comment]
Test performed:
Cloned and compiled feature branch = OK
Started client and created password = OK 
Connected API Keys with no issues = OK
Created/started PerpetualMM strategy = OK 
Filled and cancel orders work accordingly = OK
Filled orders are tracked via datadog = OK
Filled orders on History, CSV Data file matched with the exchange = OK

Current Issues (commit a8b330f52f4ea9d2f94683ecd9d79493a4063306)

Checked status - `status --live not updating`
Data integrity verified synced with exchange - `order_book --live not updating`
Checking history - History not showing `position type` (showing `NIL` instead of OPEN or CLOSE)
Fees matched with the exchange - Failed (exchange maker 0.02% and taker 0.07% vs bot use flat fees 0.07% for all)

**Comment by nikspz** [comment]
Upon checking after latest dev merged bot failed to connect/check balance for `ftx_perpetual`

Steps to reproduce:
1. Clone and install branch
2. start the bot
3. connect ftx_perpetual

Actual:
Bot showing error:
`Unhandled error in background task: cannot import name 'FundingInfo' from 'hummingbot.core.event.events' (/home/ubuntu/ftx5438p/hummingbot/core/event/events.py)`

Expected:
no errors and could successfully connect Ftx perpetual


[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/9348206/logs_hummingbot.log)
```
2022-08-16 05:15:13,021 - 128968 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: cannot import name 'FundingInfo' from 'hummingbot.core.event.events' (/home/ubuntu/ftx5438p/hummingbot/core/event/events.py)
Traceback (most recent call last):
  File "/home/ubuntu/ftx5438p/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/ftx5438p/hummingbot/client/command/balance_command.py", line 85, in show_balances
    all_ex_bals = await asyncio.wait_for(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/home/ubuntu/ftx5438p/hummingbot/user/user_balances.py", line 130, in all_balances_all_exchanges
    await self.update_exchanges(client_config_map)
  File "/home/ubuntu/ftx5438p/hummingbot/user/user_balances.py", line 126, in update_exchanges
    results = await safe_gather(*tasks)
  File "/home/ubuntu/ftx5438p/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/ubuntu/ftx5438p/hummingbot/user/user_balances.py", line 100, in update_exchange_balance
    return await self.add_exchange(exchange_name, client_config_map, **api_keys)
  File "/home/ubuntu/ftx5438p/hummingbot/user/user_balances.py", line 76, in add_exchange
    market = UserBalances.connect_market(exchange, client_config_map, **api_details)
  File "/home/ubuntu/ftx5438p/hummingbot/user/user_balances.py", line 22, in connect_market
    connector_class = get_connector_class(exchange)
  File "/home/ubuntu/ftx5438p/hummingbot/client/config/config_helpers.py", line 470, in get_connector_class
    mod = __import__(conn_setting.module_path(),
  File "/home/ubuntu/ftx5438p/hummingbot/connector/derivative/ftx_perpetual/ftx_perpetual_derivative.py", line 44, in <module>
    from hummingbot.core.event.events import (
ImportError: cannot import name 'FundingInfo' from 'hummingbot.core.event.events' (/home/ubuntu/ftx5438p/hummingbot/core/event/events.py)
```
5438 ftx perpet

**Pull request closed without merging**
