### PR TITLE
feat/whitebit spot connector

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Implementation of Whitebit exchange spot connector

The PR includes a change in the order book data source classes for altmarkets, liquid, kraken and ndax connectors. All those classes were missing a method required by the superclass, causing misleading errors in the unit tests error logs.

**Tests performed by the developer**:
Added unit tests for all new components

**Tips for QA testing**:
Run all validations required for a new connector

HIP link: https://snapshot.org/#/hbot-ip.eth/proposal/0x42a7d235f096666c08459195cc1a0f59134fd22b29c1e712cbbf9bae3d63738f

This PR comes from https://github.com/CoinAlpha/hummingbot/pull/285

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update:
- Test API valid and invalid, ok 
- Created docker image for client, tested on docker build
- Balance command displays the amount and allocation 
- Setup simple PMM strategy to test connector
- Create and cancel of orders are observed working as expected 
- Orderbook and status live matched between client to connector
- Tested long (5mins) and short(5s), all ok 
- Order execution and trade data: matched
- Hanging order with order level and max order age: ok 
- Hanging order cancellation  working as expected 
		
Pending
- Tests on source
- Running connector overnight

**Comment by nikspz** [comment]
PR Update:
Tested on source:
- Connected API keys - OK
- Confirmed wallet and exchange balance same - OK
- Created a pureMM strategy and went through initial prompts successfully - OK
- Started the strategy without issues, confirmed orders are created and cancelled based on config - OK
- Manually placed order cancellation - OK
- Confirmed order book prices is in sync with the exchange - OK
- Trade information are correct based on history command output - OK
- Compared trades in client and exchange - OK
- Confirmed hanging order/cancellation and multiple order levels works as expected - OK
- Tested on supported strategies, confirmed working - OK
- Successfully built a docker image and create a docker instance

Pending
Running connector overnight

**Review by rapcmia — APPROVED** [review]
Test performed:
- Tests invalid and valid connector APIs
- Confirmed wallet and exchange balance the same 
- Create simple pure market making and observed expected behaviors
- Orders are created and cancelled successfully
- Orderbook from client and exchange matched 
- Order execution with hanging order/cancellation and multiple order levels works as expected
- Trade data between client/csv and exchange trade history matched 
- Tested few supported strategies and observed working ok 
- Successfully built docker image for docker build
- Tested both source and docker on local and AWS

**Review by cardosofede — APPROVED** [review]
LGTM!

**Comment by JeremyKono** [comment]
Bounty has been paid. Thank you for your contribution!

**Pull request merged**
