### PR TITLE
Feat/Add position mode checks to `Perpetual MM` and `PerpetualTrading` base class

### PR DESCRIPTION
**Pull request by mhrvth**
**This PR depends on the PR** https://github.com/CoinAlpha/hummingbot/pull/152

**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Added handling of PositionModeChangeEvent.
Informs the user if position mode change was successful or not.
Attempts to resolve the situation by cancelling all active orders.

**Tests performed by the developer**:

Ran the strategy with Bybit Perpetual, tried to change the position mode.
Ran unit tests

**Tips for QA testing**:

Try to create an order in the account in one mode, and start the strategy configure for another mode.
It should print an error message and cancel the order.

### CODE REVIEW

**Comment by dennisocana** [comment]
Proposal created: https://snapshot.org/#/hbot-prp.eth/proposal/0xb3dc721d26013743a405255b9da4d1ec4dfba80f0b784633b0f91b826a55177b

**Comment by mhrvth** [comment]
**A tip for QA testing:**

I had to modify also Binance perpetual and dYdX to emit the position mode change event, otherwise the strategy would be blocked if used with them. 

Please test those two connectors specifically too.

**Comment by mhrvth** [comment]
**A tip for QA testing:**

I had to modify also Binance perpetual and dYdX to emit the position mode change event, otherwise the strategy would be blocked if used with them. 

Please test those two connectors specifically too.

**Comment by rapcmia** [comment]
PR update: We completed testing dydx and still looking into bybit and binance perpetuals connector

**Review by rapcmia — APPROVED** [review]
Test performed:
- Clone and install feature branch
- Setup simple Perpetual market-making
- Set both client and exchange to either oneway or hedge, all ok 
- Manually OPEN position on exchange on Oneway, 
	- Start client on Oneway, exit-order created 
	- Start client on Hedge, users are instructed to fix or close existing position on account 
- Manually OPEN position on exchange on Hedge, getting same behavior when testing Oneway
- Start the client and exchange both on Oneway and OPEN position via client
	- Setting the position mode to Hedge and starting the bot again wont create exit-order and inform user to fix or close existing position on account 
	- This behavior is the same as well if setting position mode initially to Hedge then to Oneway
- Tested DyDx perpetual, Bybit perpetual and Binance perpetual, all ok

**Pull request merged**
