### PR TITLE
refactor/ #6710 Rename uniswap_v3_lp Strategy to amm_v3_lp

### PR DESCRIPTION
**Pull request by HarjobandeepSingh**
A description of the changes proposed in the pull request:

This PR involves renaming the uniswap_v3_lp strategy to amm_v3_lp throughout the Hummingbot client and documentation site. The change is made to reflect the fact that DEX connectors like PancakeSwapV3 and Osmosis now support adding and removing liquidity ranges, making the strategy exchange-agnostic.

Tests performed by the developer:

After making the changes, I have run the unit tests related to the strategy and ensured that they all pass with the new strategy name. I have also tested the amm_v3_lp strategy in various scenarios to ensure it’s working as expected.

### CODE REVIEW

**Comment by nikspz** [comment]
@HarjobandeepSingh For contributions please use development branch

https://hummingbot.org/developers/contributions/#checklist

**Comment by HarjobandeepSingh** [comment]
> @HarjobandeepSingh For contributions please use development branch
> 
> https://hummingbot.org/developers/contributions/#checklist

Ok

**Comment by HarjobandeepSingh** [comment]
> @HarjobandeepSingh For contributions please use development branch
> 
> https://hummingbot.org/developers/contributions/#checklist

So now i have to create new pull request  ?
@nikspz

**Comment by nikspz** [comment]
@HarjobandeepSingh You could create new

**Comment by HarjobandeepSingh** [comment]
> @HarjobandeepSingh You could create new

@nikspz ok

**Pull request closed without merging**
