### PR TITLE
Feat/add creation timestamp to in flight orders

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
We need to start registering the orders creation timestamp as a separate field. Currently orders take that information from the last component of the order id. But there is a requirement to change the order id generation method, to ensure its uniqueness, and the creation timestamp will not be part of the order id any more in the future.

This PR adds the creation timestamp in the inflight orders. It also changes the calculation of the orders age that was done by taking the creation timestamp from the client order id. Applies the same changes to the hanging orders.
Modifies the JSON serialization/deserialization of orders to include the creation timestamp.
Changes the market recorder to use the new timestamp when storing the creation time instead of using the timestamp when the event was received (the previous logic).

**Tests performed by the developer**:
Added unit tests to validate the serialization/deserialization and the market recorder changes.
Changed existing tests for hanging orders.

**Tests performed**:
- Create and run pure market making and avellaneda market making strategies on spot connectors
- Confirmed that hanging order execution and cancellation works on both strategies and no ghost hanging orders are created when restarting the strategy
- Create and run perpetual market making on perpetual connectors
- Create and run amm_arb strategy on protocol connectors
- Confirmed that filled order event on tested strategies works as expected
- Confirmed all issues found were addressed and fixed

**Tips for QA testing**:
Since the PR modified the in flight orders for all connectors it is required to check that all of them continue working correctly. Please also test running either Pure Market Making or Avellaneda strategy using hanging orders.

This PR comes from https://github.com/CoinAlpha/hummingbot/pull/55

### CODE REVIEW

**Comment by dennisocana** [comment]
Proposal created: https://snapshot.org/#/hbot-prp.eth/proposal/0xb140cd4e6e918098bf90ce259d41890ee8c8671e820bacd600df5fedd6d41234

**Comment by nikspz** [comment]
Upon checking with @rapcmia Getting different results for testing this branch using HummingbotFoundation and Coinalpha repo

For testing using HummingbotFoundation repository, get `Unexpected error running clocktick` for the connectors when `trying to create orders on exchage`
image

**Comment by phbrgnomo** [comment]
@aarmoa @dennisocana Tests are failing. Please check before the issue before the end of the voting period.

**Comment by JeremyKono** [comment]
Hi, @aarmoa. Please resolve branch conflicts so that QA can rerun the tests. Thanks!

**Comment by aarmoa** [comment]
Sorry for the delay @phbrgnomo and @JeremyKono. I have solved the merge issues but now I still need to apply the creation timestamp changes to the new exchange Altmarkets, that seems to have been recently merged.

**Comment by aarmoa** [comment]
@phbrgnomo @JeremyKono all merging issues should be fixed now

**Comment by JeremyKono** [comment]
Hi, @aarmoa. Seems like the same issue persists on the workflow when QA reran it. Kindly check what's the issue of the PR. Thanks!

**Review by Nullably — APPROVED** [review]

**Comment by aarmoa** [comment]
Hello @JeremyKono. The issue now is different:
```
FAIL: test_list_trades (test.hummingbot.client.command.test_history_command.HistoryCommandTest)
```
This error has been introduced by one of the latest merges done in the foundation (I have seen the same error happening when working in other PR). I will push a fix to it as part of this PR.

**Review by Nullably — DISMISSED** [review]

**Comment by rapcmia** [comment]
PR update: on-going test

**Comment by phbrgnomo** [comment]
PRP have not been approved because it didnt reached the minimum quorum. (https://snapshot.org/#/hbot-prp.eth/proposal/0xb140cd4e6e918098bf90ce259d41890ee8c8671e820bacd600df5fedd6d41234)

If still interested in adding this PR to the main code base, please review it, and create a new PRP.

Thank you for the contribution!

**Comment by dennisocana** [comment]
Re-created proposal: https://snapshot.org/#/hbot-prp.eth/proposal/0x08cc77f52affed3c6e4dceb52c5b42fab77b7910ffeb66ec99e193c8f28c88a4

**Review by nikspz — APPROVED** [review]
Tested and approved by QA

Test performed:
- Setup pure market making and avellaneda strategy for spot connectors 
- Setup perpetual market making on derivative connectors 
- Setup amm_arb strategy using gateway-v1 on protocol connectors using Kovan testnet
- Monitor trades on different strategies then compare history, CSV and connector's trade history

**Pull request merged**
