### PR TITLE
Fix/dexalot lost orders fix

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This PR addresses the issue where Dexalot orders remain stuck (orphaned) on the exchange. The issue consisted in the connector erroneously returning a status of "FAILED" for an order when the transaction still hadn't been processed.

It also adds debugging statements to easily diagnose future issues.

**Tests performed by the developer**:

Unit tests.

**Tips for QA testing**:

Please ensure the behaviour is no longer reproducible.

### CODE REVIEW

**Review by cardosofede — APPROVED** [review]
LGTM!

**Comment by cardosofede** [comment]
@petioptrv can you try to modify the .coveragerc file to omit the specific folder of dexalot?

**Review by rapcmia — APPROVED** [review]
LGTM
- Ran tests on local mbp(m1)
- Setup the tests with latest development gateway version 
- Successfully setup dexalot wallet 
- Enable debugging by updating hummingbot_logs.yml and `./src/app.ts` (gateway)
- Setup Pure market making 
- Ran for 4-5hours to monitor behavior and review logs 
- Getting `order creation transaction hash for` when creating orders 
- Getting `cancel order transaction hash for` when cancelling orders 
- Review timestamps:
   - There was 3-5s delay after order creation and cancellation therefore resulting to warning of fetching orders from exchange 
   - Orders are successfully refreshed on set refresh time
- There was no stuck orders on exchange when running tests 
- There are no stuck orders after `stop` command
- Unfortunately, no opportunity for filled event 
- Build docker image successfully and no errors found on start

**Comment by petioptrv** [comment]
> @petioptrv can you try to modify the .coveragerc file to omit the specific folder of dexalot?

That's the part I'm confused about. The omission is already [there](https://github.com/CoinAlpha/hummingbot/blob/fix/dexalot-lost-orders-fix/.coveragerc#L27).

**Comment by nikspz** [comment]
@petioptrv Could you please increase and check coverage

**Comment by cardosofede** [comment]
@petioptrv I tried to do what I told you before here: https://github.com/hummingbot/hummingbot/pull/6614

**Comment by petioptrv** [comment]
@nikspz, the code is covered, but the tests are not being ran (see [here](https://github.com/hummingbot/hummingbot/blob/development/Makefile#L21)). However, as previously mentioned, the code is technically excluded from coverage as well. See [here](https://github.com/CoinAlpha/hummingbot/blob/fix/dexalot-lost-orders-fix/.coveragerc#L27). I don't understand why the pipeline is failing here

**Comment by petioptrv** [comment]
> @petioptrv I tried to do what I told you before here: #6614

@cardosofede, just noticed I missed your reply last week. I looked it up and you're right: the pattern was [wrong](https://coverage.readthedocs.io/en/latest/source.html#file-patterns). I've pushed a commit to attempt to capture everything under the `gateway` folder, as I believe was the original intent. Cheers 🍻

**Pull request merged**
