### PR TITLE
Fix gateway perpetual price quantum

### PR DESCRIPTION
**Pull request by kadirc**
**A description of the changes proposed in the pull request**:

The problem in #5890 is GatewayEVMPerpetual is using base class' (GatewayEVMAMM's) get_order_size_quantum which is based on the token info on the chain. These tokens don't necessarily match the pairs on perpetual.

The price amount is fixed 18 decimal on perp documentation, so use this fixed value in GatewayEVMPerpetual.
https://support.perp.com/hc/en-us/articles/7161930550681-Open-Close-Position

```
uint256 amount; // 18 decimals
uint256 oppositeAmountBound; // 18 decimals
uint256 deadline; // 0 decimal timestamp
uint160 sqrtPriceLimitX96; // 96-bit fixed-point number as defined [here](https://docs.uniswap.org/sdk/guides/fetching-prices#understanding-sqrtprice)

```
**Tests performed by the developer**:

The first time position was opened on perpetual. Second time, again the request was made but there was another problem using the same nonce, which is another problem. The error on #5890 didn't appear.

**Tips for QA testing**:

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update:
- Run tests on source client and docker gateway build on AWS
- Successfully build docker gateway image for tests
- Setup gateway and perpfi wallet successfully connected 
- Setup simple Spot-Perpetual Arbitrage using perpfi as derivative connector
- Observed that the PR had fix the `Unhandled error n background tasks: USD...` when executing orders
- There are also noticeably issues with the connector not recognizing the open position when the bot has been stopped or relaunch.
	- Pending github ticket shall be created when this PR is merged to development
	- Issue observed does is not related to the PR

Pending:
- Waiting for PR to be merged to developement then we can approve this #5885 

Hi @kadirc thanks for this PR we found a underlying issue on the perpfi connector. While this PR is good to be approved, we have to wait for #5885 to be merged since it was the first one to be approved, we appreciate your time on fixing this issue. Thank you 🙇

**Review by rapcmia — APPROVED** [review]
LGTM

**Comment by rapcmia** [comment]
Merged PR in behalf of Hummingbot foundation team. The fix has been added to development branch and will be available on the release version 1.11.0

**Comment by carlitogetaladajr** [comment]
Hi @kadirc , please fill up & submit the AML Policy Form via this link: https://forms.gle/fw89MmiCnwLizbHNA
This is a one-time process for each ETH Address used to receive HBOT bounty.

**Pull request merged**
