### PR TITLE
fix/ Kraken Convert a coin reward into a coin*(ETH.F -> ETH)

### PR DESCRIPTION
**Pull request by yancong001**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

coin rewards can be treated as coin for normal trade. So convert COIN.F to COIN in balance

**Tests performed by the developer**:

Script test

**Tips for QA testing**:

### CODE REVIEW

**Comment by yancong001** [comment]
when only ETH.F exists, the following script is successfully tested

```
from hummingbot.core.data_type.common import OrderType, PositionAction, PositionMode, PositionSide, TradeType

from hummingbot.client.hummingbot_application import HummingbotApplication
from hummingbot.core.data_type.common import OrderType
from hummingbot.strategy.script_strategy_base import ScriptStrategyBase
from decimal import Decimal


class TestLimitOrders(ScriptStrategyBase):
    """
    This is a simple script strategy that buys 0.01 ETH at market price, then sells it at market price.
    The objective is to test the market order functionality of the Binance connector.
    """
    trading_pair = "TRX-ETH"
    order_amount = Decimal("20")
    markets = {"kraken":{trading_pair}}
    buy_order_id = None
    sell_order_id = None

    def on_tick(self):
        if not self.buy_order_id:
            self.buy_order_id = self.connectors["kraken"].buy(
                trading_pair=self.trading_pair,
                amount=self.order_amount,
                price=Decimal("0.00002897"),
                position_action=PositionAction.OPEN,
                order_type=OrderType.LIMIT)
        HummingbotApplication.main_application().stop()
```

**Comment by nikspz** [comment]
- Reviewed now ETH.F or other currency displayed as ETH in `balance` ✅
- Could place order now using ETH-USDT etc. ✅

Pending: filled orders, other pair check

image
image

**Review by nikspz — APPROVED** [review]
Reviewed now ETH.F or other currency displayed as ETH in balance ✅
Could place order now using ETH-USDT , XRP-USDT etc.✅
Filled order events ✅

**Review by fengtality — APPROVED** [review]
Code looks good. To clarify, this fix treats ` ETH.F` tokens as `ETH`, along with similar cases. I assume these tokens are staking rewards earned on Kraken?

**Comment by nikspz** [comment]
> I assume these tokens are staking rewards earned on Kraken?

Yes, for rewards here
https://www.kraken.com/c/rewards

**Pull request merged**
