### PR TITLE
Fix/mark stopped telegram listener as not started

### PR DESCRIPTION
**Pull request by ctria**
**A description of the changes proposed in the pull request**:
Currently the telegram listener sets an internal variable when it starts and only starts if that is not set to True. This variable is not reset to False when the listener is stopped which makes it impossible to restart a stopped listener

**Tests performed by the developer**:
For testing purposes I created a command a stop_notifiers and a start_notifiers command running more or less:
```
class StopNotifiersCommand:
    def stop_notifiers(self):
        for notifier in self.notifiers:
            notifier.stop()

class StartNotifiersCommand:
    def start_notifiers(self):
        for notifier in self.notifiers:
            notifier.start()
```

And I verified that it is possible to restart the notifiers.

**Tips for QA testing**:
Included a test case:
test/hummingbot/notifier/test_telegram.py

### CODE REVIEW

**Review by aarmoa — COMMENTED** [review]
The code change looks good to me

-- Reviewed in representation of the Hummingbot Foundation Technical DAO

**Comment by aarmoa** [comment]
@ctria please remember to create the PRP for the community to vote for this PR, and add the link to the PRP as a comment or in the PR description

**Comment by ctria** [comment]
I'll do as soon as I get the 1 HBOT required :)

**Comment by ctria** [comment]
PRP: https://snapshot.org/#/hbot-prp.eth/proposal/0xebbdacbb83f41e03d25927692ad92c475e15ac4255bea18d253bf39e93bcc65e

**Comment by ctria** [comment]
As this is my first code PR where the checks run.... I'm not sure if I'm supposed to fix those issues. They seem to be related to files I haven't touched.

**Comment by JeremyKono** [comment]
Please fix the Github workflow issue in this PR. Thanks!

**Review by nikspz — APPROVED** [review]
Test performed:

- config telegram_token - OK
- config telegram_chat_id - OK
- Create/Import a strategy - OK
- Start and check telegram app - OK
- exit bot then restart - OK
- Reset global configurations - OK
- Setup telegram bot in the conf_global file - OK
- test telegram commands - OK

**Pull request merged**
