### PR TITLE
Refactor/bybit parpetual latest standards

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This PR refactors Bybit perpetual to the latest standards. It also creates the `PerpetualDerivativePyBase`, which brings the `ExchangePyBase` approach to the perpetual exchanges.

**Tests performed by the developer**:

- Test cases for the new code

**Tips for QA testing**:

Everything about this connector should be tested, plus please ensure that the other perpetual connectors can start correctly — no need to thoroughly test them.

Proposal link: https://snapshot.org/#/hbot-prp.eth/proposal/0x9694fa477470dcae142476786db58b3860024e19f77165729b377ceb2bfa52da

### CODE REVIEW

**Comment by nikspz** [comment]
Test performed:
 - clone and Install featured branch = OK
 - Connect a valid Bybit Perpetual API = OK
 - Balance output = OK
 - Create a strategy = OK
 - Import a strategy = OK
 - Starting strategy = OK
 - Status (--live) command = OK
 - Order Cancelation = OK
 - Data integrity = OK
 - Broker ID = OK
 - Data aggregate = OK
 - Order filled events = OK for trade to open 
 - Verify fee calculation = OK
 pending test:
 - Order filled events - pending for trades to close
 - Funding time
 - Run a quick test on other Perpetual connectors
 - test bybit perpetual testnet

**Review by nikspz — APPROVED** [review]
Test performed:
Cloned and compiled feature branch = OK
Created docker image and container = OK
Started client and created password = OK
Connected API with no issues = OK
Created/started PerpetualMM strategy = OK
Checked status and status --live = OK
Data integrity verified synced with exchange = OK
Filled and cancel orders work accordingly = OK
Fees matched with the exchange = OK
Filled orders are tracked via datadog = OK
Handlig Funding time = OK
Checking history = OK
Filled orders on History, CSV Data file match with the exchange = OK
Quick test on other Perpetual connectors = OK
Tested on AWS Source and Docker Build = OK
Spot-perpetual arbitrage - had an issues that also replicated on dev (not related to this PR):
https://github.com/hummingbot/hummingbot/issues/5541, https://github.com/hummingbot/hummingbot/issues/5533

**Comment by JeremyKono** [comment]
Hi @petioptrv, please resolve conflicts in this PR. Thanks!

**Comment by petioptrv** [comment]
@JeremyKono, I've updated the PR. There were non-trivial changes done to the code to bring it up to speed with changes in the connector base class, so I would suggest a thorough re-test by QA

**Comment by rapcmia** [comment]
PR update:
- Tested latest commit 
- Did same test for Spot-perpetual arbitrage and Perpetual market making (some ongoing issues spotted)
  > Cloned and compiled feature branch = OK
  > Created docker image and container = OK
  > Started client and created password = OK
  > Connected API with no issues = OK
  > Created/started PerpetualMM strategy = OK
  > Checked status and status --live = OK
  > Data integrity verified synced with exchange = OK
  > Filled and cancel orders work accordingly = OK
  > Fees matched with the exchange = OK
  > Filled orders are tracked via datadog = OK
  > Handlig Funding time = OK
  > Checking history = OK
  > Filled orders on History, CSV Data file match with the exchange = OK
  > Quick test on other Perpetual connectors = OK
  > Tested on AWS Source and Docker Build = OK
  > Spot-perpetual arbitrage - had an issues that also replicated on dev (not related to this PR):
  > Failed to perform an arbitrage using live exchange as a spot connector #5541,
  > bot showing low balance for base asset on derivative exchange #5533

Just minor checking when setting up markets for bybit_perpetual. I noticed there are some tokens that should not be listed sample is `BTC-USD, XRP-USD, etc..` and it seems these tokens is part of `Inverse contracts`. Crosschecked with dev branch and the results are below:

Screen recording from this PR

https://user-images.githubusercontent.com/73840223/182344203-e77ab1f9-9509-4ef6-9b66-aec6bc3713a5.mp4


Screenshot from development branch:
image

**Review by nikspz — APPROVED** [review]
Cloned and compiled feature branch - ok
Created docker image and container - ok
Started client and created password - ok
Connected API with no issues - ok
Created/started PerpetualMM strategy - ok
Checked status and status --live - ok
Data integrity verified synced with exchange - ok
Filled and cancel orders work accordingly - ok
Fees matched with the exchange - ok
Filled orders are tracked via datadog - ok
Handlig Funding time - ok
Checking history - ok
Filled orders on History, CSV Data file match with the exchange - ok
Quick test on other Perpetual connectors - ok
Tested on AWS Source and Docker Build - ok
Spot-perpetual arbitrage - had an issues that also replicated on dev (not related to this PR):
Failed to perform an arbitrage using live exchange as a spot connector https://github.com/hummingbot/hummingbot/issues/5541, 
bot showing low balance for base asset on derivative exchange https://github.com/hummingbot/hummingbot/issues/5533

**Pull request merged**
