### PR TITLE
[fix] fix the order_id length longer than mexc exchange API required.

### PR DESCRIPTION
**Pull request by hlxwell**
**Before submitting this PR, please make sure**:

- [*] Your code builds clean without any errors or warnings
- [*] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

When the token pair is too long, like babydoge-usdt, then the mexc API exchange will complain `{'msg': 'the length of order id should between 1 and 32', 'code': 400}`
So I added a way to trim the tracking nonce, which could make it shorter, and only trim the head of tracking nonce, since I think the head of timestamp won't change too frequent it could be safer to do so.

**Tests performed by the developer**:

Yes

**Tips for QA testing**:

I traded with token has long pair name, like babydoge-usdt, it works fine.

### CODE REVIEW

**Comment by hlxwell** [comment]
@cardosofede could you please review this fix?

**Review by cardosofede — APPROVED** [review]
LGTM!

**Comment by cardosofede** [comment]
@rapcmia @nikspz just make a quick test on PMM using MEXC in BTC-USDT and BABYDOGE-USDT

**Review by nikspz — APPROVED** [review]
Test performed:

- Cloned and install fix branch
- connected mexc
- created simple pureMM using BTC-USDT, ETH-USDT, MATIC-USDT using fix branch - got message symbol not supported API.
- Retested on latest dev-1.19.0. Got same warning message.
- image
- Tested using PPC-USDT, placed orders successfully
- Created pureMM using BABYDOGE-USDT on latest release, issue reproduced
image

- Created pureMM using BABYDOGE-USDT pair using fix branch, fixed
image

**Comment by nikspz** [comment]
The fix has been deployed on development branch (dev-1.19.0) and next hummingbot version 1.19.0

**Pull request merged**
