### PR TITLE
fix unexpected_error_while_processing_event_201

### PR DESCRIPTION
**Pull request by yancong001**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Review by rapcmia — APPROVED** [review]
- Ran tests using perpetual market making 
- Ran tests using multiple order levels of 3 
- Runtime of 7hrs and review logs
   - No error related to `unexpected_error_while_processing_event_201`
   - Found reduce orders but not related to PR
   - No tests done for v2 strategy (will be tested when merged to development)
 - Build docker image ok

**Comment by rapcmia** [comment]
Hi @yancong001 good day,
PR has been approved however we have failing tests on Github. When available, please have a look thank you

**Comment by cardosofede** [comment]
@yancong001 that method is specific when dealing with dex? seems like trying to raise the error will always raise the error why we are doing this? btw, the coverage needs 1 more line covered

**Comment by yancong001** [comment]
Sometimes exchange_id is received slowly after place_order. In this case, querying active_order raises KeyError.

The parent class “_update_lost_orders_status” method uses the deprecated "_all_trade_updates_for_order" method, so the ”_update_lost_orders_status“ method is redeclared here.

new unittest added.

**Comment by rapcmia** [comment]
Merged to development and part of release version 1.24.0

**Pull request merged**
