### PR TITLE
Feat/strategy v2

### PR DESCRIPTION
**Pull request by cardosofede**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR adds configuration to the scripts by using a folder under conf/scripts similar as the strategies config files that are under conf/strategies.
We need the variable markets in the scripts to initialize the connector in the scripts, and that's something that usually will happen after we use the config to initialize the markets, so there is an addition of a classmethod to retrieve the markets based on the config that will be used.
The solution is not so clean since we are modifying script strategy base that was designed to have a simple start of the markets.
Also in this PR were added the following controllers:

        - BollingerV1
        - TrendFollowerV1

And were adapted with configs the following scripts:

        - v2_directional-trading_bollinger_v1.py
        - v2_directional-trading_macd_bb_v1.py
        - v2_directional-trading_trend_follower_v1.py
        - v2_dman_v1_with_config.py
        - v2_dman_v2_with_config.py
        - v2_dman_v3_with_config.py
        - v2_dman_v4_with_config.py

To test this PR run inside the hummingbot terminal:

1. Run `create --script-config (the script should appear suggested)`
2. Complete all the config steps
3. Run start `--script v2_market-making_dman_v3_with_config.py --conf (the name of the config that you selected)`

**Tests performed by the developer**:

**Tips for QA testing**:
- Test all the scripts added by creating the config and running the config created.
- Make sure that all the default values makes sense and if you have any question about the parameters add it here.

### CODE REVIEW

**Comment by nikspz** [comment]
Test performed:
ran example of the config in description, got error for the trading_pairs should be the list

```
2023-12-27 22:22:50,548 - 3159950 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 1 validation error for DManV3ScriptConfig
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for DManV3ScriptConfig
trading_pairs
  value is not a valid list (type=type_error.list)
```


Changed trading_pairs to `trading_pairs: ["HBAR-USDT"]`
Was able to run the Client using that 
[dman_v1_2 - Copy.txt](https://github.com/hummingbot/hummingbot/files/13781895/dman_v1_2.-.Copy.txt)

```
start --script v2_market-making_dman_v3_with_config.py  --conf dman_v1_2.yml
```

Pending:
- Ongoing run
- Other configs

**Comment by cardosofede** [comment]
@nikspz try with this config: https://gist.github.com/cardosofede/6bc9f7c960c543a93250d29c6bdcc2fa
I think that might be important to improve the create command to allow creating these configs, what do you think?

**Comment by nikspz** [comment]
> I think that might be important to improve the create command to allow creating these configs, what do you think?

Yea that could be cool feature 🙌 to add command like 

```
create --script_config
```

or something like that

**Comment by nikspz** [comment]
@cardosofede 

Steps:
Create .yml file as provided in example
start --script v2_market-making_dman_v3_with_config.py  --conf dman_v1_2.yml
run script for a while to get position
execute stop command

Actual:
review orders to OPEN not cancelled, position not closed (exit command cancel all orders)

Expected:
orders to OPEN cancelled after stop command




[logs_dman_v1_3.log](https://github.com/hummingbot/hummingbot/files/13787129/logs_dman_v1_3.log)
[6741.zip](https://github.com/hummingbot/hummingbot/files/13787131/6741.zip)

```
2023-12-28 14:14:08,790 - 3179876 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2023-12-28 14:14:08,791 - 3179876 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'binance_perpetual'
Traceback (most recent call last):
  File "/home/nikita/strategyv2conf6741/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/nikita/strategyv2conf6741/hummingbot/client/command/stop_command.py", line 36, in stop_loop
    self.strategy.on_stop()
  File "/home/nikita/strategyv2conf6741/scripts/v2_market-making_dman_v3_with_config.py", line 94, in on_stop
    self.close_open_positions()
  File "/home/nikita/strategyv2conf6741/scripts/v2_market-making_dman_v3_with_config.py", line 102, in close_open_positions
    if trading_pair in self.markets[connector_name]:
KeyError: 'binance_perpetual'
2023-12-28 14:14:18,813 - 3179876 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2023-12-28 14:14:18,814 - 3179876 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'binance_perpetual'
Traceback (most recent call last):
  File "/home/nikita/strategyv2conf6741/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/nikita/strategyv2conf6741/hummingbot/client/command/stop_command.py", line 36, in stop_loop
    self.strategy.on_stop()
  File "/home/nikita/strategyv2conf6741/scripts/v2_market-making_dman_v3_with_config.py", line 94, in on_stop
    self.close_open_positions()
  File "/home/nikita/strategyv2conf6741/scripts/v2_market-making_dman_v3_with_config.py", line 102, in close_open_positions
    if trading_pair in self.markets[connector_name]:
KeyError: 'binance_perpetual'
```

Stop command didn't stop the bot, didnot canceled orders, cancelled after exited bot
Stop command didn't stop the bot, didnot canceled orders 2

**Comment by cardosofede** [comment]
Fixed now!

**Comment by nikspz** [comment]
> Fixed now!

@cardosofede 
commit f0e8576

[logs_dman_v1_3.log](https://github.com/hummingbot/hummingbot/files/13788332/logs_dman_v1_3.log)


```
2023-12-28 17:31:12,312 - 3192227 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 
Traceback (most recent call last):
  File "/home/nikita/strategyv2conf6741/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/nikita/strategyv2conf6741/hummingbot/client/command/start_command.py", line 124, in start_check
    self._initialize_strategy(self.strategy_name)
  File "/home/nikita/strategyv2conf6741/hummingbot/client/command/start_command.py", line 291, in _initialize_strategy
    self.start_script_strategy()
  File "/home/nikita/strategyv2conf6741/hummingbot/client/command/start_command.py", line 202, in start_script_strategy
    script_strategy, config = self.load_script_class()
  File "/home/nikita/strategyv2conf6741/hummingbot/client/command/start_command.py", line 238, in load_script_class
    script_class.init_markets(config)
  File "/home/nikita/strategyv2conf6741/hummingbot/strategy/script_strategy_base.py", line 47, in init_markets
    raise NotImplementedError
NotImplementedError
```

image

**Comment by cardosofede** [comment]
@nikspz hey Nikita, just pushed a fix

**Comment by nikspz** [comment]
@cardosofede 
start issue fix confirmed. ✅
the issue on not canceling orders on stop not reproduced as well ✅


Issue on closing position after stop command showed

Steps:
1. Create .yml file as provided in example
2. start --script v2_market-making_dman_v3_with_config.py  --conf dman_v1_4.yml
3. run script for a while to get order/s to OPEN filled
4. execute stop command 

Actual:
(remain orders to OPEN cancelled)
position not closed with ValueError: Market object for buy order is not in the whitelisted markets set.
 

Expected:
position closed with no errors


[logs_dman_v1_4.log](https://github.com/hummingbot/hummingbot/files/13817591/logs_dman_v1_4.log)
[dman_v1_4.yml.txt](https://github.com/hummingbot/hummingbot/files/13817598/dman_v1_4.yml.txt)

```
2024-01-03 09:30:11,305 - 3351933 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order x-3QreWesySHRUT60e0742f430c43cd1 for 162 to OPEN a HBAR-USDT position.
2024-01-03 09:30:11,315 - 3351933 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Open Order Created
2024-01-03 09:30:11,316 - 3351933 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704274211.0, "type": "OrderType.LIMIT", "trading_pair": "HBAR-USDT", "amount": "162", "price": "0.09830", "order_id": "x-3QreWesySHRUT60e0742f430c43cd1", "creation_timestamp": 1704274211.0, "exchange_order_id": "4254750718", "leverage": 20, "position": "OPEN", "event_name": "SellOrderCreatedEvent", "event_source": "binance_perpetual"}
2024-01-03 09:30:11,405 - 3351933 - hummingbot.connector.client_order_tracker - INFO - The SELL order x-3QreWesySHRUT60e0742f42d9e3cd1 amounting to 167/167 HBAR has been filled.
2024-01-03 09:30:11,430 - 3351933 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704274211.0, "order_id": "x-3QreWesySHRUT60e0742f42d9e3cd1", "trading_pair": "HBAR-USDT", "trade_type": "TradeType.SELL", "order_type": "OrderType.LIMIT", "price": "0.09566", "amount": "167", "trade_fee": {"percent": "0", "percent_token": "USDT", "flat_fees": [{"token": "USDT", "amount": "0.00798760"}]}, "exchange_trade_id": "179624384", "exchange_order_id": "4254750717", "leverage": 20, "position": "OPEN", "event_name": "OrderFilledEvent", "event_source": "binance_perpetual"}
2024-01-03 09:30:11,501 - 3351933 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Open Order Completed
2024-01-03 09:30:11,512 - 3351933 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704274211.0, "order_id": "x-3QreWesySHRUT60e0742f42d9e3cd1", "base_asset": "HBAR", "quote_asset": "USDT", "base_asset_amount": "167", "quote_asset_amount": "15.97522", "order_type": "OrderType.LIMIT", "exchange_order_id": "4254750717", "event_name": "SellOrderCompletedEvent", "event_source": "binance_perpetual"}
2024-01-03 09:30:11,513 - 3351933 - hummingbot.connector.client_order_tracker - INFO - SELL order x-3QreWesySHRUT60e0742f42d9e3cd1 completely filled.
2024-01-03 09:32:54,510 - 3351933 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2024-01-03 09:32:54,607 - 3351933 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704274374.0, "order_id": "x-3QreWesySHRUT60e0742f430c43cd1", "exchange_order_id": "4254750718", "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2024-01-03 09:32:54,608 - 3351933 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-3QreWesySHRUT60e0742f430c43cd1.
2024-01-03 09:32:54,792 - 3351933 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704274374.0, "order_id": "x-3QreWesySHRUT60e0742f433293cd1", "exchange_order_id": "4254750716", "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2024-01-03 09:32:54,792 - 3351933 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-3QreWesySHRUT60e0742f433293cd1.
2024-01-03 09:32:55,188 - 3351933 - hummingbot.strategy.script_strategy_base - INFO - Creating HBAR-USDT buy order: price: 0.09566 amount: 167.
2024-01-03 09:32:55,189 - 3351933 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Market object for buy order is not in the whitelisted markets set.
Traceback (most recent call last):
  File "/home/nikita/strategyv2conf6741/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/nikita/strategyv2conf6741/hummingbot/smart_components/strategy_frameworks/executor_handler_base.py", line 113, in control_loop
    self.on_stop()
  File "/home/nikita/strategyv2conf6741/hummingbot/smart_components/strategy_frameworks/market_making/market_making_executor_handler.py", line 29, in on_stop
    self.close_open_positions(connector_name=self.controller.config.exchange, trading_pair=self.controller.config.trading_pair)
  File "/home/nikita/strategyv2conf6741/hummingbot/smart_components/strategy_frameworks/executor_handler_base.py", line 126, in close_open_positions
    action(connector_name=connector_name,
  File "/home/nikita/strategyv2conf6741/hummingbot/strategy/script_strategy_base.py", line 108, in buy
    return self.buy_with_specific_market(market_pair, amount, order_type, price, position_action=position_action)
  File "hummingbot/strategy/strategy_base.pyx", line 505, in hummingbot.strategy.strategy_base.StrategyBase.buy_with_specific_market
    return self.c_buy_with_specific_market(market_trading_pair_tuple, amount,
  File "hummingbot/strategy/strategy_base.pyx", line 528, in hummingbot.strategy.strategy_base.StrategyBase.c_buy_with_specific_market
    raise ValueError(f"Market object for buy order is not in the whitelisted markets set.")
ValueError: Market object for buy order is not in the whitelisted markets set.
```

image
image

**Comment by rapcmia** [comment]
Test latest commit `44d4a72ffd253c485dab994d89f48b3a931cfc01`
- Check `create —help`, displays `—script-config` subparams ok 

Run `create —script-config`
   image
   image
    - When running `create --script-config` only, it lets the user create v1 strategies
    - Check the conf folder, no created file on conf/scripts
    - Confirmed the file created on this test is under confi/strategies folder

---

Run `create —script-config random_text`
   image
    ```
    2024-01-04 10:49:53,625 - 7020 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: reload() argument must be a module
    Traceback (most recent call last):
      File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/importlib/__init__.py", line 139, in reload
        name = module.__spec__.name
    AttributeError: 'NoneType' object has no attribute '__spec__'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/importlib/__init__.py", line 142, in reload
        name = module.__name__
    AttributeError: 'NoneType' object has no attribute '__name__'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
        return await c
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/client/command/create_command.py", line 55, in prompt_for_configuration_v2
        script_module = importlib.reload(module)
      File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/importlib/__init__.py", line 144, in reload
        raise TypeError("reload() argument must be a module")
    TypeError: reload() argument must be a module
    ```
    - When this happened, it will return `TypeError: reload() argument must be a module`
    - We are not able to run any command and have to relaunch the hummingbot terminal to work again


Steps to reproduce:
1. Open hummingbot 
2. Run `create --script-config ajksdhasd`

[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/13825362/logs_hummingbot.log)

---

Run `create —script-config v2_market-making_dman_v3_with_config.py`
- When you run `create —script-config` then hit tab, autocomplete shows scripts that are compatible with this feature ✅ 
- Copied the `v2_market-making_dman_v3_with_config.py` to `test01.py` and it displayed on autocomplete
   image
   - Tried to comment out some parts of the script to check which enables the script to be added to the list and it did not displayed `test in progress`
- Setup a .yml file 
   image
   - Observed there are no validation on this feature however user can still edit the yml file within the conf/script folder
     image
- Run `start —script v2_market-making_dman_v3_with_config.py—conf dmanv1.yml`
    image
    ```
    2024-01-04 11:14:37,006 - 8511 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'E'
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
        return await c
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/connector/perpetual_derivative_py_base.py", line 356, in _execute_set_leverage
        success, msg = await self._set_trading_pair_leverage(trading_pair, leverage)
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 760, in _set_trading_pair_leverage
        symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
      File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
        return symbol_map.inverse[trading_pair]
      File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
        return self._fwdm[key]
    KeyError: 'E'
    2024-01-04 11:14:37,013 - 8511 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'T'
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
        return await c
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/connector/perpetual_derivative_py_base.py", line 356, in _execute_set_leverage
        success, msg = await self._set_trading_pair_leverage(trading_pair, leverage)
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 760, in _set_trading_pair_leverage
        symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
      File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
        return symbol_map.inverse[trading_pair]
      File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
        return self._fwdm[key]
    KeyError: 'T'
    2024-01-04 11:14:37,016 - 8511 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'H'
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
        return await c
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/connector/perpetual_derivative_py_base.py", line 356, in _execute_set_leverage
        success, msg = await self._set_trading_pair_leverage(trading_pair, leverage)
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 760, in _set_trading_pair_leverage
        symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
      File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
        return symbol_map.inverse[trading_pair]
      File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
        return self._fwdm[key]
    KeyError: 'H'
    2024-01-04 11:14:37,017 - 8511 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: '-'
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
        return await c
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/connector/perpetual_derivative_py_base.py", line 356, in _execute_set_leverage
        success, msg = await self._set_trading_pair_leverage(trading_pair, leverage)
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 760, in _set_trading_pair_leverage
        symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
      File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
        return symbol_map.inverse[trading_pair]
      File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
        return self._fwdm[key]
    KeyError: '-'
    2024-01-04 11:14:37,019 - 8511 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'U'
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
        return await c
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/connector/perpetual_derivative_py_base.py", line 356, in _execute_set_leverage
        success, msg = await self._set_trading_pair_leverage(trading_pair, leverage)
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 760, in _set_trading_pair_leverage
        symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
      File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
        return symbol_map.inverse[trading_pair]
      File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
        return self._fwdm[key]
    KeyError: 'U'
    2024-01-04 11:14:37,020 - 8511 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'S'
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
        return await c
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/connector/perpetual_derivative_py_base.py", line 356, in _execute_set_leverage
        success, msg = await self._set_trading_pair_leverage(trading_pair, leverage)
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 760, in _set_trading_pair_leverage
        symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
      File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
        return symbol_map.inverse[trading_pair]
      File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
        return self._fwdm[key]
    KeyError: 'S'
    2024-01-04 11:14:37,022 - 8511 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'D'
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
        return await c
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/connector/perpetual_derivative_py_base.py", line 356, in _execute_set_leverage
        success, msg = await self._set_trading_pair_leverage(trading_pair, leverage)
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 760, in _set_trading_pair_leverage
        symbol = await self.exchange_symbol_associated_to_pair(trading_pair)
      File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
        return symbol_map.inverse[trading_pair]
      File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 523, in __getitem__
        return self._fwdm[key]
    KeyError: 'D'
    ```
     - Script did not start and return KeyError

Steps to reproduce: Test run on binance_perpetual mainnet and testnet to check
1. Run `create --script-conf v2_market-making_dman_v3_with_config.py` to create yml file
2. Run `start —script v2_market-making_dman_v3_with_config.py —conf created.yml`
3. Observe behavior when loading markets 

[logs_dmanv1.log](https://github.com/hummingbot/hummingbot/files/13825358/logs_dmanv1.log)
[dmanv1.yml.log](https://github.com/hummingbot/hummingbot/files/13825359/dmanv1.yml.log)

**Comment by cardosofede** [comment]
@rapcmia just fixed the issue!

**Comment by rapcmia** [comment]
Test commit `22b95df577124d`
> Script did not start and return KeyError
- Issue on keyError has been fixed ✅

Ran tests on quickstart
image
- We assume there are something that needs to be updated on `./start` script
- On the otherhand, `bin/hummingbot_quickstart.py -p a -f v2_market-making_dman_v3_with_config.py -c conf_script2.yml` works ✅
- I guess we can tag @david-hummingbot to update the start script for this PR

---

Ran tests on binance perpetual mainnet and testnet
image
- Both exchanges  had the same behavior
- Disabled `smart activation`, worked ok ✅ 
  image
  - However, We observed that the script wont create the other markets and return `not enough budget to open position` when using multiple markets 
  - Ran same setup on dmanv3 just to check and worked ok
     image

Steps to reproduce:
1. Run `create --script-conf v2...config`
   - Make sure config supports multiple market pairs
   - Disable smart activation on .yml file 
3. Run `start --script v2...config --conf your-script.yml`
4. Observe behavior 

[logs_conf_script2.log](https://github.com/hummingbot/hummingbot/files/13837673/logs_conf_script2.log)

**Comment by fengtality** [comment]
When creating configs, I think each question should include the type to give more hints to users, for example:
```
The exchange to trade on (string) >>> binance_perpetual

The leverage to use for the perpetual market (integer) >>> 1
```

**Review by fengtality — CHANGES_REQUESTED** [review]
See requested changes in comment above.

**Comment by rapcmia** [comment]
Test commit `a229f965ecedc070..`
- Overview of latest commit
    - Added variation of scripts that support config
- create —script-config
- `--help` command works ok
- Successfully create script
    - There are added info on prompts now
    - Saved on `../conf/script`
    - When changing file name, it saves with .yml file
        - What happen if with special characters `-` and `_?`:
        - All ok on names `conf_.yml` and `conf-.yml`

---

Ran tests on the following scripts:
- v2_directional-trading_bollinger_v1.py
   image
   - Created 3/3 scripts with default or different name getting same behavior 
 - v2_directional-trading_macd_bb_v1.py ✅ 
 - v2_directional-trading_trend_follower_v1.py 
   image
    ```
    2024-01-10 16:48:45,857 - 26687 - hummingbot.data_feed.candles_feed.binance_perpetual_candles.binance_perpetual_candles - INFO - Subscribed to public klines...
    2024-01-10 16:48:46,001 - 26687 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'binance_perpetual'
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
        return await c
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/smart_components/strategy_frameworks/executor_handler_base.py", line 104, in control_loop
        self.on_start()
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/smart_components/strategy_frameworks/directional_trading/directional_trading_executor_handler.py", line 22, in on_start
        self.set_leverage_and_position_mode()
      File "/Users/rapcomia/github/hummingbot/6741/hummingbot/smart_components/strategy_frameworks/directional_trading/directional_trading_executor_handler.py", line 25, in set_leverage_and_position_mode
        connector = self.strategy.connectors[self.controller.config.exchange]
    KeyError: 'binance_perpetual'
    ```
     - This error happened when using `binance_perpetual_testnet`
     - Tried to run on mainnet and had it running for around 30mins but its seems to be looking for opportunity `wip`
        image
          - On this test we tried to change the market pair, order amount and leverage and still the same behavior 
- v2_dman_v1_with_config.py ✅ 
- v2_dman_v2_with_config.py ✅ 
- v2_dman_v3_with_config.py ✅ 
- v2_dman_v4_with_config.py ✅ 

---

Ran quickstart
- `./bin/hummingbot_quickstart.py -p a -f v2_dman_v4_with_config.py -c conf_v2_dman-.yml`    ✅ 
- `./start` command will be updated on https://github.com/hummingbot/hummingbot/pull/6755

**Comment by rapcmia** [comment]
Test commit `59d76f9`
- v2_directional-trading_bollinger_v1.py
    - Issue has been fixed and ran tests on both mainnet and testnet 
- v2_dman_v2_with_config.py
    - Overlooked this part where the `order_refresh_time` is missing on the config causing error
        ```
        2024-01-11 13:56:50,695 - 8775 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'DManV2ScriptConfig' object has no attribute 'order_refresh_time'
        Traceback (most recent call last):
          File "/Users/rapcomia/github/hummingbot/6741/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
            return await c
          File "/Users/rapcomia/github/hummingbot/6741/hummingbot/client/command/start_command.py", line 125, in start_check
            self._initialize_strategy(self.strategy_name)
          File "/Users/rapcomia/github/hummingbot/6741/hummingbot/client/command/start_command.py", line 292, in _initialize_strategy
            self.start_script_strategy()
          File "/Users/rapcomia/github/hummingbot/6741/hummingbot/client/command/start_command.py", line 209, in start_script_strategy
            self.strategy = script_strategy(self.markets, config)
          File "/Users/rapcomia/github/hummingbot/6741/scripts/v2_dman_v2_with_config.py", line 75, in __init__
            order_refresh_time=config.order_refresh_time,
        AttributeError: 'DManV2ScriptConfig' object has no attribute 'order_refresh_time'
        ```
        - Followed the format of `BaseClientModel` and added `order_refresh_time`, seems to work ok 🙇🏼 

PR good to be approved

**Review by rapcmia — APPROVED** [review]

**Review by fengtality — APPROVED** [review]

**Pull request merged**
