### PR TITLE
Fix/xemm rate oracle

### PR DESCRIPTION
**Pull request by MementoRC**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Related to issue:
[XEMM - Incorrect rate oracle conversion#5695](https://github.com/hummingbot/hummingbot/issues/5695)
The strategy seemed to coerce a MakerTakerPair into a MarketTradingPair - This is just a proposal for review, since no expertise on XEMM

**Tests performed by the developer**:
Only live test with Kucoin/Kucoin. Screenshot shows rates after the rate oracle is connected:
image

**Tips for QA testing**:

### CODE REVIEW

**Comment by nikspz** [comment]
Upon checking still report warning message can't find oracle conversion rate for AVAX-USDT, using 1.0 instead

image

Steps to reproduce:

1. clone and installed feature branch
2. create/start a strategy using kucoin and pangolin_avalanche_avalanche

Actual:
Bot Showed warning message can't find oracle conversion rate for AVAX-USDT, using 1.0 instead

**Comment by MementoRC** [comment]
Is this not normal? the Rate Oracle has not started yet, it shows on the next line where it finally is CONNECTED

**Review by kadirc — COMMENTED** [review]
If conversion_rate_mode is fixed_conversion_rate,

or no conversion needed, e.g.

image

Then maybe we don't want to wait on rate oracle.

I tried to do that(unaware of this PR) on my branch, but wasn't convinced yet by the approach and my test results: [xmm_wait_rate_oracle](https://github.com/kadirc/hummingbot/commit/c8974f88c6596eb92e36206819864c5b022561ad)

**Comment by nikspz** [comment]
Hey @MementoRC Any updates? :eyes:

**Comment by MementoRC** [comment]
@nikspz, @kadirc seems to have an alternate solution to mitigate waiting for the oracle to be online. He also implemented waiting for the oracle byt changing the RateOracle, which I would prefer not to do. I don't think he has made a PR yet, I think it would be good to also look at his solution, maybe @cardosofede - I am also not a user of the XEMM, so I can't say which solution is preferable for HB

**Pull request closed without merging**
