### PR TITLE
Feat/improve data collection in candles

### PR DESCRIPTION
**Pull request by cardosofede**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Improvement in the collection of candles via rest to allow processing of WebSocket messages while the fill historical candles task is collecting the missing candles via rest.
Also a script with an example of how to download historical candles is provided.

**Tests performed by the developer**:
Run the download candles example.

**Tips for QA testing**:
Run all the scripts that use the candles component.

### CODE REVIEW

**Review by fengtality — CHANGES_REQUESTED** [review]
LGTM but please add Description to `download_candles.py`:

This script provides an example of how to use the Candles Feed to download and store historical data. It downloads 3-minute candles for 3 Binance trading pairs `["APE-USDT", "BTC-USDT", "BNB-USDT"]` and stores them in CSV files in the `/data` directory. The script stops after it has downloaded 175,000 `max_records` records for each pair.

**Comment by rapcmia** [comment]
PR update:
- Test on WSL ubuntu20.04 local 
- Debug using WSL + VSC ✅ 
- **candles_examples.py**
   - Data on OHLC in different intervals are close enough specially for {1m, 3m, 5m}
- **simple_directional_strategy.py**
  -  OHLC data ok {3m, 5m, 15m}
  -  Ran monitoring tests for different take-profit/stop-loss values 
     - _PENDING: no filled event yet occurred_
  - RSI set to default, no changes made
  - CSV file created for downloading candles
    image
     - _Currently the file has no data assuming that we haven't do filled orders_


For downloads_candles.py, we observed that it starts checking records at the max_record set `175000`

image

```
2023-04-03 14:30:58,383 - 25659 - hummingbot.data_feed.candles_feed.binance_spot_candles.binance_spot_candles - ERROR - Unexpected error occurred when getting historical klines. Retrying in 1 seconds...
Traceback (most recent call last):
  File "/home/rapcmia/github/hummingbot/6190/hummingbot/data_feed/candles_feed/binance_spot_candles/binance_spot_candles.py", line 89, in fill_historical_candles
    candles = await self.fetch_candles(end_time=end_timestamp, limit=missing_records + 1)
  File "/home/rapcmia/github/hummingbot/6190/hummingbot/data_feed/candles_feed/binance_spot_candles/binance_spot_candles.py", line 74, in fetch_candles
    candles = await rest_assistant.execute_request(url=self.candles_url,
  File "/home/rapcmia/github/hummingbot/6190/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.binance.com/api/v3/klines. HTTP status is 429. Error: {"code":-1003,"msg":"Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use WebSocket Streams for live updates to avoid polling the API."}
```

[logs_download_candles-issue.zip](https://github.com/hummingbot/hummingbot/files/11135780/logs_download_candles-issue.zip)

No CSV file created and at some point stuck for 2-3mins on same values after the unexpected error occurred and looks like something to do with the limit of requests. Changed to {75000, 50000} and observed changes are applied and not getting the error above

The timestamps on the CSV files starts from Dec 2022 to current date which we assume it would be the same for the default `max_records=1750000` The script later on reports on logs panel those that are missing and stops when download is completed

image
_Screenshot from max_records=30000_

And lastly, files are saved on ../data/ folder {.sqlite, .CSV}

Pending:
- directional strategies with filled events
- advanced_directional_strategy_example.py

**Comment by rapcmia** [comment]
PR update:
- Test latest commit `0931a56` related to max_records (50000)
- Test download_candles.py ok 
- Test simple_directional_strategy.py, ok
- Test advance_directional_strategy, ok
- Check CSV file
   image
    - Confirmed that the script now saves a local file of historical data to binance_perpetual.csv
    - Data consist of order amount, pnl entry/close price, etc.
    - Confirmed that position side is correct
    - However _we would like to confirm if it is expected that not all are on record?_
        - On the screenshot, there are some entry/close prices but not recorded
        - Confirmed that these orders are present on exchange trade history
        
Attached:
[6190.zip](https://github.com/hummingbot/hummingbot/files/11145779/6190.zip)

**Review by rapcmia — APPROVED** [review]
- Observed PR behavior by running download_candles.py 
   - The script starts at the set 50000 (default) records and store historical data to CSV file 
   - The script stops when the download is completed
- Test with simple and advance directional strategy
   - The script creates a blank binance_perpetual csv file
   - Confirmed that the script now saves a local file of historical data to binance_perpetual.csv when position successfully closed
   - Confirmed that position side correct
   - Trade data matched between csv and exchange trade history

**Review by fengtality — APPROVED** [review]

**Pull request merged**
