### PR TITLE
feat/ add Cronos chain, VVS and Mad Meerkat connector

### PR DESCRIPTION
**Pull request by CrimsonJacket**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR integrates Cronos Chain into Gateway and VVS Finance and Mad Meerkat Finance AMM connectors into the Hummingbot client.

This PR completes [HIP #21](https://snapshot.org/#/hbot-ip.eth/proposal/0x9e8d1424df8c4fbc8820faef66168d7313b0d6540fffcb3e6905b43cdd3ad6e3) task.

**Tests performed by the developer**:
Adds relevant components to integrate the Cronos chain into Gateway.
1. Manual tests are performed using the `curl` command. These tests for general connectivity with the Gateway service.
2. Unit tests were included to test basic evm functions, i.e. token approvals, balances, etc.

Adds relevant components to integrate VVS Finance and Mad Meerkat Finance AMM connectors
1. Manual tests were performed using the relevant `curl` commands.
2. Unit tests were included to tests some trading functionalities, i.e. fetching prices and executing trades.
3. Running of `amm-arb` strategies on the MMF and VVS connectors.

This PR also includes a refactor to the nonce manager and functions that send transactions to the network .i.e. execute trade functions in connectors, approval and cancel functions. 

**Tips for QA testing**:
Test the integration of the aformentioned by running `amm-arb` strategies.
Using of `mainnet` network is preferred to ensure that expected behaviour closely resembles that of actual trading.

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update:
- Test on Curl Endpoints for both `mad_meerkat` and `vvs`
	- port: ok 
	- wallet/add: ok 
	- network/balance: ok
	- evm/approve: ok 
	- evm/allowance: ok 
	- amm/price: ok
	- amm/trade: ok 
	
Pending:
- Setup testbots to run overnight for long term tests

**Review by nikspz — DISMISSED** [review]
Tests Performed:
 - Setup MMF and VVS connectors wallet successfully
 - Tested connector wallet using existing private key
 - Created an AMM_Arbitrage using the connector and Papertrade connector
 - Started strategy = OK
 - Verify token approval = OK
 - Changed rate oracle to coingecko + extra tokens wrapped-cro,crypto-com-chain,usd-coin (CRO not showing using binance rate oracle source)
- Successfully triggered no arbitrage opportunity for both connectors
- Check order execution of VVS nd MMF conenctor = all OK
- Tested endpoint curl tests
- Ran testbot overnight for longterm tests monitoring and reviewed log files
- Successfully tested on source and docker

**Comment by JeremyKono** [comment]
Hi @CrimsonJacket, can you please fix failing tests in this PR? Thanks.

**Comment by vic-en** [comment]
Main connector files have been added to the coveragePathIgnore list in order to make the workflow pass.
Adding them to that list only prevents coverage calculation on them. Unit test will still be run for those files.

**Review by rapcmia — APPROVED** [review]
LGTM

**Review by Faouzijedidi1 — APPROVED** [review]

**Comment by carlitogetaladajr** [comment]
For CoinAlpha team, please fill up & submit the AML Policy Form via this link: https://forms.gle/3wCGykiQtjEAY2J17
This is a one-time process for each ETH Address used to received HBOT bounty.

**Pull request merged**
