### PR TITLE
Feat/bybit connector

### PR DESCRIPTION
**Pull request by yancong001**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR create Bybit connector to the latest standards. 

**Tests performed by the developer**:

* Test cases for the new code

**Tips for QA testing**:
Normal QA test for Perpetuals connectors.

### CODE REVIEW

**Comment by rapcmia** [comment]
Hi @yancong001 good day
We noticed the file changes is empty based on the screenshot below, can you confirm if this is correct?
image

**Comment by yancong001** [comment]
I will submit my other codes in these two days

**Comment by yancong001** [comment]
hi @rapcmia ,here is my pr,please test it
hi @cardosofede ,please review it

**Comment by rapcmia** [comment]
PR update
- Source and docker installation: ok 
- Setup simple PMM strategy for monitoring: ok 
- Create and cancellation of orders: ok 
- Monitor balance if displayed correctly upon order create/cancellation: ok 
- Ran for couple of hours and review logs regarding order fills, hanging orders and possible errors

We noticed when checking `history --verbose` to display the filled orders, there are same price and and amount with a little time difference (minutes). Reviewed the log file found out that these orders share same order_id and the exchange only displays 1 of the two records on the client

Screenshot 2022-11-10 211133

Screenshot 2022-11-10 213439

On the logs below, we noticed that there was an event where another filled order is recorded by the client which we labeled `# noticed this line...` and we assume that this is most likely the reason `history` command shows the double records.

```
2022-11-10 10:33:37,117 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1668076417.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.00700", "price": "1167.36", "order_id": "BYBIT-BEHUT5ed1b4e4b26345bf131e1", "creation_timestamp": 1668076417.0, "exchange_order_id": "1286312656371761920", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "bybit"}
2022-11-10 10:33:37,117 - 1 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER BUY order BYBIT-BEHUT5ed1b4e4b25ae5bf131e1 for 0.00700 ETH-USDT.
2022-11-10 10:33:37,132 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1668076417.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.00700", "price": "1179.24", "order_id": "BYBIT-BEHUT5ed1b4e4b25ae5bf131e1", "creation_timestamp": 1668076417.0, "exchange_order_id": "1286312656422093568", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "bybit"}


# 10:35:32 timestamp BUY 1179.24 with 0.007 order amount 
2022-11-10 10:35:32,197 - 1 - hummingbot.connector.client_order_tracker - INFO - The BUY order BYBIT-BEHUT5ed1b4e4b25ae5bf131e1 amounting to 0.007/0.00700 ETH has been filled.
2022-11-10 10:35:32,220 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Maker buy order of 0.007 ETH filled. [clock=2022-11-10 10:35:32+00:00]
2022-11-10 10:35:32,220 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1668076532.0, "order_id": "BYBIT-BEHUT5ed1b4e4b25ae5bf131e1", "trading_pair": "ETH-USDT", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT_MAKER", "price": "1179.24", "amount": "0.007", "trade_fee": {"percent": "0", "percent_token": null, "flat_fees": [{"token": "ETH", "amount": "0"}]}, "exchange_trade_id": "1668076533021", "leverage": 1, "position": "NIL", "event_name": "OrderFilledEvent", "event_source": "bybit"}
2022-11-10 10:35:32,221 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Maker buy order BYBIT-BEHUT5ed1b4e4b25ae5bf131e1 (0.00700 ETH @ 1179.24 USDT) has been completely filled. [clock=2022-11-10 10:35:32+00:00]
2022-11-10 10:35:32,236 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1668076532.0, "order_id": "BYBIT-BEHUT5ed1b4e4b25ae5bf131e1", "base_asset": "ETH", "quote_asset": "USDT", "base_asset_amount": "0.007", "quote_asset_amount": "8.25468", "order_type": "OrderType.LIMIT_MAKER", "exchange_order_id": "1286312656422093568", "event_name": "BuyOrderCompletedEvent", "event_source": "bybit"}
2022-11-10 10:35:32,237 - 1 - hummingbot.connector.client_order_tracker - INFO - BUY order BYBIT-BEHUT5ed1b4e4b25ae5bf131e1 completely filled.
2022-11-10 10:35:37,001 - 1 - hummingbot.strategy.hanging_orders_tracker - INFO - Updating hanging orders...
2022-11-10 10:35:37,001 - 1 - hummingbot.strategy.hanging_orders_tracker - INFO - Original hanging orders: {LimitOrder('BYBIT-SEHUT5ed1b4e4b26c15bf131e1', 'ETH-USDT', False, 'ETH', 'USDT', 1195.86, 0.00700, NaN, 1668076417000000)}
2022-11-10 10:35:37,001 - 1 - hummingbot.strategy.hanging_orders_tracker - INFO - Equivalent hanging orders: frozenset({HangingOrder(order_id='BYBIT-SEHUT5ed1b4e4b26c15bf131e1', trading_pair='ETH-USDT', is_buy=False, price=Decimal('1195.86'), amount=Decimal('0.00700'), creation_timestamp=1668076417.0)})
2022-11-10 10:35:37,001 - 1 - hummingbot.strategy.hanging_orders_tracker - INFO - Need to create: frozenset({HangingOrder(order_id='BYBIT-SEHUT5ed1b4e4b26c15bf131e1', trading_pair='ETH-USDT', is_buy=False, price=Decimal('1195.86'), amount=Decimal('0.00700'), creation_timestamp=1668076417.0)})
2022-11-10 10:35:37,001 - 1 - hummingbot.strategy.hanging_orders_tracker - INFO - Need to cancel: set()
2022-11-10 10:35:37,001 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order BYBIT-BEHUT5ed1b4e4b26345bf131e1. [clock=2022-11-10 10:35:37+00:00]
2022-11-10 10:35:37,001 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order BYBIT-SEHUT5ed1b4e4b26e85bf131e1. [clock=2022-11-10 10:35:37+00:00]
2022-11-10 10:35:37,082 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1668076537.0, "order_id": "BYBIT-BEHUT5ed1b4e4b26345bf131e1", "exchange_order_id": "1286312656371761920", "event_name": "OrderCancelledEvent", "event_source": "bybit"}
2022-11-10 10:35:37,082 - 1 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order BYBIT-BEHUT5ed1b4e4b26345bf131e1.
2022-11-10 10:35:37,274 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1668076537.0, "order_id": "BYBIT-SEHUT5ed1b4e4b26e85bf131e1", "exchange_order_id": "1286312656296285696", "event_name": "OrderCancelledEvent", "event_source": "bybit"}
2022-11-10 10:35:37,274 - 1 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order BYBIT-SEHUT5ed1b4e4b26e85bf131e1.
2022-11-10 10:35:48,000 - 1 - hummingbot.strategy.hanging_orders_tracker - INFO - Hanging order passed max_distance from price=1.500% LimitOrder('BYBIT-SEHUT5ed1b4e4b26c15bf131e1', 'ETH-USDT', False, 'ETH', 'USDT', 1195.86, 0.00700, NaN, 1668076417000000). Removing...
2022-11-10 10:35:48,000 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Canceling the limit order BYBIT-SEHUT5ed1b4e4b26c15bf131e1. [clock=2022-11-10 10:35:48+00:00]
2022-11-10 10:35:48,070 - 1 - hummingbot.strategy.hanging_orders_tracker - INFO - (ETH-USDT) Hanging order BYBIT-SEHUT5ed1b4e4b26c15bf131e1 canceled.
2022-11-10 10:35:48,071 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1668076548.0, "order_id": "BYBIT-SEHUT5ed1b4e4b26c15bf131e1", "exchange_order_id": "1286312656338207488", "event_name": "OrderCancelledEvent", "event_source": "bybit"}
2022-11-10 10:35:48,071 - 1 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order BYBIT-SEHUT5ed1b4e4b26c15bf131e1.

# noticed this line that the but order amount has doubled 0.014/0.00700
2022-11-10 10:36:00,314 - 1 - hummingbot.connector.client_order_tracker - INFO - The BUY order BYBIT-BEHUT5ed1b4e4b25ae5bf131e1 amounting to 0.014/0.00700 ETH has been filled.

# 10:35:32 timestamp BUY 1179.24 with 0.007 order amount 
2022-11-10 10:36:00,334 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Maker buy order of 0.007 ETH filled. [clock=2022-11-10 10:36:00+00:00]


2022-11-10 10:36:00,335 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1668076560.0, "order_id": "BYBIT-BEHUT5ed1b4e4b25ae5bf131e1", "trading_pair": "ETH-USDT", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT_MAKER", "price": "1179.24", "amount": "0.007", "trade_fee": {"percent": "0", "percent_token": "ETH", "flat_fees": [{"token": "ETH", "amount": "0"}]}, "exchange_trade_id": "1286313621548221184", "leverage": 1, "position": "NIL", "event_name": "OrderFilledEvent", "event_source": "bybit"}
2022-11-10 10:36:03,001 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 2 bid orders at (Size, Price): ['0.007 ETH, 1170.7 USDT', '0.00657 ETH, 1158.91 USDT']
```

Please also observed that most of the issue occurred at the time the bot hits the timestamp of `AA:bb:00` 
image

This has been crosschecked on development branch for 2/3 attempts and we still trying to check if can be reproduce. However at this moment after a number of trades recorded there is no occurrence of this issue that only happen when PR was tested.

Steps to reproduce:
1. Setup PMM for Bybit
2. Set spreads tight enough to order fills (setup killswitch to control the number of trades)
3. Once you have a good number of trades, run `history --verbose` and check the orders
4. Compare the timestamps from the strategy log file found in `../logs/xxx.log` folder

Attached:
[logs_pmm-bybit.log-commented.zip](https://github.com/hummingbot/hummingbot/files/9981338/logs_pmm-bybit.log-commented.zip)

**Comment by nikspz** [comment]
Tests performed:

Connect API key - OK
Balance output - OK
Create a strategy - OK
Import a strategy - OK
Starting strategy - OK
Check status - OK
Order cancellation - OK
Check data integrity - OK
Broker ID - OK
Handling partial fills - Got some partial fills that behave as expected
Data aggregate - OK
Handling multiple orders - OK
Handling long refresh rate - OK
Handling fast refresh rate - OK
Verify fee calculation - OK
Handling hanging orders - OK
Interrupt a hanging order - OK

Order filled events - Got the same `issue reported above` when using Bybit spot connector on AWS Source
`the exchange only displays 1 of the two records on the client`

Steps to reproduce:

1. Clone and install feature PR
2. Create pureMM strategy using bybit
3. set tight spreads to get mutiple filled orders
4. Check trades that happened close and after to xx:xx:00s

image
image
image

**Comment by yancong001** [comment]
hi @rapcmia @nikspz ,
thanks
I have noticed and fixed this problem

**Comment by nikspz** [comment]
@yancong001 The issue fixed on [8140989](https://github.com/hummingbot/hummingbot/pull/5860/commits/8140989a0750dae66d4b782a1e4e2fa436a2f9be) can't reproduce it on AWS Source and Docker, for hanigng orders as well, no stuck orders and worked as expected with it
image


Tests performed:
Connect API key - OK
Balance output - OK
Create a strategy - OK
Import a strategy - OK
Starting strategy - OK
Check status - OK
Order cancellation - OK
Check data integrity - OK
Broker ID - OK
Order filled events - OK
Handling hanging orders - OK
Interrupt a hanging order - OK
Handling partial fills - OK
Data aggregate - OK
Handling multiple orders - OK
Handling long refresh rate - OK
Handling fast refresh rate - OK
Verify fee calculation - OK

Pending test:
Run the bot overnight

**Review by nikspz — APPROVED** [review]
Tests performed:

- Connect API key - confirmed working
- Balance output - confirmed working
- Create a strategy - confirmed working
- Import a strategy - confirmed working
- Starting strategy - confirmed working
- Check status - confirmed working
- Order cancellation - confirmed working
- Check data integrity matched with the exchange
- Created orders have a Broker ID
- Order filled events handling as expected
- Handling and Interrupt hanging orders works as expected
- Handling partial fills - confirmed
- Data aggregate - confirmed
- Handling multiple orders - OK
- Handling long refresh rate - OK
- Handling fast refresh rate - OK
- Verified fee calculation is correct
- Ran the bot overnight

Note: Overnight bot got rare The WS disconnection, Close code = 1006, bot was able to recover

**Review by cardosofede — APPROVED** [review]
LGTM!

**Comment by carlitogetaladajr** [comment]
Hi @yancong001, please fill up & submit the AML Policy Form via this link: https://forms.gle/3wCGykiQtjEAY2J17
This is a one-time process for each ETH Address used to received HBOT bounty.

**Comment by yancong001** [comment]
I have submitted it

**Pull request merged**
