### PR TITLE
Feat / Add  "Remote Command Executor" module

### PR DESCRIPTION
**Pull request by TheHolyRoger**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR adds the new "Remote Command Executor" module to Hummingbot.

It has been developed and tested with [RogerThat](https://github.com/TheHolyRoger/RogerThat) - a web server that can relay messages from e.g. TradingView to Hummingbot, as well as messages between bot instances.

This module on it's own simply adds a service to Hummingbot that listens to a websocket for commands and remote events. Basic usage allows Hummingbot to receive external commands and excute them as if typed in the console. Advanced usage allows strategy and user scripting integration, with hooks and examples included in this PR

**Tests performed by the developer**:
Many. Unit tests included.

**Tips for QA testing**:
Best used with RogerThat and following instructions in the [README](https://github.com/TheHolyRoger/RogerThat/blob/master/README.md)

### CODE REVIEW

**Comment by Nullably** [comment]
@TheHolyRoger Thanks for submitting this PR, very nice feature. But there is a dependency on RogerThat component which is not a part of this PR, sorry we cannot have this dependency as it would be very difficult to maintain in the future. Can the web server be part of Hummingbot?

**Comment by TheHolyRoger** [comment]
@Nullably it's not really a dependency for the feature itself, the websockets listening and command execution will work with anything, the RogerThat component is just for TradingView listening.

If you explore RogerThat you'll see why it would be overly complicated to include inside hummingbot, since it's a group of dockerised containers, with firewalls etc to create a secure public facing web server

**Comment by mifeng** [comment]
@RobHBOT Please set up a call between @TheHolyRoger and @Nullably to discuss the web server dependency in more detail.

**Comment by kovacspeter** [comment]
What is the status of this feature - is it done or does it require more work? Will there be any further changes? It is something that I am looking into as well and would like to use it / try it.

**Comment by TheHolyRoger** [comment]
@kovacspeter it works, feel free to try it!

The PR might potentially be merged before more work is done, I'm not sure

**Comment by fengtality** [comment]
Closing in favor of the updated Orchestration Module launched in [v.1.12](https://docs.hummingbot.org/release-notes/1.12.0)

**Pull request closed without merging**
