### PR TITLE
removed injective lib

### PR DESCRIPTION
**Pull request by fengtality**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

- removed `injective-py` to resolve the segmentation fault issue with Intel Macs:

Screen Shot 2023-08-25 at 7 44 51 AM

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Review by rapcmia — APPROVED** [review]
- Test on Windows WSL Ubuntu 20.04lts
- Run `./uninstall && conda clean -a -y && ./clean`
- Fresh installation from this PR and another on staging/development
- Able to start the hummingbot client
- Build docker image ad run docker compose file ✅

**Comment by rapcmia** [comment]
Getting workflow failed related to `pyinjective`

image

**Comment by fengtality** [comment]
I think we should ignore this workflow issue for now since it's clearly
related to the change which hopefully is temporary

**Comment by cardosofede** [comment]
closed by #6547

**Pull request closed without merging**
