### PR TITLE
(feat) Update of Huobi spot connector to the latest spot connector st…

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Updated version of Huobi spot connector to make it compliant with the latest spot connectors code standards.
The unit tests have also been updated, and the exchange class unit tests are now implemented based on ExchangeConnectorTests

**Tests performed by the developer**:
All unit tests passing in green

**Tips for QA testing**:
Please run all validations for a spot connector

Solves #5793

HGP: https://snapshot.org/#/hbot.eth/proposal/0x12714ef2fe805472b119ef37b274dccb6ef1541fcc91b70517651a5080b9275b

### CODE REVIEW

**Comment by nikspz** [comment]
Tests performed:
- Cloned and installed feature branch
- Started the client, created password
- Connected API key successfully
- Checked Balance is OK
- Created/Imported/Started a strategy using Huobi
- Checked status and status --live
- Checked order cancellation and Manually placed order on stop
- Checked data integrity (order_book, ticker, status --live) - OK
- Broker ID - OK
- Handling Order filled events - OK
- Handling/Interrupt  hanging orders - OK
- Handling partial fills - OK
- Compatibility check - OK
- Data aggregate confirmed
- Handling multiple orders - OK
- Handling long refresh rate - OK
- Handling fast refresh rate - OK
- Test different token pairs
- Verify fee calculation - OK


@aarmoa Could you please say if that's expected?
Currently bot constantly showed `WARNING - The websocket connection was closed. Close code = 1003 `

Steps to reproduce:
Create a pureMM (or other) strategy using Huobi (observed better on long refresh time)
Start the bot 

Actual:
`bot constantly showed `WARNING - The websocket connection was closed. Close code = 1003 ``
then INFO - Subscribed to public orderbook and trade channels...

Expected: 
No errors during the bot run

[5892huobi.zip](https://github.com/hummingbot/hummingbot/files/10029188/5892huobi.zip)
[logs_huobi-pmm.log](https://github.com/hummingbot/hummingbot/files/10029181/logs_huobi-pmm.log)

```2022-11-17 06:34:30,222 - 5937 - hummingbot.connector.exchange.huobi.huobi_api_order_book_data_source.HuobiAPIOrderBookDataSource - WARNING - The websocket connection was closed (The WS connection was closed unexpectedly. Close code = 1003 msg data: 1003)
```
image

**Comment by aarmoa** [comment]
Hello @nikspz. The code 1003 is the code that is triggered by the websocket framework when the connection is lost because it has been closed in the other end. It seems like Huobi is closing the connections.

**Comment by aarmoa** [comment]
Hello @nikspz, I have pushed a fix for the issue

**Review by nikspz — APPROVED** [review]
Tests performed:
- Cloned and installed feature branch
- Started the client, created password
- Connected API key successfully
- Checked Balance is OK
- Created/Imported/Started a strategy using Huobi
- Checked status and status --live
- Order creation and cancellation - OK
- Orderbook matched between client and exchange when running --live (status, ticker and orderbook)
- Broker ID - OK
- Handling Order filled events - OK
- Handling/Interrupt  hanging orders - OK
- Handling partial fills - OK
- Compatibility check - OK
- Data aggregate confirmed
- Handling multiple orders - OK
- Handling long refresh rate - OK
- Handling fast refresh rate - OK
- Test different token pairs
- History -verbose, CSV, data log matched with the exchange
- Verify fees calculation is OK and matched with the exchange
- Longrun of pureMM strategy using huobi not getting any errors

Tested on AWS Ubuntu Source and Docker

**Review by cardosofede — APPROVED** [review]
LGTM!

**Pull request merged**
