### PR TITLE
fix/help function: 'NoneType' object has no attribute 'format_help'

### PR DESCRIPTION
**Pull request by ashwinrajesh8**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
New try/except block to catch `AtributeError` mentioned in issue #5189
This error is encountered whenever a help argument does not exist, resulting in `subparser` being of `NoneType`

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by mhrvth** [comment]
LGTM!

-- Review provided in representation of the Hummingbot Foundation Technical DAO

**Review by ashrajesh — DISMISSED** [review]

**Comment by carlitogetaladajr** [comment]
PRP at Snapshot:

https://snapshot.org/#/hbot-prp.eth/proposal/0x8ae60e50253ad2ea68b5156efe60b9b4e1a62ed8b4ee08719791220b2f102a32

**Comment by carlitogetaladajr** [comment]
PRP Snapshot Link:

https://snapshot.org/#/hbot-prp.eth/proposal/0xd0f4b5538168f3a5a0c38d8512effcee65f209144f0ca40e88a2d2d2d8263d9d

**Comment by JeremyKono** [comment]
Hi @ashrajesh, please rebase your PR to `development` because we don't push changes to `master` branch

**Comment by JeremyKono** [comment]
Hi @ashrajesh, please make the necessary changes or we will close this PR. Thanks!

**Pull request closed without merging**
