### PR TITLE
Fix/fix quickstart style

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

A fix for the quickstart

### CODE REVIEW

**Comment by mhrvth** [comment]
Bug: https://github.com/hummingbot/hummingbot/issues/5346

**Comment by rapcmia** [comment]
Testing in progress

**Comment by rapcmia** [comment]
Hi @mhrvth currently I can only test it on Windows Ubuntu18LTS terminal w/ docker desktop atm due to issues on docker build for development branch for MacOS and AWS instances. After I successfully created the docker image and run `./create.sh` script, I'm getting the error below:

image

Tried to run `docker start, docker attach and ./start.sh` getting same error
image

Also, we found the error regarding the `style` but this time within the `bin/hummingbot.py` when entering incorrect password. Please advise if this can be added as a fix as well, here is the [comment](https://github.com/hummingbot/hummingbot/issues/5346#issuecomment-1143179941), Thank you!

**Comment by mhrvth** [comment]
@rapcmia Hi, I've pushed a fix, it should solve the issue, but I haven't tested it yet.

**Comment by rapcmia** [comment]
Hi @mhrvth confirmed the issue on the incorrect password has been resolved and no errors on the source build. I am able to build a docker image for this PR and managed to set up a password for the client however it is still getting the error of `TypeError: can only concatenate str (not "NoneType") to str`

image

https://user-images.githubusercontent.com/73840223/171554959-2defdbf1-2ea5-4979-836a-90552e480e7c.mp4

**Review by rapcmia — APPROVED** [review]
Test performed:
- Install branch successfully
- Setup password on source build, ok 
- Relaunch and enter an incorrect password, the client will not return any error anymore
- Build docker image, ok 
- Setup client using helper script `./create.sh`, all ok 
- Relaunch client and relaunch using `./start.sh` all ok 
- Enter anincorrect password, the client will not return any error anymore
- Run `docker start && docker attach`, repeat same steps for the incorrect password, all ok 
- Tested on AWS, Mac and Windows WSL

**Pull request merged**
