### PR TITLE
Feat/injective perp

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This PR introduces the Injective perpetual connector for the hummingbot client.

**Tests performed by the developer**:

- Added unit tests for the new code.
- Manually tested the connector's functionality with a PMM strategy.

**Tips for QA testing**:

Please test the full extent of the perpetual connector's functionality.

Link to Gateway PR: https://github.com/hummingbot/gateway/pull/81
Link to PRP: https://snapshot.org/#/hbot-prp.eth/proposal/0x1e36039ae9ff72c133b2bcf4e7c3aa66b25693b195ac3e5c31ab7fe3f813d745

### CODE REVIEW

**Comment by petioptrv** [comment]
@nikspz, replying to your [comment](https://github.com/hummingbot/gateway/pull/81#issuecomment-1513678748) here. I am not able to determine what exactly is going wrong based on the information in the logs. I have added multiple debugging statements both in the injective perpetual connector as well as the perpetual MM strategy. Please try to reproduce the issues you experienced using including these new changes.

Also, please enable debugging while testing. I have attached a `hummingbot_logs.yml` config file that will enable this for the client.

@mrhzysbl, @rxlxrxsx, please also do setup a run with the configs provided by @nikspz in his original message (I have added the file in the attached zip). Please also don't forget to enable debug logging (conf file for that in the zip). I will run a test on my end as well. Hopefully we can reproduce this quickly.

[injper.zip](https://github.com/hummingbot/hummingbot/files/11268784/injper.zip)

**Comment by petioptrv** [comment]
@nikspz, to summarize on the [issues](https://github.com/hummingbot/gateway/pull/81#issuecomment-1513678748) posted on the gateway PR and the latest one on this PR.

The first and the third issue on the Gateway PR, as well as the issue posted on this PR are due to Injective chain occasionally dropping a transaction. This can be verified with the additional debugging statements in the logs you provided in your [last comment above](https://github.com/hummingbot/hummingbot/pull/6200#issuecomment-1514790398). We can see that the the order `SIJUT5f9b0b5033eef578ef4f14ee122fe27980765d6c72879` was successfully submitted by Gateway, receiving a tx hash `EA5505B3F567924D110F1172830E86F36667EF00AF06225123CC129FDF2B60BC` in response. However, if we look for that tx hash on the [Injective explorer](https://explorer.injective.network/), we cannot find it.

In that situation, up to now, the bot will mark the order as lost after 10 iterations of the order status update loop (which happens every 2m). In the above logs, the bot has been attempting to get the status for 10m, so still 10m to go. I have now pushed a commit adjusting that number to 3 attempts, so the bot should be recovering after 6m of failed order status fetching.

Re the second issue on the gateway PR comment, the buy order that has remained on the exchange after the last stop command is actually still present in the attached database, so the bot should re-attempt a cancelation once restarted. This is expected behaviour.

**Review by rapcmia — APPROVED** [review]
Test summary
- Successfully setup on local and AWS instance both running Ubuntu20.04
- Setup both this PR81 and PR6200 successfully
- Command gateway list shows injective_perpetual ok 
- Setup wallet successfully and balance displayed all ok 
- Setup simple perpetual market making using INJ-USDT
- Order creation and cancellation ok however:
    - There are instances of failed cancellation due to timeout possible connection to the exchange
    - The connector would attempt to fetch the order and cancel which works after given time
    - At the time of testing it took a while to successfully cancel an order
- Successfully open position and created take-profit/stop-loss:
    - Observed stuck to attempt to renew SL orders and advised that possible exchange not recorded the transaction resulting txhash not available on explorer.
- Client successfully retrieved open position ok 

Note: PR good to be approved based on Bronze tier standard and can be merged to development. Community is advise that this connector may have issues which will be address by the maintainer on next possible updates

**Review by fengtality — APPROVED** [review]
LGTM - I will merge this in since it branch may impact the Gateway changes I am making

**Pull request merged**
