### PR TITLE
Feat/bot orchestration external events

### PR DESCRIPTION
**Pull request by klpanagi**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This PR implements the features of Phase 2 for [HIP-Bot Orchestration](https://hummingbot-foundation.notion.site/Bot-Orchestration-fcac18bd90d74b0ebca9b260617522f0#1a435ce4e3b0410aa4a50295b91f22af).

More specifically it provides interfaces which enable consuming external events within bot instances, via a message broker. Furthermore, it allows subscribing to external topics for consuming messages.

- External Event Listener: Uses the `EEventQueueFactory` and `EEventListenerFactory` classes
- External Topic Listener: Uses the `ETopicQueueFactory` and `ETopicListenerFactory` classes

The specification defines a base URI that follows the format `{namespace}/{bot_id}/external/events/*` for consuming external events. This means that messages send to topics that follow the specification URI will be captured and consumed as external events. The name of the event is defined by the URI, for example an event arrived at `hbot/bot1/external/events/test/a` will have the name/id of `test.a`. Notice that URI slashes (`/`) are transformed to dots (`.`) when constructing the name of the event, for future multi-broker and multi-protocol support purposes.

The `EEventQueueFactory`, `EEventListenerFactory`,  `ETopicQueueFactory` and `ETopicListenerFactory` classes can be used within strategies to listen to external events and topic messages. A script example is also included (`scripts/external_events_example.py`) in this PR that demostrates usage of the provided classes.

Finally, this PR extends the global configuration and adds the `mqtt_external_events` parameter for globally enabling/disabling external events feature for bot instances.

**Tests performed by the developer**:

- [x] Tested from source installation and setup
- [x] Tested docker container installation and setup
- [x] Send  external events via MQTT and consume within a script strategy
- [x] Send  messages to costom topics via MQTT and consume within a script strategy

**Tips for QA testing**:

To test external events:

- Build this PR
- Start a bot
- Set `instance_id` parameter (e.g. `config instance_id bot1`)
- Ensure you have an MQTT broker deployed somewhere and configure parameters properly in hummingbot client
- Start mqtt bridge with `mqtt start`
- Start the `external_events_example.py` script strategy: `start --script external_events_example.py`
- Use the `external_events.py` example from the [hbot-remote-client-py](https://github.com/klpanagi/hbot-remote-client-py/blob/main/examples/external_events.py) repository to send events to the bot: `./external_events.py bot1`

### CODE REVIEW

**Review by rapcmia — DISMISSED** [review]
LGTM

- Ran the test on WSL (ubuntu20.04)
- Successfully installed client and integrate MQTT brokers using `mqtt {start,restart}`
- Ran `start --script external_events_example.py, all ok
- Setup https://github.com/hummingbot/hbot-remote-client-py/pull/1 by running the `setup.py install` 
- Run` external_events <instance_id>`
- Observed client behavior, it is sending the data to the client
- Ran the same setup for the following brokers
   - emqx_obs ✅
   - emqx_v4: no go, https://github.com/hummingbot/brokers/issues/3
   - emqx_v5 ✅
    - rabbitmq ✅

**Comment by rapcmia** [comment]
Hi @klpanagi PR is good to be approved, may you please check the GitHub failed test? it seems that it has insufficient coverage. Thank you

**Comment by klpanagi** [comment]
@rapcmia I have pushed some tests and the CI seems to pass.

**Review by rapcmia — DISMISSED** [review]

**Comment by cardosofede** [comment]
@klpanagi so far is a very good PR, but before approving it we have to discuss the implementation of the factories to create queues and listeners. I have some ideas to make the more user-friendly.
I will contact you via Discord to set up a meeting and define this.

**Comment by rapcmia** [comment]
Hi @klpanagi we are able to setup before using same steps but the current commit wont give us any events on the log panel.

image

Tested other examples like `commands_example.py` and worked ok

Steps to reproduce:
1. Change instance_id {test01}
2. mqtt connection successful {emqx_v4, emqx_v5}
3. `start --script external_events_example.py`
4. Setup `hbot-rc` using https://github.com/klpanagi/hbot-remote-client-py
5. Ran ./external_events.py test01, ok but no event on client side

**Review by rapcmia — APPROVED** [review]
LGTM

- Setup this PR with brokers and https://github.com/klpanagi/hbot-remote-client-py, all ok 
- MQTT connection and change modified `instance_id`
- Run script` external_event_examples.py`
- Run ./external_events.py {instance_id}, client received event logs

**Review by cardosofede — APPROVED** [review]
LGTM!

**Pull request merged**
