### PR TITLE
Hedge/ Fixes

### PR DESCRIPTION
**Pull request by leastchaos**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using the approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Add more info to facilitate debugging.
1. Refactor the status screen and add more information and log
2. fixed position name referring to True and False to ONE-WAY and HEDGE
3. Fixed issues related to typing
4. for hedge by amount,
  a. change the matching of pairs from the match by trading pair to match by base asset
  b. change hedge price calculation for hedge by the amount to use mid-price instead of VWAP price.
      i. This is mainly used to calculate the market price to put since hummingbot only allows limit orders. Users can still increase slippage to guarantee their trade is made.

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by leastchaos** [comment]
@JeremyKono @rapcmia Can I check what is the process to get this merged now?

**Comment by rapcmia** [comment]
Hi @leastchaos good day to you,
Apologies I may have overlooked this PR and added to the board earlier. I assume we can have this merge since its fix for community strategy however I have to confirm with the team. I will get back to you

**Review by rapcmia — APPROVED** [review]
LGTM

**Review by cardosofede — APPROVED** [review]
LGTM!

**Comment by rapcmia** [comment]
In behalf of Foundation team we merged this PR to development and will be included on the next Hummingbot version 1.12.0

**Pull request merged**
