### PR TITLE
Feat/fixed grid strategy

### PR DESCRIPTION
**Pull request by rkc2000**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

A description of the changes proposed in the pull request:

Add the new fixed grid strategy that was approved in the following snapshot vote:
https://snapshot.org/#/hbot-ip.eth/proposal/0xaf21d826282fcc0a4d77ad0fb775c37b7a5935af1ce106686065b4336de2f83f

Commonwealth discussion about this strategy:
https://commonwealth.im/hummingbot-foundation/discussion/3763-fixed-grid-strategy-for-hummingbot

Medium article explaining and demonstrating the strategy:
https://medium.com/@rkc2000/introducing-the-fixed-grid-strategy-for-hummingbot-d9b011c71e9b

Tests performed by the developer:
The new strategy has been tested out in paper trading and in live trading. Some samples from these runs are given in the medium article above.

Tips for QA testing:

### CODE REVIEW

**Comment by rkc2000** [comment]
pre-commit is successful when I run it locally now.
Screenshot 2022-06-03 at 15 38 50

**Comment by rkc2000** [comment]
@JeremyKono please try running the checks again when you get a chance.

**Comment by rkc2000** [comment]
@arnelhbot the bug should be resolved now. The method of calculating order age has changed in the codebase and I just updated my code with it.

**Comment by JeremyKono** [comment]
Hi @rkc2000, can you please look at the failed Github tests?

**Comment by rkc2000** [comment]
Hi @JeremyKono it looks to me like all tests have passed? Could you point me to which tests have failed?

**Review by rapcmia — APPROVED** [review]
Test performed:
- Clone feature branch and started client with no errors
- Tested using Gate_io and papertrade connector
- Start the bot and calc grid_spread, all ok
- Orders are created based on the grid_level where:
    - Sell orders are created from i-th up to N
    - Buy orders are created from i-th up to 1
- When insufficient balance, the client tries to rebalance by creating a limit order using the start_order_spread
- Tested Long, Short and Neutral bot
- When an order is filled, it gets updated on the next tick
- Trade data from history, CSV and exchange trade history matched

**Comment by abduramann** [comment]
So should we wait for the next month's release? or will you publish an intermediate release?

I mean the users by "we" :) @rapcmia

**Pull request merged**
