### PR TITLE
Fix/gate io wrong available balance

### PR DESCRIPTION
**Pull request by cardosofede**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Remove the logic that updates the gate io balances via WS because the messages from this channel is only received when an order has fills. For that reason, the available balance wasn't changing. 
The solution eliminates the subscription via ws to the balance channels and manages all the logic via rest.

**Tests performed by the developer**:
Pure market making strategy and check that the available balance is correct.

**Tips for QA testing**:
Run a pure market making strategy but also try to get some fills and check if the connector is working ok.

### CODE REVIEW

**Comment by nikspz** [comment]
Test performed:

Cloned and Install the feature branch, started without any issue
Connect Gate.io API key and checked balance successfully
Created Pure_MM with multiple order levels
Order creation and cancel orders according to the strategy - ok
Filled orders are recorded and confirmed in logs/history/CSV and exchange - ok
Partial fills - ok
Data integrity is synced with exchange (had delay with available balance, orders placed accordingly to the available balance) 
Filled orders are tracked correctly on datadog - ok
Fees matched logs and exchange - ok

Tested on AWS Ubuntu Source
Note: 
Didn't noticed issue mentioned in https://github.com/hummingbot/hummingbot/issues/5476 
noticed little delay in updating available balance, do not affects orders creation.
Delay happened everytiime on filled trade

Steps:
Create a pureMM strategy using gate.io
Set tight spreads to get trades
run status --live

Actual:
Notice that's a delay updating available balance after trade happened

[5679.zip](https://github.com/hummingbot/hummingbot/files/9533256/5679.zip)
5679gate delay

**Comment by cardosofede** [comment]
@nikspz thank you very much Nikita!
In the video I can see that the **available balance** is updated correctly, but the **total balance** is delayed. Do you agree?

**Comment by nikspz** [comment]
> @nikspz thank you very much Nikita! In the video I can see that the **available balance** is updated correctly, but the **total balance** is delayed. Do you agree?

Oh yeah, changed it. That's about Total balance is delayed, Fede

**Review by nikspz — APPROVED** [review]
Test performed:
- Cloned and Install the feature branch, started without any issue
- Connect Gate.io API key and checked balance successfully
- Created Pure_MM with multiple order levels
- Order creation and cancel orders according to the strategy - ok
- Filled orders are recorded and confirmed in logs/history/CSV and exchange - ok
- Partial fills - ok
- Data integrity is synced with exchange (had delay with total balance, orders placed accordingly to the available balance)
- Filled orders are tracked correctly on datadog - ok
- Fees matched logs and exchange - ok

Note: Discussed to create separate PR for `total balance` issue

**Review by Faouzijedidi1 — APPROVED** [review]

**Pull request merged**
