### PR TITLE
fix/fix unnecessary text in split order level prompt

### PR DESCRIPTION
**Pull request by leastchaos**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Fix unnecessary text prompt as mentioned in https://github.com/hummingbot/hummingbot/issues/5193

**Tests performed by the developer**:

image

**Tips for QA testing**:

### CODE REVIEW

**Comment by leastchaos** [comment]
@JeremyKono Hi, should this PR be merged into dev or staging to fix this issue? https://github.com/hummingbot/hummingbot/issues/5193

**Comment by JeremyKono** [comment]
@leastchaos nothing is going into the `staging` branch. Only in `development` and you should also create a PRP for this one and after the voting, if the PRP finishes before the end of the month then it will be merged in `development` and go into the next release

**Comment by leastchaos** [comment]
Noted. I have raised the PRP https://snapshot.org/#/hbot-prp.eth/proposal/0x66c25aa0e46b3fe79b40d5fea79bfd8c9bc814d6c0e32d9e31e7d74bcb183be1

**Review by nikspz — APPROVED** [review]
Test performed:

- Setup simple market making strategy
- Check `config split_order_levels_enabled` promt and logic work as expected
- Run test order_levels, order_level_spreads and order_levels_amount, ok
- Set split_order_level_enable to true, bypass order_amount, order_level, order_level_amount and order_level_spreads
- Set bid_order_level_spread and bid_order_level_amount, ok
- Set ask_order_level_spread and ask_order_level_amount, ok
- The number of orders are created depending on the values set for both bid/ask_order_level_spread and bid/ask_order_level_amount
- Orders created and canceled match from client and connector

**Comment by aarmoa** [comment]
@JeremyKono this PR has been approved two weeks ago by QA and the PRP is already closed (community voted `For`). It should be merged into development branch.

**Comment by dennisocana** [comment]
I agree with @aarmoa - development should overlap with staging i.e. we should be able to continue pushing changes to `development` branch and `staging` contains all changes to be included in the upcoming release (code freeze). This way, QA can continuously test the staging environment without blocking developers / contributors.

@mifeng also related to the message above, we mentioned before it's a good approach to delete `staging` branch every new release and create a new one based on the state of `development` branch on the next cut-off / code freeze. This way is cleaner.

**Comment by dennisocana** [comment]
We should probably create a thread in commonwealth if there are more points to this discussion.

**Pull request merged**
