### PR TITLE
Support polygon connector quickswap

### PR DESCRIPTION
**Pull request by james-hummingbot**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by JeremyKono** [comment]
hi @james-hummingbot, please resolve failing tests in this PR. Thanks!

**Comment by rapcmia** [comment]
PR udpate:
Initially tested and tried to manually create docker image for this PR however when starting the client and checking the docker logs we are getting this error of ` throw new Error(The JSON schema for namespace ${id} (${schemaPath}) does not exist.);` on both WSL and AWS(Ubuntu20.04) instance

image

Issue does not happened when crosschecked on development branch

**Comment by nikspz** [comment]
Ongoing test:
clone and install feature branch - OK
create gateway v2 docker image - OK
added infura - OK
connect quickswap - OK
check balance - OK
create amm arb strategy - OK
start/stop amm arb strategy - Failed

Failed to start/stop strategy using quickswap_polygon_mainnet

Steps:
1. Create amm_arb strategy using quickswap_polygon_mainnet and binance papertrade
2. Start/stop a strategy

Actual:
Bot returns an ERROR - Unhandled error in background task - NotImplementedError
Can't stop the strategy, only restart the bot help

Expected: 
You could start and stop the strategy successfully

[logs_conf_amm_arb_1.log](https://github.com/hummingbot/hummingbot/files/8967177/logs_conf_amm_arb_1.log)
[conf_amm_arb_1.txt](https://github.com/hummingbot/hummingbot/files/8967178/conf_amm_arb_1.txt)
```
2022-06-23 12:05:27,182 - 581702 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 
Traceback (most recent call last):
  File "/home/ubuntu/5378poly/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/5378poly/hummingbot/client/command/start_command.py", line 126, in start_check
    chain: Chain = Chain.from_str(connector_details['chain'])
  File "/home/ubuntu/5378poly/hummingbot/client/command/gateway_api_manager.py", line 26, in from_str
    raise NotImplementedError
NotImplementedError
```

23 06 22 quickswap - failed to start or stop the bot2

**Comment by rapcmia** [comment]
PR update:
- Manually created gateway docker image successfully
- `gateway connect quickswap` and selected `mumbai` all ok 
- Balance check, all ok 

Setup amm-arb using MATIC-DAI and MATIC-USDT however getting the same error upon start. 

```
2022-06-24 08:47:40,659 - 244549 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 
Traceback (most recent call last):
  File "/home/ubuntu/github/5378/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/github/5378/hummingbot/client/command/start_command.py", line 126, in start_check
    chain: Chain = Chain.from_str(connector_details['chain'])
  File "/home/ubuntu/github/5378/hummingbot/client/command/gateway_api_manager.py", line 26, in from_str
    raise NotImplementedError
NotImplementedError
```

[logs_amm-polygon-mumbai.log](https://github.com/hummingbot/hummingbot/files/8974830/logs_amm-polygon-mumbai.log)

**Comment by rapcmia** [comment]
PR update:
- Tested `e84ebfb` answap MATIC to WMATIC for mumbai testnet
- Successfully manually created gateway image for testing this PR using new GATEWAY_DOCKER TAG: hummingbot/hummingbot from commit c45b46b
- Execute `gateway create` ok 
- Execute `gateway connect quickswap` and selected `mumbai`, no error received
- Setup simple AMM-ARB using WMATIC-DAI and ETH-USDT, ok

When starting the strategy, we got an error that we need to input a nodeAPI for polygon which can be created on Moralis.io as per prompt message on the screenshot below. Created a testnet Dapps directing to Polygon mumbai and added to the client. It is given that WMATIC shows 0 on the balance since we still haven't connected the correct node.

Prompt to add Moralis API key:
image

However it seems that we need to also change the nodeURL from `https://matic-mumbai.chainstacklabs.com` to `https://speedy-nodes-nyc.moralis.io/{}/polygon/mumbai` based on other connectors setup using moralis.  After updating it, the client managed to trigger the `no arbitrage opportunity` which is indication that its worked
image

Set min_profitability to negative value to trigger trade execution, we noticed that here are instances that **trades are executed on the gateway docker logs but not on the client**. On the screenshow below we would notice that the client returns an error of `Order buy-WMATIC-DAI-1657088338316156 has failed...` and founds another arbitrage opportunity which also happened the same that the trade is not recorded to the client
image

Client logs: Order has been created under  `0xeb15c1a4ef67d9215f11c997a863bb559fe156095766a9652e39cc3efc362fdc`
```
2022-07-06 14:19:00,625 - 2048 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order buy-WMATIC-DAI-1657088338316156 for 2.000000000000000 WMATIC-DAI.
2022-07-06 14:19:00,643 - 2048 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1657088340.0, "type": "OrderType.LIMIT", "trading_pair": "WMATIC-DAI", "amount": "2.000000000000000", "price": "0.307302286900000", "order_id": "buy-WMATIC-DAI-1657088338316156", "creation_timestamp": 1657088338.0, "exchange_order_id": "0xeb15c1a4ef67d9215f11c997a863bb559fe156095766a9652e39cc3efc362fdc", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "quickswap_polygon_mumbai"}
2022-07-06 14:19:01,733 - 2048 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WMATIC-DAI-1657088338316156.
2022-07-06 14:19:02,628 - 2048 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WMATIC-DAI-1657088338316156.
2022-07-06 14:19:03,751 - 2048 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WMATIC-DAI-1657088338316156.
2022-07-06 14:19:04,770 - 2048 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WMATIC-DAI-1657088338316156.
2022-07-06 14:19:05,822 - 2048 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WMATIC-DAI-1657088338316156.
2022-07-06 14:19:06,608 - 2048 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WMATIC-DAI-1657088338316156.
2022-07-06 14:19:07,864 - 2048 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WMATIC-DAI-1657088338316156.
2022-07-06 14:19:08,812 - 2048 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WMATIC-DAI-1657088338316156.
2022-07-06 14:19:10,112 - 2048 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WMATIC-DAI-1657088338316156.
2022-07-06 14:19:11,781 - 2048 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WMATIC-DAI-1657088338316156.
2022-07-06 14:19:12,724 - 2048 - GatewayEVMAMM - WARNING - Failed to fetch transaction status for the order buy-WMATIC-DAI-1657088338316156.
2022-07-06 14:19:12,739 - 2048 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1657088352.0, "order_id": "buy-WMATIC-DAI-1657088338316156", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "quickswap_polygon_mumbai"}
2022-07-06 14:19:12,739 - 2048 - hummingbot.connector.client_order_tracker - INFO - Order buy-WMATIC-DAI-1657088338316156 has failed. Order Update: OrderUpdate(trading_pair='WMATIC-DAI', update_timestamp=1657088352.0, new_state=<OrderState.FAILED: 6>, client_order_id='buy-WMATIC-DAI-1657088338316156', exchange_order_id=None, misc_updates=None)
```

Docker logs: 
```
2022-07-06 07:39:00 | info | 	Trade has been executed, txHash is 0xeb15c1a4ef67d9215f11c997a863bb559fe156095766a9652e39cc3efc362fdc, nonce is 18, gasPrice is 100. | undefined
```

Checking the trades executed that 2/4 trades are recorded on client and CSV however on the [wallet address](https://mumbai.polygonscan.com/address/0x2DF4D30df17Ed1029aa67cE4D35603260f1f252f) its 4 that has all successful transaction. Underlined the 2 txhash that are not recorded
image


Steps to reproduce:
1. Setup AMM arbitrage using quickswap_mumbai
2. Used WMATIC-DAI and papertrade ETH-USDT
3. Setup min_profitability to negative value to trigger arbitrage
4. Start the bot and monitor the client and docker logs
5. Check used wallet address for successful tx

[amm-quickswap-mumbai.zip](https://github.com/hummingbot/hummingbot/files/9052321/amm-quickswap-mumbai.zip)

**Comment by rapcmia** [comment]
PR update: 
- Tested latest commit `e26bb618f75` and confirmed that when setting up mumbai or mainnet, the default nodeURL is now using the moralis node `https://speedy-nodes-nyc.moralis.io/{}/polygon/...`
   > However it seems that we need to also change the nodeURL from `https://matic-mumbai.chainstacklabs.com` to `https://speedy-nodes-nyc.moralis.io/{}/polygon/mumbai` based on other connectors setup using moralis. After updating it, the client managed to trigger the `no arbitrage opportunity` which is indication that its worked
- There are no problem with gateway create and gateway config params

However there are still instances of orders failing when trades are executed on the client resulting to dropping arbitrage but txhash are noticeable successful on docker logs:

Client Order ID `0x59ac45318c3a845017a55bb6e25bdcd3d6668ab5945541cd0c7190356eff117c`
image

Docker logs, [Mumbai testnet txhash](https://mumbai.polygonscan.com/tx/0x59ac45318c3a845017a55bb6e25bdcd3d6668ab5945541cd0c7190356eff117c)
```
2022-07-07 01:49:11 | info | 	Trade has been executed, txHash is 0x59ac45318c3a845017a55bb6e25bdcd3d6668ab5945541cd0c7190356eff117c, nonce is 23, gasPrice is 100. | undefined
```
Tried to do multiple trades but still getting the same behavior

[e26bb618f75.zip](https://github.com/hummingbot/hummingbot/files/9059455/e26bb618f75.zip)

**Review by nikspz — APPROVED** [review]
Test performed:
 - Clone and install feature branch successful,
 - Create a gateway docker container manually from /gateway folder for testing
 - Gateway generate certs/ gateway create, ok 
 - Setup moralis node API keys, ok
 - Connect quickswap wallet (mumbai testnet), ok
 - Create an AMM_Arbitrage using quickswap and any CEX or Papertrade connector, ok
 - Start strategy and verify approval
 - Check order execution in quickswap
 - Trade data from history/csv/txhash matched
 - Compare the fees paid
 - Tested on AWS ubuntu source and docker

**Pull request merged**
