### PR TITLE
Fix/kucoin query trading fees

### PR DESCRIPTION
**Pull request by riven314**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Fix failure to get trading fees when trading symbols are more than 10 in Kucoin exchange

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Review by rapcmia — DISMISSED** [review]
LGTM

- Created user script and crosscheck on development branch and able to reproduce the issue 
- Use the same script on this PR and not getting the error

[test.py.log](https://github.com/hummingbot/hummingbot/files/11273387/test.py.log)

**Comment by riven314** [comment]
seems test coverage is not enough
any suggestion on how I can update the unit test to increase the coverage? @rapcmia

**Review by cardosofede — DISMISSED** [review]
LGTM!

**Comment by cardosofede** [comment]
@riven314 the PR is good to go, but the coverage is not enough. To know what you can add I will recommend you the following: 
- make test
- make development-diff-cover
That will show you the lines of your changes that are not covered.
Also you can use PyCharm to do it, if you have questions about it ping me on discord ;) and congrats for your first PR!!!
@rapcmia we can't merge this pr until the coverage is met.

**Comment by rapcmia** [comment]
> the PR is good to go, but the coverage is not enough. To know what you can add I will recommend you the following:
> 
> * make test
> * make development-diff-cover
>   That will show you the lines of your changes that are not covered.

Hi @riven314 Checking if you can have a look with the test coverage so we can complete this PR? thank you

**Comment by riven314** [comment]
@rapcmia 
Ok, I will add related test coverage this weekend

**Comment by nikspz** [comment]
Hi @riven314 is there any updates?

**Comment by nikspz** [comment]
@riven314 Could you please ping me here if you're still working on it

**Comment by riven314** [comment]
hey @nikspz 
I need some help on how I should update the unit tests
coz I noticed there are already some unit tests covering `self.exchange._update_trading_fees`, for example:  
https://github.com/hummingbot/hummingbot/blob/master/test/hummingbot/connector/exchange/kucoin/test_kucoin_exchange.py#L402

I am not sure why my changes are not covered. I am stuck on this part

**Comment by nikspz** [comment]
@riven314 You could try to run `make test` locally under the root `hummingbot` folder to see what lines need more coverage

**Comment by riven314** [comment]
@nikspz @rapcmia 
I have updated branch and it should pass coverage test now
my changes included a try catch for `KeyError` and I tried to add a unit test to cover the raise of `KeyError`
but for some reason it still was not covered, so I decided to remove the try-catch
this makes the coverage test pass

**Comment by riven314** [comment]
@rapcmia @cardosofede 
The build has passed. Could u help review again?

**Comment by nikspz** [comment]
Merged the PR in behalf of foundation team to development and will be available on the next version 1.16.0

**Pull request merged**
