### PR TITLE
Fix/change port

### LINKED ISSUE #5618: Change default Gateway port from 5000 to a larger number
**Feature Suggestion**

* Change default Gateway port from `5000` to a larger number - suggest `15888`
* Change in Gateway server, Hummingbot client, and `gateway create` command that maps 

**Impact**

Port 5000 is silently used for Airplay settings on newer M-generation Macs, so using 5000 as the default results in hard-to-detect bugs.

**Additional context**

Must test Gateway source and Docker afterwards to ensure that both methods of installation are working

### PR DESCRIPTION
**Pull request by mifeng**
* Remove unused files in Gateway setup folder
* Change default nodeURL providers in template to https://www.ankr.com/ endpoints
* Fix #5618, changes default Gateway port to 15888

### CODE REVIEW

**Comment by rapcmia** [comment]
Hi @mifeng kindly fix the branch conflicts. Thank you

**Comment by nikspz** [comment]
Test performed:

Cloned and installed branch
Manually create gateway docker image from ../gateway/ folder
Confirmed port number is changed from 5000 to 15888
connected all connector except uniswap mainnet (had an issue with that, exist on development branch)
Balance is displaying correctly
Setup simple AMM arb for token approval
Noticed `issues` not related to PR for `Arbitrum_one` and `uniswap-ethereum-mainnet`, `uniswapLP`( (https://github.com/hummingbot/hummingbot/issues/5642)
Optimism: ok
Avalanche: ok
Harmony: ok
Polygon: ok

Tested on AWS Ubuntu source gw docker

**Comment by nikspz** [comment]
Could you please update the branch with the latest development?

**Review by nikspz — APPROVED** [review]
Test performed:

Cloned and installed branch
Manually create gateway docker image from ../gateway/ folder
Confirmed port number is changed from 5000 to 15888
Balance is displaying correctly
Setup simple AMM arb for token approval
Noticed issues not related to PR for Arbitrum_one (should be fixed with #5664) and uniswap-ethereum (replicated on dev branch, uniswapLP (https://github.com/hummingbot/hummingbot/issues/5642)
Optimism: ok
Avalanche: ok
Harmony: ok
Polygon mumbai: ok

**Review by Faouzijedidi1 — APPROVED** [review]
LGTM!

**Pull request merged**
