### PR TITLE
(fix) You can't just pass empty or blank passwords

### PR DESCRIPTION
**Pull request by tomasgaudino**
#5211 needs to verify both conditions: None for omiting and bool(password.strip()) for only whitespaces. Check if message its ok!

**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by rapcmia** [comment]
Hi @tomasgaudino good day to you,
Looks like we are having failed GitHub checks on your pull request, would you be able to check this and resolved? Thank you!

image

**Comment by tomasgaudino** [comment]
Hi! I'm fine and you?

I'm really sorry about that, it's my first contribution and i'm still getting used to this!

Please let me solve it tomorrow if is that possible, i'm going to review it with a friend.

Won't pass further than tomorrow 😁

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JeremyKono** [comment]
Hi, what PR fixes the issue? This one or https://github.com/hummingbot/hummingbot/pull/5675?

**Comment by tomasgaudino** [comment]
Hi! I reviewed code in #5675, so use that one. The other (#5669) was sent by mistake. I just sent rapcmia another email explaining that this is my first contribution, so I'm I little bit lost with this formalities. I'm sorry about that.

I hope #5675 fixes the problem, in the meanwhile I'll keep learning more of Hummingbot and Github.

Thanks!

________________________________
De: Jeremy Kono ***@***.***>
Enviado: jueves, 8 de septiembre de 2022 23:38
Para: hummingbot/hummingbot ***@***.***>
Cc: Tomás Gaudino ***@***.***>; Mention ***@***.***>
Asunto: Re: [hummingbot/hummingbot] (fix) You can't just pass empty or blank passwords (PR #5669)


Hi, what PR fixes the issue? This one or #5675<https://github.com/hummingbot/hummingbot/pull/5675>?

**Comment by tomasgaudino** [comment]
All right so now it failed again with this code!

[cid:1c35d414-3893-4502-9f5b-1e3855f7e3b8]

Third will be the last one. I'm on it, don't get disappointed!


Enviado desde Outlook<http://aka.ms/weboutlook>

________________________________
De: Tomás Gaudino ***@***.***>
Enviado: jueves, 8 de septiembre de 2022 23:43
Para: hummingbot/hummingbot ***@***.***>
Asunto: RE: [hummingbot/hummingbot] (fix) You can't just pass empty or blank passwords (PR #5669)

Hi! I reviewed code in #5675, so use that one. The other (#5669) was sent by mistake. I just sent rapcmia another email explaining that this is my first contribution, so I'm I little bit lost with this formalities. I'm sorry about that.

I hope #5675 fixes the problem, in the meanwhile I'll keep learning more of Hummingbot and Github.

Thanks!

________________________________
De: Jeremy Kono ***@***.***>
Enviado: jueves, 8 de septiembre de 2022 23:38
Para: hummingbot/hummingbot ***@***.***>
Cc: Tomás Gaudino ***@***.***>; Mention ***@***.***>
Asunto: Re: [hummingbot/hummingbot] (fix) You can't just pass empty or blank passwords (PR #5669)


Hi, what PR fixes the issue? This one or #5675<https://github.com/hummingbot/hummingbot/pull/5675>?

**Comment by JeremyKono** [comment]
It's ok if the tests fails, you can always fix the issues with the failing tests in the same PR rather than passing another PR. Also, please point the PR to development instead of master and please rebase if necessary. Thanks.

**Comment by tomasgaudino** [comment]
All right thanks!

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tomasgaudino** [comment]
Hi Arnel, I'm on it. I hope not to be disappointing you with all this failures. Next try will be my last one! 😄


Enviado desde Outlook<http://aka.ms/weboutlook>

________________________________
De: arnelhbot ***@***.***>
Enviado: viernes, 9 de septiembre de 2022 04:02
Para: hummingbot/hummingbot ***@***.***>
Cc: Tomás Gaudino ***@***.***>; Mention ***@***.***>
Asunto: Re: [hummingbot/hummingbot] (fix) You can't just pass empty or blank passwords (PR #5669)


PR Update:

Test performed:

  *   Clone and compile feature branch
  *   Start bot
  *   Enter a blank password
  *   Create password
  *   Reenter created password
  *   Migration completed
  *   Working accordingly

We have noticed that when you select cancel on the create password it will revert you to a loop where it will ask you to try again. The expected behavior when selecting cancel is for the bot to exit and return the user to the terminal.

[image]<https://user-images.githubusercontent.com/99257257/189277012-e9bb07e4-c889-40a3-bf1d-37d1f50eb6db.png>

https://user-images.githubusercontent.com/99257257/189277461-57a8cc84-6752-4298-9513-f03729f11d58.mp4

**Pull request closed without merging**
