### PR TITLE
Feat/ascendex spot connector update

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Updated version of AscendEx spot connector to make it compliant with the latest spot connectors code standards.
The unit tests have also been updated, and the exchange class unit tests are now implemented based on ExchangeConnectorTests

**Tests performed by the developer**:
All unit tests passing in green

**Tips for QA testing**:
Please run all validations for a spot connector

Solves #5792 

HGP: https://snapshot.org/#/hbot.eth/proposal/0x12714ef2fe805472b119ef37b274dccb6ef1541fcc91b70517651a5080b9275b

### CODE REVIEW

**Comment by aarmoa** [comment]
Nice catch @arnelhbot. I have pushed a fix to the error caused by sending incorrect headers for the DELETE requests AscendEx uses for order cancelation

**Comment by rapcmia** [comment]
PR update:
- Latest fix solved issue on `Failed to cancel the following orders`
- Current runtime of 3hrs we have not experienced error on orderbook or user streams 
- The client create and cancel orders accordingly
- Status and Orderbook live is working as expected, prices are updated and matched between client and exchange 
- Long term bot still running on AWS with the following being monitored: 
   - Order execution: `pending`
   - Hanging orders cancelled, refreshed due to max_order_age: `pending`
   - Does exchange return error orderbook streams after killswitch? : `pending`

**Comment by rapcmia** [comment]
Hi @aarmoa thanks for the update, PR is good to be approved. Just one question for the connecting the API key, we would like to confirm if this expected that it would return this long html error when updating using an incorrect API key? 

https://user-images.githubusercontent.com/73840223/203976648-456192c3-52e4-41ac-8e3f-d408735e9afa.mp4

This is also observed if you enter a invalid API key at the initial setup of connector. 
image

This is a screenshot of development branch when connecting or accidentally enter incorrect API key
Screenshot 2022-11-25 192806

**Comment by aarmoa** [comment]
Hello @rapcmia. Nice catch. It is very odd that they are returning an HTML page response to a request that should return a JSON responde. I will adapt the code to avoid dumping the whole HTML error page response into the log.

**Review by rapcmia — APPROVED** [review]
Test performed:
- Test adding connector API, all ok 
- Setup simple PMM strategy
- Orders are created and cancel successfully
- Orderbook and status live data matched between client and connector
- Setup testbot long term with average runtime of 8hrs~
	- Orders are recorded 
	- Trade data between client and exchange trade history matched
	- Fees paid are displaying correctly 
	- Hanging orders are created 
	- Hanging orders are refreshed at max_order_age 
	- No noticeable users or orderbook stream error so far
- Killswitch triggered and no stuck orders on exchange 
- Ran test on both source and docker build

**Comment by leecarney** [comment]
@aarmoa This looks great. Also just to draw your attention that Ascendex offer a realtime depth connection option which is 300ms faster - https://github.com/ascendex/ascendex-pro-api/blob/master/misc/real_time_orderbook_feed.md

**Review by cardosofede — APPROVED** [review]
LGTM!

**Pull request merged**
