### PR TITLE
MNT: update to coinbase 1.6.2

### PR DESCRIPTION
**Pull request by MementoRC**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Aligns the auth to the official SDK `coinbase-advanced-py` 1.6.2. Upgrade `pyjwt` as a conda package to v2.9.0

**Tests performed by the developer**:
covergae tests in `coinbase_advanced_trade` connector directory

**Tips for QA testing**:

### CODE REVIEW

**Comment by MementoRC** [comment]
@cardosofede This is related to the ping you semt me on discord. It allows to use the latest official SDK from Coinbase

**Comment by nikspz** [comment]
commit a47fc00

- removed old conda envs
- Cloned and installed PR7229 successfully with no issues
- connected coinbase_advanced_trade with new API keys
- created/started pureMM successfully
- Review issue reported in #7220 


[logs_conf_pure_mm_1.log](https://github.com/user-attachments/files/17024246/logs_conf_pure_mm_1.log)
[mempr.zip](https://github.com/user-attachments/files/17024247/mempr.zip)


```
2024-09-17 07:04:55,351 - 1646838 - hummingbot.connector.exchange.coinbase_advanced_trade.coinbase_advanced_trade_api_order_book_data_source.CoinbaseAdvancedTradeAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/nikita/cb2/hummingbot/core/data_type/order_book_tracker_data_source.py", line 80, in listen_for_subscriptions
    await self._process_websocket_messages(websocket_assistant=ws)
  File "/home/hummingbot/nikita/cb2/hummingbot/connector/exchange/coinbase_advanced_trade/coinbase_advanced_trade_api_order_book_data_source.py", line 183, in _process_websocket_messages
    async for ws_response in websocket_assistant.iter_messages():
  File "/home/hummingbot/nikita/cb2/hummingbot/core/web_assistant/ws_assistant.py", line 64, in iter_messages
    response = await self._connection.receive()
  File "/home/hummingbot/nikita/cb2/hummingbot/core/web_assistant/connections/ws_connection.py", line 64, in receive
    response = self._build_resp(msg)
  File "/home/hummingbot/nikita/cb2/hummingbot/core/web_assistant/connections/ws_connection.py", line 134, in _build_resp
    data = msg.json()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 131, in json
    return loads(self.data)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not WebSocketError
```


image

**Comment by MementoRC** [comment]
@isreallee82 This has a different resolution of the WebSocketError, it keeps the default from `aiohttp` (it seems coinbase is the only connector with this issue) but updates the max size when an error is encountered, thought this means a mandatory disconnect, loss of messages

**Comment by MementoRC** [comment]
This PR was merged into https://github.com/hummingbot/hummingbot/pull/7220

**Pull request closed without merging**
