### PR TITLE
Feat/improve market data provider

### PR DESCRIPTION
**Pull request by cardosofede**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update:
- Build whl on local successfully
- Change backend-api (development) environment.yml  using direct path of wheel
- Setup deploy on source ok 
- Run backtesting on PMM
  image
  image
  ```
  See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
    df_filtered["filled_amount_quote"].iloc[-1] = df_filtered["filled_amount_quote"].iloc[-1] * 2
  /Users/rapcomia/miniconda3/envs/backend-api/lib/python3.10/site-packages/hummingbot/strategy_v2/backtesting/executors_simulator/position_executor_simulator.py:79: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
  You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
  A typical example is when you are setting values in a column of a DataFrame, like:
  
  df["col"][row_indexer] = value
  
  Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.
  
  See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
    df_filtered["filled_amount_quote"].iloc[-1] = df_filtered["filled_amount_quote"].iloc[-1] * 2
  /Users/rapcomia/miniconda3/envs/backend-api/lib/python3.10/site-packages/hummingbot/strategy_v2/backtesting/executors_simulator/position_executor_simulator.py:79: SettingWithCopyWarning:
  A value is trying to be set on a copy of a slice from a DataFrame
  
  See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
    df_filtered["filled_amount_quote"].iloc[-1] = df_filtered["filled_amount_quote"].iloc[-1] * 2
  INFO:     127.0.0.1:57849 - "POST /run-backtesting HTTP/1.1" 200 OK
  INFO:     127.0.0.1:57857 - "GET /is-docker-running HTTP/1.1" 200 OK
  INFO:     127.0.0.1:57858 - "GET /all-controller-configs HTTP/1.1" 200 OK
  ```
   - Compare with development branch and not able to reproduce this behavior
   - Observed that the PNL % are far different compare to development
 
Steps to reproduce:
- Build backend-api env using default environment.yml
- Run deploy on source ok 
- Run backtesting on PMM and PMM dynamic getting same behavior on this PR

**Comment by rapcmia** [comment]
PR update: 
Since we can build the hummingbot lib succcessfully, proceed with testing `dydx_v4_perpetual` and found an issue with backend-api found here https://github.com/hummingbot/deploy/issues/65

**Comment by rapcmia** [comment]
PR update on commit `b67c66fb9fc5a696858331f34d2021fb5fb45604`
- Review running bot for 13hours and observed an uptrend on one of the markets that pulled most of the assets which cause imbalance and spam `not enough budget to open position` on executor.
- Observed broken pipe errors from OKX spot connector which is being investigated separately `not related`
- After stopping the controllers from dashboard, `unexpected error running clock tick` occurred after manual cashout
  ```
  2024-09-18 00:38:32,254 - 15 - hummingbot.strategy.script_strategy_base - INFO - Manual cash out for controller gs_DOGS-USDT_0.1.
  2024-09-18 00:38:32,255 - 15 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
  Traceback (most recent call last):
    File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
      child_iterator.c_tick(self._current_tick)
    File "hummingbot/strategy/strategy_py_base.pyx", line 44, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_tick
      self.tick(timestamp)
    File "/home/hummingbot/hummingbot/strategy/script_strategy_base.py", line 75, in tick
      self.on_tick()
    File "/home/hummingbot/scripts/v2_with_controllers.py", line 82, in on_tick
      self.control_cash_out()
    File "/home/hummingbot/scripts/v2_with_controllers.py", line 174, in control_cash_out
      self.check_manual_cash_out()
    File "/home/hummingbot/scripts/v2_with_controllers.py", line 191, in check_manual_cash_out
      self.executor_orchestrator.execute_actions(
    File "/home/hummingbot/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 81, in execute_actions
      self.execute_action(action)
    File "/home/hummingbot/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 72, in execute_action
      self.stop_executor(action)
    File "/home/hummingbot/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 123, in stop_executor
      executor.early_stop()
    File "/home/hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 603, in early_stop
      self.place_close_order_and_cancel_open_orders(close_type=CloseType.EARLY_STOP)
    File "/home/hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 463, in place_close_order_and_cancel_open_orders
      if self.amount_to_close >= self.trading_rules.min_order_size:
    File "/home/hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 105, in amount_to_close
      if self._open_order.fee_asset == self.config.trading_pair.split("-")[0]:
  AttributeError: 'NoneType' object has no attribute 'fee_asset'
  2024-09-18 00:38:32,704 - 15 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for DOGS-USDT. 3/3 completed.
  2024-09-18 00:38:50,725 - 15 - hummingbot.strategy.script_strategy_base - INFO - Manual cash out for controller gs_PEPE-USDT_0.1.
  2024-09-18 00:38:50,728 - 15 - hummingbot.strategy.script_strategy_base - INFO - (PEPE-USDT) Canceling the limit order 93027a12dac34fBCSPEUT06b51c39e86. [clock=2024-09-18 00:38:33+00:00]
  2024-09-18 00:38:50,729 - 15 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
  Traceback (most recent call last):
    File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
      child_iterator.c_tick(self._current_tick)
    File "hummingbot/strategy/strategy_py_base.pyx", line 44, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_tick
      self.tick(timestamp)
    File "/home/hummingbot/hummingbot/strategy/script_strategy_base.py", line 75, in tick
      self.on_tick()
    File "/home/hummingbot/scripts/v2_with_controllers.py", line 82, in on_tick
      self.control_cash_out()
    File "/home/hummingbot/scripts/v2_with_controllers.py", line 174, in control_cash_out
      self.check_manual_cash_out()
    File "/home/hummingbot/scripts/v2_with_controllers.py", line 191, in check_manual_cash_out
      self.executor_orchestrator.execute_actions(
    File "/home/hummingbot/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 81, in execute_actions
      self.execute_action(action)
    File "/home/hummingbot/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 72, in execute_action
      self.stop_executor(action)
    File "/home/hummingbot/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 123, in stop_executor
      executor.early_stop()
    File "/home/hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 603, in early_stop
      self.place_close_order_and_cancel_open_orders(close_type=CloseType.EARLY_STOP)
    File "/home/hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 463, in place_close_order_and_cancel_open_orders
      if self.amount_to_close >= self.trading_rules.min_order_size:
    File "/home/hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 105, in amount_to_close
      if self._open_order.fee_asset == self.config.trading_pair.split("-")[0]:
  AttributeError: 'NoneType' object has no attribute 'fee_asset'
  2024-09-18 00:39:13,965 - 15 - hummingbot.strategy.script_strategy_base - INFO - Manual cash out for controller gs_SOL-USDT_0.1.
  2024-09-18 00:39:13,967 - 15 - hummingbot.strategy_v2.executors.executor_orchestrator - ERROR - Executor ID FkwmTKp4jAAAHJebwSuYe1kZfpdsJ4AhzssR9cDWwAcx not found for controller gs_SOL-USDT_0.1.
  2024-09-18 00:39:13,968 - 15 - hummingbot.strategy_v2.executors.executor_orchestrator - ERROR - Executor ID F8zLSa4zVjoC21YYTUqVSxyyaUThWCUfuVzuB1rvrYmz not found for controller gs_SOL-USDT_0.1.
  2024-09-18 00:39:13,969 - 15 - hummingbot.strategy_v2.executors.executor_orchestrator - ERROR - Executor ID ACpxzfnhn2g4VBTy4azUvwtmESffCcejKAsUgT8WCpBU not found for controller gs_SOL-USDT_0.1.
  2024-09-18 00:39:13,970 - 15 - hummingbot.strategy_v2.executors.executor_orchestrator - ERROR - Executor ID 9pZCNJxUowcpKhcqrsEWqtTpaqpKUxFbXv8KxNNHzLsh not found for controller gs_SOL-USDT_0.1.
  2024-09-18 00:39:13,970 - 15 - hummingbot.strategy_v2.executors.executor_orchestrator - ERROR - Executor ID DXZ1DyXViQYvt3DxjkjGFj6Q3Zzyuoc9E5R1NCTjN44o not found for controller gs_SOL-USDT_0.1.
  2024-09-18 00:39:13,971 - 15 - hummingbot.strategy_v2.executors.executor_orchestrator - ERROR - Executor ID FUcTSZQSChF5BR4f8XyPU7Ld7AedwuLMks1TdgiymasY not found for controller gs_SOL-USDT_0.1.
  2024-09-18 00:39:13,972 - 15 - hummingbot.strategy_v2.executors.executor_orchestrator - ERROR - Executor ID WzftXMxbhgCyCAt2vFfs7d2ALgV6zAgyVhShnUhjd4D not found for controller gs_SOL-USDT_0.1.
  2024-09-18 00:39:13,972 - 15 - hummingbot.strategy_v2.executors.executor_orchestrator - ERROR - Executor ID G4qQt3whhnuegeYNSwUS5qQARaajWviP6xL7R66ypYrG not found for controller gs_SOL-USDT_0.1.
  2024-09-18 00:39:13,973 - 15 - hummingbot.strategy_v2.executors.executor_orchestrator - ERROR - Executor ID CzNP4XU91VXaUHWQCbpkBRcigcwSYuf66LqRv8zf9p9U not found for controller gs_SOL-USDT_0.1.
  2024-09-18 00:39:13,974 - 15 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
  Traceback (most recent call last):
    File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
      child_iterator.c_tick(self._current_tick)
    File "hummingbot/strategy/strategy_py_base.pyx", line 44, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_tick
      self.tick(timestamp)
    File "/home/hummingbot/hummingbot/strategy/script_strategy_base.py", line 75, in tick
      self.on_tick()
    File "/home/hummingbot/scripts/v2_with_controllers.py", line 82, in on_tick
      self.control_cash_out()
    File "/home/hummingbot/scripts/v2_with_controllers.py", line 174, in control_cash_out
      self.check_manual_cash_out()
    File "/home/hummingbot/scripts/v2_with_controllers.py", line 191, in check_manual_cash_out
      self.executor_orchestrator.execute_actions(
    File "/home/hummingbot/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 81, in execute_actions
      self.execute_action(action)
    File "/home/hummingbot/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 72, in execute_action
      self.stop_executor(action)
    File "/home/hummingbot/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 123, in stop_executor
      executor.early_stop()
    File "/home/hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 603, in early_stop
      self.place_close_order_and_cancel_open_orders(close_type=CloseType.EARLY_STOP)
    File "/home/hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 463, in place_close_order_and_cancel_open_orders
      if self.amount_to_close >= self.trading_rules.min_order_size:
    File "/home/hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 105, in amount_to_close
      if self._open_order.fee_asset == self.config.trading_pair.split("-")[0]:
  AttributeError: 'NoneType' object has no attribute 'fee_asset'
  ```

Steps to reproduce:
1. After getting a number of orders filled and opened executors, stop the all controllers on dashboard
2. Check error after manual cashout

[hummingbot-grid_strike_okx_3p-2024.09.17_11.52.zip](https://github.com/user-attachments/files/17038039/hummingbot-grid_strike_okx_3p-2024.09.17_11.52.zip)

**Comment by rapcmia** [comment]
PR update:
- Check files changes and there was on `v2_with_controller.py` script
- When deployed the GS controllers and use the latest v2_with_controller.py of this PR, does not start
  image

Steps to reproduce:
- Clone this PR and copy the v2_with_controller.py from `./script`
  - Paste it to backend-apit's `./bot/scripts/`
- Build config from GS market analyzer then deploy

[09242024.zip](https://github.com/user-attachments/files/17109877/09242024.zip)

**Review by nikspz — APPROVED** [review]

**Comment by nikspz** [comment]
Test performed:
- Cloned and install PR7214
- Manually built docker image successfully
- changed setup_dev.sh file to use this image, used Deploy repo to setup with setup_dev.sh
- used latest quants-lab to set up grid_strike strategy
- set up grid_strike successfully using 5 pairs
- after 2.3 days review no failed executors, some closed with take profit successfully
- review errors like: 
  - WARNING - Failed to fetch trade updates for order x-XEKWYICXSCIUT622da80b9e398b0bd. Error: Error executing request GET https://api.binance.com/api/v3/myTrades. HTTP status is 400. Error: {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
  - NETWORK - Error fetching trades update for the order CATI-USDT: Error executing request GET https://api.binance.com/api/v3/myTrades. HTTP status is 400. Error: {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}.
- bot was able to recover

**Pull request merged**
