### PR TITLE
Fix/Bybit Perpetual - Spot-perp arbitrage position mode issue

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Sends a request to change position mode to ONEWAY if not in ONEWAY.

**Tests performed by the developer**:

Ran the strategy with Bybit Perpetual testnet

### CODE REVIEW

**Review by aarmoa — COMMENTED** [review]
The change looks good to me

-- Reviewed in representation of Hummingbot Foundation Technical DAO

**Comment by aarmoa** [comment]
PRP: https://snapshot.org/#/hbot-prp.eth/proposal/0x22c626eebfe7182dc67203099e7c56c8afe24228d18d2bb2c40f68f6075ed611

**Comment by JeremyKono** [comment]
Hi @mhrvth, can you see what causes the failed Github tests in this PR?

**Comment by mhrvth** [comment]
> Hi @mhrvth, can you see what causes the failed Github tests in this PR?

I can't tell what's the problem, there's no clear error message. Your `isort` hook failed for some reason. It didn't happen in our PR.

**Comment by rapcmia** [comment]
Tested setting up manual orders to OPEN position while on Hedge and wait for the trade to complete. After opening a position, Start the bot and noticed `Changing position failed mode to ONEWAY failed. Reason: position is not empty..cannot continue. please resolved the issue in the account..` but at the same time `trading started`

Screenshot 2022-05-11 143530
 
 The bot seems to consider the OPEN position and continue to close out the arbitrage position. Changed the min_clossing_arbitrage_pct to -1 to trigger trade getting `Error submitting order to Bybit Perpetual`
 
image

Crosscheck with Binance perp with the same steps and config, the bot does not continue with the same logs indicate that to resolved the issue in the account.

Attached: 
[spot-perp-bybit.zip](https://github.com/hummingbot/hummingbot/files/8667397/spot-perp-bybit.zip)

**Comment by mhrvth** [comment]
@rapcmia Hi, I've pushed a fix to the PR.

**Comment by rapcmia** [comment]
Latest commit fixed the issue below. The client does not start and display `Cannot continue. Please resolved the issue in the account` Test complete but will run last test once github validation issue is fixed (just to make sure). Thank you

> Tested setting up manual orders to OPEN position while on Hedge and wait for the trade to complete. After opening a position, Start the bot and noticed `Changing position failed mode to ONEWAY failed. Reason: position is not empty..cannot continue. please resolved the issue in the account..` but at the same time `trading started`

Sample recording for client running when there is a manual OPEN position and on hedge mode in the exchange:

https://user-images.githubusercontent.com/73840223/168033103-8d555348-2807-4967-8471-5c6e40046c37.mp4

**Comment by aarmoa** [comment]
@JeremyKono I have committed a fix for the `isort` issue.
@mhrvth please the next time this happens let's not only say that the error was not happening in CoinAlpha PR. If the error is present in the foundation PR we need to solve it anyways because we want the change merged. You can use this command in the future to solve `isort` problems:
`pre-commit run --files $(git diff --name-only origin/development)`

**Comment by JeremyKono** [comment]
Seems like the Github tests are failing again, can you guys take another look and see what the issue is @mhrvth @aarmoa?

**Comment by mhrvth** [comment]
@JeremyKono Hello, the issues should be fixed now.

**Review by nikspz — APPROVED** [review]
Test performed:
 - Install the feature branch and start the Hummingbot client
 -  spot-perpetual arbitrage strategy using bybit_perpetual and Hedge mode
 - Start the strategy and verify that the position mode is switched to One-Way
 - Restart the spot-perpetual arbitrage strategy with manually open an order in the exchange
 -  Verify that strategy will not start until manually opened order is not cancelled on the website (Needs restart after cancelling the order)
 - Created a spot-perpetual arbitrage using Binance_perpetual and Hedge mode
 - Start the strategy and verify that the position mode is switched to One-Way

**Pull request merged**
