### PR TITLE
Feat / add algorand amm

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This adds the algorand amm generic connector to the client which is currently necessary for connectors like Tinyman.

**Tests performed by the developer**:
- End-to-end testing with the gateway - https://github.com/hummingbot/gateway/pull/90

**Tips for QA testing**:
- Perform end-to-end testing with the gateway - https://github.com/hummingbot/gateway/pull/90

PRP - https://snapshot.org/#/hbot-prp.eth/proposal/0x08a53dead66043ee8e8b0e65229a99b52be2e212a640e992eb72c9b4cd388701

### CODE REVIEW

**Comment by fengtality** [comment]
Set connector tier for `tinyman` to `BRONZE`"

Screen Shot 2023-05-10 at 6 28 48 AM

**Review by fengtality — APPROVED** [review]

**Comment by fengtality** [comment]
@vic-en I actually mean to click Request Changes

**Review by fengtality — CHANGES_REQUESTED** [review]
see comments

**Comment by fengtality** [comment]
@vic-en Actually, I'd like to understand better why we need special logic for Algorand in the client at all, since the functionality looks similar to what the EVM AMM connectors are doing.

We need to keep the Hummingbot codebase as simple as possible, so anything that makes it more complex like this code should require a high bar to get merged in.

Please schedule a call with me tmrw to go over it.

**Comment by fengtality** [comment]
Discussed with @vic-en - he will make some changes to how the client handles chain connectors to make the codebase more maintainable going forward.

**Comment by vic-en** [comment]
@fengtality I addressed the issue like we discussed.
@nikspz This should first be tested with branch on pr https://github.com/hummingbot/gateway/pull/105
After that branch is merged to development. I'll make a small update to https://github.com/hummingbot/gateway/pull/90 so you can do a full test of tinyman again.

**Review by fengtality — APPROVED** [review]

**Review by fengtality — DISMISSED** [review]

**Comment by nikspz** [comment]
Failed to start the strategy using goBTC-USDC pair 
Found out that adding `goBTC with connector-tokens will break the balance command`.
Loom video:
https://www.loom.com/share/5c040e30e1cd408b9f45ae76c42dcf8a
 you could add it as gateway connector-tokens tinyman GOBTC and it will display correct GOBTC balance
image

however user can't create GOBTC since bot using remote tokenList and it says goBTC with lower key letters
image
https://mainnet.analytics.tinyman.org/api/v1/assets/?limit=1000&is_pool_member=true&with_statistics=false&verified_only=true 
image



User failed to create amm_arb strategy using GOBTC-USDC:
image

**Comment by vic-en** [comment]
@nikspz I updated both client and gateway. Pls test again.

**Comment by nikspz** [comment]
Initial test:

@vic-en  
Bot flooded with Unhandled error in background task: 'NoneType' object is not subscriptable (See log file for stack trace dump) 

Steps to reproduce:
1. Clone latest version of PR6277 and gwPR90
2. Review now bot using capital letters (GOBTC-USDC is allowed)
3. Create/start the strategy using tinyman algorand mainnet
4. Review log pane

Actual:
Bot flooded with Unhandled error in background task: 'NoneType' object is not subscriptable (See log file for stack trace dump) 


Expected:
bot not flooded with the Errors/warnings



```
2023-05-19 13:33:11,002 - 5166 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/etozhe/algo6277/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/etozhe/algo6277/hummingbot/strategy/amm_arb/amm_arb.py", line 240, in apply_gateway_transaction_cancel_interval
    if self.is_gateway_market(self._market_info_1) and self.is_gateway_market_evm_compatible(self._market_info_1):
  File "/home/etozhe/algo6277/hummingbot/strategy/amm_arb/amm_arb.py", line 173, in is_gateway_market_evm_compatible
    return connector_spec["chain_type"] == "EVM"
TypeError: 'NoneType' object is not subscriptable
2023-05-19 13:33:12,003 - 5166 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/etozhe/algo6277/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/etozhe/algo6277/hummingbot/strategy/amm_arb/amm_arb.py", line 240, in apply_gateway_transaction_cancel_interval
    if self.is_gateway_market(self._market_info_1) and self.is_gateway_market_evm_compatible(self._market_info_1):
  File "/home/etozhe/algo6277/hummingbot/strategy/amm_arb/amm_arb.py", line 173, in is_gateway_market_evm_compatible
    return connector_spec["chain_type"] == "EVM"
TypeError: 'NoneType' object is not subscriptable
2023-05-19 13:33:13,003 - 5166 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/etozhe/algo6277/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/etozhe/algo6277/hummingbot/strategy/amm_arb/amm_arb.py", line 240, in apply_gateway_transaction_cancel_interval
    if self.is_gateway_market(self._market_info_1) and self.is_gateway_market_evm_compatible(self._market_info_1):
  File "/home/etozhe/algo6277/hummingbot/strategy/amm_arb/amm_arb.py", line 173, in is_gateway_market_evm_compatible
    return connector_spec["chain_type"] == "EVM"
TypeError: 'NoneType' object is not subscriptable
2023-05-19 13:33:14,003 - 5166 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/etozhe/algo6277/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/etozhe/algo6277/hummingbot/strategy/amm_arb/amm_arb.py", line 240, in apply_gateway_transaction_cancel_interval
    if self.is_gateway_market(self._market_info_1) and self.is_gateway_market_evm_compatible(self._market_info_1):
  File "/home/etozhe/algo6277/hummingbot/strategy/amm_arb/amm_arb.py", line 173, in is_gateway_market_evm_compatible
    return connector_spec["chain_type"] == "EVM"
TypeError: 'NoneType' object is not subscriptable
2023-05-19 13:33:15,003 - 5166 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/etozhe/algo6277/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/etozhe/algo6277/hummingbot/strategy/amm_arb/amm_arb.py", line 240, in apply_gateway_transaction_cancel_interval
    if self.is_gateway_market(self._market_info_1) and self.is_gateway_market_evm_compatible(self._market_info_1):
  File "/home/etozhe/algo6277/hummingbot/strategy/amm_arb/amm_arb.py", line 173, in is_gateway_market_evm_compatible
    return connector_spec["chain_type"] == "EVM"
TypeError: 'NoneType' object is not subscriptable
2023-05-19 13:33:16,005 - 5166 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/etozhe/algo6277/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/etozhe/algo6277/hummingbot/strategy/amm_arb/amm_arb.py", line 240, in apply_gateway_transaction_cancel_interval
    if self.is_gateway_market(self._market_info_1) and self.is_gateway_market_evm_compatible(self._market_info_1):
  File "/home/etozhe/algo6277/hummingbot/strategy/amm_arb/amm_arb.py", line 173, in is_gateway_market_evm_compatible
    return connector_spec["chain_type"] == "EVM"
TypeError: 'NoneType' object is not subscriptable
2023-05-19 13:33:17,003 - 5166 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/etozhe/algo6277/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/etozhe/algo6277/hummingbot/strategy/amm_arb/amm_arb.py", line 240, in apply_gateway_transaction_cancel_interval
    if self.is_gateway_market(self._market_info_1) and self.is_gateway_market_evm_compatible(self._market_info_1):
  File "/home/etozhe/algo6277/hummingbot/strategy/amm_arb/amm_arb.py", line 173, in is_gateway_market_evm_compatible
    return connector_spec["chain_type"] == "EVM"
TypeError: 'NoneType' object is not subscriptable
```
image

**Review by nikspz — APPROVED** [review]
Test performed:
- Cloned and installed PR6277 and gw90
- connected tinyman with a seed phrase
- checked balance dysplays correct amount
- added gateway connector-tokens to tinyman and check balance displays new tokens
- created/started amm_arb strategy using tinyman_algorand_mainnet, bot showing profitability for trades
- order execution for ALGO-USDC: okay
- connect other gateway connectors successfully (traderjoe, uniswap_arbitrum, quickswap, dexalot, pancakeswap)
- checked curl commands is okay with gw90
- Docker build: ok, tested on local ubuntu,mbp(m1) and build docker image for this PR and PR90

**Comment by vic-en** [comment]
@nikspz pls re-test.

**Review by fengtality — APPROVED** [review]

**Review by cardosofede — APPROVED** [review]
LGTM! Just adapt the suggestion that @fengtality did

**Review by cardosofede — APPROVED** [review]
LGTM! Just adapt the suggestion that @fengtality did

**Comment by fengtality** [comment]
The last commit that @vic-en added might have fixed the issue - seems like there was a typo @nikspz

**Review by nikspz — APPROVED** [review]
Retest commit 87dff470cefd542a62bb5ef82007b81ff9b64ae0

Test performed:
- Cloned and installed PR6277 and gw90
- Manually build docker image successfully
- connected tinyman with a seed phrase
- checked balance dysplays correct amount
- added gateway connector-tokens to tinyman and check balance displays new tokens
- created/started amm_arb strategy using tinyman_algorand_mainnet, bot showing profitability for trades
- order execution for ALGO-USDC,GOBTC-USDC: okay
- connect other gateway connectors successfully (traderjoe, uniswap_arbitrum, quickswap, dexalot, pancakeswap)
- created/started stategies for dexalot/traderjoe/uniswap/arbitrum//quickswap/polygon: ok

**Comment by nikspz** [comment]
Merged the PR in behalf of foundation team to development and will be available on the next version 1.16.0

**Pull request merged**
