### PR TITLE
MQTT config command to return current configuration parameters

### PR DESCRIPTION
**Pull request by klpanagi**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This PR changes the remote `config` command so that it returns the configuration parameters.

Will require a relevant PR in the https://github.com/hummingbot/hbot-remote-client-py repo to update response message.

**Tests performed by the developer**:

Call the `config` command via MQTT.

**Tips for QA testing**:

### CODE REVIEW

**Comment by nikspz** [comment]
Test performed:
Clone and install commit [cb5bcbc](https://github.com/hummingbot/hummingbot/pull/6196/commits/cb5bcbc4650e9c771b3da66cf9038e77f53d9797)
Clone and install commlib-py, commlib-cli and brokers repo
Run emqx_v5
- Started strategy with 
`commlib-cli --host localhost --port 1883 --btype mqtt rpcc 'hbot/bot1/start' '{"strategy": "paper"}' `
- Started script with 
`commlib-cli --host localhost --port 1883 --btype mqtt rpcc 'hbot/bot1/start' '{"script": "dca_example"}'`
- Listen to logs: ok
- Listen to events: ok
- Listen to notifications: ok
- Listen to heartbeats: ok
- Execute Start command: ok, 200
- Execute Stop command: ok, 200
- Execute Import command: ok, 200
- Execute History command: ok, 200
- Execute Balance Paper commands: ok, 200
- Execute Config command / List Config : 
`Config and global config showing`, response is `400`: 

commlib-cli --host localhost --port 1883 --btype mqtt rpcc 'hbot/bot1/config' '{"params": []}'
```
{'changes': [], 'config': {}, 'status': 400, 'msg': "'dict' object has no attribute 'dict'"}
```
- Execute Config command / Set Single Parameter: 
`Single parameter changed`, response is `400`

commlib-cli --host localhost --port 1883 --btype mqtt rpcc 'hbot/bot1/config' '{"params": [["mqtt_bridge.mqtt_autostart", 1]]}'

```
{'changes': [['mqtt_bridge.mqtt_autostart', 1]], 'config': {}, 'status': 400, 'msg': "'dict' object has no attribute 'dict'"}
```
- Execute Config command / Set Multiple Parameters with a single call: 
`Multiple parameters changed successfully`, but response status is `400`

commlib-cli --host localhost --port 1883 --btype mqtt rpcc 'hbot/bot1/config' '{"params": [["ask_spread", 1], ["bid_spread", 1]]}'


```
 {'changes': [['ask_spread', 1], ['bid_spread', 1]], 'config': {}, 'status': 400, 'msg': "'dict' object has no attribute 'dict'"}

```

**Comment by nikspz** [comment]
Test performed:

- Clone and install commit 
- Clone and install commlib-py, commlib-cli and brokers repo
- Run emqx_v5
- Started strategy successfully with 
commlib-cli --host localhost --port 1883 --btype mqtt rpcc 'hbot/bot1/start' '{"strategy": "paper"}' 
- Started script successfully with 
commlib-cli --host localhost --port 1883 --btype mqtt rpcc 'hbot/bot1/start' '{"script": "dca_example"}' 
- Listen to logs: ok
- Listen to events: ok
- Listen to notifications: ok
- Listen to heartbeats: ok
- Execute Start command: ok, 200
- Execute Stop command: ok, 200
- Execute Import command: ok, 200
- Execute History command: ok, 200
- Execute Balance Paper commands: ok, 200
- Execute Config command / List Config : ok, 200
- Execute Config command / Set Single Parameter: ok, 200
- Execute Config command / Set Multiple Parameters with a single call: ok, 200

**Comment by nikspz** [comment]
@klpanagi Could you please fix failing tests?

**Comment by klpanagi** [comment]
> @klpanagi Could you please fix failing tests?

Yeah, it is a coverage issue, I will add more tests.

**Review by nikspz — APPROVED** [review]
LGTM, pending for failing tests fix

**Comment by klpanagi** [comment]
@nikspz The coverage of the mqtt source code seems to be high enough (for a standalone module) at 81.6% and the overall coverage is calculated at 79.48%.

2023-04-09-144131_1019x57_scrot
2023-04-09-144118_1057x52_scrot


I have covered almost everithing, except blocks which are caused by specific runtime exceptions and async-lated threading checks.

I have noticed that common excludes are not included in the coverage rc file, thus I also created a PR that adds some common excludes for python coverage.

**Comment by klpanagi** [comment]
@nikspz I have pushed some more tests and the coverage passed with success.

**Review by nikspz — APPROVED** [review]

**Review by cardosofede — APPROVED** [review]
LGTM!

**Pull request merged**
