### PR TITLE
Fix/ Polkadex hanging orders and broken pipes

### PR DESCRIPTION
**Pull request by Nullably**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Used `connect_async` to create gql permanent session (the session auto reconnects if needed)
- Used `runtime_config` to create scale object instead of substrate as per https://github.com/hummingbot/hummingbot/pull/6645
- Fixed unit tests

**Tests performed by the developer**:
- Tested on Polkadex with market making strategy
- Unit tests

**Tips for QA testing**:

### CODE REVIEW

**Review by cardosofede — APPROVED** [review]
LGTM! @rapcmia can we test so we can merge it in?

**Comment by rapcmia** [comment]
QA having issues with our polkadex wallet and still looking how we can fix it. This is not related to the PR but a blocker for us atm 🙇🏼 
image

**Comment by rapcmia** [comment]
PR update:
- Ran tests on cloud server via source
    - Setup wallet successful
    - Setup simple pmm strategy
    - Orders are created and cancelled successul
        - There are instances of `error on fetching status update for active order.. Order not found` which seem to be common on some CLOB connectors available atm (dexalot)
            ```          
            2023-11-14 08:15:50,888 - 3858908 - hummingbot.connector.exchange.polkadex.polkadex_exchange.PolkadexExchange - WARNING - Error fetching status update for the active order 0x48424f5442445455543630613138363465643763336461626435386630653865: Order not found
            ```
            - These errors can be reproduced with longer order refresh time
    - There are also instance of lost order
        ```
        2023-11-14 09:32:25,102 - 3858908 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order 0x48424f5442445455543630613139373661326261353961626435386630653865 for 2.3 DOT-USDT.
        2023-11-14 09:32:25,123 - 3858908 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1699954345.0, "type": "OrderType.LIMIT", "trading_pair": "DOT-USDT", "amount": "2.3", "price": "5.395", "order_id": "0x48424f5442445455543630613139373661326261353961626435386630653865", "creation_timestamp": 1699954341.0, "exchange_order_id": "0x66050eba253f23fe2010475587c810dd2efa577ede89b4d0138ea519232196d0", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "polkadex"}
        2023-11-14 09:32:26,140 - 3858908 - hummingbot.connector.exchange.polkadex.polkadex_exchange.PolkadexExchange - WARNING - Error fetching status update for the active order 0x48424f5442445455543630613139373661326261353961626435386630653865: Order not found 0x48424f5442445455543630613139373661326261353961626435386630653865 (0x66050eba253f23fe2010475587c810dd2efa577ede89b4d0138ea519232196d0).
        2023-11-14 09:32:30,695 - 3858908 - hummingbot.connector.exchange.polkadex.polkadex_exchange.PolkadexExchange - WARNING - Error fetching status update for the active order 0x48424f5442445455543630613139373661326261353961626435386630653865: Order not found 0x48424f5442445455543630613139373661326261353961626435386630653865 (0x66050eba253f23fe2010475587c810dd2efa577ede89b4d0138ea519232196d0).
        2023-11-14 09:32:36,021 - 3858908 - hummingbot.connector.exchange.polkadex.polkadex_exchange.PolkadexExchange - WARNING - Error fetching status update for the active order 0x48424f5442445455543630613139373661326261353961626435386630653865: Order not found 0x48424f5442445455543630613139373661326261353961626435386630653865 (0x66050eba253f23fe2010475587c810dd2efa577ede89b4d0138ea519232196d0).
        2023-11-14 09:32:40,616 - 3858908 - hummingbot.connector.exchange.polkadex.polkadex_exchange.PolkadexExchange - WARNING - Error fetching status update for the active order 0x48424f5442445455543630613139373661326261353961626435386630653865: Order not found 0x48424f5442445455543630613139373661326261353961626435386630653865 (0x66050eba253f23fe2010475587c810dd2efa577ede89b4d0138ea519232196d0).
        2023-11-14 09:32:40,617 - 3858908 - hummingbot.connector.client_order_tracker - WARNING - The order 0x48424f5442445455543630613139373661326261353961626435386630653865(0x66050eba253f23fe2010475587c810dd2efa577ede89b4d0138ea519232196d0) will be considered lost. Please check its status in the exchange.
        2023-11-14 09:32:40,627 - 3858908 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1699954360.0, "order_id": "0x48424f5442445455543630613139373661326261353961626435386630653865", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "polkadex"}
        2023-11-14 09:32:40,627 - 3858908 - hummingbot.connector.client_order_tracker - INFO - Order 0x48424f5442445455543630613139373661326261353961626435386630653865 has failed. Order Update: OrderUpdate(trading_pair='DOT-USDT', update_timestamp=1699954360.0, new_state=<OrderState.FAILED: 6>, client_order_id='0x48424f5442445455543630613139373661326261353961626435386630653865', exchange_order_id=None, misc_updates=None)
        2023-11-14 09:32:43,503 - 3858908 - hummingbot.connector.exchange.polkadex.polkadex_exchange.PolkadexExchange - WARNING - Failed to cancel order 0x48424f5442445455543630613139373661326261353961626435386630653865 (order not found)
        2023-11-14 09:32:43,504 - 3858908 - hummingbot.connector.client_order_tracker - INFO - The lost order 0x48424f5442445455543630613139373661326261353961626435386630653865(0x66050eba253f23fe2010475587c810dd2efa577ede89b4d0138ea519232196d0) was not found and will be removed
        ```
        - Took 18s after creation of BUY order
        - Started with having `exchange_id` and ended up with `None`


Steps to reproduce:
- Setup pure market making with polkadex
- Setup spreads enough for trade fill and refresh refresh time of 15mins 
- Observe connector behavior 

[logs_pmm-polkadex-1.log](https://github.com/hummingbot/hummingbot/files/13365873/logs_pmm-polkadex-1.log)

**Review by rapcmia — APPROVED** [review]
- Ran long term bots and compare results from development
	- No `ssl.SSLEOFError: EOF occurred in violation of protocol` on this PR which is found on development
- There was a case of lost order happened only once 
- Hanging order created and renewed successfully
- Build docker for this PR no error found

**Comment by visiondream3** [comment]
I still see errors where the connector loses track of existing orders and therefore fails to cancel them. They pile up into hundreds of open orders in the OB, which needs to be manually cancelled or by using a script.

`2023-12-07 15:32:15,354 - 24807 - hummingbot.connector.exchange.polkadex.polkadex_exchange.PolkadexExchange - WARNING - Error fetching status update for the active order 0x48424f5442505855543630626564326330356466356231646435623832323238: Order not found 0x48424f5442505855543630626564326330356466356231646435623832323238 (0xf974635c81837ee3a42751857269cdf7288489f29830c5c26f1381f0f60b5930).
2023-12-07 15:32:15,840 - 24807 - hummingbot.connector.exchange.polkadex.polkadex_exchange.PolkadexExchange - WARNING - Error fetching status update for the active order 0x48424f5453505855543630626564326330356530313531646435623832323238: Order not found 0x48424f5453505855543630626564326330356530313531646435623832323238 (0xac4b315ff413245145e8c3075831e24c4b5ca8a03906d1d5ed1d4ab258b3a072).
2023-12-07 15:32:20,622 - 24807 - hummingbot.connector.exchange.polkadex.polkadex_exchange.PolkadexExchange - WARNING - Error fetching status update for the active order 0x48424f5442505855543630626564326330356466356231646435623832323238: Order not found 0x48424f5442505855543630626564326330356466356231646435623832323238 (0xf974635c81837ee3a42751857269cdf7288489f29830c5c26f1381f0f60b5930).
2023-12-07 15:32:21,136 - 24807 - hummingbot.connector.exchange.polkadex.polkadex_exchange.PolkadexExchange - WARNING - Error fetching status update for the active order 0x48424f5453505855543630626564326330356530313531646435623832323238: Order not found 0x48424f5453505855543630626564326330356530313531646435623832323238 (0xac4b315ff413245145e8c3075831e24c4b5ca8a03906d1d5ed1d4ab258b3a072).
`

**Pull request merged**
