### PR TITLE
Feat/fixed_grid_script_added

### PR DESCRIPTION
**Pull request by rkc2000**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Add the fixed grid script for spot markets to the codebase. 

**Tests performed by the developer**:
Paper trading and live runs have been performed. 

**Tips for QA testing**:

### CODE REVIEW

**Comment by rkc2000** [comment]
Tests are failing, I think because of isort failing.. not sure why. Can you help @cardosofede ?

**Comment by fengtality** [comment]
@rkc2000 There are linting issues with your script. Please activate the conda `hummingbot` environment before committing. It will show you the issues to fix:

```
Flake8...................................................................Failed
- hook id: flake8
- exit code: 1

scripts/fixed_grid.py:53:89: E226 missing whitespace around arithmetic operator
scripts/fixed_grid.py:56:64: E226 missing whitespace around arithmetic operator
scripts/fixed_grid.py:59:62: E226 missing whitespace around arithmetic operator
scripts/fixed_grid.py:62:88: E226 missing whitespace around arithmetic operator
scripts/fixed_grid.py:64:62: E226 missing whitespace around arithmetic operator
scripts/fixed_grid.py:68:67: E226 missing whitespace around arithmetic operator
scripts/fixed_grid.py:117:73: W291 trailing whitespace
scripts/fixed_grid.py:130:76: W291 trailing whitespace
scripts/fixed_grid.py:161:46: E231 missing whitespace after ','
scripts/fixed_grid.py:180:1: W293 blank line contains whitespace
scripts/fixed_grid.py:192:1: W293 blank line contains whitespace
scripts/fixed_grid.py:210:1: W293 blank line contains whitespace
scripts/fixed_grid.py:212:5: E303 too many blank lines (2)
scripts/fixed_grid.py:256:1: W293 blank line contains whitespace
scripts/fixed_grid.py:263:69: W291 trailing whitespace
scripts/fixed_grid.py:264:1: W293 blank line contains whitespace
scripts/fixed_grid.py:[27](https://github.com/hummingbot/hummingbot/actions/runs/5616226672/job/15218158256#step:6:28)6:13: E225 missing whitespace around operator
scripts/fixed_grid.py:[29](https://github.com/hummingbot/hummingbot/actions/runs/5616226672/job/15218158256#step:6:30)3:1: W293 blank line contains whitespace
scripts/fixed_grid.py:[30](https://github.com/hummingbot/hummingbot/actions/runs/5616226672/job/15218158256#step:6:31)5:5: E303 too many blank lines (2)
scripts/fixed_grid.py:308:92: W291 trailing whitespace
```

**Comment by rkc2000** [comment]
@fengtality I think I've fixed those in the previous commits. The latest tests show Flake8 passing but isort failing. 

Screenshot 2023-07-21 at 15 25 04

**Comment by fengtality** [comment]
isort is similar. I think it will make the changes itself when you run git
commit

**Comment by rkc2000** [comment]
Checks are passing now (I ran isort command on the script file locally and committed the changes).

**Review by cardosofede — APPROVED** [review]
LGTM!

**Pull request merged**
