### PR TITLE
(fix) change name of trading_pairs property

### LINKED ISSUE #5720: Trading pairs property wrong in Paper Trade exchange
**Describe the bug**
The property to access the trading pairs of the paper trade exchange is trading_pair and it should be trading_pairs as the rest of the connectors.
This is an issue because if you are writing a script and you want to test it in paper trade and then run live, the method will be different and you should change the property.

**Steps To Reproduce**
Run a script and access the trading pairs of a paper trade connector and then use the same connector without paper trade.

Here are the steps to reproduce the issue (see attachments in the section below):

Run this script:
Change the extension to .py
[paper_trade_issue.txt](https://github.com/hummingbot/hummingbot/files/9609531/paper_trade_issue.txt)

**Screenshots**
Logs showing that the Binance connector shows the trading pairs while the paper trade exchange connector has an issue
image

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

### PR DESCRIPTION
**Pull request by cardosofede**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This PR Closes #5720 
Now the property trading_pairs is available in the paper_trade exchange and returns a list of trading pairs.

**Tests performed by the developer**:
Run the same script of the issue and check that it's returning the same list

**Tips for QA testing**:
Test the pure market making strategies with paper trade for 5 minutes and check if all is working ok.

### CODE REVIEW

**Comment by nikspz** [comment]
Tried to start the script @cardosofede pinned in https://github.com/hummingbot/hummingbot/issues/5720
Got this issue:
image

**Comment by nikspz** [comment]
Retested, works now
image

**Review by nikspz — DISMISSED** [review]
Test performed:
- Cloned and installed feature branch
- Download a script provided in https://github.com/hummingbot/hummingbot/issues/5720
- Changed extension to .py
- start --script paper_trade_issue.py and ran the bot for a while
- Reviewed That Unexpected error for paper trade now fixed

**Review by rapcmia — APPROVED** [review]
> Test performed:
> 
> * Cloned and installed feature branch
> * Download a script provided in #5720
> * Changed extension to .py
> * start --script paper_trade_issue.py and ran the bot for a while
> * Reviewed That Unexpected error for paper trade now fixed

LGTM

**Pull request merged**
