### PR TITLE
fix/MEXC exchange, when the token price is super small

### PR DESCRIPTION
**Pull request by hlxwell**
Before submitting this PR, please make sure:

[*] Your code builds clean without any errors or warnings
[*] You are using approved title ("feat/", "fix/", "docs/", "refactor/")
A description of the changes proposed in the pull request:

Fix the bug in mexc exchange, when the token price is super small, which has many zero after the decimal point, you will not able to place order on the mexc, since the number will be converted to scientific notation.

Tests performed by the developer:

Tested with mexc, and it is able to place order which has price like 0.000000001

Tips for QA testing:

### CODE REVIEW

**Comment by cardosofede** [comment]
@hlxwell thanks for the contribution! Can you please provide an example of token that you experience this so QA can test it?
cc.: @rapcmia @nikspz

**Comment by hlxwell** [comment]
image

sure, you can try above tokens to test it.

**Review by nikspz — APPROVED** [review]
Test performed:
- Clone and install fix branch
- Manually built docker image successfully
- Created simple pureMM strategy using ZKDOGE-USDT Pair
    - latest develoment crosscheck: bot wasn't able to place orders (Failed to submit order)
image
    - The PR6473, Client was able to create orders
image
image

**Review by cardosofede — APPROVED** [review]
LGTM!

**Pull request merged**
