### PR TITLE
Fix/Remove _last_recv_time variable from Binance

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

`_last_recv_time` variable removed because it's not needed anymore.

**Tests performed by the developer**:

Ran unit tests

**Tips for QA testing**:

Nothing specific to test.

### CODE REVIEW

**Comment by aarmoa** [comment]
PRP: https://snapshot.org/#/hbot-prp.eth/proposal/0x4a6413c5227f88f95e65e16b8789696f384bc826f77615114365467fdf9daac1

**Comment by rapcmia** [comment]
Hi @mhrvth good day,
It seems the PRP submitted has no votes and already completed, kindly resubmit again if you still plan to continue this PR. Thank you

Link: https://snapshot.org/#/hbot-prp.eth/proposal/0x4a6413c5227f88f95e65e16b8789696f384bc826f77615114365467fdf9daac1

**Comment by mhrvth** [comment]
Created a new PRP: https://snapshot.org/#/hbot-prp.eth/proposal/0xd14e5b91b16819554db1f0429a6fe916a2239feb29d744e95f1060bccb7336ce

**Review by rapcmia — APPROVED** [review]
Test performed
- Install branch successfully
- Connected API and balance check
- Setup simple pure market-making strategy
- Start the bot and monitor order create/cancellation, all ok
- Setup short and long refresh time then disconnect to network, the client managed to reconnect
- Filled trade event all ok
    - Test with after filled event, disconnect to network then reconnect
    - Trade data from history —verbose, CSV and exchange history matched
- Tested multiple and hanging orders, all ok

**Pull request merged**
