### PR TITLE
Feat/pancake swap

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
This pr introduces the Binance SC and Pancake swap on top of the OSS project.
HIP link: https://snapshot.org/#/hbot-ip.eth/proposal/0xeb7772e5b7cf52a4308cfab8b4bb8ffd6142291aef83ea1cea3ccf100084f954

**Tests performed by the developer**:
- Ensured all test pass locally.
- Did basic endpoint testing and a bit of end-to-end connection from the client.

**Tips for QA testing**:
- Ensure all new curl tests work
- End-to-end testing with AMM arb strategy and ensure there are no issues.

### CODE REVIEW

**Comment by JeremyKono** [comment]
@vic-en please resolve conflcits. Thanks

**Comment by rapcmia** [comment]
PR update:
- Successfully setup docker gateway build for endpoint tests
- Endpoint tests on Curl
  - Setup BSC env variables
  - port: ok
  - wallet/add: ok
  - wallet/remove: ok
  - network/balances: ok
  - evm/nonce: ok
  - evm/approve: ok
  - amm/price: ok 
  - amm/trade: ok 

Getting the same results with https://github.com/hummingbot/hummingbot/pull/5894#issuecomment-1318257153

**Comment by rapcmia** [comment]
PR update:
- Setup docker for both client and gateway successfully 
- Connected Pancake wallet, balance displays the expected amounts 
- Setup AMM arbitrage with runtime of 30-45mins
- The rate probability is showing as expected and not unrealistic percentages (e.g 334.1%, -58%, etc..)
- Noticeable unhandled errors on rate conversion which are not part of the PR 
- Order execution:
   - Multiple order even triggered all recorded and txhash show successful swaps
   - Set min_profitability for interval arbitrage opportunity. Trades are successfully recorded
   - When balance not enough, the client would return `..below required order amount`
   - Trades matched from txhash and client history/csv files 
   - Trade fees recorded on BNB matched

Hi @vic-en PR is good for approval however we encounter this issue when setting up `debug_shim` for pancake_swap on AMM-Arbitrage. Is this something that we can fix here since its something to do with the strategy or we can create a separate ticket? Thank you
image
```

2022-11-18 16:21:31,206 - 3203 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Unsupported chain: binance-smart-chain
Traceback (most recent call last):
  File "/home/rapcmia/github/5895/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/rapcmia/github/5895/hummingbot/client/command/start_command.py", line 119, in start_check
    self._initialize_strategy(self.strategy_name)
  File "/home/rapcmia/github/5895/hummingbot/client/command/start_command.py", line 251, in _initialize_strategy
    start_strategy(self)
  File "/home/rapcmia/github/5895/hummingbot/strategy/amm_arb/start.py", line 47, in start
    raise ValueError(f"Unsupported chain: {amm_market_info.market.chain}")
ValueError: Unsupported chain: binance-smart-chain
```

[amm-bsc-pancake.zip](https://github.com/hummingbot/hummingbot/files/10039476/amm-bsc-pancake.zip)

**Review by rapcmia — APPROVED** [review]
Test summary:
- Setup successfully on both source and docker gateway build 
- Successfully connected Pancakeswap wallet and balance displays correct
- Connector-tokens feature also is displaying the tokens relevant to the connector 
- Setup simple AMM-arbitrage with Pancakeswap
- Runtime of more than 45mins no error found
- Rate probability is working as expected as no observed unrealistic rates (e.g 303%, -94% etc)
- Order execution:
	- Multiple order event triggered, all recorded and txhash show successfully swap
	- Set min_profitability for interval arbitrage opporunity. Trades successfully recorded
	- When balance not enough, the client return `below required order amount`
	- Trades matched from txhash and client history/csv files
- Tested on bot source and docker client build both running on AWS and local instances 
- Successfully tested endpoints via curl commands 
- Confirmed issue on debug_shim is expected since it only support ethereum and solan for HBF

**Comment by mrmikeo** [comment]
Don't forget to unwrap BNB in core/gateway/utils.py

**Pull request merged**
