### PR TITLE
Fix/Bybit Perpetual - Multiple bug fixes

### PR DESCRIPTION
**Pull request by mhrvth**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

- adds and undocumented `position_idx` parameter in `_create_order()` API call
- adds an API call to switch position mode in `set_position_mode()`
- changes order tracking to `ClientOrderTracker`
- on order cancellation failure doesn't stops tracking but sends an update to the `ClientOrderTracker` to deal with it
- Fixes these issues:
   - Error submitting orders - https://github.com/hummingbot/hummingbot/issues/5113
   - Filled trades are not getting recorded - https://github.com/hummingbot/hummingbot/issues/4975
   - Insufficient balance and order getting omitted warning message.
   - Unable to connect bybit perpetual testnet - https://github.com/hummingbot/hummingbot/issues/5096
   - Trading pair symbol cannot be found - https://github.com/hummingbot/hummingbot/issues/4372
   - Not showing Position in the bot status after cancel manually and restart the strategy - https://github.com/hummingbot/hummingbot/issues/4778

**Tests performed by the developer**:

- ran oneway & hedge mode with perpetual MM live market
- printed API responses for position mode switching
- ran unit tests

### CODE REVIEW

**Comment by dennisocana** [comment]
Proposal created: https://snapshot.org/#/hbot-prp.eth/proposal/0x5df0940226ed19c29e299b117355405ade7a20a03fb0404c5021c1f30746ef13

**Comment by rapcmia** [comment]
While testing we encounter instances of the client getting an `Error submitting order to Bybit Perpetual...` on both local and AWS test. We monitor if the client is able to recover from the error but every order_refresh_time (30s) it seems that its getting the same error all over again.

Below is the error we got from checking XRP-USDT and ETH-USDT
image

Below is a recording where the bot managed to recover from the error, see `00:10s - 00:40s`

https://user-images.githubusercontent.com/73840223/163356019-592cb863-201e-4104-abba-c510818c7ebf.mp4

This error also happen when testing the position retrieval and we have to `stop and start` the bot again to get it working ok. We also tried to reinstall/recompile but no go. Thanks

Steps to reproduce:
1. Setup Perpetual market making using Bybit connector
2. Set your position mode either oneway or hedge
3. Setup spreads enough for trades to OPEN/CLOSE position
4. Start the bot and monitor log panel

Attached:
[perp-bybit.zip](https://github.com/hummingbot/hummingbot/files/8488069/perp-bybit.zip)

**Comment by mhrvth** [comment]
After examining the logs, the reason why you're getting the error is because the Perpetual MM doesn't change the position mode to the one specified in the configuration. This will be addressed in another PR. But regarding this PR, it's not a problem of the connector. To fix the issue, change the position mode in the account to match the selected position mode in the strategy configuration.

**Review by rapcmia — APPROVED** [review]
Test performed 
- Install fix branch, all ok 
- Setup simple perpetual market making strategy using Bybit perpetual
- Connect API and balance check, ok 
- Monitor order creation and cancellation, ok 
- Setup Oneway and Hedge mode, all ok 
- Trade data on history, CSV and exchange trade history matched
- The client is able to retrieve open positions
- The client was able to handle multiple order levels
- Tested reported issues/5113, 4975, 5096, 4372 and 4778, all fixed

**Pull request merged**
