### PR TITLE
Fix/multi cert folders

### PR DESCRIPTION
**Pull request by vic-en**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
- Removes multi-gateway paths

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Review by Faouzijedidi1 — APPROVED** [review]

**Comment by rapcmia** [comment]
PR update:
- Clone and installation successful
- Managed to create gateway image for docker build
- Tested using two same PRs (we will name it A and B)
	- Intially setup the two PRs with different set of password when "gateway generate_certs" on the client 
	- Setting up gateway connectors on A (uniswap-kovan and pangolin-avax) then balance, all ok
	- Setting up gateway connectors on B (uniswap-kovan and pangolin-avax), no go
		- Setting up nodeURL is ok 
		- However it then asked if we want to setup wallet using existing pkey which we did not yet setup on the client
			- Could we confirm if this is the expected behavior for this PR? then we can assume that the user should always setup same passphrase or all gateway on different client
			- We are getting this error message on client 
                        image   

Client logs
```
2022-09-05 06:59:27,556 - 796458 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Error on POST https://localhost:29256/network/balances Error: {'message': 'Failed to load wallet: Error: invalid password', 'httpErrorCode': 500, 'errorCode': 1005, 'stack': 'Error: Failed to load wallet: Error: invalid password\n    at Object.<anonymous> (/usr/src/app/dist/src/chains/ethereum/ethereum.controllers.js:75:19)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/dist/src/chains/ethereum/ethereum.controllers.js:6:65)'}
Traceback (most recent call last):
  File "/home/ubuntu/github/5646a/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/github/5646a/hummingbot/client/command/gateway_command.py", line 445, in _gateway_connect
    balances: Dict[str, Any] = await self._get_gateway_instance().get_balances(
  File "/home/ubuntu/github/5646a/hummingbot/core/gateway/gateway_http_client.py", line 280, in get_balances
    return await self.api_request("post", "network/balances", {
  File "/home/ubuntu/github/5646a/hummingbot/core/gateway/gateway_http_client.py", line 218, in api_request
    raise e
  File "/home/ubuntu/github/5646a/hummingbot/core/gateway/gateway_http_client.py", line 206, in api_request
    raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
ValueError: Error on POST https://localhost:29256/network/balances Error: {'message': 'Failed to load wallet: Error: invalid password', 'httpErrorCode': 500, 'errorCode': 1005, 'stack': 'Error: Failed to load wallet: Error: invalid password\n    at Object.<anonymous> (/usr/src/app/dist/src/chains/ethereum/ethereum.controllers.js:75:19)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/dist/src/chains/ethereum/ethereum.controllers.js:6:65)'}
```

Another scenario we would want to confirm:
- For multiple clients, it will now share on `certs, logs and conf` folder?
- Do we have a step on how a user can reset the passphrase of the gateway cert?

Steps to reproduce:
1. Create 2 Hummingbot client and use gateway docker build for testing (we named A and B)
2. Setup "gateway generate_certs" each with different passphrases
3. Setup gateway connector on A, should be no problem (uniswap-kovan and pangolin-avax)
4. Setup gateway connector on B, it prompted us if we want to use existing key
5. Select Yes, notice the error on logs

Attached:
[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/9487850/logs_hummingbot.log)


Pending test:
- Source client and gateway build
- Testing with same passphrases

**Comment by nikspz** [comment]
Could we add a suggestion?
Is it possible to left `separate logs folders for every instance` if user run `multiple bots` using `Source+gwv2docker`?

Could be useful to get log files for the separate instances and it could help triage issues

Old logic for certs:
image
image
Could we use old logic for the log files?

**Comment by mifeng** [comment]
I tested this from a source Docker installation, and running `gateway generate-certs` works well. However, I couldn't run `gateway create` successfully as it doesn't seem to detect Gateway.
Screen Shot 2022-09-14 at 5 07 17 PM

@arnelhbot can you verify that you were able to run `gateway create` successfully?

@nikspz You are pointing out a different issue that we should solve by moving the `conf` and `logs` folders out of that location. For now, let's ignore the multiple bots use case and just test Docker HB + Docker Gateway, and Source HB + Source Gateway, single bot only.

**Comment by nikspz** [comment]
Test performed:
Cloned and installed feature branch - ok
Create docker image of HB - ok
Gateway generate certs - ok
Confirmed gateway created certs in .../instance_files/hummingbot_certs/  - ok
Gateway create successfully created docker image - ok
Ran single bot Docker HB + Docker Gateway - ok

certs PR dockert docker

Pending test: 
Source HB + Source Gateway single bot

**Pull request closed without merging**
