### PR TITLE
Feat/coin cap rate source

### PR DESCRIPTION
**Pull request by petioptrv**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

This PR is associated to bounty issue: https://github.com/hummingbot/hummingbot/issues/6517.

This PR introduces the [CoinCap](https://coincap.io/) rate source for the rate oracle. It is possible to obtain an API key [here](https://coincap.io/api-key).

CoinCap adds an alternative to CoinGecko, and its API allows for price streaming, which is included in this PR.

Note that CoinCap's API uses asset names rather than symbols, which means users must configure an asset map like `'BTC:bitcoin,DOGE:dogecoin'` to the `assets_map` of the rate source's config.

Note also that the only consequence of a faulty API key (or no API key) is that the user will have lower rate limits. If a faulty API key is detected, the client will issue a warning log.

The PR had to make significant changes to the configuration modules in order to allow configuring a secret API key in the client config map.

**Tests performed by the developer**:

- Unit tests added.
- Manually tested the functionality.

**Tips for QA testing**:

Obtain an API key [here](https://coincap.io/api-key) and run a full test on the functionality of the rate provider. Please not that the global token must be configured to `USD` in order for `rate --token {TOKEN}` to work. That is because CoinCap only supports USD as a quote, and that rate functionality cannot perform conversions. However, the `rate --pair {BASE}-{QUOTE}` will work with pairs that don't include `USD` as quote.

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update:
- Test latest commit `d73b100fe1f9`
- Check [Coincap](https://coincap.io/) and [created API key](https://coincap.io/api-key)
- Ran `config rate_oracle_source`
  image
  - How to add multiple symbols? 
     image
  - What happens if invalid API key?
     image
  - What happens if incorrect global token?
     image
       - Global must be set to USD when using coincap using `config global_token.global_token_name`
- Setup AMM-arb on pancakeswap
    - WBNB not supported on coincap, still works ok
    - Added multiple symbols and displays the balance ok
    - Start with not adding USDT on symbols getting:
      image
       - Added USDT on `config rate_oracle_sourc.asset_map`
       image
- Build docker image and check rate_oracle coincap ✅

**Review by rapcmia — APPROVED** [review]

**Review by cardosofede — APPROVED** [review]
LGTM! Thanks for the contribution @petioptrv 
Do you think that are other important things that we can improve in the codebase in terms of configuration?
@rapcmia after finishing testing we can merge it once the test are passing

**Comment by cardosofede** [comment]
@petioptrv yeah totally agree, I think that we should refactor a little bit the settings and the app, I'm working in the distribution of the library and currently the codebase is using the HummingbotApplication for a lot of things and running a lot of process that probably we should omit unless we are looking for them

**Comment by cardosofede** [comment]
@petioptrv I fixed in another PR the issues with the environment. Now the workflow is failing due formatting conventions.

**Comment by rapcmia** [comment]
Merged to development and will be part of release version 1.20.0

**Pull request merged**
