### PR TITLE
(feat) improve max retries executor

### PR DESCRIPTION
**Pull request by cardosofede**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
The current retries of the executor were updated every time that an event came, generating conflicts on the current retries of other executors.

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update `test in progress`
- Running bot with kucoin as connector 
- Setup single and multiple level orders each pair with diff setup
- Using 2 v2 controllers with rebalance enabled on 1 script config, monitoring results and post update

**Comment by rapcmia** [comment]
PR update:


> * Using 2 v2 controllers with rebalance enabled on 1 script config, monitoring results and post update

- Rebalance every 60s still ok using new default 5usd
- Not able to reproduce max retries, set rebalance to null and modified config again to run overnight

**Comment by rapcmia** [comment]
PR update:
- Run tests with 1 script with 2 controllers 
- Max retries triggered 
- Trace retries from 0 to 10 ok
    - Interval on each retries occurred every 1s
- While in the process of retries, other executor managed to placed and open executor ok
- Other executor retry occurred due to insufficient balance does not hinder the other executor from placing orders ok
- Observed status does not display any of the close types besides `INSUFFICIENT_FUNDS`
	- Redo tests again for the next 3hours and review logs 
	- This time closetypes are displayed ok
	- Executors are opened/closed ok
	    - Observed partial fills happened, all ok
	    - Observed two executors happened to be closed at the same time and retried ok
- I still have a running bot for monitoring

[10092024.zip](https://github.com/user-attachments/files/17305558/10092024.zip)

**Comment by rapcmia** [comment]
PR update:
- Setup GS with 2 controllers running on remote server 
- Ran GS on PR using okx subaccount ok
- Orders are placed and cancel accordingly, no stuck order on exchange
- After couple of hours, still no retry happened
- Modified grid_allocation and nlvels to trigger low min order size
- Run both on development and this PR
- Observed changes from the PR in which:
  - See logs on `development` where retries exceeds 10 attempts
    ```
    2024-10-10 19:35:10,748 - 617 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Sell order amount 572032.0337938924579776467482 is lower than the minimum order size 1000000. The order will not be created, increase the amount to be higher than the minimum order size.
    2024-10-10 19:35:10,748 - 617 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Buy order amount 775378.7426935464630800429441 is lower than the minimum order size 1000000. The order will not be created, increase the amount to be higher than the minimum order size.
    2024-10-10 19:35:10,748 - 617 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Buy order amount 310319.3456730908717533711346 is lower than the minimum order size 1000000. The order will not be created, increase the amount to be higher than the minimum order size.
    2024-10-10 19:35:10,748 - 617 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Buy order amount 307640.7734226328036709371418 is lower than the minimum order size 1000000. The order will not be created, increase the amount to be higher than the minimum order size.
    2024-10-10 19:35:10,749 - 617 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Buy order amount 305008.0465205944427263237167 is lower than the minimum order size 1000000. The order will not be created, increase the amount to be higher than the minimum order size.
    2024-10-10 19:35:10,749 - 617 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Buy order amount 304315.9157223922811163023826 is lower than the minimum order size 1000000. The order will not be created, increase the amount to be higher than the minimum order size.
    2024-10-10 19:35:10,749 - 617 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Buy order amount 304315.9157223922811163023826 is lower than the minimum order size 1000000. The order will not be created, increase the amount to be higher than the minimum order size.
    2024-10-10 19:35:10,749 - 617 - hummingbot.strategy_v2.executors.position_executor.position_executor - ERROR - Open order failed. Retrying 10/10
    2024-10-10 19:35:10,749 - 617 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1728560110.0, "order_id": "93027a12dac34fBCSPEUT96db9be5de9", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "okx"}
    2024-10-10 19:35:10,750 - 617 - hummingbot.connector.client_order_tracker - INFO - Order 93027a12dac34fBCSPEUT96db9be5de9 has failed. Order Update: OrderUpdate(trading_pair='PEPE-USDT', update_timestamp=1728560110.0, new_state=<OrderState.FAILED: 6>, client_order_id='93027a12dac34fBCSPEUT96db9be5de9', exchange_order_id=None, misc_updates=None)
    2024-10-10 19:35:10,751 - 617 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1728560110.0, "order_id": "93027a12dac34fBCBPEUT9fab0925a4e", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "okx"}
    2024-10-10 19:35:10,751 - 617 - hummingbot.strategy_v2.executors.position_executor.position_executor - ERROR - Open order failed. Retrying 11/10
    2024-10-10 19:35:10,751 - 617 - hummingbot.connector.client_order_tracker - INFO - Order 93027a12dac34fBCBPEUT9fab0925a4e has failed. Order Update: OrderUpdate(trading_pair='PEPE-USDT', update_timestamp=1728560110.0, new_state=<OrderState.FAILED: 6>, client_order_id='93027a12dac34fBCBPEUT9fab0925a4e', exchange_order_id=None, misc_updates=None)
    2024-10-10 19:35:10,752 - 617 - hummingbot.strategy_v2.executors.position_executor.position_executor - ERROR - Open order failed. Retrying 12/10
    2024-10-10 19:35:10,752 - 617 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1728560110.0, "order_id": "93027a12dac34fBCBPEUT1907d290977", "order_type": "OrderType.LIMIT_MAKER", "event_name": "MarketOrderFailureEvent", "event_source": "okx"}
    2024-10-10 19:35:10,753 - 617 - hummingbot.connector.client_order_tracker - INFO - Order 93027a12dac34fBCBPEUT1907d290977 has failed. Order Update: OrderUpdate(trading_pair='PEPE-USDT', update_timestamp=1728560110.0, new_state=<OrderState.FAILED: 6>, client_order_id='93027a12dac34fBCBPEUT1907d290977', exchange_order_id=None, misc_updates=None)
    2024-10-10 19:35:10,753 - 617 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1728560110.0, "order_id": "93027a12dac34fBCBPEUT9600f346124", "order_type": "OrderType.LIMIT_MAKER", "event_name": "MarketOrderFailureEvent", "event_source": "okx"}
    2024-10-10 19:35:10,753 - 617 - hummingbot.strategy_v2.executors.position_executor.position_executor - ERROR - Open order failed. Retrying 13/10
    2024-10-10 19:35:10,754 - 617 - hummingbot.connector.client_order_tracker - INFO - Order 93027a12dac34fBCBPEUT9600f346124 has failed. Order Update: OrderUpdate(trading_pair='PEPE-USDT', update_timestamp=1728560110.0, new_state=<OrderState.FAILED: 6>, client_order_id='93027a12dac34fBCBPEUT9600f346124', exchange_order_id=None, misc_updates=None)
    2024-10-10 19:35:10,754 - 617 - hummingbot.strategy_v2.executors.position_executor.position_executor - ERROR - Open order failed. Retrying 14/10
    2024-10-10 19:35:10,754 - 617 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1728560110.0, "order_id": "93027a12dac34fBCBPEUT5be8e4c61eb", "order_type": "OrderType.LIMIT_MAKER", "event_name": "MarketOrderFailureEvent", "event_source": "okx"}
    2024-10-10 19:35:10,755 - 617 - hummingbot.connector.client_order_tracker - INFO - Order 93027a12dac34fBCBPEUT5be8e4c61eb has failed. Order Update: OrderUpdate(trading_pair='PEPE-USDT', update_timestamp=1728560110.0, new_state=<OrderState.FAILED: 6>, client_order_id='93027a12dac34fBCBPEUT5be8e4c61eb', exchange_order_id=None, misc_updates=None)
    2024-10-10 19:35:10,755 - 617 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1728560110.0, "order_id": "93027a12dac34fBCBPEUT877b17f9547", "order_type": "OrderType.LIMIT_MAKER", "event_name": "MarketOrderFailureEvent", "event_source": "okx"}
    2024-10-10 19:35:10,756 - 617 - hummingbot.strategy_v2.executors.position_executor.position_executor - ERROR - Open order failed. Retrying 15/10
    2024-10-10 19:35:10,756 - 617 - hummingbot.connector.client_order_tracker - INFO - Order 93027a12dac34fBCBPEUT877b17f9547 has failed. Order Update: OrderUpdate(trading_pair='PEPE-USDT', update_timestamp=1728560110.0, new_state=<OrderState.FAILED: 6>, client_order_id='93027a12dac34fBCBPEUT877b17f9547', exchange_order_id=None, misc_updates=None)
    2024-10-10 19:35:10,756 - 617 - hummingbot.strategy_v2.executors.position_executor.position_executor - ERROR - Open order failed. Retrying 16/10
    2024-10-10 19:35:10,756 - 617 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1728560110.0, "order_id": "93027a12dac34fBCBPEUTab3d9da631f", "order_type": "OrderType.LIMIT_MAKER", "event_name": "MarketOrderFailureEvent", "event_source": "okx"}
    2024-10-10 19:35:10,757 - 617 - hummingbot.connector.client_order_tracker - INFO - Order 93027a12dac34fBCBPEUTab3d9da631f has failed. Order Update: OrderUpdate(trading_pair='PEPE-USDT', update_timestamp=1728560110.0, new_state=<OrderState.FAILED: 6>, client_order_id='93027a12dac34fBCBPEUTab3d9da631f', exchange_order_id=None, misc_updates=None)
    2024-10-10 19:35:10,875 - 617 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - NETWORK - Error submitting sell LIMIT_MAKER order to Okx for 7.770 EIGEN-USDT 3.650.
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/hummingbot/dev-hummingbot/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
        await self._place_order_and_process_update(order=order, **kwargs,)
      File "/Users/rapcomia/github/hummingbot/hummingbot/dev-hummingbot/hummingbot/connector/exchange_py_base.py", line 469, in _place_order_and_process_update
        exchange_order_id, update_timestamp = await self._place_order(
      File "/Users/rapcomia/github/hummingbot/hummingbot/dev-hummingbot/hummingbot/connector/exchange/okx/okx_exchange.py", line 211, in _place_order
        raise IOError(f"Error submitting order {order_id}: {data['sMsg']}")
    OSError: Error submitting order 93027a12dac34fBCSENUT10cf6c6c8b3: Order failed. Insufficient EIGEN balance in account. 
    2024-10-10 19:35:10,876 - 617 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Failed to submit SELL order to Okx. Check API key and network connection.
    2024-10-10 19:35:10,909 - 617 - hummingbot.strategy_v2.executors.position_executor.position_executor - ERROR - Open order failed. Retrying 17/10
    2024-10-10 19:35:10,909 - 617 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1728560110.0, "order_id": "93027a12dac34fBCSENUT10cf6c6c8b3", "order_type": "OrderType.LIMIT_MAKER", "event_name": "MarketOrderFailureEvent", "event_source": "okx"}
    2024-10-10 19:35:10,911 - 617 - hummingbot.connector.client_order_tracker - INFO - Order 93027a12dac34fBCSENUT10cf6c6c8b3 has failed. Order Update: OrderUpdate(trading_pair='EIGEN-USDT', update_timestamp=1728560110.0, new_state=<OrderState.FAILED: 6>, client_order_id='93027a12dac34fBCSENUT10cf6c6c8b3', exchange_order_id=None, misc_updates=None)
    2024-10-10 19:35:10,912 - 617 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order 93027a12dac34fBCBSIUT17bc020af55 for 3.9936 SUI-USDT at 1.6276.
    2024-10-10 19:35:10,917 - 617 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1728560110.0, "type": "OrderType.LIMIT", "trading_pair": "SUI-USDT", "amount": "3.9936", "price": "1.6276", "order_id": "93027a12dac34fBCBSIUT17bc020af55", "creation_timestamp": 1728560110.0, "exchange_order_id": "1880984649132998657", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "okx"}
    2024-10-10 19:35:10,956 - 617 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order 93027a12dac34fBCSSIUTf29dc07a41f for 3.2696 SUI-USDT at 1.9880.
    2024-10-10 19:35:10,965 - 617 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1728560110.0, "type": "OrderType.LIMIT", "trading_pair": "SUI-USDT", "amount": "3.2696", "price": "1.9880", "order_id": "93027a12dac34fBCSSIUTf29dc07a41f", "creation_timestamp": 1728560110.0, "exchange_order_id": "1880984649468542977", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "okx"}
    2024-10-10 19:35:11,741 - 617 - hummingbot.strategy_v2.executors.position_executor.position_executor - ERROR - Not enough budget to open position.
    2024-10-10 19:35:11,742 - 617 - hummingbot.strategy_v2.executors.position_executor.position_executor - ERROR - Not enough budget to open position.
    ```
  - Improved handling of max retries ✅ 
    ```
    024-10-10 11:39:43,283 - 156079 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Sell order amount 572032.0337938924579776467482 is lower than the minimum order size 1000000. The order will not be created, increase the amount to be higher than the minimum order size.
    2024-10-10 11:39:43,284 - 156079 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Buy order amount 775378.7426935464630800429441 is lower than the minimum order size 1000000. The order will not be created, increase the amount to be higher than the minimum order size.
    2024-10-10 11:39:43,284 - 156079 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Buy order amount 307640.7734226328036709371418 is lower than the minimum order size 1000000. The order will not be created, increase the amount to be higher than the minimum order size.
    2024-10-10 11:39:43,285 - 156079 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Buy order amount 305008.0465205944427263237167 is lower than the minimum order size 1000000. The order will not be created, increase the amount to be higher than the minimum order size.
    2024-10-10 11:39:43,285 - 156079 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - WARNING - Buy order amount 302419.9979486968358109509644 is lower than the minimum order size 1000000. The order will not be created, increase the amount to be higher than the minimum order size.
    2024-10-10 11:39:43,288 - 156079 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1728560383.0, "order_id": "93027a12dac34fBCSPEUT4f63489c204", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "okx"}
    2024-10-10 11:39:43,292 - 156079 - hummingbot.connector.client_order_tracker - INFO - Order 93027a12dac34fBCSPEUT4f63489c204 has failed. Order Update: OrderUpdate(trading_pair='PEPE-USDT', update_timestamp=1728560383.0, new_state=<OrderState.FAILED: 6>, client_order_id='93027a12dac34fBCSPEUT4f63489c204', exchange_order_id=None, misc_updates=None)
    2024-10-10 11:39:43,295 - 156079 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1728560383.0, "order_id": "93027a12dac34fBCBPEUTc6a2ab7622b", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "okx"}
    2024-10-10 11:39:43,298 - 156079 - hummingbot.connector.client_order_tracker - INFO - Order 93027a12dac34fBCBPEUTc6a2ab7622b has failed. Order Update: OrderUpdate(trading_pair='PEPE-USDT', update_timestamp=1728560383.0, new_state=<OrderState.FAILED: 6>, client_order_id='93027a12dac34fBCBPEUTc6a2ab7622b', exchange_order_id=None, misc_updates=None)
    2024-10-10 11:39:43,300 - 156079 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1728560383.0, "order_id": "93027a12dac34fBCBPEUTeff7d186193", "order_type": "OrderType.LIMIT_MAKER", "event_name": "MarketOrderFailureEvent", "event_source": "okx"}
    2024-10-10 11:39:43,304 - 156079 - hummingbot.connector.client_order_tracker - INFO - Order 93027a12dac34fBCBPEUTeff7d186193 has failed. Order Update: OrderUpdate(trading_pair='PEPE-USDT', update_timestamp=1728560383.0, new_state=<OrderState.FAILED: 6>, client_order_id='93027a12dac34fBCBPEUTeff7d186193', exchange_order_id=None, misc_updates=None)
    2024-10-10 11:39:43,306 - 156079 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1728560383.0, "order_id": "93027a12dac34fBCBPEUT5cc7898f90c", "order_type": "OrderType.LIMIT_MAKER", "event_name": "MarketOrderFailureEvent", "event_source": "okx"}
    2024-10-10 11:39:43,309 - 156079 - hummingbot.connector.client_order_tracker - INFO - Order 93027a12dac34fBCBPEUT5cc7898f90c has failed. Order Update: OrderUpdate(trading_pair='PEPE-USDT', update_timestamp=1728560383.0, new_state=<OrderState.FAILED: 6>, client_order_id='93027a12dac34fBCBPEUT5cc7898f90c', exchange_order_id=None, misc_updates=None)
    2024-10-10 11:39:43,311 - 156079 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1728560383.0, "order_id": "93027a12dac34fBCBPEUT0d1b1f8c78b", "order_type": "OrderType.LIMIT_MAKER", "event_name": "MarketOrderFailureEvent", "event_source": "okx"}
    2024-10-10 11:39:43,314 - 156079 - hummingbot.connector.client_order_tracker - INFO - Order 93027a12dac34fBCBPEUT0d1b1f8c78b has failed. Order Update: OrderUpdate(trading_pair='PEPE-USDT', update_timestamp=1728560383.0, new_state=<OrderState.FAILED: 6>, client_order_id='93027a12dac34fBCBPEUT0d1b1f8c78b', exchange_order_id=None, misc_updates=None)
    ```

[10102024-controllers.zip](https://github.com/user-attachments/files/17327660/10102024-controllers.zip)

**Review by rapcmia — APPROVED** [review]
- Run test on source local and remote
- Run 1 script with 2 PMM simple controllers
- Run 1 script with GS config generated from Quantslab
- Observed max retries when:
	- Runing long term bots
	- When rebalancing and not enough asset to place market order 
	- When placing order but not enough balance 
	- When running multiple levels and place orders
- Rebalance default now is 5
- Build docker image ok

**Comment by nikspz** [comment]
Test performed:
- Run test on cloud server
- Build docker image ok
- Run 1 script with 3 pmm_simple controllers
- Run 1 script with 1 pmm_simple controller
- Run 1 script with 1 macd_bb_v1 controller
- max retries when showed on:
  - Stopping strategy and after market order to close position filled partially 
  - When rebalancing and not enough asset to place market order
  - When placing order but not enough balance
  - When running multiple levels on multiple pairs and place orders
- Reviewed after executor/s failed on pmm_simple with 10/10 retries (after insufficient balance since other SELL orders placed to OPEN before) there's base (SOL) left unsold on exchange. (when other not failed closed with market)

**Pull request merged**
