### PR TITLE
feat/bitget connector

### PR DESCRIPTION
**Pull request by aarmoa**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Implementation of the perpetual connector to Bitget exchange.
The connector supports the three available product types:
- UMCBL
- CMCBL
- DMCBL

For UMCBL the collateral token is always USDT (the quote token for the trading pairs)
For CMCBL the collateral token is always USDC
For DMCBL the collateral token is always the base asset of the trading pair

The API documentation is https://bitgetlimited.github.io/apidoc/en/spot/#welcome

**Tests performed by the developer**:
Added unit tests for all connector components. All tests passing in green.

- Build Docker image and create instance using it
- Start the client without any errors
- Connect invalid/valid API keys
- Pull balance without any issue
- Create/start strategy without any errors
- No issue on creation and cancellation of orders
- Open position is recognized upon restart
- status/orderbook is sync
- Filled trades + fee are logged correctly
- Checked funding payment on time
- Run the bot on multiple order levels
- Checking invalid API key gets rejected with a correct error message to end user
- Connecting correct and a valid API key
- Checking balance thereafter if it is getting displayed or not
- Cross verifying it with an exchange if the balance is pulled correctly or not
- Created a Perpetual market-making strategy with USDC quote tokens. The strategy runs as expected.
- Created a Perpetual market-making strategy with USD quote tokens. 

**Tips for QA testing**:
Please validate the new connector with any strategy using perpetual connectors.
Include all validations for new connectors.

HIP Link: https://snapshot.org/#/hbot-ip.eth/proposal/0x3644b2a83d69310201f24d44060c2edfcaf7c0cfab511f6f9bf211faa6c8f894

### CODE REVIEW

**Comment by nikspz** [comment]
Test performed:
- Start the client without any errors - Flooded with could not fetch trading fees from Bidget perpetual
- Connect invalid/valid API keys - OK
- Pull balance without any issue - Not showing USDC balance
- Run the BTC-USDC Pair - Bot Failed to place orders, showed Insufficient balance (however got USDC on USDC-Futures balance)
- Create/start strategy without any errors - OK
- No issue on creation and cancellation of orders - OK
- Open position is recognized upon restart - OK
- Status/orderbook is sync - OK
- Filled trades + fee are logged correctly - OK
- Run the bot on multiple order levels - OK

**Comment by nikspz** [comment]
Actual:
Bot showed There's an Error - `There was an error parsing a trading pair information (BTC-USD)` at the start of the instance
Bot constantly Flood with `could not fetch trading fees from Bidget perpetual` messages

Expected: 
There's no errors at start/running a bot


```
2022-10-28 09:17:08,448 - 312826 - hummingbot.connector.derivative.bitget_perpetual.bitget_perpetual_derivative.BitgetPerpetualDerivative - ERROR - There was an error parsing a trading pair information (BTC-USD)
2022-10-28 09:17:08,448 - 312826 - hummingbot.connector.derivative.bitget_perpetual.bitget_perpetual_derivative.BitgetPerpetualDerivative - ERROR - There was an error parsing a trading pair information (BTC-USD)
```
image

[logs_conf_perpetual_market_making_1.log](https://github.com/hummingbot/hummingbot/files/9887806/logs_conf_perpetual_market_making_1.log)

[5822bitget.zip](https://github.com/hummingbot/hummingbot/files/9887804/5822bitget.zip)
image

**Comment by nikspz** [comment]
1) Failed to check available balance for `USDC-Futures`

Steps:
1. clone and install feature branch
2. connect API key bitget perpetual
3. check `balance`

Actual:
Balance not showed USDC

Expected:
Balance command showed available USDC asset amount

Bitget no USDC showed in balance

2) Bot showed `Insufficient balance for USDC-Futures pair`

Actual:
Bot showed Insufficient balance for USDC-Futures pair

Expected: 
Bot able to place orders using USDC-Futures pairs

image

**Comment by aarmoa** [comment]
I have pushed a change to solve the bugs

**Comment by nikspz** [comment]
@aarmoa 

latest commit 85c3a2b

Bot flooded with Unexpected error while listening to user stream
still placing/refreshing orders

Steps:
1. clone and install feature branch
2. run the bot with bidget_perpetual connected
3. create/start perpetualMM

Actual:
Bot flooded with `Unexpected error while listening to user stream`

Expected:
No errors showed while running the bot

```
2022-11-03 18:04:41,578 - 404813 - hummingbot.connector.derivative.bitget_perpetual.bitget_perpetual_user_stream_data_source.BitgetPerpetualUserStreamDataSource - INFO - Subscribed to private account, position and orders channels...
2022-11-03 18:04:41,718 - 404813 - hummingbot.connector.derivative.bitget_perpetual.bitget_perpetual_user_stream_data_source.BitgetPerpetualUserStreamDataSource - ERROR - Unexpected error while listening to user stream. Retrying after 5 seconds...
Traceback (most recent call last):
  File "/home/ubuntu/bitget5822/hummingbot/core/data_type/user_stream_tracker_data_source.py", line 48, in listen_for_user_stream
    await self._process_websocket_messages(websocket_assistant=self._ws_assistant, queue=output)
  File "/home/ubuntu/bitget5822/hummingbot/connector/derivative/bitget_perpetual/bitget_perpetual_user_stream_data_source.py", line 56, in _process_websocket_messages
    await asyncio.wait_for(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/home/ubuntu/bitget5822/hummingbot/core/data_type/user_stream_tracker_data_source.py", line 79, in _process_websocket_messages
    await self._process_event_message(event_message=data, queue=queue)
  File "/home/ubuntu/bitget5822/hummingbot/connector/derivative/bitget_perpetual/bitget_perpetual_user_stream_data_source.py", line 68, in _process_event_message
    self._pong_response_event.set()
AttributeError: 'NoneType' object has no attribute 'set'
```

[logs_conf_perpetual_market_making_1.log](https://github.com/hummingbot/hummingbot/files/9932226/logs_conf_perpetual_market_making_1.log)
[logs_conf_perpetual_market_making_2.log](https://github.com/hummingbot/hummingbot/files/9932227/logs_conf_perpetual_market_making_2.log)

image
__________________________________________________

https://github.com/hummingbot/hummingbot/pull/5822#issuecomment-1294868860
The issues still showed on latest commit 85c3a2b
> 1. Failed to check available balance for `USDC-Futures`
> 

Steps:
1. run the bot with bidget_perpetual connected
2. run  `balance` command

Actual:
Bot failed to check balance on USDC Futures (with the balance command)

Expected:
Bot show all balance including USDC

image
image

> 2. Bot showed `Insufficient balance for USDC-Futures pair`
> 

Steps:
1. run the bot with bidget_perpetual connected
2. create/start perpetualMM using ETH-USDC pair and order amount 0.01 or more
3. run `status --live`

Actual:
Bot unstable to show USDC balance in `status --live`


Bitget no USDC showed in balance

**Comment by nikspz** [comment]
@aarmoa 
Summary for issues above:

Bot flooded with `Unexpected error while listening to user stream` but still placing/refreshing orders
Bot still failed to check `USDC` `balance`
Bot unstable to show USDC balance in `status --live`

Test performed:

Start the client without any errors - Bot flooded with `Unexpected error while listening to user stream` but still placing/refreshing orders
Connected valid API keys = OK
Pull balance without any issue - Not showing `USDC balance`
CMCBL - Ran the BTC-USDC/ETH-USDC Pairs - Placed orders, was able to recognized position after restart
Create strategy without any errors = OK
No issue on creation and cancellation of orders = OK
Open position is recognized upon restart = OK
Status/orderbook is sync - Bot unstable to show USDC balance in `status --live`
Filled trades + fee are logged correctly = OK
Run the bot on multiple order levels (XRP-USDT) = OK

**Comment by aarmoa** [comment]
@nikspz I pushed a fix for the two issues detected by QA

**Comment by aarmoa** [comment]
Thank you @arnelhbot. That seems as an error that could happen if the connection is unstable. But I will investigate a little bit more to discard any issue with the latest fix

**Comment by aarmoa** [comment]
I made a change that I think will solve the problem (I tested it locally and it works, but we need to run a longer run to correctly verify the fix)

**Comment by rapcmia** [comment]
Hi @aarmoa thanks for the update, we've managed to run some tests earlier for both source and docker on AWS instances and confirmed that we had not noticed this happened for couple of hours. We setup a testbot overnight for monitoring then review log files. We should be able to provide update tomorrow about commit `5e185df`

**Review by cardosofede — APPROVED** [review]
LGTM! just one question because it doesn't affect the performance @aarmoa, the FULL_ORDER_BOOK_RESET_DELTA_SECONDS will be 9223372036854775807 if the computer is 64 bits, is this okey?

**Review by nikspz — APPROVED** [review]
Test performed:

- Cloned and installed feature branch
- Manually created Docker Image
- Started bot and created password
- Connected Bitget API Key and checked balance
- Checked Balance shows all the tokens
- Created/started/checked Perpetual_MM strategy using UMCBL, CMCBL, DMCBL types pairs
- Order cancellation = OK
- Opened and Closed positions, filled orders = OK
- Position retrieval working as expected
- Checked Status, Status -live updating
- Data Integrity (ticker, status, order_book --live)  synced with exchange
- History, CSV data matches with exchange
- No issues during Overnight run
- Tested on AWS Source and Docker

**Comment by aarmoa** [comment]
@cardosofede Yes, that is correct. Basically we want that timeout to never happen for Bitget. We should never refresh the order book using REST requests because that will break the synchronization

**Pull request merged**
