### PR TITLE
fix/hyperliquid_recreates_reversing_order_on_close

### PR DESCRIPTION
**Pull request by yancong001**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Comment by nikspz** [comment]
commit 8dfc7f0

Test performed:
- Cloned PR7013
- Set up dmanv3 controller using hyperliquid and config from #6948 
- Review issue not reproduced during 22 hours
- no errors showed during the run

Pending: ongoing longrun


image

**Comment by nikspz** [comment]
@yancong001 could you add tests to this one?

**Comment by yancong001** [comment]
added

**Review by nikspz — APPROVED** [review]
Test performed:
- Cloned PR7013
- Set up dmanv3 controller using hyperliquid and config from #6948 
- no errors showed during the run
- Review issue not reproduced during ~3 days

**Comment by nikspz** [comment]
https://github.com/hummingbot/hummingbot/issues/7024
Reproduced on this PR as well
@yancong001 could you have a look?

**Comment by yancong001** [comment]
The problem has been solved

**Review by cardosofede — APPROVED** [review]
LGTM! Great work @yancong001

**Comment by tijsk** [comment]
I've been testing this and noticed the same as nikspz. Now the script isn't working on Hyperliquid.
Last week I was able to place order, but they reversed again after a while. Now the orders aren't submitted to Hyperliquid (no  data in "Order history")

The logs are attached. If you need more info just let me know.
[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/15332473/logs_hummingbot.log)

**Comment by yancong001** [comment]
> I've been testing this and noticed the same as nikspz. Now the script isn't working on Hyperliquid. Last week I was able to place order, but they reversed again after a while. Now the orders aren't submitted to Hyperliquid (no data in "Order history")
> 
> The logs are attached. If you need more info just let me know. [logs_conf_v2_generic_with_controllers_HL-dman.log](https://github.com/hummingbot/hummingbot/files/15332483/logs_conf_v2_generic_with_controllers_HL-dman.log)

The issue was fixed at #7027

**Pull request merged**
