### PR TITLE
Feat/cex poll changes

### PR DESCRIPTION
**Pull request by cardosofede**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Remove the connectors that didn't meet the quorum, and change the tiers of cex.

**Tests performed by the developer**:
Run local test

**Tips for QA testing**:

### CODE REVIEW

**Comment by nikspz** [comment]
Steps: 
Cloned and installed feature branch
Start the bot instance
Check connect, status commands

Actual:
Gold connectors are Green, Silver are grey and Bronze are Yellow
There's still connectors with unknown status (ciex, k2, probit_kr)
`AWS showed commands `painted red` on the local client it `painted yellow` when checking status, config and other commands

image
image

Is it better to change `gold to yellow`, `silver just silver`. or Just dont put colors on it? 
Also I think  red color on the AWS could mess up the users little bit

**Comment by nikspz** [comment]
image

Steps:
Clone and install feature branch
Create docker image manually (`docker build -t hummingbot/hummingbot:newcex -f Dockerfile .` )
Create/start docker instance

Actual:
Bot showed warning message for related to Override Fees

traceback:
```
11:18:25 - root - Cannot find corresponding config to key liquid_buy_percent_fee_deducted_from_returns in template.
11:18:25 - root - Cannot find corresponding config to key liquid_maker_fixed_fees in template.
11:18:25 - root - Cannot find corresponding config to key liquid_maker_percent_fee in template.
11:18:25 - root - Cannot find corresponding config to key liquid_percent_fee_token in template.
11:18:25 - root - Cannot find corresponding config to key liquid_taker_fixed_fees in template.
11:18:25 - root - Cannot find corresponding config to key liquid_taker_percent_fee in template.
```

**Comment by rapcmia** [comment]
PR update:
- Text color now displays correct on both source and docker build for WSL, AWS and Mac(m1)
   image
- Background color for command has been fixed  ✅ 
- Error on corresponding config has been fixed ✅ 

However we would like to address that whenever we stop and change exchange, it seems it still displays the previous exchange tier. This would be fix by importing the strategy file again. Crosscheck the behavior on development branch and this only happens on the PR

Paper trade
Screenshot 2023-01-20 101243

Spot connector
Screenshot 2023-01-20 100624

Perpetual connector 
Screenshot 2023-01-20 100959

Steps to reproduce:
1. Setup simple PureMM or PerpMM strategy
2. Start the client and notice the prompt about `connector status: xxxx...`
3. Stop the client and change the connector `config exchange`
4. Repeat step 4 and notice the prompt that it would display the previous connector tier
5. Try to do Step 3 and add a number of connectors and start the bot again, it should be observe the same results
6. By `import` command and start the client works as expected

**Comment by nikspz** [comment]
@Faouzijedidi1 latest commit [442ce91](https://github.com/hummingbot/hummingbot/pull/6017/commits/442ce91de5d2a13d7a6259b5fcd5d62282f1be5f)

`Connector status` NOT showing for GOLD, SILVER and BRONZE connector after start command
after start command `Connector status` showing only for paper trade connector 

Steps to reproduce:

1. clone and install latest commit 442ce91
2. create/start simple pureMM strategy using paper trade connector (binance_paper_trade)
3. pay attention bot showed connector status: UNKNOWN
4. stop the bot
5. config exchange change to Gold connector (binance) or (same for Silver or Bronze)
6. start the bot

Actual:
Bot will show 
`Paper trading active: all orders are simulated and no real orders are placed`
`Connector status: UNKNOWN`

Expected:
Bot will show actual status of the connector (Gold, Silver or Bronze)
no Paper trade warning message showed for (Gold, Silver or Bronze connectors)


image

image
image

**Review by nikspz — APPROVED** [review]
- Successfully install source/docker build
- Reported issues has been fixed 
- Removed connectors: CELO, Latoken, Digifinex, BTC Markets, WazirX, Beaxy, Eve, CoinZoom and Liquid
- Updated connector status: GOLD,SILVER and BRONZE
- Check autocomplete lists and configs for connectors, all ok

**Pull request merged**
