### PR TITLE
Fix/gateio and kuocin perpetual incorrect orderbook amount

### PR DESCRIPTION
**Pull request by yancong001**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
G Gate io  8 •

The current gateioperpetual & kucoinperpetual's orderbook volume is wrong and 100 times ( contract size) larger than the actual number.
Change the contract size of the existing orderbook to the amount.

**Tests performed by the developer**:
unittest

**Tips for QA testing**:

Compare the orderbook of gateioperpetual & kucoinperpetual for the web page with the orderbook for hummingbot

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update
- Test on AWS and local WSL
- Test latest commit `1bdd3fb28c497839ea90603007bc7ba54a1b1476`
   image
   - Behavior of gateio and kucoin perpetual still the same returning the same format as the reported screenshot
   - It seems on the exchange it displays `9.30K` which the same as `9300` on the client

Could you please let us know what expected behavior should we see? Thank you 🙇🏼

**Comment by yancong001** [comment]
For BTC_USDT and ETH_USDT, you can see in the orderbook that the volume is different. @rapcmia

**Review by cardosofede — APPROVED** [review]
LGTM!

**Review by cardosofede — APPROVED** [review]
LGTM!

**Pull request merged**
