### PR TITLE
fix/binance_market_order_no_price

### PR DESCRIPTION
**Pull request by lt7**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Fixes Binance market order without price fails with illegal characters #5251

**Tests performed by the developer**:

Added new unit test for market orders

**Tips for QA testing**:

Create custom strategy with market orders for binance to test.

### CODE REVIEW

**Comment by lt7** [comment]
https://snapshot.org/#/hbot-prp.eth/proposal/0xfc400d06f751f735c4f622def8fb73dee21365001e31b7099d8e31b6edefb969

**Comment by aarmoa** [comment]
Hello @lt7. Please take a look at the method `supported_order_types`. Binance connector was developed to not use orders without prices (ie: market order types). That means that orders should never be created without price.
Besides that, the fix implementation is incorrect because in the case a price is not provided the order amount is not quantized, what is an error because we always need to ensure the client creates orders with an amount considered valid by the exchange trading rules.

-- Hummingbot Foundation Technical DAO review

**Comment by lt7** [comment]
> Hello @lt7. Please take a look at the method `supported_order_types`. Binance connector was developed to not use orders without prices (ie: market order types). That means that orders should never be created without price. Besides that, the fix implementation is incorrect because in the case a price is not provided the order amount is not quantized, what is an error because we always need to ensure the client creates orders with an amount considered valid by the exchange trading rules.
> 
> -- Hummingbot Foundation Technical DAO review

Thanks @aarmoa, I missed `supported_order_types` and https://github.com/hummingbot/hummingbot/blob/master/hummingbot/connector/exchange/binance/binance_exchange.py#L466 comment seemed to indicate it was supported, I'll update this method or are there some other concerns?

Good point about the order amount not quantized, that was a miss as https://github.com/hummingbot/hummingbot/blob/master/hummingbot/connector/exchange/binance/binance_exchange.py#L346 self.get_price was timing out in the unit test, any pointers/suggestions how to mock that ?

**Comment by aarmoa** [comment]
@lt7 I would suggest to not use market orders. They introduce the risk of being executed at prices far away from the intended trading price in high volatility scenario. Please remember that you can simulate a market order by sending a limit order with a price equal (or even lower/higher) to the best bid price or best ask price. But since the order includes a price you will be sure that the market cant execute your order at unexpected prices.

**Comment by lt7** [comment]
thanks for the feedback @aarmoa. I'm building a new strategy that had a use-case for market, stop_loss, take_profit etc so thought I'd PR a fix, but no worries if there is no interest. 
 
> @lt7 I would suggest to not use market orders. They introduce the risk of being executed at prices far away from the intended trading price in high volatility scenario. Please remember that you can simulate a market order by sending a limit order with a price equal (or even lower/higher) to the best bid price or best ask price. But since the order includes a price you will be sure that the market cant execute your order at unexpected prices.

**Comment by JeremyKono** [comment]
Will be closing this PR as it is not ideal to be in the codebase.

**Comment by mifeng** [comment]
Personally, I disagree with the approach that exchange connectors shouldn't support market orders. CoinAlpha removed market orders from connectors back in 2020, but in hindsight I think it was a hasty decision that didn't benefit the open source community. I don't think connectors should be opinionated and dictate what strategy builders can and can't do. Instead, they should just map the API of the exchange and give strategy builders full power. I would support and vote for an improvement proposal that adds market order support to the main connectors.

**Pull request closed without merging**
