### PR TITLE
Remove suspend and restore feature from start and exit commands respe…

### PR DESCRIPTION
**Pull request by klpanagi**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

Remove pause and restore features from the Hummingbot client, as described by the relevant bounty: https://github.com/orgs/hummingbot/projects/7/views/1?pane=issue&itemId=17905944

**Tests performed by the developer**:

- Upstream Unitests
- exit / start and capture behavior

**Tips for QA testing**:

### CODE REVIEW

**Comment by nikspz** [comment]
Test performed:
- source:
    - start/stop/exit commands works as expected
    - —suspend don’t show for stop,exit on TAB: ok
    - start doesn’t show —restore on TAB : ok
    - stop —suspend, exit —suspend command causes unrecognized arguments: ok
    - Forced exit -f, exit —force commands removed
        - that’s not nessasary
- docker
    - start/stop/exit commands works as expected
    - start/stop/exit commands works as expected
    - —suspend don’t show for stop,exit on TAB: ok
    - start doesn’t show —restore on TAB : ok
    - stop —suspend, exit —suspend command causes unrecognized arguments: ok
    - Forced exit -f, exit —force commands removed
        - that’s not nessasary

@klpanagi Forced exit removed on current commit [ba52941](https://github.com/hummingbot/hummingbot/pull/6008/commits/ba5294195ce52e6f30a0782dc5e0d98b564aa3c9) that's not needed cause that's allow user to do forced restart of the bot

Steps:
1. Clone and install feature branch
2. create/import the strategy and Start the bot
3. Do the `exit -f` or `exit --force` command

Actual:
unrecognized arguments: -f
unrecognized arguments: --force

Expected:
bot stopped all the orders
successful forced exit

PR6008 exit -f exit --force deleted

**Comment by klpanagi** [comment]
Hello @nikspz,

> Forced exit removed on current commit [ba52941](https://github.com/hummingbot/hummingbot/pull/6008/commits/ba5294195ce52e6f30a0782dc5e0d98b564aa3c9) that's not needed cause that's allow user to do forced restart of the bot

Thought from a comment in https://github.com/hummingbot/hummingbot/issues/4428 that you do not want the feature of exiting without terminating any open orders.

Pushed a commit that reverts these changes to the exit command.

**Review by nikspz — APPROVED** [review]
Test performed:
- source:
  - start/stop/exit commands works as expected
  - —suspend don’t show for stop,exit on TAB: ok
  - start doesn’t show —restore on TAB : ok
  - stop —suspend, exit —suspend, start —restore command causes unrecognized arguments: ok
  - Forced exit -f, exit —force command works: ok
- docker
  - start/stop/exit commands works as expected
  - start/stop/exit commands works as expected
  - —suspend don’t show for stop,exit on TAB: ok
  - start doesn’t show —restore on TAB : ok
  - stop —suspend, exit —suspend, start —restore command causes unrecognized arguments: ok
  - Forced exit -f, exit —force commands works: ok

**Comment by nikspz** [comment]
In behalf of Foundation team we merged this PR to development for the upcoming Hummingbot version 1.12.0

**Pull request merged**
