### PR TITLE
(fix) change strategy name from uniwap_v3 to amm_v3

### PR DESCRIPTION
**Pull request by fengtality**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

- Changes strategy name from `uniswap_v3_lp` to `amm_v3_lp`

### CODE REVIEW

**Comment by nikspz** [comment]
Steps: 
1. clone and installed fix branch
2. connected uniswapLP succesfully
3. create amm_v3_lp startegy
4. after last step got an error

Actual:
Got an error FileNotFoundError: [Errno 2] No such file or directory: '/home/etozhe/renameunilp6721/hummingbot/templates/conf_amm_v3_lp_strategy_TEMPLATE.yml'


image

**Comment by fengtality** [comment]
@nikspz @rapcmia  if possible we should get this PR merged into the Dec release since David and I have already changed the strategy name in the release notes PR.

**Comment by nikspz** [comment]
@fengtality Could you please fix failing tests 
and rename unilp6721/hummingbot/templates/conf_amm_v3_lp_strategy_TEMPLATE.yml ?
It's need to be renamed from uniswap_v3_lp to conf_amm_v3_lp_strategy_TEMPLATE.yml

**Review by nikspz — APPROVED** [review]
Test performed:

- Cloned and installed feature branch (PR6721) and gateway latest development
- generated gateway certs successfully and set up gateway to ONLINE
- succesfully connected pancakeswapLP and uniswapLP
- created/started amm_v3_lp startegy using uniswapLP
- added liquidity to uniswapLP successfully
- created/started amm_v3_lp startegy using pancakeswapLP
- added liquidity to pancakeswapLP successfully

**Pull request merged**
