### PR TITLE
Refactor/ rename Huobi to HTX

### PR DESCRIPTION
**Pull request by blagodar1**
**Before submitting this PR, please make sure**:

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

**Tests performed by the developer**:

**Tips for QA testing**:

### CODE REVIEW

**Review by cardosofede — CHANGES_REQUESTED** [review]
Only revert the flake 8 change that you made and review that the endpoints are not changing.

**Comment by cardosofede** [comment]
@nikspz try to run a strategy in HTX too

**Comment by nikspz** [comment]
Test performed: 
- Cloned and installed PR6796
- Connected HTX successfully
- checked balance successfully
- Created/started pureMM using htx with no issues
- Checked status and order_book succesfully update in --live
- Review filled orders events handled succesfully,  in Client/exchange matched

**Review by nikspz — APPROVED** [review]

**Review by cardosofede — APPROVED** [review]
LGTM!

**Pull request merged**
