### PR TITLE
Add ping pong to user stream ascendex to prevent websocket timeout

### PR DESCRIPTION
**Pull request by leecarney**
Before submitting this PR, please make sure:

    [Y ] Your code builds clean without any errors or warnings
    [ Y] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

A description of the changes proposed in the pull request:
Websockets are kept alive using ping pong instead of being closed by the ascendex servers prematurely which is causing HB to create a new session. If there are multiple bots doing this the bots will be IP banned from the ascendex websocket resulting in console errors.

Tests performed by the developer:
Local build test after commit.
Local test against ascendex and websockets are not closed

Tips for QA testing:
Set up live trade against ascendex. No websocket errors

### CODE REVIEW

**Comment by leecarney** [comment]
https://snapshot.org/#/hbot-prp.eth/proposal/0x6b8ef2b48ff616b485b394b7052d560fd17d4d20485f71814c68a42d436dc49b

**Comment by JeremyKono** [comment]
Hi @leecarney, is this intended to be a fix or a new feature? If a bug fix, you don't need to create a PRP next time.

**Comment by rapcmia** [comment]
PR update:
- Setup testbot to run overnight with killswitch enabled
- Killswitched triggered and noticed that the client return `Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...` after few hours

image

```
-09 14:46:11,866 - 7979 - hummingbot.core.utils.kill_switch - INFO - Kill switch threshold reached. Stopping the bot...
2022-11-09 14:46:11,866 - 7979 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2022-11-09 21:13:35,606 - 7979 - hummingbot.connector.exchange.ascend_ex.ascend_ex_api_order_book_data_source - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/ubuntu/github/5854/hummingbot/connector/exchange/ascend_ex/ascend_ex_api_order_book_data_source.py", line 262, in listen_for_subscriptions
    async for ws_response in ws.iter_messages():
  File "/home/ubuntu/github/5854/hummingbot/core/web_assistant/ws_assistant.py", line 69, in iter_messages
    response = await self._connection.receive()
  File "/home/ubuntu/github/5854/hummingbot/core/web_assistant/connections/ws_connection.py", line 62, in receive
    msg = await self._process_message(msg)
  File "/home/ubuntu/github/5854/hummingbot/core/web_assistant/connections/ws_connection.py", line 84, in _process_message
    msg = await self._check_msg_types(msg)
  File "/home/ubuntu/github/5854/hummingbot/core/web_assistant/connections/ws_connection.py", line 89, in _check_msg_types
    msg = await self._check_msg_closed_type(msg)
  File "/home/ubuntu/github/5854/hummingbot/core/web_assistant/connections/ws_connection.py", line 99, in _check_msg_closed_type
    raise ConnectionError(
ConnectionError: The WS connection was closed unexpectedly. Close code = 1006 msg data: None
2022-11-09 21:13:41,208 - 7979 - hummingbot.connector.exchange.ascend_ex.ascend_ex_api_order_book_data_source - INFO - Subscribed to ['ETH-USDT'] orderbook trading and delta streams...
2022-11-10 02:00:43,677 - 7979 - hummingbot.connector.exchange.ascend_ex.ascend_ex_api_order_book_data_source - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/ubuntu/github/5854/hummingbot/connector/exchange/ascend_ex/ascend_ex_api_order_book_data_source.py", line 262, in listen_for_subscriptions
    async for ws_response in ws.iter_messages():
  File "/home/ubuntu/github/5854/hummingbot/core/web_assistant/ws_assistant.py", line 69, in iter_messages
    response = await self._connection.receive()
  File "/home/ubuntu/github/5854/hummingbot/core/web_assistant/connections/ws_connection.py", line 62, in receive
    msg = await self._process_message(msg)
  File "/home/ubuntu/github/5854/hummingbot/core/web_assistant/connections/ws_connection.py", line 84, in _process_message
    msg = await self._check_msg_types(msg)
  File "/home/ubuntu/github/5854/hummingbot/core/web_assistant/connections/ws_connection.py", line 89, in _check_msg_types
    msg = await self._check_msg_closed_type(msg)
  File "/home/ubuntu/github/5854/hummingbot/core/web_assistant/connections/ws_connection.py", line 99, in _check_msg_closed_type
    raise ConnectionError(
ConnectionError: The WS connection was closed unexpectedly. Close code = 1006 msg data: None
2022-11-10 02:00:49,263 - 7979 - hummingbot.connector.exchange.ascend_ex.ascend_ex_api_order_book_data_source - INFO - Subscribed to ['ETH-USDT'] orderbook trading and delta streams...
```

Steps to reproduce:
1. Setup PMM using Ascendex 
2. Setup killswitch and spreads tight enough for orders to be filled 
3. Wait until killswitch is triggered

Attached:
[logs_pmm-ascendex-test.log](https://github.com/hummingbot/hummingbot/files/9977175/logs_pmm-ascendex-test.log)

**Comment by nikspz** [comment]
Closing PR since it did not meet the required quorum
https://snapshot.org/#/hbot-prp.eth/proposal/0x6b8ef2b48ff616b485b394b7052d560fd17d4d20485f71814c68a42d436dc49b

**Comment by nikspz** [comment]
Re-opened since it's a bugfix

**Comment by leecarney** [comment]
@rapcmia Pushed a fix if you can test.

**Review by leecarney — COMMENTED** [review]
@rapcmia Can you try this branch?

**Comment by rapcmia** [comment]
Hi @leecarney Thanks for the update, im running the same setup and will monitor the results overnight

**Comment by leecarney** [comment]
@rapcmia Great testing thanks. Updated PR - this version has been working great for me all day if you could retest.

**Comment by leecarney** [comment]
@rapcmia Linting fixed if you can rerun the workflow.

**Comment by leecarney** [comment]
@rapcmia Isort fixed...again pls

**Comment by leecarney** [comment]
@rapcmia  This isort issue isn't occuring on my local setup inside conda if you have any suggestions
Screenshot 2022-11-21 at 07 41 14

**Comment by leecarney** [comment]
@nikspz I've resolved the isort errors - can you run the workflow? 
I would say we need to resolve this issue and then retest https://github.com/hummingbot/hummingbot/issues/5826#issuecomment-1325711231 against it.

**Comment by leecarney** [comment]
@rapcmia Typo fixed. Run again thanks...

**Comment by leecarney** [comment]
@rapcmia Latest workflow errors not related to this PR.

**Comment by rapcmia** [comment]
Hi @leecarney apologies on the delay,
Yes I have rerun the workflow and see how it goes. I will look into this PR and update you today, thank you 🙇

**Comment by rapcmia** [comment]
Hi @leecarney good day,
We happen to have another PR that refactors the whole Ascendex connector and its a update to fix most of its issue. I'll discuss this bounty with the team but for now you may want to check out this PR #5891

**Comment by leecarney** [comment]
@rapcmia Ha well that one definitely looks more comprehensive!

**Comment by carlitogetaladajr** [comment]
@leecarney, please fill up & submit the AML Policy Form via this link: https://forms.gle/wUukH8LSj6jYoa8V6
This is a one-time process for each ETH Address used to receive HBOT bounty.

**Pull request closed without merging**
