### PR TITLE
fix/Do not read the whole CSV file every time we want to write.

### PR DESCRIPTION
**Pull request by cheemeng**
**Before submitting this PR, please make sure**:

- [X] Your code builds clean without any errors or warnings
- [X] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

There is no need to read the whole CSV file in memory (and spend time parsing it as well) if we are only checking the first row

### CODE REVIEW

**Review by mhrvth — APPROVED** [review]
LGTM

-- Review submitted in representation of the Hummingbot Foundation Technical DAO

**Comment by cheemeng** [comment]
> LGTM
> 
> -- Review submitted in representation of the Hummingbot Foundation Technical DAO

Sorry, forgot to rebase with upstream dev earlier

**Comment by nikspz** [comment]
Steps:
1. clone and install feature branch
2. create/start pureMM strategy with tight spreads
3. wait for multiple trades filled

Bot not recorded second trade filled and return that error:
[csv5459.zip](https://github.com/hummingbot/hummingbot/files/9120154/csv5459.zip)
```
2022-07-15 10:36:05,421 - 74338 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1657881365.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-DAI", "amount": "0.01000000", "price": "1217.48000000", "order_id": "x-XEKWYICXSEHDI182016e0a098cb05b", "creation_timestamp": 1657881365.0, "exchange_order_id": "452529104", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "binance"}
2022-07-15 10:36:13,048 - 74338 - hummingbot.connector.client_order_tracker - INFO - The SELL order x-XEKWYICXSEHDI182016e0a098cb05b amounting to 0.01000000/0.01000000 ETH has been filled.
2022-07-15 10:36:13,048 - 74338 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-DAI) Maker sell order of 0.01000000 ETH filled. [clock=2022-07-15 10:36:13+00:00]
2022-07-15 10:36:13,054 - 74338 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - ERROR - Unexpected error while processing event 107.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
    self(arg)
  File "/home/ubuntu/csv5459/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/home/ubuntu/csv5459/hummingbot/connector/markets_recorder.py", line 274, in _did_fill_order
    self.append_to_csv(trade_fill_record)
  File "/home/ubuntu/csv5459/hummingbot/connector/markets_recorder.py", line 319, in append_to_csv
    if (os.path.exists(csv_path) and (not self._csv_matches_header(csv_path, field_names))):
  File "/home/ubuntu/csv5459/hummingbot/connector/markets_recorder.py", line 303, in _csv_matches_header
    return tuple(df.iloc[0].values) == header
AttributeError: 'TextFileReader' object has no attribute 'iloc'
```

image

**Comment by JeremyKono** [comment]
Hi @cheemeng, can you please fix the issues stated by QA? And also please fix github unit tests to pass. Thanks

**Pull request closed without merging**
