### PR TITLE
Check for node API key when starting a strategy that uses gateway

### PR DESCRIPTION
**Pull request by james-hummingbot**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:

### gateway
- default RPC for avalanche is now Moralis
- update docker setup script to handle null value correctly

### hummingbot
- in `gateway create`, make Infura API key optional
- after calling `start`, check if gateway is required, then check the chain/network for API keys. If the API key does not exist, prompt the user to input it

**Tests performed by the developer**:

**Tips for QA testing**:

- Run `gateway create` with and without providing an Inufura Key.
- run amm_arb with uniswap and/or avalanche
- when the api keys are null or empty string, `start` should prompt you for an api key. otherwise it should work as normal

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update: 
Tested on Local with docker desktop on Windows (WSL/Ubuntu18lts) and MacOs. However we are still working on the AWS instance since we are encountering some issues with starting the docker

image

**Comment by JeremyKono** [comment]
Hi @james-hummingbot can you please resolve the conflicts in this PR? Thanks!

**Comment by rapcmia** [comment]
We tried to crosscheck with local and docker desktop which works ok but still getting this error on AWS instance. This issue happen even with or without adding the infura key on the initial prompt after gateway create. The issue happens after we changed the docker tag to `26090`, please advise if we are missing something on the setup 

image

```
Done pulling Gateway docker image.
2022-05-16 09:12:17,822 - 6007 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 409 Client Error for http+docker://localhost/v1.41/containers/17606f779f6fe96582611d8d4562e2686ff62f24c6ed486da6a13f42615cf27a/exec: Conflict ("Container 17606f779f6fe96582611d8d4562e2686ff62f24c6ed486da6a13f42615cf27a is not running")
Traceback (most recent call last):
  File "/home/ubuntu/github/5268/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/github/5268/hummingbot/client/command/gateway_command.py", line 229, in _create_gateway
    await self._generate_gateway_confs(container_id=container_info["Id"])
  File "/home/ubuntu/github/5268/hummingbot/client/command/gateway_command.py", line 129, in _generate_gateway_confs
    exec_info = await docker_ipc(method_name="exec_create",
  File "/home/ubuntu/github/5268/hummingbot/core/gateway/__init__.py", line 176, in docker_ipc
    raise e
  File "/home/ubuntu/github/5268/hummingbot/core/gateway/__init__.py", line 169, in docker_ipc
    raise data
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.41/containers/17606f779f6fe96582611d8d4562e2686ff62f24c6ed486da6a13f42615cf27a/exec: Conflict ("Container 17606f779f6fe96582611d8d4562e2686ff62f24c6ed486da6a13f42615cf27a is not running")
```

Checking the docker container, it does not start and kept on getting exit. Tried to wait for couple of minutes the Gateway status does not changed from `off`. Also tried to run `gateway start` but the container still getting exit.

Tried to clear the `.hummingbot-gateway` folder and delete the docker images and redo the steps but still same issue.

Steps to reproduce:
1. Changed docker tag to 26096
2. Generate certs and gateway create
3. After pulling Gateway docker image, either enter (or not) the infura key on the prompt
4. Notice error on log panel


Attach:

[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/8699021/logs_hummingbot.log)

**Comment by rapcmia** [comment]
Hi @james-hummingbot thanks for checking it again. I tried to delete the branch and made sure that I have no running container and deleted the image and redo the steps while docker tag is set to `26096` but still it kept on crashing for my AWS instance. I tried to investigate by running `docker run -entrypoint="/bin/bash" -i coinalpha/gateway-dev-v2:26096` and getting:

`WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested`

image

image

**Review by rapcmia — APPROVED** [review]
Test performed:
- Install feature branch successfully
- Modify ./hummingbot/core/gateway/ init.py file, DOCKER TAG to `26096-linux` or `26096`
- Generate certs and gateway create, all ok 
- Did not enter infura key, gateway still connected and checked docker instance, all ok 
- Restart client, it managed to reconnect to gateway
- Setup gateway avalanche.nodeAPIkey using moralis, all ok 
- Setup simple AMM-Arb, the client will prompt if missing infura key
- Setup with moralis node only then start strategy specially running on pangolin, all ok 
- Tested on local source/docker and AWS instance all ok

**Pull request merged**
